### ISSUE TITLE
New Branch to Support Magnum Bays

### ISSUE THREAD

**Issue by carolynvs** [gophercloud/gophercloud#10]
The magnum API isn't solidified yet. I will have access to an environment this week and will update the ticket with additional details on each action.
- POST /bays - create a cluster
- GET /bays/[id] - get cluster info
- PUT /bays/[id] - update a cluster, currently that only means increasing the node count
- DELETE /bays - delete a cluster

**Comment by carolynvs** [comment]
@jrperritt Would you please assign this to me? 😄

**Comment by jrperritt** [comment]
>> The magnum API isn't solidified yet.

To be clear, we're waiting until the API is finalized to add support for this, correct?

>> Would you please assign this to me?

I think only members of the org (and maybe collaborators?) can be assigned issues. If it's important for accounting purposes, I can try to figure out how to get you added. Otherwise, it's known the issue is yours.

**Comment by jrperritt** [comment]
Because the Magnum API isn't finalized yet, I think the best we can do here is create a `magnum` branch that can hold the code for the unfinalized API. [If and] when the API becomes solidified, we can review and merge into `master`.

**Comment by jrperritt** [comment]
Branch is here: https://github.com/gophercloud/gophercloud/tree/magnum

**Comment by carolynvs** [comment]
Thanks!

**Comment by jrperritt** [comment]
Changed issue title to be more practical for now. If and when the API stabilizes we can look at supporting this.
