### ISSUE TITLE
Create and get project property

### ISSUE THREAD

**Issue by deponian** [gophercloud/gophercloud#1004]
Hello.

Openstack projects are able to contain extra key-value properties apart from their basic information like ID, description, parent ID and other. But there is no property field in CreateOpts or Project struct for gophercloud projects.

Is it really not realized or I just can not find it?

**Comment by jtopjian** [comment]
@deponian It's currently not supported. The other identity resources have an `Extra` field, but this feature was never added to projects. It should be easy enough to do, though. If this is something you'd like to work on, I would be happy to review. Otherwise I can get to this as soon as I can.

**Comment by deponian** [comment]
Thank you for the answer. I'll try to implement support of extra fields for projects in the near future.

**Comment by kayrus** [comment]
There are two independent properties:
* a regular property, which can be set via `Extra` field.
* an `options` property, which is an object: https://docs.openstack.org/keystone/latest/admin/resource-options.html

**Comment by jtopjian** [comment]
Implemented in #1951
