### ISSUE TITLE
Add an external network filter option

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1009]
I have a use case that requires to filter out external networks from network requests. It could be done by adding the following option:

* [router:external](https://github.com/openstack/neutron-lib/blob/f42bcbcb3fdcfa9cb3d0ffe1bba810a317ba3c9b/neutron_lib/api/definitions/external_net.py#L21)

[Reference](https://specs.openstack.org/openstack/neutron-specs/specs/api/external_networks__external-net_.html)

I found [this code](https://github.com/gophercloud/gophercloud/blob/c53578fc5176a5508a400609e00cd669d412f45c/openstack/networking/v2/extensions/external/requests.go), but it looks like it is applicable only when you modify the network.

**Comment by jtopjian** [comment]
Thanks for digging into this.  :smile: 

> I found this code, but it looks like it is applicable only when you modify the network.

Good find. This is the right file we need to modify.

Neutron's heavy use of extensions makes working with Gophercloud _very_ verbose. Both Neutron and Gophercloud have legitimate design decisions, but the two together can make even the smallest change require a good amount of work.

This isn't something I'd expect someone new to Gophercloud to be able to easily figure out, so I created #1010 which implements this.

#1010 also includes an amended doc example and an acceptance test on how to use this.

It's possible to create some code to cover this verbosity up and make it more easier to work with. I have this somewhere on my todo list.

Please let me know if you have any questions. :)

**Comment by jtopjian** [comment]
Implemented in #1010
