### ISSUE TITLE
Subnet Gateway Behavior

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#101]
When creating a subnet, there are three different actions that can happen:

1. When `gateway_ip` is omitted, Neutron will provision a default gateway.
2. When `gateway_ip` is specified with a value of nil/None, no gateway is provisioned.
3. When `gateway_ip` is specified and is a valid IP, that IP is used for the gateway.

Currently, gophercloud can do 1 and 3, but not 2.

[reference](https://github.com/openstack/neutron/blob/ba788da398b31d5433a91bdc72ff2695b475fa41/neutron/api/v2/attributes.py#L119-L127)

**Comment by jrperritt** [comment]
closed by #102
