### ISSUE TITLE
range over objects is not properly supported

### ISSUE THREAD

**Issue by awskii** [gophercloud/gophercloud#1049]
Hello.

When you will try to GET object with some `Range` parameter, you will receive 206 HTTP status code, which is not properly supported by library. In my case that leads to endless printing into terminal of `\x00\x00\x00`.

**Comment by jtopjian** [comment]
This sounds correct to me. Thank you :)

https://github.com/openstack/swift/blob/de9cee090b024c6e5db152043525d32a6fe37b7a/swift/common/middleware/s3api/controllers/obj.py#L51-L56

Fixed in #1050
