### ISSUE TITLE
container name and directory name is not url encoded by default

### ISSUE THREAD

**Issue by awskii** [gophercloud/gophercloud#1051]
Hello.

When i review my code, I understood that i want to get rid of patterns like that:
```go
object := objects.Download(c.swift, url.PathEscape(container), url.PathEscape(dir), opts)
if err := object.Err; err != nil {
    ...
}
```
And in my opinion, library should encode container and directory name for me, because library should hide any backstage work from me.

Previously i thought that there are no encoding problems before i met directory names like "тестовый пул+данные" which were not properly decoded by server. I think, that can be misleading new library users.

But I am not 100% sure that it should be made by library. What do you think about that?

**Comment by jtopjian** [comment]
> library should hide any backstage work from me.

This is purely in my opinion, but hiding things should only be done when absolutely necessary. And this is usually done closer to the developer's application and not closer to the core libraries. A slightly exaggerated example is asking why the core Go `net/http` library doesn't already do `PathEscape` internally?

> But I am not 100% sure that it should be made by library. What do you think about that?

Gophercloud isn't supposed to be a friendly library that hides difficult things from the developer. It's meant to be a very thin Go library to interact with the OpenStack APIs. The developer should build friendlier libraries to interface between Gophercloud and their application.

An example of this is here: https://github.com/gophercloud/utils/pull/47

That PR is using Gophercloud to communicate with the Object Storage service but also adds a massive amount of logic on top of it.

I think `url.PathEscape` might be better suited in the above PR.
