### ISSUE TITLE
AllPages is making one extra call to OpenStack API

### ISSUE THREAD

**Issue by garbage-collector** [gophercloud/gophercloud#1054]
Hi !

While starting to use the gophercloud library, I noticed that using the AllPages() function (https://github.com/gophercloud/gophercloud/blob/master/pagination/pager.go#L125) from the pager ends with performing one not needed call to the OpenStack.

For listing flavors, for example, it performs two calls to OpenStack API.

The first call is done to get the "testPage" (https://github.com/gophercloud/gophercloud/blob/master/pagination/pager.go#L132).
The second call is done to get results by calling the EachPage function.

So if you have N pages of results, it looks like the code will perform N+1 calls to the OpenStack API.

This looks like an issue as all GET calls will end with a higher response time because of the double calls.

Is this a normal behavior ?

One way to fix it is to consider the "testPage" as a "firstPage" but I prefer to discuss about the issue before creating a PR.

Thanks

**Comment by jtopjian** [comment]
> Is this a normal behavior ?

Maybe? :)

I can confirm this behavior exists. It's possible it was an oversight or doing a test/probe of the first page is required to bootstrap the `AllPages` process. 

If you're able to fix the issue, by all means go for it. The CI environment will run enough `AllPages` calls to determine if anything breaks (hopefully).

**Comment by garbage-collector** [comment]
Pull request created https://github.com/gophercloud/gophercloud/pull/1056 :)

**Comment by jtopjian** [comment]
Implemented in #1056
