### ISSUE TITLE
Incorrect end-point for `NewIdentityV3`?

### ISSUE THREAD

**Issue by fatmcgav** [gophercloud/gophercloud#107]
https://github.com/gophercloud/gophercloud/blob/master/openstack/client.go#L205 has the end-point listed as "identity". 

I believe it should be "identityv3" for the v3 API. 

Can raise a PR if helpful.

**Comment by jrperritt** [comment]
> I believe it should be "identityv3" for the v3 API.

Per the style guide, we need proof in the OpenStack source code.

> Can raise a PR if helpful.

Sure. Before starting, please read and adhere to the [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md).

**Comment by fatmcgav** [comment]
Hmm, I'm struggling to find any OpenStack doc's that prove one way or the other... 
One reference in the Python SDK docs: [type](http://developer.openstack.org/sdks/python/openstacksdk/users/resources/identity/v3/service.html#openstack.identity.v3.service.Service.type) - but that does note that the list isnt explicit... 

The above assertion was based on the service catalog provided by an Openstack provider that I'm currently working with... Though guess it's possible that they've used 'identityv3' as a non-standard thing... :( 

@jtopjian Have you used any other OS installations that support Keystone v3? Do they use 'identity', or 'identityv3'? 

Cheers

**Comment by jtopjian** [comment]
I think identityv3 is non-standard - at least now. I coincidentally just finished digging around code in Heat and `keystoneclient` and noticed `identity` is referenced with version discovery done after.

I think the best place to find the source is `keystoneclient`. Maybe an older release used both `identity` and `identityv3`. Depending on the age of the release, there might be grounds to supporting both for a time.

Another option is to be able to override the endpoint names in Gophercloud.

**Comment by fatmcgav** [comment]
Ok, cheers for the response... 

I'll follow up with the cloud provider... 

And yes, it is possible to override the endpoint type:
```go
	client, err := openstack.NewIdentityV3(provider, gophercloud.EndpointOpts{
		Region: "uk-1",
		Type:   "identityv3",
	})
```

I'll go ahead and close for time-being :)
