### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1084]
This topic has come up a few times, both on and offline, and I figured I'd make an official issue to discuss. The driver for this is https://github.com/terraform-providers/terraform-provider-openstack/pull/359.

Using Terraform as an example, vendoring is currently done ad-hoc depending on the package in question. This is the safest approach and it's worked very well. However, as the linked PR describes, compatibility with tools will cause this method to become difficult, if not impossible, to use.

One possible way forward is to begin tagging Gophercloud with a release so applications can begin vendoring at a certain tag.

Even if tool compatibility is not a driver for this, it still makes sense to begin versioning Gophercloud.

With that in mind, we'll need to determine a version scheme to use.

As an operations person, I've run into so many different versioning schemes from different projects. They all have their advantages and disadvantages.

SemVer is the most popular, though I've always found it confusing because it seems everyone has their own rules for what constitutes a major and minor release. 

A scheme which includes major and minor numbers might open the door to version branches. While these are worthwhile, this introduces a lot of administrative work for the core team and I don't think there's capacity for that.

An incremental scheme such as v1, v2, v3, 2018.1, 2018.2, etc is very simple but pushes the responsibility of looking for breaking changes onto the consumer of the code. Personally, I think this is done with semver anyway as a precaution, but maybe that's just my experience.

A predictable schedule such as every six months (2018.02, 2018.08) is a valid scheme, but given the bursts of activity in Gophercloud, this might cause some consumers to have to wait a long time for a feature.

_edit_: As well, periods of inactivity work against a predictable schedule.

There are, of course, other schemes.

I like the idea of an incremental scheme for a few reasons:

1. It's simple.
2. Gophercloud already makes no guarantees about breaking changes.
3. Go development places heavy emphasis on testing which should catch breaking changes.
4. I enjoy going against the status quo.

(side thought: one could think of a commit as an incremental version number, though an unfriendly one)

However, as I've stated: I'm more of an operations person and only play a developer. I could be unknowingly omitting serious considerations.

I welcome any thoughts.

**Comment by jtopjian** [comment]
Thinking about this more, I'm still leaning on some type of incremental version. A release schedule could be something like the following:

* Upon the merge of something other than only a doc. This would mean that we would be at version 358 after 358 merge have been made. If tag exhaustion is a concern, then this would be an issue. However, lots of tags gives the ability to review changes easily and slowly move forward.
* After an arbitrary amount of merges were made. This would be at the discretion of a core.
* Once a week, depending on activity (variation of the above).

When thinking about a way to automatically handle tagged releases, the first option is the most possible. The second option could be possible with some type of Github hook. The third, I think, is the most difficult to automate as it would require some type of hosted cron with logic to determine if the minimum amount of merges happened.

**Comment by hogepodge** [comment]
Personally, I think that semver makes the most sense for versioning.  Simple rule, you make a breaking change to the API it increases the major version. You add new functionality, it's a minor release. Often it's abused for marketing reasons, but I don't think we would run into that issue here. Within the OpenStack community there's an argument that you should never make breaking changes to an API so semver is useless, but that's not a position I would take. Semver takes more work because it forces the developer to think about how their patch is changing the code in a strictly prescribed senst.

With regards to the release schedule. Versioning after every patch is the same as pointing to a GIT SHA, maybe a bit easier since it's incremental. It would be nice to distinguish between new features and bug fixes also (which semver does nicely imo). Arbitrary feels... arbitrary. Same as once a week.

Ultimately it's a decision that's best left up to the maintainers of the project. Like everything else, if it's documented everyone understands where you're coming from and there are no surprises.

If not semver, I would vote for incremental version. Things tied to dates drive me a bit crazy.

**Comment by jtopjian** [comment]
All good points and I do agree. This reply isn't debating those points, it's more for posterity and having a record of discussion.

> Semver takes more work

This is the crux of the issue with choosing semver. To me, semver implies support. The most difficult and time consuming parts aren't even technical: it's debating if one person's feature is another's breakage, deferring merges until later, fielding support and apologies if a decision didn't work out, etc.

If Gophercloud was at the point of full feature parity with the Python family of SDKs, I'd be all for semver and focusing most attention to support. But with the availability of myself and @jrperritt, I lean heavily on not guaranteeing backwards compatibility.

With that in mind, I don't want to come off like I'm not in favor of providing stability and support. Those are _really_ important items for anything. I would just prefer to do it when the project is in a better shape to be able to.

> Versioning after every patch is the same as pointing to a GIT SHA, maybe a bit easier since it's incremental

I was unclear on this. By "merge", I really meant "Pull Request" which could include more than one commit. This would mean slightly less version increases. Slightly :)

**Comment by hogepodge** [comment]
> I was unclear on this. By "merge", I really meant "Pull Request" which could include more than one commit. This would mean slightly less version increases. Slightly :)

I have an allergic reaction to un-squashed PRs. The mistake is entirely mine. :-)

**Comment by Frassle** [comment]
> If Gophercloud was at the point of full feature parity with the Python family of SDKs, I'd be all for semver and focusing most attention to support.

Why not use semver v0? "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable." That gets you using semver in preparation for when it is stable enough to use v1, but doesn't put any stability constraints on now.

For now you could just increment minor and patch numbers for new features, bugfixes respectively.

**Comment by jtopjian** [comment]
> Why not use semver v0?

Certainly an option :)

**Comment by jtopjian** [comment]
I think @Frassle's idea will work best as it's a good balance of all considerations. I'll wait for @jrperritt to weigh in when he has some time. 

Assuming semver v0 is the choice we go with, the next step would be to tag the latest commit as `v0.1.0` and go from there.

**Comment by dkt26111** [comment]
+1 for using semver. I also would like to see a release with a minor version increment when support is added for a new OpenStack project.  E.g. when all the Magnum related APIs are merged, it would warrant a minor version bump.

**Comment by carlwgeorge** [comment]
I'm working on packaging this library into Fedora, as it's a dependency of other software I'm packaging.  I'd like to share the perspective of Linux distro packagers.

> SemVer is the most popular, though I've always found it confusing because it seems everyone has their own rules for what constitutes a major and minor release.

There is only one set of semantic versioning rules, the ones on https://semver.org.  Anything else is not semantic versioning.

> A scheme which includes major and minor numbers might open the door to version branches.

> To me, semver implies support.

Only if you want to.  Semantic version doesn't commit you to anything with regards to older versions.

> The most difficult and time consuming parts aren't even technical: it's debating if one person's feature is another's breakage, deferring merges until later, fielding support and apologies if a decision didn't work out, etc.

You don't have to be perfect here.  Semantic versioning is all about conveying the developer's intent.  If a user sees an upgrade from 1.0.0 to 1.1.0, they can assume that you don't intend to introduce breaking changes in that release.  Mistakes happen, and that's OK.

> Why not use semver v0?

Agreed, as that seems to reflect to current state of the project based on what I've read so far.  (Not applicable here, but for a laugh check out https://0ver.org).

Fedora has some draft packaging guidelines with great rationale for doing releases, I'd encourage you to read through these as well.

https://fedoraproject.org/wiki/More_Go_packaging#Releasing

**Comment by mrhillsman** [comment]
@jtopjian

**Comment by jtopjian** [comment]
I _really_ appreciate everyone's input.

Please don't get me wrong: I understand the merits and qualities of semver. However, as I mentioned before, semver implies support and a guarantee to users. Maybe I'm just jaded from running too many projects in production that don't live up to that guarantee.

But since I cannot provide the guarantee I'd expect a project to have, then we're going with semver v0. Possibly indefinitely. 

And with all that said, I have just released v0.1.0.

Future releases will happen arbitrarily: if a batch of updates happened in a short period of time, we'll do a release. If a number of weeks have gone by and there have been only a few updates, we'll do a periodic release.

Since Gophercloud still hasn't implemented a large part of the OpenStack API, I'd imagine some projects will still choose to use the latest HEAD commit, for when there are times they want to begin using a newly implemented feature but before a release has happened. And that's fine, too.

Again, thank you all.
