### ISSUE TITLE
Adding missing ProvisioningStatus fields to lbaas v2

### ISSUE THREAD

**Issue by Ladicle** [gophercloud/gophercloud#1087]
I added ProvisioningStatus fields to /v2.0/lbaas models a several days ago (https://github.com/gophercloud/gophercloud/issues/1066), but extensions lbaas v2 is also missing ProvisioningStatus fields. It's already deprecated as of Queens, but I still need it for my old OpenStack cluster.

https://developer.openstack.org/api-ref/network/v2/index.html?expanded=#show-load-balancer-status-tree

**Comment by jtopjian** [comment]
For reference, the `provisioning_status` field is defined here:

https://github.com/openstack/neutron-lbaas/blob/36f0f578a689be3964c8bb56f07982bb22852148/neutron_lbaas/services/loadbalancer/data_models.py

Search for "provisioning_status".

**Comment by jtopjian** [comment]
Implemented in #1088
