### ISSUE TITLE
Container v1: Acceptance Test Failures

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1089]
Beginning two days ago, the Zun/Container v1 acceptance tests began failing:

```
2018-07-04 10:46:36.917099 | ubuntu-xenial | === RUN   TestCapsule
2018-07-04 10:46:38.120525 | ubuntu-xenial | --- FAIL: TestCapsule (1.20s)
2018-07-04 10:46:38.120764 | ubuntu-xenial | 	convenience.go:35: [1;31mFailure in capsules_test.go, line 65: unexpected error [0m[1;33m"Internal Server Error"[0m[1;31m[0m
2018-07-04 10:46:38.120820 | ubuntu-xenial | FAIL
2018-07-04 10:46:38.121596 | ubuntu-xenial | FAIL	github.com/gophercloud/gophercloud/acceptance/openstack/container/v1	1.211s
```

http://logs.openlabtesting.org/logs/88/1088/c6aebc73e7fd6841a00c3031cb595813ae651a7a/check/gophercloud-acceptance-test/8109231/job-output.txt.gz

This is consistently happening with every test run.

/cc @yongfengdu @hongbin @liu-sheng

**Comment by hongbin** [comment]
Looking into it

**Comment by hongbin** [comment]
This patch is an attempt to fix: https://review.openstack.org/#/c/580257/

**Comment by jtopjian** [comment]
@hongbin From reading the upstream Zun patches, if Gophercloud supported microversions, I don't think that would have prevented this issue. 

The upstream you identified as the cause of the test failures is here: https://review.openstack.org/#/c/571398/

I might be incorrect, but I don't see anything in that code which is checking for a microversion before performing an action. As an example, this is how Nova handles different behavior depending on the microversion:

https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/migrations.py#L116-L143

According to the microversion spec, all prior behavior should still be successful and not require a microversion increase to the client. It's only after the client opts-in to a microversion that new features, such as `restart_policy` should be seen.

**Comment by hongbin** [comment]
@jtopjian 

You are right. The 'restart_policy' change doesn't check the API version. As a result, backward-compatibility breaks. Unfortunately, I failed to catch that in code review. Sorry about that. I have filled a ticket to fix it: https://bugs.launchpad.net/zun/+bug/1780279 at Zun side.

**Comment by hongbin** [comment]
In addition to https://review.openstack.org/#/c/580257/ , we also needs https://github.com/gophercloud/gophercloud/pull/1097 to make the CI happy.

**Comment by jtopjian** [comment]
@hongbin I'm going to close this issue since CI is now happy again. Since #1098 has its own dedicated issue, the future PR can be linked to that issue.

Thank you so much for your help with this - especially with getting the upstream patch quickly in place :)
