### ISSUE TITLE
Container v1: Support API microversion

### ISSUE THREAD

**Issue by hongbin** [gophercloud/gophercloud#1091]
Zun is using API microversion [1]. It would be great if gophercloud can leverage it. A use case it so ping a specific API version to avoid breakage.

[1] https://docs.openstack.org/zun/latest/contributor/api-microversion.html

**Comment by jtopjian** [comment]
@hongbin There's a _really_ long discussion about this at #441. It might be best to close this issue in favor of #441 unless there's something specific to Zun here.

The summary is that microversions (while a helpful feature) are not at all easy to implement in a typed language like Go :(

**Comment by hongbin** [comment]
Sure. Zun would like to align with the final decision at #441. Close this one.
