### ISSUE TITLE
Zun: the acceptance test should wait for the capsule to be 'Running' after create

### ISSUE THREAD

**Issue by hongbin** [gophercloud/gophercloud#1098]
Here is the capsule acceptance test: https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/container/v1/capsules_test.go . The test created a capsule but doesn't wait for the capsule to become 'Running'. It is better to do that.

As a reference, here is how we tested it in tempest: https://review.openstack.org/#/c/546007/

Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

**Comment by jtopjian** [comment]
@hongbin This is pretty easy to implement. You can see an example of how the acceptance tests wait for Compute Instances to become active here:

https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/compute/v2/compute.go#L937-L957

https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/compute/v2/compute.go#L470-L472

The `WaitFor` function can go in a file called `acceptance/openstack/container/v1/capsules.go` which will allow it to be re-used in other acceptance tests in the future.

**Comment by hongbin** [comment]
@jtopjian , ACK. Thanks for the hints.
