### ISSUE TITLE
Senlin: Missing Clusterpolicies  Get/List

### ISSUE THREAD

**Issue by JackKuei** [gophercloud/gophercloud#1109]
Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

**Comment by jtopjian** [comment]
@JackKuei These are bundled under the `clusters` package.

**Comment by JackKuei** [comment]
@jtopjian See them now. clusterpolicies.Get ==> clusters.GetPolicy, clusterpolicies.List ==> clusters.ListPolicies()
