### ISSUE TITLE
[wip] Query for image by name

### ISSUE THREAD

**Issue by tcarrio** [gophercloud/gophercloud#1111]
It is currently not possible to use gophercloud for querying by the image name (from what I can see in `/openstack/compute/v2/images`). 

This functionality is another use case which would be beneficial to users in various scenarios, e.g. Packer/Terraform image searches.

I'm currently developing an implementation that works by generating a slice of `Image`s with a separate function `getFromNameURL`, as opposed to the other `GET /images/{id}` function `getURL`. Any guidance or suggestions on the preferred manner of implementation would be appreciated and I'm very open to feedback. 

The following API endpoint is found in the Openstack source code at: https://github.com/openstack/glance/blob/master/glance/api/v2/images.py#L161

**Comment by jtopjian** [comment]
https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/images is a very old set of API calls. It was used for communicating with the Image API via the Compute API, so you could do things like:

```
nova image-list
```

and it would proxy the request to the image service. 

While this will still work with some older OpenStack environments, it's no longer supported and I'd recommend against any new work in that area. Instead, look at the image service proper: https://github.com/gophercloud/gophercloud/tree/master/openstack/imageservice/v2

Gophercloud currently supports the ability to issue a List query and filter by Name:

https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/requests.go#L39

Let me know if this helps or if you have any questions.

**Comment by tcarrio** [comment]
That is extremely helpful! I will look to using that instead. It seems to have what I was looking for already with `ListOpts`. Thank you!

**Comment by tcarrio** [comment]
Closing since `imageservice` provides the functionality I was looking for.
