### ISSUE TITLE
Bug: Can't pass ListPoliciesOpts options to Senlin's cluster ListPolicies 

### ISSUE THREAD

**Issue by JackKuei** [gophercloud/gophercloud#1113]
Environment: DevStack, stable/queen branch
gophercloud version: HEAD of master, 45c2d035713fa44f366921035a44610ac5d45beb

Observed behavior:
When invoking clusters.ListPolicies(client, clusterID, clusters.ListPoliciesOpts{Name: "Test"}), the ListPoliciesOpts cannot be passed in

Expected behaviour:
Should allow ListPoliciesOpts to be passed in

**Comment by jtopjian** [comment]
Fixed in #1114
