### ISSUE TITLE
Bug: Senlin Node's should use "project" field rather than "project_id"

### ISSUE THREAD

**Issue by JackKuei** [gophercloud/gophercloud#1116]
Environment: DevStack, stable/queen branch
gophercloud version: HEAD of master, 45c2d035713fa44f366921035a44610ac5d45beb

Observed behavior:
When invoking nodes.List(...) the project UUID is returning empty due to the response should use "project" rather than "project_id". 

Expected behaviour:
The project field should be properly populated

**Comment by jtopjian** [comment]
Fixed in #1117
