### ISSUE TITLE
Openstack base_endpoint.go regex does not support URI patterns with a base containing "*v.*"

### ISSUE THREAD

**Issue by scott-chaney** [gophercloud/gophercloud#1130]
https://github.com/gophercloud/gophercloud/blob/master/openstack/utils/base_endpoint.go#L22

This pattern does not support something like "https://dev.keystone.net:5000/v3.0", the base is translated as "https://de"

Something like:

`versionRe := regexp.MustCompile("/v[0-9].*[0-9]*/?")`

...should do the trick.

**Comment by jtopjian** [comment]
@scott-chaney Nice find :)

No doubt eventually someone is going to have `https://dev01.example.com`, so I did a more permanent fix at #1132

**Comment by jtopjian** [comment]
Fixed in #1132
