### ISSUE TITLE
Cinder volume pagination is broken

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#1138]
PR coming up in a minute.

**Comment by jtopjian** [comment]
@majewsky Do you mean the lack of paging support with v2 volumes?

If so, we'll want to have an implementation similar to what was done with v3 volumes: https://github.com/gophercloud/gophercloud/commit/a5c718687f9222e37c96d8c0210bebd242f926b5#diff-bd6235f833e16ceebe7aaa5b948a593f

Which includes `ListOpts` support for sorting, marker, etc.

**Comment by majewsky** [comment]
done

**Comment by jtopjian** [comment]
Fixed in #1139 

Thanks @majewsky!
