### ISSUE TITLE
Support for shared file systems API V2 (manila)

### ISSUE THREAD

**Issue by mvalkon** [gophercloud/gophercloud#114]
Gophercloud does not support [the shared file systems API](http://developer.openstack.org/api-ref-share-v2.html). We are using this API in our organization and will implement a library for go to use in our product. If possible, only the latest microversion of the API will be implemented.

We'd like to contribute our implementation to the gophercloud library. This issue is opened to track the progress for the PR's regarding this feature.

**Comment by jrperritt** [comment]
Great. The [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md) contains useful information when making contributions.

**Comment by mvalkon** [comment]
Any pointers on ways to orchestrate the PR's would be valued. We're aiming to produce small PR's implementing one API operation each, but this leads to PR's having duplicated content until merged.

**Comment by jrperritt** [comment]
> We're aiming to produce small PR's implementing one API operation each, but this leads to PR's having duplicated content until merged.

That's expected. If the PRs are small, they can be reviewed (and merged) more quickly, allowing you to go to the next one. The PRs will be reviewed in order.

Aside from that, can you either create individual issues or checkboxes in this issue's description for each operation/PR to aid in record-keeping?

**Comment by mvalkon** [comment]
@jrperritt Sure, do you have a preferred approach? I'd probably go for the checkbox one, but have no strong opinion.

**Comment by mvalkon** [comment]
Opted to go with separate issues in order to maintain sanity in the record-keeping.

**Comment by jrperritt** [comment]
>> Opted to go with separate issues

Great, no preference here.

I will review all of the currently-open Manila PRs tomorrow.

**Comment by mvalkon** [comment]
@jrperritt thanks a lot!

**Comment by pospispa** [comment]
I'd like to use Gophercloud in Kubernetes to communicate with the shared file systems API (Manila).
It's great that a part of the work was successfully completed. However, a part of the work is in PRs that are waiting for review and merge.

From my point of view it seems that the Gophercloud project got stuck as there are no new commits in the master branch since mid-November.

Please, are there any plans to revive this project and have reviews and merges to master start happening again?

**Comment by mvalkon** [comment]
@pospispa I'd be willing to continue contributing on my own time if this project is revived. 

@jrperritt @jtopjian can you update on the situation?

**Comment by jtopjian** [comment]
@mvalkon Sorry, Mikko, I haven't heard anything wrt PR reviews. It's possible @jrperritt is tied up with some other work or is on holidays. Hang tight :)

**Comment by jrperritt** [comment]
Yes, I've just returned from holiday. I will be looking at/addressing all outstanding issues/PRs this week.

**Comment by jtopjian** [comment]
I think at this point, Gophercloud has a decent amount of support for shared file system. Given there weren't any specific resources detailed in this issue and since it's been common to open a separate issue for missing SFS API calls, I'm going to close this issue.
