### ISSUE TITLE
Feature: Add /network/v2.0/network-ip-availability requests

### ISSUE THREAD

**Issue by serboox** [gophercloud/gophercloud#1144]
Please add this requests in upstream:
1. List Network IP Availability -> `curl -X GET http://openstack/network/v2.0/network-ip-availability -H "X-Auth-Token: ####"`
2. Show Network IP Availability -> `curl -X GET http://openstack/network/v2.0/network-ip-availabilities/{network_id} -H "X-Auth-Token: ####"`

Documentation [link](https://developer.openstack.org/api-ref/network/v2/)

**Comment by jtopjian** [comment]
Implemented in #1154
