### ISSUE TITLE
Blockstorage v2: volume results struct missing ProjectID/TenantID field

### ISSUE THREAD

**Issue by waynr** [gophercloud/gophercloud#1145]
Confirming this is a real field by appealing to cinder codebase:

* https://github.com/openstack/cinder/blob/e4954bf341c41f62821d0729388a43b70eb67e2d/cinder/volume/api.py#L551 <- main API classes' `get` method uses `cinder.objects.Volume`
* https://github.com/openstack/cinder/blob/e4954bf341c41f62821d0729388a43b70eb67e2d/cinder/objects/volume.py#L76 <- `cinder.objects.Volume` defines a `project_id` field.

One thing I'm not certain about given the above `project_id` field reference is why the API docs indicate `tenant_id`: https://developer.openstack.org/api-ref/block-storage/v3/index.html#volumes-volumes

I'll work on submitting a PR sometime in the next day.

**Comment by jtopjian** [comment]
@waynr 

> One thing I'm not certain about given the above project_id field reference is why the API docs indicate tenant_id:

There's a volume extension somewhere in the Cinder code that adds `os-vol-tenant-attr:tenant_id`. We have that defined here:

https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/volumetenants/doc.go

However, if `project_id` is now a first-class non-extension attribute in volumes, it would be great to get that added in. :)

**Comment by jtopjian** [comment]
@waynr I was just doing some testing for #1139 and noticed that `project_id` is not listed in the response body:

```
2018/07/25 01:42:49 [DEBUG] OpenStack Request URL: GET http://cinder:8776/v2/20c6b343b2b8453d92018a8654343589/volumes/detail
2018/07/25 01:42:49 [DEBUG] OpenStack request Headers:
Accept: application/json
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
2018/07/25 01:42:50 [DEBUG] OpenStack Response Code: 200
2018/07/25 01:42:50 [DEBUG] OpenStack Response Headers:
Content-Length: 871
Content-Type: application/json
Date: Wed, 25 Jul 2018 01:42:49 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Compute-Request-Id: req-068befe6-c05c-4f52-a8ab-865253680ec2
X-Openstack-Request-Id: req-068befe6-c05c-4f52-a8ab-865253680ec2
2018/07/25 01:42:50 [DEBUG] OpenStack Response Body: {
  "volumes": [
    {
      "attachments": [],
      "availability_zone": "nova",
      "bootable": "false",
      "consistencygroup_id": null,
      "created_at": "2018-07-25T01:42:47.000000",
      "description": null,
      "encrypted": false,
      "id": "65189705-13fc-4fa6-81b5-3ebbca185a5f",
      "links": [
        {
          "href": "http://cinder:8776/v2/20c6b343b2b8453d92018a8654343589/volumes/65189705-13fc-4fa6-81b5-3ebbca185a5f",
          "rel": "self"
        },
        {
          "href": "http://cinder:8776/20c6b343b2b8453d92018a8654343589/volumes/65189705-13fc-4fa6-81b5-3ebbca185a5f",
          "rel": "bookmark"
        }
      ],
      "metadata": {},
      "multiattach": false,
      "name": "ACPTTESTH6RdODRUsombSu9a",
      "os-vol-tenant-attr:tenant_id": "20c6b343b2b8453d92018a8654343589",
      "replication_status": null,
      "size": 1,
      "snapshot_id": null,
      "source_volid": null,
      "status": "available",
      "updated_at": "2018-07-25T01:42:48.000000",
      "user_id": "5c70d99f4a8641c38f8084b32b5e5c0e",
      "volume_type": null
    }
  ]
}
```

The above is a v2 response. v3 is the same.

Both have the `os-vol-tenant-attr:tenant_id` field set, though.

I wonder if `project_id` is referenced internally but not actually sent in any output?

**Comment by waynr** [comment]
Thanks for the heads up, was just about to start tinkering with it myself.

Also, apparently I was working on this around two months ago but must have got side tracked and forgot about it because I already have the `os-vol-tenant-attr:tenant_id` implementation in my working copy of the repo.

**Comment by waynr** [comment]
I don't think my PR is going to be accepted so I'm not going to submit it. I'll just use https://godoc.org/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumetenants as inconvenient as it is.

**Comment by jtopjian** [comment]
I agree that the extension is inconvenient. One solution I've been meaning to get to is to add a bunch of pre-made structs to `gophercloud/utils` which contain the base struct + all standard extensions.
