### ISSUE TITLE
Hotfix: ToServerRebootMap

### ISSUE THREAD

**Issue by serboox** [gophercloud/gophercloud#1151]
Link to method: [link](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go)
Now:
// ToServerRebootMap builds a body for the reboot request.
`func (opts *RebootOpts) ToServerRebootMap() (map[string]interface{}, error) {
	return gophercloud.BuildRequestBody(opts, "reboot")
}`
We get an error:
`cannot use rebootOpts (type servers.RebootOpts) as type servers.RebootOptsBuilder in argument to servers.Reboot:
  servers.RebootOpts does not implement servers.RebootOptsBuilder (ToServerRebootMap method has pointer receiver)`

Should be:
// ToServerRebootMap builds a body for the reboot request.
`func (opts RebootOpts) ToServerRebootMap() (map[string]interface{}, error) {
	return gophercloud.BuildRequestBody(opts, "reboot")
}`

**Comment by jtopjian** [comment]
Fixed in #1152
