### ISSUE TITLE
Compute V2: Flavors sort_key and sort_dir query arguments

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1155]
Right now the OpenStack Compute service support `sort_key` and `sort_dir` query arguments to allow user to specify direction or key for sorting.
It would be great if Gophercloud supported those options in the `ListOpts` for the `flavors` package.

Documentation:
https://developer.openstack.org/api-ref/compute/#list-flavors

**Comment by jtopjian** [comment]
Implemented in #1156
