### ISSUE TITLE
Compute V2: Unrescue action

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1164]
Right now there is only rescue action that is implemented inside `servers/requests.go` along with others core Compute API calls.
Users who uses Gophercloud can't send the `Unrescue` request to return server to its original state.

API documentation:
https://developer.openstack.org/api-ref/compute/#unrescue-server-unrescue-action

There seems to be a separate issue to move the Rescue extension into the `servers/extenstion` directory to follow the common Gophercloud structuring: #425.

@jtopjian in what way is better to proceed with this task? Should I start a PR that migrates the Rescue extension to a separate package? After that I can create another PR which adds Unrescue action into that new extension.
As far as I understand from #1160, it's the preffered way of structuring Gophercloud packages.

Or I can just add yet another request method into the core `servers` package?

**Comment by jtopjian** [comment]
> in what way is better to proceed with this task? Should I start a PR that migrates the Rescue extension to a separate package? After that I can create another PR which adds Unrescue action into that new extension.

This approach sounds good to me.

**Comment by ozerovandrei** [comment]
Implemented in #1169
