### ISSUE TITLE
Bugfix: Headers not be set

### ISSUE THREAD

**Issue by serboox** [gophercloud/gophercloud#1170]
Let's look at this method [link](https://github.com/gophercloud/gophercloud/blob/5a70be10fdef2e0bc31ef6633fdc581d8e9777dc/openstack/compute/v2/servers/requests.go#L740)
``` go
package servers

func CreateImage(client *gophercloud.ServiceClient, id string, opts CreateImageOptsBuilder) (r CreateImageResult) {
	b, err := opts.ToServerCreateImageMap()
	if err != nil {
		r.Err = err
		return
	}
	resp, err := client.Post(actionURL(client, id), b, nil, &gophercloud.RequestOpts{
		OkCodes: []int{202},
	})
	r.Err = err
	r.Header = resp.Header
	return
}
```
Variable `r CreateImageResult` contain *http.Response headers 
``` go
r.Header = resp.Header
```
and method return `gophercloud.Result` structure with fill `Err error` and `Header http.Header` field
``` go
package servers

type CreateImageResult struct {
	gophercloud.Result
}
```
``` go
package gophercloud

type Result struct {
	// Body is the payload of the HTTP response from the server. In most cases,
	// this will be the deserialized JSON structure.
	Body interface{}

	// Header contains the HTTP header structure from the original response.
	Header http.Header

	// Err is an error that occurred during the operation. It's deferred until
	// extraction to make it easier to chain the Extract call.
	Err error
}
```
**But why other methods ignore response headers?** 
For example: [link](https://github.com/gophercloud/gophercloud/blob/5a70be10fdef2e0bc31ef6633fdc581d8e9777dc/openstack/compute/v2/servers/requests.go#L279)
```go
package servers

func Create(client *gophercloud.ServiceClient, opts CreateOptsBuilder) (r CreateResult) {
	reqBody, err := opts.ToServerCreateMap()
	if err != nil {
		r.Err = err
		return
	}
	_, r.Err = client.Post(listURL(client), reqBody, &r.Body, nil)
	return
}
```

```go
package servers

type CreateResult struct {
	serverResult
}
```
```go
package servers

type serverResult struct {
	gophercloud.Result
}
```
I suggest correcting these methods and adding the ability to return headers:
```go
package servers

func Create(client *gophercloud.ServiceClient, opts CreateOptsBuilder) (r CreateResult) {
	reqBody, err := opts.ToServerCreateMap()
	if err != nil {
		r.Err = err
		return
	}
	resp, err := client.Post(listURL(client), reqBody, &r.Body, nil)
        r.Err = err
	r.Header = resp.Header
	return
}
```
With regard to these methods: [link](https://github.com/gophercloud/gophercloud/blob/5a70be10fdef2e0bc31ef6633fdc581d8e9777dc/openstack/compute/v2/servers/requests.go#L291)
```go
package servers

func Delete(client *gophercloud.ServiceClient, id string) (r DeleteResult) {
	_, r.Err = client.Delete(deleteURL(client, id), nil)
	return
}
```
I suggest add a second return variable `http.Header` 
```go
package servers

func Delete(client *gophercloud.ServiceClient, id string) (r DeleteResult, h http.Header) {
	resp, err := client.Delete(deleteURL(client, id), nil)
        r.Err = err
        h = resp.Header
	return
}
```
or change `DeleteResult`
``` go
package servers

type DeleteResult struct {
	gophercloud.ErrResult
}
```
to:
``` go
package servers

type DeleteResult struct {
	gophercloud.Result
}
```
```go
package servers

func Delete(client *gophercloud.ServiceClient, id string) (r DeleteResult) {
	resp, err := client.Delete(deleteURL(client, id), nil)
        r.Err = err
        r.Header = resp.Header
	return
}
```

**Comment by jtopjian** [comment]
> But why other methods ignore response headers?

Possibly because that's how people submitted the code and there wasn't a need to see the headers in certain results.

> I suggest add a second return variable http.Header

That's not needed. Even with an `ErrResult` you can still extract the headers if they are set. Adding a second return variable would also require a _massive_ refactoring of Gophercloud.

**Comment by serboox** [comment]
> That's not needed. Even with an ErrResult you can still extract the headers if they are set. Adding a second return variable would also require a massive refactoring of Gophercloud.

Yes, I'm sorry, you're right. These methods can be changed in the following way

```go
package servers

func Delete(client *gophercloud.ServiceClient, id string) (r DeleteResult) {
	resp, err := client.Delete(deleteURL(client, id), nil)
        r.Err = err
        r.Header = resp.Header
	return
}
```
**I can make these changes and send PR's?**

**Comment by jtopjian** [comment]
> Yes, I'm sorry, you're right. These methods can be changed in the following way

Right :)

> I can make these changes and send PR's?

Absolutely - it would be much appreciated. But before you get started, let's just double-check.

@jrperritt just to confirm: is there a reason why some requests do not set the result headers? Or is it just a feature which was left out?

**Comment by jtopjian** [comment]
I think all requests contain an `X-OpenStack-Request-Id` or something like that. There's been an increase in interest in obtaining that header lately.

**Comment by serboox** [comment]
> @serboox before you start working on this, which header fields are you interested in specifically?

Yes @jrperritt I need `X-Compute-Request-Id` header. I will be use this header for validation RabbitMQ queue messages.

**Comment by jrperritt** [comment]
OK, let me think about it. Note you could already do this with a custom `ProviderClient.HTTPClient`.

**Comment by jtopjian** [comment]
I'm in favor of this for two reasons:

1. It creates a consistent pattern across all requests.
2. `res` will now contain the full result, body and headers. Even if one (or both) do not have content, it's still the full result accessible to the user.

I realize blanketing this change is going to require a lot of work. If @serboox is up to the task, I think that's awesome.

**Comment by petri-ojala** [comment]
Any simple example how to implement it with a custom HTTPClient?

I've only used them for the transport itself (e.g. InsecureSkipVerify for TLS) so not very familiar how to do it for the get/post requests.  I have similar need to access the request ID's and noticed that it would be quite a task to go through all the code to add header support..

**Comment by petri-ojala** [comment]
Answering to myself :)  Got it working like charm.

```
xxx.Provider.HTTPClient = http.Client{Transport: HeaderRoundTripper{http.DefaultTransport}}

// http.RoundTripper interface
type HeaderRoundTripper struct {
	Proxied http.RoundTripper
}

func (lrt HeaderRoundTripper) RoundTrip(req *http.Request) (res *http.Response, e error) {
	// Send the request
	res, e = lrt.Proxied.RoundTrip(req)

	// If no error, save headers
	if e == nil {
		...
	}

	return
}
```

**Comment by kayrus** [comment]
Related to #1918

**Comment by kayrus** [comment]
@jtopjian I suggest the following change:

```diff
diff --git a/service_client.go b/service_client.go
index f222f05a..fd31e295 100644
--- a/service_client.go
+++ b/service_client.go
@@ -152,3 +152,11 @@ func (client *ServiceClient) Request(method, url string, options *RequestOpts) (
        }
        return client.ProviderClient.Request(method, url, options)
 }
+
+// ParseResponse is a helper function to parse http.Response to constituents.
+func ParseResponse(resp *http.Response, err error) (interface{}, http.Header, error) {
+       if resp != nil {
+               return resp.Body, resp.Header, err
+       }
+       return nil, nil, err
+}
```

And changes to `request.go` will look like:

```diff
-        _, r.Err = client.Get(url(client, id), &r.Body, nil)
+       resp, err := client.Get(url(client, id), &r.Body, nil)
+       _, r.Header, r.Err = gophercloud.ParseResponse(resp, err)
```

**Comment by jtopjian** [comment]
@kayrus Sure - let's try it out.
