### ISSUE TITLE
Senlin Bug: Policies Delete Should Use ExtractErr Instead Of Extract

### ISSUE THREAD

**Issue by JackKuei** [gophercloud/gophercloud#1171]
To keep it consistent with other gophercloud senlin APIs, rather than use Extract with DeleteHeader, caller should use ExtractErr, and obtain the header with something like res.Header["X-Openstack-Request-Id"][0]

[DeleteHeader source link](https://github.com/gophercloud/gophercloud/blob/master/openstack/clustering/v1/policies/results.go#L142 )
```golang
// DeleteHeader contains the delete information from a delete policy request.
type DeleteHeader struct {
	RequestID string `json:"X-OpenStack-Request-ID"`
}
```

[Extract source link](https://github.com/gophercloud/gophercloud/blob/master/openstack/clustering/v1/policies/results.go#L147)
```golang
func (r DeleteResult) Extract() (*DeleteHeader, error) {
	var s *DeleteHeader
	err := r.HeaderResult.ExtractInto(&s)
	return s, err
}
```

**Comment by jtopjian** [comment]
Fixed in #1172
