### ISSUE TITLE
Loadbalancers v2: LoadBalancer struct missing vip_network_id

### ISSUE THREAD

**Issue by waynr** [gophercloud/gophercloud#1176]
https://github.com/openstack/octavia/blob/fa0f0525e62a999aa14da46950c70cd741503179/octavia/api/v2/types/load_balancer.py#L52

**Comment by lukemgriffith** [comment]
This would be greatly appreciated if it was implemented. Building load balancers with Terraform currently requires a subnet Id what certainty is not scalable.

**Comment by lukemgriffith** [comment]
I've created a fork to implement this. https://github.com/lukemgriffith/terraform-provider-openstack/tree/loadbalancer_network_id

Currently running acceptance tests, will then raise a pull request.

**Comment by jtopjian** [comment]
Implemented in #1422
