### ISSUE TITLE
Magnum: ClusterTemplate APIServerPort should be int instead of string

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1185]
Hello.

I've just started implementing Magnum Cluster templates resource for the [terraform-provider-openstack#402](https://github.com/terraform-providers/terraform-provider-openstack/issues/402) and I got a JSON unmarshalling error regarding "apiserver_port" field.

It seems that there should be `int` type instead of `string`: [cluster_template.py#L82](https://github.com/openstack/magnum/blob/stable/rocky/magnum/api/controllers/v1/cluster_template.py#L82).

**Comment by jtopjian** [comment]
Fixed in #1186
