### ISSUE TITLE
Add support to get statistics for loadbalancer and listener.

### ISSUE THREAD

**Issue by velp** [gophercloud/gophercloud#1189]
Octavia provides simple statistics about loadbalancer's and listener's work. For this functionality gophercloud must use endpoints:
1. _.../loadbalancers/{id}/stats_
2. _.../listeners/{id}/stats_

See doc-reference:
https://developer.openstack.org/api-ref/load-balancer/v2/#get-load-balancer-statistics
https://developer.openstack.org/api-ref/load-balancer/v2/#get-listener-statistics

**Comment by jtopjian** [comment]
Implemented in #1190
