### ISSUE TITLE
Workflow V2: Adding Mistral APIs

### ISSUE THREAD

**Issue by garbage-collector** [gophercloud/gophercloud#1199]
It looks like gophercloud is missing workflow v2 implementation: https://docs.openstack.org/mistral/latest/

I'd be happy to propose a Pull Request to handle Mistral APIs, what do you think about this?

I've already prepared the [branche here](https://github.com/garbage-collector/gophercloud/tree/workflow-api), waiting your "LGTM" to propose the Pull Request.

Thanks !

**Comment by jtopjian** [comment]
Very cool. 

If you haven't yet, please read the [contributor's tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) which should explain the right process for this (let me know if it's unclear). Basically, please do not open one large PR of Mistral - it'll have to be broken out into several PRs.

When someone already has a large body of work done, I admit that this can be a pain, but it has proven worthwhile every time.

The current Magnum issue (https://github.com/gophercloud/gophercloud/issues/1062) might be a good template to go off of.

Short of that, this sounds good to me and we really appreciate the contribution. :)

**Comment by garbage-collector** [comment]
Ok, I'll have a look on this next week, I'll split my actual work into 3 PRs (I've worked on the workflows, executions and crontriggers APIs).

Acceptance tests are working on a DevStack with Mistral installed, so last work is to split into different PRs, not such a pain :)

Thanks !

**Comment by jrperritt** [comment]
It will need more than 3 PRs. See [here](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-05-pull-requests.md#adding-an-entire-openstack-project).

**Comment by garbage-collector** [comment]
Here it is!

I really tried to follow all the contributing process, feel free to tell if I'm doing it wrong.

[Mistral API Doc](https://docs.openstack.org/mistral/latest/api/index.html)
[Mistral source code](https://github.com/openstack/mistral)

---

[Workflows](https://docs.openstack.org/mistral/latest/api/v2.html#workflows)

- [x] Manage Workflow: Create
- [x] Manage Workflow: Delete
- [x] Manage Workflow: Get
- [x] Manage Workflow: List
- [ ] Manage Workflow: Update

---

[Executions](https://docs.openstack.org/mistral/latest/api/v2.html#executions)

- [x] Manage Execution: Create
- [x] Manage Execution: Delete
- [x] Manage Execution: Get
- [x] Manage Execution: List
- [ ] Manage Execution: Update

---

[Cron Triggers](https://docs.openstack.org/mistral/latest/api/v2.html#cron-triggers)

- [x] Manage Cron Triggers: Create
- [x] Manage Cron Triggers: Delete
- [x] Manage Cron Triggers: Get
- [x] Manage Cron Triggers: List
- [ ] Manage Cron Triggers: Update

---

Other components are not handled yet.

**Comment by garbage-collector** [comment]
Thanks for the answer :)

I fixed the boxes.

I just opened several PRs because all the works was already done on my side (yup, my mistake was to code before making this issue). This is why there are so many PRs. It's OK for me to rebase PR if needed, but it was really easier on my side to have dependencies on PRs, especially for acceptance testing purpose (executions and cron triggers rely on workflows).

All PRs are ready for review: code, comments, tests are done. I'll add a comment on each PR.

BTW, I saw that 2 PRs failed on acceptance tests, but I didn't find easily where I can find the report in order to understand the issue. Can you help ?

Thanks :)

**Comment by garbage-collector** [comment]
Comments added on each PR where build and acceptances tests are OK.

I just need some help to understand why build failed for 2 PRs (regarding PRs where tests are OK, it looks like relaunching the acceptances could fix the issue).

**Comment by jtopjian** [comment]
@garbage-collector This is all looking good - nice work :)

Before we close this issue out, we'll want to make sure `doc.go` is complete for all packages.

**Comment by garbage-collector** [comment]
Thanks for all merges :)

I just sent the last two PRs for review, and I fixed doc.go for all pages (workflows, executions, crontriggers).

Feel free to tell me if you want another PR to fix the workflows doc, but I found easier to integrate it in one of the existing PRs.

**Comment by garbage-collector** [comment]
All Pull Requests have been merged a couple of weeks ago. Do we keep this issue opened for mistral components other than workflow/execution/cron trigger, or do we close this one and another one will be opened for those components ?

Thanks for merging all this stuff :)

**Comment by jtopjian** [comment]
@garbage-collector I think we can close this issue and open new issues for any further APIs. Thank you for working on this -- it's really appreciated!
