### ISSUE TITLE
Block Storage: Add additional multiattach support

### ISSUE THREAD

**Issue by jamesmmccarthy** [gophercloud/gophercloud#1228]
In blockstorage some level of multiattach support is already in place, however there looks to be some gaps. As an example, some multiattach implementation is completed here:
github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/results.go:        Multiattach bool `json:"multiattach"`

Whereas functionality looks to be missing here:
github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go

At the moment, it's unclear where/what work is needed in total to flesh this out further, as things progress I hope to use this issue to house multiattach-related work and link all corresponding PRs to this issue.

**Comment by jtopjian** [comment]
> Whereas functionality looks to be missing here:
github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go

One quick note: if Block Storage v2 supports multiattach, then v3 should as well. In the past, we have seen that all v2 patches can be done in the exact same way for v3, so feel free to submit v3 updates bundled with v2.

**Comment by jamesmmccarthy** [comment]
The 4273563 commit is superceded by the f07e31e one, I didn't realize it would add a comment in this issue - please ignore the comment relating to 4273563

**Comment by jamesmmccarthy** [comment]
Hmm ok, well I ended up amending the most recent commit and force pushing back to my fork (to fix a formatting issue) - I see this is why the commits stack up here like this.

**Comment by jamesmmccarthy** [comment]
I believe this issue can be closed, there was another part dealing with attachments however that has been addressed in the terraform-provider-openstack itself.

**Comment by jtopjian** [comment]
Sounds good. Thank you for all your work!
