### ISSUE TITLE
Add networking v2.0 floating-ip support

### ISSUE THREAD

**Issue by beeva-germanmoya** [gophercloud/gophercloud#123]
After compute API microversion 2.35, the floating-ip calls were deprecated, so you need to use networking v2.0 floatings-ip calls.

Links:

- The deprecated API: http://developer.openstack.org/api-ref/compute/?expanded=create-allocate-floating-ip-address-detail#list-floating-ip-pools
- The active API: http://developer.openstack.org/api-ref/networking/v2/#list-floating-ips

**Comment by jtopjian** [comment]
@beeva-germanmoya Networking v2 floating IPs are already supported [here](https://github.com/gophercloud/gophercloud/tree/master/openstack/networking/v2/extensions/layer3/floatingips). Is there something missing there that needs added?

**Comment by beeva-germanmoya** [comment]
Thanks @jtopjian. That module is just what was searching. This issue has no sense now.
