### ISSUE TITLE
security group rule description

### ISSUE THREAD

**Issue by jsm222** [gophercloud/gophercloud#1230]
Could we add an optional string field description for security group rule as in https://github.com/jsm222/gophercloud/commit/debf32f0abb5d0122bc0e93d15b2c72259765888

**Comment by jtopjian** [comment]
If "description" is a valid field in the security group rule API, then sure. If you'd like to submit a PR, please follow the [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) and we can get it reviewed.

**Comment by jsm222** [comment]
Standard attributes has the descripton [field](https://github.com/openstack/neutron/blob/24c8f952b27e3bfaabad7f41edf283145cce7600/neutron/db/standard_attr.py#L56)
As [documented](https://github.com/openstack/neutron/blob/master/doc/source/contributor/internals/api_extensions.rst) security_group_rules has StandardAttributes
and here in [code](https://github.com/openstack/neutron/blob/a388701ddfe628e9a5bd16a78422164799b11ef8/neutron/db/models/securitygroup.py#L68) it extends standard_attr.HasStandardAttributes
And in the openstack [docs](https://developer.openstack.org/api-ref/network/v2/index.html#create-security-group-rule)

**Comment by jtopjian** [comment]
Implemented in #1231
