### ISSUE TITLE
Bug: Senlin profile create is missing "version" field for spec when sending to api backend

### ISSUE THREAD

**Issue by JackKuei** [gophercloud/gophercloud#1249]
Running the clustering profile acceptance test failed because the version field is missing in the request json results in 500 error being returned by the api backend.

`{
  "profile": {
    "name": "TESTACC-InhooUHk",
    "spec": {
      "properties": {
        "flavor": "t2.small",
        "image": "centos7.3-latest",
        "name": "TESTACC-InhooUHk",
        "networks": [
          {
            "network": "sandbox-internal-net"
          }
        ],
        "security_groups": ""
      },
      "type": "os.nova.server"
    }
  }
}`

The 'version' key is missing from the provided spec map.

Reference:  #[823 [Add support for Senlin clustering]](https://github.com/gophercloud/gophercloud/issues/823)

**Comment by jtopjian** [comment]
Fixed in #1250
