### ISSUE TITLE
Octavia: Load balancer pool support for UDP

### ISSUE THREAD

**Issue by itsc0lin** [gophercloud/gophercloud#1252]
The create pool POST operation `protocol` attribute supports an additional argument: `UDP` in the Rocky release of Octavia. This operation is currently not successful when using gophercloud due to the absence of the protocol definition in the listener and pools resources of the lbaas_v2 driver for Openstack.

https://developer.openstack.org/api-ref/load-balancer/v2/index.html#create-pool

**Comment by itsc0lin** [comment]
The relevant changes to the Octavia project can be found here https://github.com/openstack/octavia/commit/a890f2ba35fed4424cf9dcff8224d699431beb45

**Comment by jtopjian** [comment]
Implemented in #1253
