### ISSUE TITLE
Add support for Neutron Standard Attributes Tag Extension

### ISSUE THREAD

**Issue by hardys** [gophercloud/gophercloud#1260]
I've been working with gophercloud and noticed there's no supporting for tagging neutron resources.

Over the last few releases it seems there's a fairly standard way of tagging multiple resource types, documented here:

https://developer.openstack.org/api-ref/network/v2/#standard-attributes-tag-extension

The OpenStack CLI supports this via e.g openstack network create foo --tag abc, but internally this is two API calls, one to create the network/port/subnet/router etc, then another to resource_type/resource_id/tags to set the resource tags.

This potentially makes it easier to add support for all resource types that support tagging, as we hopefully don't need to update every resource, but instead expose this tags API via gophercloud.

I'll push a PR demonstrating this so we can discuss, open to other ideas if there's a better approach.

Line references to the code which implements this in Neutron:

Note this isn't quite a normal CRUD API since it operates on existing resources:

PUT that adds either a single tag (append):
https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L115

... or replaces all of them with a list:
https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L127

Delete one tag:
https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L140

... or delete them all:
https://github.com/openstack/neutron/blob/master/neutron/extensions/tagging.py#L152

When these are implemented it would be good to look at List filtering by tag (which Neutron also supports) but I guess that will be a separate issue - getting the ability to set/unset tags is a prerequisite.

Task List (one task per API action referenced in the API docs above):
- [x] Replace all tags
- [x] Remove all tags
- [x] Confirm a tag
- [x] Add a tag
- [x] List tags
- [x] Remove a tag

**Comment by jtopjian** [comment]
This sounds good to me. If you'd like, you can use this issue to house all PRs which implement the actions. It's common to create a checklist. For example: https://github.com/gophercloud/gophercloud/issues/1199

**Comment by jtopjian** [comment]
@hardys I think this suite is complete? If so, thank you so much - really nice work!

**Comment by hardys** [comment]
@jtopjian yes this is now complete, thanks for all the reviews! :)
