### ISSUE TITLE
Bug: Designate client should not add "v2/" to the endpoint URL retrieved from the catalog

### ISSUE THREAD

**Issue by ynojima** [gophercloud/gophercloud#1261]
https://github.com/gophercloud/gophercloud/blob/12bd25dcbf16eb2a3fa8332bd1136de2304cbdd0/openstack/client.go#L371

Since gophercloud adds "v2/" to the Designate endpoint URL retrieved from the catalog,
it doesn't work in my environment. 

I dug the commit history and found that there was a conversation about adding "v2/" path fragment.

https://github.com/gophercloud/gophercloud/pull/271/files/09115091267350f443c84b2e7a2bd26b4f26cf13#r105315279

It seems original author ( @jtopjian ) 's test environment doesn't have 'v2/' in its catalog data, but 
catalog data should have 'v2/', and gophercloud should not add 'v2/', because as far as we tested with openstack official python-designateclient, official one expects catalog data contains 'v2/'.

**Comment by jtopjian** [comment]
Hi there,

Can you point to an official reference that shows Designate should be published with a `/v2` endpoint? The Designate installation guide shows the creation of a versionless endpoint:

https://docs.openstack.org/designate/latest/install/install-ubuntu.html

In addition, the `python-designateclient` is working for me with a versionless endpoint.

Gophercloud's DNS/Designate support is regularly tested as well as in wide use via Terraform. This is the first reported problem we've had on the endpoint. Is it possible that the OpenStack cloud in question is misconfigured?

**Comment by ynojima** [comment]
Thank you for your comment.
I confirmed latest devstack does register endpoint to the catalog without "/v2" in its url path as you said.
Sorry for taking your time.
I'll close this issue.
