### ISSUE TITLE
Shared file systems: Shares

### ISSUE THREAD

**Issue by mvalkon** [gophercloud/gophercloud#129]
This issue is raised to track the development of the [`shares`](http://developer.openstack.org/api-ref/shared-file-systems/?expanded=#shares) -actions in the shared file systems api v2
- [x] Create a share (#119)
- [x] Delete a share (#120)
- [x] List shares (#1095)
- [x] Show a share (#127)
- [ ] Manage share
- [x] Update share

This issue is a part of #114

**Comment by kayrus** [comment]
Reference for the `Update share`:
API ref: https://developer.openstack.org/api-ref/shared-file-system/?expanded=update-share-detail#update-share
Manila code: v2 ShareController inherits v1 https://github.com/openstack/manila/blob/4f22d0b19e782800b06deba74e6ec15708e5db33/manila/api/v1/shares.py#L210..L214 -> https://github.com/openstack/manila/blob/4f22d0b19e782800b06deba74e6ec15708e5db33/manila/api/v2/shares.py#L26 -> https://github.com/openstack/manila/blob/4f22d0b19e782800b06deba74e6ec15708e5db33/manila/api/v2/shares.py#L40

**Comment by pierreprinetti** [comment]
I am closing this issue, as the implementation (thanks @kayrus) seems to have mostly covered the current needs. Please open a new issue if something is missing and you need it!

**Comment by pierreprinetti** [comment]
and thanks @mvalkon !
