### ISSUE TITLE
Computer V2: why don't we support "Create Multiple Servers" 

### ISSUE THREAD

**Issue by npu21** [gophercloud/gophercloud#1306]
As we can see, the struct  CreateOpts only support create one server one time,but there is a second kind of create call which can build multiple servers at once. This supports all the same parameters as create with a few additional attributes specific to multiple create. refer here please https://developer.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail
In some scenario, we need this ability and it's supposed to be more efficient.
So, do we have a plan to support this or maybe I miss some backgroud info here?

**Comment by jtopjian** [comment]
I could have swore we already had this as an [extension](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions) but it looks like we don't.

Looks like no one hasn't contributed it.

**Comment by npu21** [comment]
@jtopjian ,yeah, just go through the  [https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions](url),but seems don't have this feature;
I could contribute a PR for this and hopes the github is ok then 🤔

**Comment by jtopjian** [comment]
Implemented in #1471
