### ISSUE TITLE
Blockstorage V2: Should support "cascade" and "force" options

### ISSUE THREAD

**Issue by waynr** [gophercloud/gophercloud#1309]
Currently with gophercloud the only way to delete a volume with snapshots is to delete the snapshot(s) then delete the volume. This isn't strictly necessary since Cinder supports a `cascade` option which automatically deletes snapshots related to a volume.

Not using `cascade` also makes it extremely difficult to deterministically delete all volumes and snapshots -- based on my testing, volumes created from snapshots add to the chain of dependent objects and in theory one could create snapshots from volumes created from snapshots created from volumes until one runs out of disk space for metadata on the underlying storage.

* https://github.com/openstack/cinder/blob/31a885c046a28f795cfc1e83ec5ceca4ef005301/cinder/api/v2/volumes.py#L71
* https://github.com/openstack/cinder/blob/3ef65dfaf3e9f8932c5bbe8cddb1a2a40855f625/cinder/volume/api.py#L379
* https://github.com/openstack/cinder/blob/3ef65dfaf3e9f8932c5bbe8cddb1a2a40855f625/cinder/volume/api.py#L479
* https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=delete-a-volume-detail#delete-a-volume

**Comment by waynr** [comment]
Gonna try my hand at fixing this.

**Comment by kayrus** [comment]
@jtopjian this issue can be closed, since it was fixed by #1311
