### ISSUE TITLE
 Octavia: Load balancer pool support for PROXY

### ISSUE THREAD

**Issue by itsc0lin** [gophercloud/gophercloud#1322]
The create pool POST operation protocol attribute supports an additional argument: PROXY in the Rocky release of Octavia. This operation is currently not successful when using gophercloud due to the absence of the protocol definition in the listener and pools requests of the lbaas_v2 driver for Openstack.

**Comment by itsc0lin** [comment]
Can see in this section that PROXY is among the supported protocols:

https://github.com/openstack/octavia/blob/a0112c4b378d02a4c3a0a86265859db54ce3de75/octavia/common/constants.py#L74-L76

**Comment by jtopjian** [comment]
Implemented in #1323
