### ISSUE TITLE
Compute V2: support for scheduler data on compute server creation.

### ISSUE THREAD

**Issue by rodcloutier** [gophercloud/gophercloud#1325]
The OpenStack api for compute allows to specify data for the scheduler in the
form of an additional fields in the `/server` `POST` api route. See the [OpenStack api-ref Create Server](https://developer.openstack.org/api-ref/compute/?expanded=create-server-detail)
for more detailed informations.

Example:
```
{
    "server" : {
        "accessIPv4": "1.2.3.4",
        "accessIPv6": "80fe::",
        "name" : "new-server-test",
        "imageRef" : "70a599e0-31e7-49b7-b260-868f441e862b",
        "flavorRef" : "1",
        "availability_zone": "nova",
        "OS-DCF:diskConfig": "AUTO",
        "metadata" : {
            "My Server Name" : "Apache1"
        },
        "personality": [
            {
                "path": "/etc/banner.txt",
                "contents": "ICAgICAgDQoiQSBjbG91ZCBkb2VzIG5vdCBrbm93IHdoeSBp dCBtb3ZlcyBpbiBqdXN0IHN1Y2ggYSBkaXJlY3Rpb24gYW5k IGF0IHN1Y2ggYSBzcGVlZC4uLkl0IGZlZWxzIGFuIGltcHVs c2lvbi4uLnRoaXMgaXMgdGhlIHBsYWNlIHRvIGdvIG5vdy4g QnV0IHRoZSBza3kga25vd3MgdGhlIHJlYXNvbnMgYW5kIHRo ZSBwYXR0ZXJucyBiZWhpbmQgYWxsIGNsb3VkcywgYW5kIHlv dSB3aWxsIGtub3csIHRvbywgd2hlbiB5b3UgbGlmdCB5b3Vy c2VsZiBoaWdoIGVub3VnaCB0byBzZWUgYmV5b25kIGhvcml6 b25zLiINCg0KLVJpY2hhcmQgQmFjaA=="
            }
        ],
        "security_groups": [
            {
                "name": "default"
            }
        ],
        "user_data" : "IyEvYmluL2Jhc2gKL2Jpbi9zdQplY2hvICJJIGFtIGluIHlvdSEiCg=="
    },
    "OS-SCH-HNT:scheduler_hints": {
        "same_host": "48e6a9f6-30af-47e0-bc04-acaed113bb4e"
    }
}
```
The proposal is add the `OS-SCH-HNT:scheduler_hints` field in create server request for the [compute/v2/servers POST](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L285)

This will require to:

* Add new option to control the field in the `OS-SCH-HNT:scheduler_hints` in  [CreateOpts](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L130),
* Update [ToServerCreateMap()](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L196)  to create the new post payload.

We are willing to start working on the feature once the design is accepted.

**Comment by jtopjian** [comment]
@rodcloutier Scheduler hints are already available [here](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/schedulerhints).

**Comment by rodcloutier** [comment]
@jtopjian Thanks. I totally missed it.

**Comment by jtopjian** [comment]
No problem :)
