### ISSUE TITLE
Network v2: Only set ResourceBase when needed

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1331]
In clouds where the Network v2 service has been published with a "versioned" endpoint, the service client returned by `NewNetworkV2` will be broke since `NewNetworkV2` is also adding `/v2.0/`.

Arguably, publishing the Network service in this way is a customization or configuration error of the cloud in question, but since there's not an easy way to override `ResourceBase` while still retaining compatibility with existing Gophercloud-based apps, we should consider fixing this in Gophercloud itself.

**Comment by clayg** [comment]
For tidiness, do you think it would be better to close this pending a resolution on #1330 ?

**Comment by jtopjian** [comment]
Yep
