### ISSUE TITLE
Add DefaultPoolID update support for the lbaas_v2 listener

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1333]
ATM DefaultPoolID is available only for [new objects](https://github.com/gophercloud/gophercloud/blob/3a7818a07cfc862267a0b03635075a444c92dcda/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go#L101).

Openstack API [does support](https://developer.openstack.org/api-ref/load-balancer/v2/index.html?expanded=update-a-listener-detail#update-a-listener) the `DefaultPoolID` update.

Also it should be possible to unset the default pool from the listener, see #1332

PR is available here: https://github.com/gophercloud/gophercloud/pull/1313

**Comment by jtopjian** [comment]
@kayrus The "new objects" link you gave references the Neutron LBaaS v2 service, but the API documentation you linked to is for Octavia. In the PR, you're updating both. Most likely both do support this, but we need references to the actual Python service API code to verify this (see [here](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-03-code-hunting.md) for instructions). 

* https://github.com/openstack/neutron-lbaas
* https://github.com/openstack/octavia

Please let me know if you have any questions!

**Comment by kayrus** [comment]
neutron-lbaas has an extension since mitaka

There is a shared pool extension for neutron-lbaas: https://github.com/openstack/neutron-lbaas/commit/4f3cf154829fcd69ecf3fa7f4e49f82d0104a4f0

Here are the release notes: https://github.com/openstack/neutron-lbaas/blob/master/releasenotes/notes/l7-and-shared-pools-support-0e181d9b2383db16.yaml

Here the octavia code:

POST: https://github.com/openstack/octavia/blob/d2324cc27611c3237a2931fdbc7b4e69d35e18bb/octavia/api/v2/types/listener.py#L114
PUT: https://github.com/openstack/octavia/blob/d2324cc27611c3237a2931fdbc7b4e69d35e18bb/octavia/api/v2/types/listener.py#L152

let me know if it is enough

**Comment by jtopjian** [comment]
@kayrus This looks good to me. For the neutron-lbaas side, it looks like this field is defined here: https://github.com/openstack/neutron-lbaas/blob/ad3453b90c2772f7349e950eb87f7f6395feeb2e/neutron_lbaas/extensions/sharedpools.py#L53-L56

This means that the `shared_pools` extension needs to be enabled for this field to be valid. It's possible that's a default extension.

**Comment by jtopjian** [comment]
If it's an extension that is not loaded by default then the feature needs to be added as a separate package. For example: https://github.com/gophercloud/gophercloud/tree/master/openstack/networking/v2/extensions/fwaas/routerinsertion

**Comment by jtopjian** [comment]
> How can I identify if it is loaded by default or not?

The easiest way is to either:

1. Check the environment you're working in.
2. If you don't have admin access to that environment, set up a devstack environment and see if you can determine if it was automatically loaded.

However, I got lucky looking through the Neutron code and am pretty confident that it's loaded by default:

* https://github.com/openstack/neutron-lbaas/blob/c672b0d5675e3723df76f4943d9f3e5e7d63fb88/neutron_lbaas/services/loadbalancer/plugin.py
* https://github.com/openstack/neutron/blob/ca13e651c972c4eea5c00e1a84b504e0a34afc55/neutron/manager.py#L169-L179

> BTW, what is the min openstack version supported by gophercloud?

We don't have an official minimum, but de-facto tends to be Mitaka.

**Comment by kayrus** [comment]
Brilliant. Does it mean that I don't need to rewrite the PR as an extension?

**Comment by jtopjian** [comment]
Yes, I think we're safe leaving it as a new field to Listeners.

**Comment by jtopjian** [comment]
Implemented in #1313
