### ISSUE TITLE
The problem with reauth process

### ISSUE THREAD

**Issue by sunny-hw** [gophercloud/gophercloud#1335]
I think the initialization of the tac&tao should be put into func(), otherwise the client will carry the TokenID when the second re-authentication, and there may be problems.

	if options.AllowReauth {
		// here we're creating a throw-away client (tac). it's a copy of the user's provider client, but
		// with the token and reauth func zeroed out. combined with setting `AllowReauth` to `false`,
		// this should retry authentication only once
		tac := *client
		tac.ReauthFunc = nil
		tac.TokenID = ""
		tao := options
		tao.AllowReauth = false
		client.ReauthFunc = func() error {
			err := v2auth(&tac, endpoint, tao, eo)
			if err != nil {
				return err
			}
			client.TokenID = tac.TokenID
			return nil
		}
	}
https://github.com/gophercloud/gophercloud/blob/fac2636416a98a198b71b7ebd8d6acba6a989cd4/openstack/client.go#L158

**Comment by jtopjian** [comment]
@sunny-hw Are you able to reproduce this issue with a unit test?

**Comment by kayrus** [comment]
I suppose this issue can be closed, because an enhanced logic was introduced in #1226.
