### ISSUE TITLE
LBaaSv2 / Octavia: Add l7policy member for the listener structure

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1352]
Mitaka neutron-lbaas extension doesn't return the listener_id for the l7policy, thus it is impossible to identify the loadbalancer status (pending, error, etc).

LB statuses API returns the whole tree of the dependent LB components. Therefore it is possible to detect the LB associated with the L7listener. Adding the the string below won't harm, since it is a result structure:

```diff
diff --git a/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go b/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
index 81cda90..1ec6a5a 100644
--- a/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
+++ b/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
@@ -2,6 +2,7 @@ package listeners
 
 import (
        "github.com/gophercloud/gophercloud"
+       "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies"
        "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools"
        "github.com/gophercloud/gophercloud/pagination"
 )
@@ -55,6 +56,9 @@ type Listener struct {
        // Pools are the pools which are part of this listener.
        Pools []pools.Pool `json:"pools"`
 
+       // L7policies are the L7 policies which are part of this listener.
+       L7Policies []l7policies.L7Policy `json:"l7policies"`
+
        // The provisioning status of the listener.
        // This value is ACTIVE, PENDING_* or ERROR.
        ProvisioningStatus string `json:"provisioning_status"`
```

I honestly tried to find the corresponding openstack python code, which handles this tree behavior, but failed. I just know that it works in Mitaka. Test could be done via curl:

```
$ curl -H "Content-Type: application/json" -H "X-Auth-Token: ${OS_AUTH_TOKEN}" 'http://api:5000/v2.0/lbaas/loadbalancers/977ce39f-3326-489c-8594-023d8b6cc5cf/statuses' | jq -r
```

 Objections?

**Comment by jtopjian** [comment]
So a normal GET on a listener won't return the `l7policies`, but when you query the status of a load balancer, the returned "deep" result contains `l7policies` in the listener portion?

**Comment by kayrus** [comment]
Correct, in Mitaka. Can you test this in Octavia?

**Comment by jtopjian** [comment]
I can confirm that `l7policies` are returned when doing a standard GET to listeners in Octavia:

```json
{
  "listener": {
    "admin_state_up": true,
    "connection_limit": -1,
    "created_at": "2018-12-13T18:09:33",
    "default_pool_id": null,
    "default_tls_container_ref": null,
    "description": "",
    "id": "7a694bf8-b02f-4247-8e52-a0f6ac764930",
    "insert_headers": {},
    "l7policies": [
      {
        "id": "bacdd87e-3b95-421d-bd23-4e0ee8565b0c"
      }
    ],
    "loadbalancers": [
      {
        "id": "f878bf1b-284c-49e2-be46-d68d9382d44f"
      }
    ],
    "name": "",
    "operating_status": "ONLINE",
    "project_id": "c212707a4ec34f43ac88e3c1a43ee7b0",
    "protocol": "TCP",
    "protocol_port": 21,
    "provisioning_status": "ACTIVE",
    "sni_container_refs": [],
    "updated_at": "2018-12-13T18:09:41"
  }
}
```

However, `/status` is returning a very small amount of information:

```json
{
  "statuses": {
    "loadbalancer": {
      "id": "f878bf1b-284c-49e2-be46-d68d9382d44f",
      "listeners": [
        {
          "id": "7a694bf8-b02f-4247-8e52-a0f6ac764930",
          "name": "",
          "operating_status": "ONLINE",
          "pools": [],
          "provisioning_status": "ACTIVE"
        }
      ],
      "name": "TESTACCT-Aw0fCHnu",
      "operating_status": "ONLINE",
      "provisioning_status": "ACTIVE"
    }
  }
}
```



I also checked Vexxhost's Neutron LBaaS v2 service and see that GET to the listener is _not_ returning the L7 Policies:

```json
{
  "listener": {
    "admin_state_up": true,
    "connection_limit": -1,
    "default_pool_id": null,
    "default_tls_container_ref": null,
    "description": "",
    "id": "30201bed-7514-4401-99e8-7ebd98bbd5a3",
    "loadbalancers": [
      {
        "id": "398fdd63-1a31-4a7d-ab34-2ce694a7b2a6"
      }
    ],
    "name": "",
    "protocol": "HTTP",
    "protocol_port": 46,
    "sni_container_refs": [],
    "tenant_id": "c212707a4ec34f43ac88e3c1a43ee7b0"
  }
}
```

But `/status` is:

```json
{
  "statuses": {
    "loadbalancer": {
      "id": "398fdd63-1a31-4a7d-ab34-2ce694a7b2a6",
      "listeners": [
        {
          "id": "30201bed-7514-4401-99e8-7ebd98bbd5a3",
          "l7policies": [
            {
              "action": "REDIRECT_TO_URL",
              "id": "39f4e76e-6bea-4ade-89e5-492aba398568",
              "name": "TESTACCT-DLvQbKWT",
              "provisioning_status": "PENDING_CREATE",
              "rules": []
            }
          ],
          "name": "",
          "operating_status": "ONLINE",
          "pools": [],
          "provisioning_status": "ACTIVE"
        }
      ],
      "name": "TESTACCT-O65EJVy6",
      "operating_status": "ONLINE",
      "pools": [],
      "provisioning_status": "ACTIVE"
    }
  }
}
```

:neutral_face: 

This is a weird situation. Let's go ahead and add `L7Policies` field to the listener results for both Neutron and Octavia. For the Neutron implementation, add some additional doc comments like:

> This field seems to only be returned during a call to a load balancer's /status

If we don't add this field, that means we'll have to duplicate every lbaas result struct and I don't think this single field warrants that. This whole thing seems like a very weird API oddity that is perhaps being caused unintentionally in the Neutron code.

**Comment by jtopjian** [comment]
If I had to guess, this is being caused here: https://github.com/openstack/neutron-lbaas/blob/mitaka-eol/neutron_lbaas/extensions/loadbalancerv2.py#L453-L458

(This also appears to be the case in other tags/branches post-Mitaka, too)

I could be wrong (I haven't fully traced the code), but it appears that block is registering the L7 fields to the load balancer which is why it is returned when doing a `/status` and it has the "deep" results. But it's possible that no injection is being done for the listener model specifically.

**Comment by kayrus** [comment]
Also relates to https://github.com/terraform-providers/terraform-provider-openstack/issues/546
