### ISSUE TITLE
LBaaS_v2: don't omit IDs during the update

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1355]
Similar to #1350.

Listener field should be `null` if it is empty:
* default_pool_id [ref](https://github.com/openstack/neutron-lbaas/blob/mitaka-eol/neutron_lbaas/extensions/sharedpools.py#L55)

**Comment by jtopjian** [comment]
@kayrus From the previous version of this issue, it looks like there will be a few other fields to update? If so, and on the topic of small PRs, you can have multiple PRs opened, each chained off of a previous. This helps accelerate your work-in-progress while waiting for testing/review/approval of other PRs.

There are two methods of doing this, both described [here](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-05-pull-requests.md#dealing-with-related-pull-requests).

**Comment by kayrus** [comment]
> there will be a few other fields to update? 

Yesterday I reviewed neutron lbaas_v2 code and tried to identify pain points in l7 and loadbalancerv2 extensions, but I completely forgot to take a look on sharedpools extension. Considering this, there won't be more fields.

> each chained off of a previous

When I do so, the chained PR looks much bigger and there are a lot of commits from the initial branch. I already did it for l7policy and l7rules, but it appeared to be a mess with rebases and conflics. Nevertheless if you insist, will try them again.

**Comment by jtopjian** [comment]
> When I do so, the chained PR looks much bigger and there are a lot of commits from the initial branch.

This is true, but let's say you have 9 commits spread out across 3 PRs. Each of those PRs is only focused on 3 commits. Additionally, the first PR of a chain will be small-ish, with no other commits interfering with the review. Once it's merged, the reviewer can either ignore previously reviewed work or ask for a rebase which will cut out the parent commits.
