### ISSUE TITLE
LBaaSv2 / Octavia: Add provisioning status struct member for l7policy and l7rule results

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1362]
Neutron LBaaSv2 extension in Mitaka returns l7policies and l7rules provisioning statuses when getting Load Balancer `/statuses` results:

```json
{
  "statuses": {
    "loadbalancer": {
      "name": "loadbalancer_1",
      "provisioning_status": "ERROR",
      "listeners": [
        {
          "name": "listener_1",
          "provisioning_status": "ACTIVE",
          "pools": [
            {
              "name": "pool_1",
              "provisioning_status": "ACTIVE",
              "healthmonitor": {},
              "members": [],
              "id": "dc48ef18-ebd9-4c67-81a3-977630fb15e3",
              "operating_status": "ONLINE"
            }
          ],
          "l7policies": [
            {
              "name": "test",
              "provisioning_status": "ERROR",
              "rules": [
                {
                  "type": "PATH",
                  "id": "8f782815-1bb5-4010-a68c-fed5433b0bb6",
                  "provisioning_status": "ACTIVE"
                }
              ],
              "action": "REDIRECT_TO_POOL",
              "id": "8b9b92d1-ebcd-4bff-938e-6d0cae139f4c",
              "operating_status": "DEGRADED"
            }
          ],
          "id": "6399c03f-703e-45d8-8b58-67228bf706ef",
          "operating_status": "DEGRADED"
        }
      ],
      "pools": [
        {
          "name": "pool_1",
          "provisioning_status": "ACTIVE",
          "healthmonitor": {},
          "members": [],
          "id": "dc48ef18-ebd9-4c67-81a3-977630fb15e3",
          "operating_status": "ONLINE"
        }
      ],
      "id": "4a9a810a-3794-4e22-aa16-03356554a43d",
      "operating_status": "DEGRADED"
    }
  }
}
```

We can add them into the l7policies structures.

Followup from the https://github.com/terraform-providers/terraform-provider-openstack/issues/546 and https://github.com/terraform-providers/terraform-provider-openstack/pull/527
Relates to #1352 and https://github.com/terraform-providers/terraform-provider-openstack/issues/546

**Comment by jtopjian** [comment]
The code can be seen here: https://github.com/openstack/neutron-lbaas/blob/ad3453b90c2772f7349e950eb87f7f6395feeb2e/neutron_lbaas/services/loadbalancer/data_models.py

And searching for `provisioning_status` and `operating_status`. The caveat here, as mentioned, is that they are only returned when doing a status on the load balancer.

**Comment by jtopjian** [comment]
@kayrus Actually, according to the above link, L7 resources do not have an `operating_status` field. In fact, they seem to be explicitly excluded:

* https://github.com/openstack/neutron-lbaas/blob/c672b0d5675e3723df76f4943d9f3e5e7d63fb88/neutron_lbaas/services/loadbalancer/plugin.py#L1062-L1076
* https://github.com/openstack/neutron-lbaas/blob/c672b0d5675e3723df76f4943d9f3e5e7d63fb88/neutron_lbaas/services/loadbalancer/plugin.py#L1154-L1155

I'm not sure how they are appearing in your output - might require further investigation.

**Comment by kayrus** [comment]
Since neutron extension code will be used in Octavia as well, Octavia supports both `provisioning_status` and `operating status` for l7rule: https://developer.openstack.org/api-ref/load-balancer/v2/?expanded=show-l7-rule-details-detail#show-l7-rule-details
I guess its worth adding `operating` field for rule l7?

**Comment by kayrus** [comment]
> they seem to be explicitly excluded

Looks like the status is excluded when it is ok. If it is not ok, then it is returned.

**Comment by jtopjian** [comment]
>  Since neutron extension code will be used in Octavia as well (terraform provider), 

Remember that this is only coincidental because the code across the two projects is the same. In order to update the structs in Gophercloud, we need to ensure the fields exist in the off-chance that there's a difference. In this case, Octavia supports these fields as well:

* https://github.com/openstack/octavia/blob/f1b9e463cc062c4943983944d371f604ea904609/octavia/api/v2/types/l7policy.py#L33-L34
* https://github.com/openstack/octavia/blob/f1b9e463cc062c4943983944d371f604ea904609/octavia/api/v2/types/l7rule.py#L34-L35

**Comment by jtopjian** [comment]
> I guess its worth adding operating_status field for l7 rule as well?

From what I can see, it's a valid field, so go for it :)

**Comment by kayrus** [comment]
I put statuses into neutron lbaas with an exception comment, and in octavia without an exception comment.
