### ISSUE TITLE
LBaaSv2 / Octavia: merge acceptance tests

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1363]
Every change, which was made for lbaas_v2 extension, could be reflected in octavia code, tests also should be synced. It is hard to maintain these tests via copy-paste. I'd prefer to merge them.

**Comment by jtopjian** [comment]
I think it's safe to say that all LBaaS v2 tests can be run by Octavia, but not the other way around. 

There's indeed a good amount of overlap, but as Octavia continues to develop, there will be areas that are different (though small in the beginning). The notable example of this is Octavia's Cascading Delete support.

If the LBaaS v2 tests could be imported into the Octavia packages, that would be the best way to go. This way Octavia is triggering a test in its own namespace.

Additionally, I have a note to myself to break the L7 stuff out into their own separate tests. This way the core LB functionality (everything but L7) can be tested in environments that don't support L7.

**Comment by jtopjian** [comment]
I'm going to close this issue. There have been a handful of small updates to the acceptance tests which are unique to Octavia. While there is some overlap between Octavia and LBaaSv2, they should be treated separately.
