### ISSUE TITLE
Compute V2: support for strings services IDs

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1370]
OpenStack Compute V2 API Services response contains string representation for `id` field starting from `2.53` microversion: [2.53 os-services](https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#maximum-in-pike).

Currently Gophercloud supports only int representation for this field: [services/results.go#L23](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/services/results.go#L23) and it should be fixed.

[API reference](https://developer.openstack.org/api-ref/compute/?expanded=list-compute-services-detail#list-compute-services)
[Gophercloud Microversions discussion](https://github.com/gophercloud/gophercloud/issues/441)

**Comment by jtopjian** [comment]
Implemented in #1500
