### ISSUE TITLE
Why does gophercloud ignores zerovalue?

### ISSUE THREAD

**Issue by xioxu** [gophercloud/gophercloud#1384]
If a struct has a requied field and use basic type like 'int', 'bool', if the value is 0, false, gophercloud.BuildRequestBody will throw an error, the reason is because params.go will ignore the zerovalue.

My question is the zero value may be the expected value,  in that case, how do we submit a zerovalue?

BTW, I strongly suggest gophercloud provides some nullable types, like Java Integer, like C# NullabeInt ..., use point is really not a user friendly practice, but It seems we hava no other choise in current gophercloud.

**Comment by jtopjian** [comment]
@xioxu zero values are handled by using pointer types:

* `*int`
* `*bool`
* etc

These are used throughout Gophercloud.

Can you provide a specific issue you are seeing?

**Comment by jtopjian** [comment]
>  use point is really not a user friendly practice, but It seems we hava no other choise in current gophercloud.

I believe you mean "but it seems we have no other choice in current Go" :slightly_smiling_face: 

What Gophercloud is doing is standard best practice with Go. But again, let me know if you are seeing a specific issue, in which case there might be a bug.

**Comment by xioxu** [comment]
1. How to handl if the server response { size: null }
2. To set a value to a *int, we have to define a useless variable.

In golang office package, it also provides some NullableType in sql package to solve similar scence, What I sugges is like https://gopkg.in/nullbio/null.v6, what do you think about it?

**Comment by jtopjian** [comment]
> I also agree that the pointer can handle that cases, but I just think pointer is not user friendly.

I appreciate the input, but I think this is an opinion that varies from person to person (and project to project).

For example, the AWS Go SDK uses pointer fields for _everything_: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#ImportImageInput

I think a pointer provides a clear indication that a field has a special behavior when a zero-value is used. This indication would be lost if we used some kind of custom nullable-type for all fields.
