### ISSUE TITLE
Compute V2: support for strings hypervisors IDs

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1388]
OpenStack Compute V2 API Hypervisors response contains string representation for id field starting from 2.53 microversion: [2.53 os-hypervisors](https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#maximum-in-pike).

Currently Gophercloud supports only int representation for this field: [hypervisors/results.go#L75](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/hypervisors/results.go#L75) and it should be fixed.

[API reference](https://developer.openstack.org/api-ref/compute/?expanded=#list-hypervisors)
[Gophercloud Microversions discussion](https://github.com/gophercloud/gophercloud/issues/441)

**Comment by jtopjian** [comment]
Implemented in #1500
