### ISSUE TITLE
Networking v2: add DNS extension support

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1399]
https://github.com/openstack/neutron/blob/mitaka-eol/neutron/extensions/dns.py#L207..L236

For ports, floating IPs and networks.

**Comment by jtopjian** [comment]
@kayrus See https://github.com/gophercloud/gophercloud/issues/776 and the corresponding PR for more information about this.

**Comment by kayrus** [comment]
Duplicate #776

**Comment by kayrus** [comment]
Won't close, since this PR contains API references. @jtopjian is it required to create an extension or just add these fields into the existing structures?

**Comment by jtopjian** [comment]
See my comment here: https://github.com/gophercloud/gophercloud/pull/777#issuecomment-366842867

**Comment by kayrus** [comment]
Ok
