### ISSUE TITLE
Octavia: tags support for load balancers

### ISSUE THREAD

**Issue by lingxiankong** [gophercloud/gophercloud#1404]
- [x] Include `tags` for getting load balancer
- [x] Include `tags` for listing load balancers
- [x] Specify `tags` for creating load balancer
- [x] Specify `tags` for updating load balancer
- [x] Query load balancer by tags

**Comment by lingxiankong** [comment]
Waiting for this patch https://review.openstack.org/632013 in octavia.

**Comment by jtopjian** [comment]
@lingxiankong Thank you for your work on this! I'm going to close this, but let me know if you'd like it re-opened for further work.

🎉
