### ISSUE TITLE
Bug: Messaging Claims Create Causes Crash 

### ISSUE THREAD

**Issue by JackKuei** [gophercloud/gophercloud#1420]
Got panic trace due to runtime error. Possibly triggered with authentication failure

Jan 17 07:08:34 xxxx[3961]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 17 07:08:34 xxxx[3961]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb56cb8]
Jan 17 07:08:34 xxxx[3961]: goroutine 99 [running]:
Jan 17 07:08:34 xxxx[3961]: xxxx/vendor/github.com/gophercloud/gophercloud/openstack/messaging/v2/claims.Create(0xc0001a3f90, 0xc000450e70, 0x25, 0xef0880, 0
Jan 17 07:08:34 xxxx[3961]: xxxx/vendor/github.com/gophercloud/gophercloud/openstack/messaging/v2/claims/requests.go:60 +0x1d8

**Comment by jtopjian** [comment]
Fixed in #1421
