### ISSUE TITLE
Openstack client: don't fail on ErrDefault429

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1428]
If there are too many requests made to the openstack API, terraform just fails. Any objections on adding wait -> retry approach into the client logic?

**Comment by jtopjian** [comment]
> Any objections on adding wait -> retry approach into the client logic?

Yes, it should be up to the application to resolve that.

**Comment by jtopjian** [comment]
For Terraform specifically, is this relevant? https://github.com/terraform-providers/terraform-provider-openstack/pull/413

**Comment by kayrus** [comment]
Unfortunately not, that option works only when there is a transport level problem.

**Comment by jtopjian** [comment]
@kayrus Right, that PR specifically was about transport level problems, but the same area of code should be able to handle this, too:

```diff
diff --git a/openstack/types.go b/openstack/types.go
index b1601d6..d40948f 100644
--- a/openstack/types.go
+++ b/openstack/types.go
@@ -87,6 +87,10 @@ func (lrt *LogRoundTripper) RoundTrip(request *http.Request) (*http.Response, er
                response.Body, err = lrt.logResponse(response.Body, response.Header.Get("Content-Type"))
        }
 
+       if response.StatusCode == 429 {
+               // retry
+       }
+
        return response, err
 }
```
