### ISSUE TITLE
Provide versioned releases

### ISSUE THREAD

**Issue by onitake** [gophercloud/gophercloud#1432]
Due to a breaking API change in https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/volumes/requests.go#L86 , I'm having trouble updating transitive dependencies in a project related to Kubernetes.

Since this API is unversioned and gophercloud doesn't provide versioned releases, it's hard to track down where the API was changed and pin the commit hash.

Please introduce release tags for gophercloud so it's easier to track changes.

**Comment by jtopjian** [comment]
This is a valid request, but I'm going to close this in favor of #1084.
