### ISSUE TITLE
An auth with token example is needed

### ISSUE THREAD

**Issue by larryck** [gophercloud/gophercloud#1455]
From the README.md file we know clearly how to auth with username/passwd. But it really took me some time to figure out how to auth with tokenid. So I think an example will be great for new users to handle this quickly.  We can add some thing like this:

```
  // auth with token
    opts := gophercloud.AuthOptions{
        IdentityEndpoint: "{identityendpoint}",
        TokenID: "{tokenid}",
        TenantID: "{tenantid}",
    }
    provider, err := openstack.AuthenticatedClient(opts)
```

**Comment by jtopjian** [comment]
Implemented in #1540
