### ISSUE TITLE
Run Baremetal acceptance tests on openlab

### ISSUE THREAD

**Issue by iurygregory** [gophercloud/gophercloud#1466]
All PR's for #1429 have acceptance tests, but we don't have ironic enable on the openlab CI.
I've already talked with the openlab people and we can have Ironic running on devstack, my proposal is:

- Add support to enable ironic service on openlab
- Enable ironic on  gophercloud-acceptance-test job or create a new job.

Any thoughts?

**Comment by jtopjian** [comment]
This sounds fine with me, though let's have Ironic be tested in a separate job than the default suite that is run.

**Comment by iurygregory** [comment]
Hi @jtopjian I will start this work next week =) Thanks

**Comment by jtopjian** [comment]
Implemented in #1483
