### ISSUE TITLE
Networking V2: Failed to delete external gateway info

### ISSUE THREAD

**Issue by posox** [gophercloud/gophercloud#1467]
ExternalGatewayInfo cannot be deleted for the router. I use the following code:

```
updateOpts := routers.UpdateOpts{
  GatewayInfo: &routers.GatewayInfo{},
}
_, err := routers.Update(client, routerID, updateOpts)
```

In neutron logs I see:
```
update failed (client error): Invalid input for external_gateway_info. Reason: '' is not a valid UUID.
```

`GatewayInfo` struct should be empty for deleting external gateway for router.

**Comment by jtopjian** [comment]
Fixed in #1470 

@posox Thank you for reporting and fixing this.
