### ISSUE TITLE
Feature request: support context.Context to cancel/time-out requests

### ISSUE THREAD

**Issue by simonpasquier** [gophercloud/gophercloud#1476]
IMHO it would be neat if one could pass an existing `context.Context` that would be propagated to the outgoing HTTP requests. Concrete example: Prometheus uses gophercloud for its [OpenStack service discovery](https://github.com/prometheus/prometheus/tree/master/discovery/openstack) (aka SD) which lists OpenStack instances at regular intervals. The SD goroutine gets a context that is canceled when it needs to exit (because the program stops or the configuration gets reloaded). Right now it means that when a request to the Nova API is in progress and the context is canceled, we need to wait for the request completion before effectively returning.

Implementation-wise, I could see it as an additional `Context` field to the [`gophercloud.ProviderClient`](https://godoc.org/github.com/gophercloud/gophercloud#ProviderClient) struct. If not nil, the context would be injected in the constructed [`http.Request`](https://github.com/gophercloud/gophercloud/blob/307b801773c3c1018ca059dd511b9a08714e97d6/provider_client.go#L313).

If this is something that is found helpful, I'm willing to start a PR.

**Comment by jtopjian** [comment]
@simonpasquier This sounds interesting and I think it's worth exploring more.
