### ISSUE TITLE
Networking V2: Impossible to create/update port binding profile with the nested struct

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1477]
It is impossible to set nested struct into the `binding:profile`. Currently the best we can do is to set an escaped json string as a value.

For instance, the json for the `local_link_information` key below:

```json
[
    {
      "switch_info": "test1",
      "port_id": "Ethernet3/4",
      "switch_id": "12:34:56:78:9A:BC"
    },
    {
      "switch_info": "test2",
      "port_id": "Ethernet3/4",
      "switch_id": "12:34:56:78:9A:BD"
    }
  ]
```

results in:

```json
"local_link_information": "[{\"switch_info\": \"test1\", \"port_id\": \"Ethernet3/4\", \"switch_id\": \"12:34:56:78:9A:BC\"}, {\"switch_info\": \"test2\", \"port_id\": \"Ethernet3/4\", \"switch_id\": \"12:34:56:78:9A:BD\"}]"
```

**Comment by jtopjian** [comment]
Looks like a map/dictionary/object is the correct data structure: https://github.com/openstack/neutron-lib/blob/98764984c9ab722312b89236da2456bc40429987/neutron_lib/api/definitions/portbindings.py#L178
