### ISSUE TITLE
Possible to create invalid v3 auth if just project_name defined.

### ISSUE THREAD

**Issue by leigh-j** [gophercloud/gophercloud#1491]
When using v3 auth and using projects not in the default domain, specifying just project name is not valid according to the spec.
[From the spec](https://developer.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-scoped-authorization-detail#authenticating-with-an-application-credential)

> An ID is sufficient to uniquely identify a project but if a project is specified by name, then the domain of the project must also be specified in order to uniquely identify the project by name. A domain scope may be specified by either the domain’s ID or name with equivalent results.

This is a quirky corner case with the openstack api.

**Comment by jtopjian** [comment]
Fixed in #1492
