### ISSUE TITLE
baremetal APIs need support for 409 conflict errors

### ISSUE THREAD

**Issue by dhellmann** [gophercloud/gophercloud#1497]
Many Ironic API calls for nodes return a 409 status if the node is "locked" by some other operation at the time of the call. It will be more convenient for callers if there is an error class to handle 409 errors like other common error codes.

- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L507
- https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L642

**Comment by dhellmann** [comment]
@jtopjian I'm working on this change now. I was going to just call the error class ErrDefault409 to match the others that had HTTP status codes in their names. Does that seem OK, or would you rather have it called ErrConflict or something?

**Comment by jtopjian** [comment]
@dhellmann Sounds good - thanks! The individual errors are helpful and I can totally merge #1498 when it's ready, but just a side note that you can still access the 409 (or any other missing error) without the specific error type. We do this a lot in Terraform: https://github.com/terraform-providers/terraform-provider-openstack/search?q=409&unscoped_q=409

**Comment by dhellmann** [comment]
Yeah, I had to do that in one or two places already in our code, too. This seemed like it would make it less of a hassle, but there's no rush on merging it.

**Comment by jtopjian** [comment]
> This seemed like it would make it less of a hassle

Agreed. I just wanted to make sure you weren't being blocked in the meantime :)

> but there's no rush on merging it

It looks like OpenLab is having some issues. I'm quite sure the patch is good, but will wait until everything is back up and running. If the downtime goes on for a while, I'll test it offline.

**Comment by dhellmann** [comment]
> > This seemed like it would make it less of a hassle
> 
> Agreed. I just wanted to make sure you weren't being blocked in the meantime :)

Yep, thanks!

> > but there's no rush on merging it
> 
> It looks like OpenLab is having some issues. I'm quite sure the patch is good, but will wait until everything is back up and running. If the downtime goes on for a while, I'll test it offline.

Sure, no problem.

**Comment by jtopjian** [comment]
Implemented in #1498
