### ISSUE TITLE
Network v2: Use a string pointer for Network UpdateOpts Name

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1508]
The `Name` field in networks' `UpdateOpts` should be a `*string` instead of a `string`:

https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/networks/requests.go#L115

This is to allow a name to be set to `""`.

**Comment by kayrus** [comment]
https://github.com/openstack/neutron/blob/mitaka-eol/neutron/api/v2/attributes.py#L683

Probably you have to do the same for other network objects. Except subnetpools https://github.com/openstack/neutron/blob/mitaka-eol/neutron/api/v2/attributes.py#L835

**Comment by jtopjian** [comment]
Implemented in #1539
