### ISSUE TITLE
Objectstorage v1: metadata cannot be removed from containers

### ISSUE THREAD

**Issue by NeilW** [gophercloud/gophercloud#1511]
There doesn't appear to be a way to remove metadata entry from a container with gophercloud. If you set a key to a null string the empty header is stripped from the request when the POST is made. 

If sending empty headers is not possible, there is a X-Remove-Container-Metadata-XXX header option, which would probably require another field (RemoveMetadata []string).

**Comment by NeilW** [comment]
https://developer.openstack.org/api-ref/object-store/?expanded=#create-update-or-delete-container-metadata

**Comment by jtopjian** [comment]
@NeilW I apologize for the late reply on this. This will be resolved when #1538 is merged.

**Comment by jtopjian** [comment]
Implemented in #1538
