### ISSUE TITLE
Is there a way to get the hardware configuration histories of an instance?

### ISSUE THREAD

**Issue by sirius1024** [gophercloud/gophercloud#1522]
Is there a way to get change history of the flavor of an instance? It will be useful for the billing things or audit check.
For example, an instance upgrade from 2 CPU cores to 4 so we should change its flavor, I want to get those records to show the change history.

**Comment by jtopjian** [comment]
@sirius1024 There isn't an API call to retrieve the history of a flavor. In fact, the last time I checked, a flavor's history is not recorded in the underlying Nova database, either.

I'm going to close this issue, but let me know if you have any other questions.

**Comment by sirius1024** [comment]
@jtopjian Sorry for my poor English. What I want to do is get histories of an instance, just like flavor changed, mount new disk etc.
If we have requirements to do an accurate billing/charging module, should we do some hook stuff when the instance its hardware configuration(flavor) changed?

**Comment by jtopjian** [comment]
I think there are two things to look into:

1. Notifications: https://docs.openstack.org/nova/latest/reference/notifications.html

Notifications are emitted from Nova whenever an action happens. These are emitted in real-time and might be lost.

2. List instance actions: https://developer.openstack.org/api-ref/compute/?expanded=list-actions-for-server-detail#list-actions-for-server

This API call has not been implemented in OpenStack yet. If this is what you're looking for, I can re-open this issue as a feature request to have this added.
