### ISSUE TITLE
Support listing loadbalancer API versions

### ISSUE THREAD

**Issue by MaysaMacedo** [gophercloud/gophercloud#1523]
The OpenStack Octavia API includes, in its 2.5 version, the support for tagging octavia resources.
When trying to consume this new API support, already added in Gophercloud, the version of Octavia API needs to be verified, because if tags is not supported in the applied version, another filtering solution must be used.

This issue is about adding apiversions package for load-balancer described in here:
`
https://developer.openstack.org/api-ref/load-balancer/?expanded=#`

**Comment by jtopjian** [comment]
@MaysaMacedo You're in luck 🙂 

This PR should help you with this: https://github.com/gophercloud/gophercloud/pull/1521

**Comment by lingxiankong** [comment]
Hi @MaysaMacedo, for double check, if you don't specify tags param when creating the resource, do you still see the error?

**Comment by MaysaMacedo** [comment]
Thank you, @jtopjian  :)

Hi @lingxiankong, I've only had the opportunity to test in an env that octavia API did not have tag support. Thus, when creating a resource and then filtering with tags to delete specific resources, would result in an error, which I believe to be the expected behavior.

**Comment by ozerovandrei** [comment]
Implemented in #1524, thank you @MaysaMacedo !
