### ISSUE TITLE
Keymanager: add "Expiration" into the secrets CreateOpts

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1526]
It is useful to control the expiration date of the certificate, therefore I suggest to add an Expiration field into the barbican secret resource. refs to https://github.com/terraform-providers/terraform-provider-openstack/pull/650
The fix is very simple and I already verified it works.

source code refs: https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/objects/secret.py#L32
https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/common/validators.py#L162
https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/api/controllers/secrets.py#L424
https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/api/controllers/secrets.py#L435
https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/api/controllers/secrets.py#L442
https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/plugin/resources.py#L359..L361
https://github.com/openstack/barbican/blob/4c0ddda941289fba8e5ec4341b5d02d155d46162/barbican/model/repositories.py#L391

The `secret_model` is passed through the function with the `expiration` field.

**Comment by jtopjian** [comment]
Implemented in #1537
