### ISSUE TITLE
Providing region results in no suitable endpoint could be found

### ISSUE THREAD

**Issue by floreks** [gophercloud/gophercloud#1532]
When providing a `Region` parameter while talking to API `v3.2`+, the above error is returned.

```go
sc, err := goopenstack.NewIdentityV3(authClient, gophercloud.EndpointOpts{Region: region})
```

[This](https://github.com/gophercloud/gophercloud/blob/master/openstack/endpoint_location.go#L86-L89) part of code checks if provided `Region` or `RegionID` of `Endpoint` matches `Region` specified in `EndpointOpts`.

The weird thing is that the `Endpoint` structure I am getting when debugging the code looks like this:

| ID | Region | RegionID | Interface | URL |
| --- | ---------- | ------------ | ------------ | ------ |
| 31324596ad02403290f51b5a20ddfc21 | * | * | public | https://url/v3 |

Is it normal that `*` is returned instead of correct region id/name? If so, shouldn't this check be extended to do a regex match with the provided region?

Removing `EndpointOpts` from the `NewIdentityV3` call "fixes" it on our side, but I am wondering if it is not a bug.

**Comment by jtopjian** [comment]
> Is it normal that * is returned instead of correct region id/name?

I'm not sure. Is this a new way of handling regions in a newer version of OpenStack? Is `*` a valid value or is this something unique that your cloud is doing?

Generally, the `Region` field should be whatever `OS_REGION_NAME` is set to - usually a human-readable name. But if Regions are being reported differently in Keystone, then, yes, we probably should extend the check with either an explicit `*` or some kind of regex.

**Comment by floreks** [comment]
This is external client infrastracture. I will ask if this is some custom openstack configuration or default one and report back.

**Comment by floreks** [comment]
Unfortunately, we are not in contact with the customer anymore and we can't confirm if this is a custom openstack installation.

**Comment by jtopjian** [comment]
@floreks Thank you for looking into this. I'm going to close this issue for now but anyone is free to request it to be re-opened if they can provide more information.

**Comment by hdurand0710** [comment]
It seems that we have another occurence of this issue at a customer. I've asked if they have a custom or a default open stack installation.
In the meantime, can we (@jtopjian ) please re-open this issue ?
