### ISSUE TITLE
Networking v2: Cannot unset DNS Nameservers

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1535]
Per https://github.com/terraform-providers/terraform-provider-openstack/issues/728, it's not possible to unset all of the DNS Nameservers in a subnet.

**Comment by kayrus** [comment]
Thanks, I'm incapable of handling all the PRs

**Comment by jtopjian** [comment]
No worries at all - you do plenty as it is 🙂  Making sure the bugs are reported is extremely helpful in itself.

**Comment by jtopjian** [comment]
Implemented in #1535
