### ISSUE TITLE
imageservice missing in gophercloud/gophercloud but availabile in rackspace/gophercloud

### ISSUE THREAD

**Issue by kars7e** [gophercloud/gophercloud#154]
Hi gophercloud team, 

I've noticed that imageservice is available in rackspace/gophercloud: https://github.com/rackspace/gophercloud/tree/master/openstack/imageservice/v2

However it's missing in this repo: https://github.com/gophercloud/gophercloud/tree/master/openstack

Was that intentional, or will that part also get ported to new repo?

Thanks,
Karol

**Comment by jrperritt** [comment]
> will that part also get ported to new repo?

I am currently working on exactly this.

**Comment by jrperritt** [comment]
closed by #171

**Comment by kars7e** [comment]
Thanks @jrperritt !

**Comment by jtopjian** [comment]
Nice!
