### ISSUE TITLE
Add additional fields at struct UpdateOpts same as Volume struct

### ISSUE THREAD

**Issue by unixzen** [gophercloud/gophercloud#1547]
Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

**Comment by unixzen** [comment]
Hello!

I try make snapshot of volume and get error message

```
error message: {"badRequest": {"message": "Invalid volume: Volume 91cedfd1-1d8b-4d62-bdb1-4414a21e01db status must be available, but current status is: in-use.", "code": 400}}
```

But i try change status of volume to available for making snapshot, but i get another error:

```
./snapshot_create.go:38:41: unknown field 'Status' in struct literal of type volumes.UpdateOpts 
```
I think that problem
https://godoc.org/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes#UpdateOpts

At struct UpdatOpts there are 3 fields, but at the same time at Volume struct about 20. Can you fix this? Or may be i can try make PR. Thanks!

**Comment by jtopjian** [comment]
The block storage API only allows a subset of fields to be updated: https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=update-a-volume-detail#update-a-volume

If your environment requires you to detach a volume before snapshotting, perhaps the [`volumeattach`](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/volumeattach) package can help?

**Comment by unixzen** [comment]
At my environment i can't detach volume. I found flag force (https://godoc.org/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots#CreateOpts), i could be using it. But i saw that PR (https://github.com/gophercloud/gophercloud/pull/960) still not merge to master branch. And it means gophercloud still not support cinder backup possibility?

**Comment by unixzen** [comment]
> At my environment i can't detach volume. I found flag force (https://godoc.org/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots#CreateOpts), i could be using it. But i saw that PR (#960) still not merge to master branch. And it means gophercloud still not support cinder backup possibility?

What about this @jtopjian :point_up: , i mean merge request about backup possibility?

**Comment by jtopjian** [comment]
@unixzen I'll work on getting #960 merged. It needs to be cleaned up / reorganized as well as have acceptance tests added.

**Comment by unixzen** [comment]
> @unixzen I'll work on getting #960 merged. It needs to be cleaned up / reorganized as well as have acceptance tests added.

What i could be doing for helping by that task? As i understood, need write tests and make 1 commit at 1 action? As you describe there https://github.com/gophercloud/gophercloud/pull/960. Perhaps you give me step-by-step guide and i start doing something useful, may be some details i wrong understood.

**Comment by jtopjian** [comment]
@unixzen I apologize for the delay. The snapshots have been merged. I'm going to close this issue but please let me know if you have any questions.
