### ISSUE TITLE
Baremetal API v1: constants declared as strings and not the appropriate type

### ISSUE THREAD

**Issue by stbenjam** [gophercloud/gophercloud#1557]
Only Enroll is a nodes.ProvisionState, I had the misconception that the type got inherited by the other variables in a const block, like iota does but that doesn't seem to be the case:

https://github.com/gophercloud/gophercloud/blob/master/openstack/baremetal/v1/nodes/requests.go#L21

**Comment by jtopjian** [comment]
@stbenjam Good catch. I've left a description about this here: https://github.com/metal3-io/baremetal-operator/pull/171/files#r279417949
