### ISSUE TITLE
GitHub Templates

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#156]
Would it make sense to create a some [GitHub templates](https://github.com/blog/2111-issue-and-pull-request-templates)?

This might help point new contributors to the style guide or a friendly reminder to either ensure a corresponding issue is opened, make sure relevant API docs and code is referenced in issues, etc.

**Comment by jrperritt** [comment]
I think that's a great idea

**Comment by jrperritt** [comment]
I'll take care of this.

**Comment by jrperritt** [comment]
closed by #180 (though they can probably be improved)
