### ISSUE TITLE
Add SSSD Support to GopherCloud Keystone Auth

### ISSUE THREAD

**Issue by hogepodge** [gophercloud/gophercloud#1560]
We intent to add an additional header to Keystone authentication to enable SSSD support for Kerberos-based (GSSAPI) authetication. This will require the addition of a golang kerberos library to support the authentication. Candidate libraries include:

https://gopkg.in/jcmturner/gokrb5.v5
https://github.com/apcera/gssapi

This is to extend support to the kubernetes/cloud-provider-openstack. 

https://github.com/kubernetes/cloud-provider-openstack/issues/406
cc @strigazi 
cc @Fedosin

**Comment by jtopjian** [comment]
> This will require the addition of a golang kerberos library to support the authentication

I'm not familiar with SSSD, so I'm not sure why/if the libraries have to be tightly coupled to Gophercloud. One concern I have about this is how it will affect projects that consume Gophercloud. For example, per https://github.com/apcera/gssapi#building:

> This library is go get compatible. However, it also requires header files to build against the GSSAPI C library on your platform.

We'll definitely want to look at how the kerberos part of this can be decoupled.
