### ISSUE TITLE
Updating a recordset removes TTL

### ISSUE THREAD

**Issue by Kiemes** [gophercloud/gophercloud#1562]
I am using terraform v0.11.13 with OpenStack provider v1.17.0.

Creating a recordset like this with `terraform apply`  results in the intended recordset with a TTL of 1800:
<pre>
resource "openstack_dns_recordset_v2" "rs_example_com" {
  zone_id = "${var.zone_id}"
  name = "test.example.com"
  description = "An example record set"
  <b>ttl = 1800</b>
  type = "A"
  records = ["10.0.0.1"]
}
</pre>

Updating the recordset i.e. the `records` IP to `10.0.0.2` with `terraform apply`, removes the `ttl` value.

Result from `openstack recordset show c13f7e8d-90dc-43e3-9f83-1e5c84a164aa dcd22312-9171-4c85-8ff3-4d362e3a9fff` after the update:

<pre>
+-------------+--------------------------------------+
| Field       | Value                                |
+-------------+--------------------------------------+
| action      | NONE                                 |
| created_at  | 2019-05-06T13:31:27.000000           |
| description | An example record set                |
| id          | dcd22312-9171-4c85-8ff3-4d362e3a9fff |
| name        | test.example.com  |
| project_id  | 10dd7b72021c4b12bb872e8dc43b34fe     |
| records     | 10.0.0.2                             |
| status      | ACTIVE                               |
| <b>ttl</b>         | <b>None</b>                                 |
| type        | A                                    |
| updated_at  | 2019-05-06T13:34:42.000000           |
| version     | 2                                    |
| zone_id     | c13f7e8d-90dc-43e3-9f83-1e5c84a164aa |
| zone_name   | test.example.com       |
+-------------+--------------------------------------+
</pre>

It looks like, the request to OpenStack [updating the recordset](https://developer.openstack.org/api-ref/dns/?expanded=update-a-recordset-detail#update-a-recordset) contains a `"ttl" : null` attribute in the request body. I cannot say it for sure since the actual request call is not logged. I didn't use Wireshark or so to verify. Sending an PUT on recordset containing `"ttl" : null` will set `ttl` of the recordset to null when it had a value before. This seems to be happening [here](https://github.com/gophercloud/gophercloud/blob/master/openstack/dns/v2/recordsets/requests.go#L138-L142) since the [update method](https://github.com/terraform-providers/terraform-provider-openstack/blob/f584c08329660563c8772bbf6755ca0571cd4297/openstack/resource_openstack_dns_recordset_v2.go#L171) in terraform-provider-openstack sends `TTL:0` [here](https://github.com/terraform-providers/terraform-provider-openstack/blob/f584c08329660563c8772bbf6755ca0571cd4297/openstack/resource_openstack_dns_recordset_v2.go#L201)

Not sending TTL info in the update request if TTL was not changed should fix this. I am not sure where you best fix this, in gophercloud or terraform-provider-openstack or both, but since you are anyhow maintaining both repos, I guess you can decide best @jtopjian.

**Comment by jtopjian** [comment]
@Kiemes Good catch.

#1563 is the first part of fixing this. Once merged, I'll get Terraform fixed.

**Comment by jtopjian** [comment]
Fixed in #1563
