### ISSUE TITLE
identity/v3/tokens.Get() swallows connection errors

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#1569]
PR coming up in a second.

*Edit:* Maybe to provide a bit more context, I was seeing an entirely empty `GetResult` returned from a call to `tokens.Get()`, because the endpoint I was using was not reachable from my development machine. With the fix in #1570, I'm now seeing an appropriate error in `result.Err`.

**Comment by jtopjian** [comment]
Fixed in #1570
