### ISSUE TITLE
Wrong umlauts encoding when working with environment variables in Windows

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1572]
When user sources an UTF-8 environment file with umlauts in powershell, auth doesn't work. It is caused by bad encoding features. I could assume that it's an encoding file issue, but regular openstack python CLI tools don't support ENV, when they are not in UTF-8, they fail with:

```sh
$ openstack server list
'utf8' codec can't decode byte 0xfc in position 1: invalid start byte
```

I prepared a test file:

```
$ cat foo.ps1
$env:FOO="ü"
$ file foo.ps1
foo.ps1: UTF-8 Unicode text
```

* source env file in windows powershell: `.\foo.ps1`
* run go app within powershell

And here is the output:

```sh
$ .\test.exe
2019/05/17 13:45:11 Converted from Ã¼
2019/05/17 13:45:11 ü
```

It means that with the same `openrc.ps1` file containing umlauts in `OS_` ENVs, python CLI will work, but go app will fail to auth.

If you fix the **ps1** file encoding, then go apps will work, but python apps will fail.

### Code

Cross compiling with `GOOS=windows CGO_ENABLED=0`

```go
package main

import (
        "log"
        "os"

        "golang.org/x/sys/windows"
        "golang.org/x/text/encoding/charmap"
)

func main() {
        env := os.Getenv("FOO")
        if windows.GetACP() == 1252 {
                if v, err := charmap.Windows1252.NewEncoder().String(env); err == nil {
                        log.Printf("Converted from %s", env)
                        env = v
                }
        }
        log.Println(env)
}
```

### Question

So far it works fine, when do a conversion after fetching the variable from `os.Getenv` like in the code above. I'm not sure what kind of bug it is: openstack CLI, golang, or gophercloud. @jtopjian your expert advice is appreciated.

UPD:
in git-bash the situation is different:
* golang workaround doesn't work, it converts `ü` to `�`
* openstack cli fails with `$ openstack server list`
`utf8' codec can't decode byte 0xfc in position 1: invalid start byte`
Another suspect is windows powershell or git-bash.

**Comment by jtopjian** [comment]
Unfortunately I don't have access to a Windows workstation to verify this. But since I'm not able to reproduce this on Linux, I'm leaning towards this being something specific to Windows (whether it's git-bash, powershell, etc)

I also found this which might be helpful? 

https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/understanding-file-encoding

**Comment by kayrus** [comment]
@jtopjian thanks for the link. However even BOM header hasn't helped. It helps golang tools, however python tools stop working. I found a [way](https://gist.github.com/kayrus/66e30b750f9511ac1195b6b992ef19eb) to detect powershell/bash and now goapps work fine for me so far.

**Comment by kayrus** [comment]
@jtopjian is it possible to put [this code](https://github.com/sapcc/cloud-env) into the gophercloud upstream?
