### ISSUE TITLE
Support for Server Diagnostics

### ISSUE THREAD

**Issue by nareiber** [gophercloud/gophercloud#1585]
Nova has some diagnostic information for instances. The format and structure is dependent on nova api microversion[1], so I was just going to return a gophercloud result that callers can extract into their own structures depending on their nova api microversion. Also, my cloud's nova api is < 2.48 so I cannot test the new response in a real environment :)

Use case:  we dump stats on the computes and the instances residing on said compute into graphite/grafana to easily spot when an instance is being gluttonous and risking the computes health.

[1] https://developer.openstack.org/api-ref/compute/?expanded=show-server-diagnostics-detail

**Comment by jtopjian** [comment]
@nareiber Just a heads up that I've changed the return type to a map instead of a pointer to map here: https://github.com/gophercloud/gophercloud/pull/1596/commits/e15bc592646bc9139350e5f29453fa47df0084b8

**Comment by jtopjian** [comment]
Implemented in #1592 and #1596
