### ISSUE TITLE
Z and non-Z time formats in trove api.

### ISSUE THREAD

**Issue by fmy** [gophercloud/gophercloud#159]
Create an issue corresponds to PR #155 .

I think some solutions below.
- suffix Z values if not exists
- fix trove api's python code

**Comment by esalipe** [comment]
Created an alternative fix for this that keeps using time.Time in #196. As described in the PR, trove stores the times in `datetime` objects and then generates time values using `isoformat()` which means the returned values are in non-Z format.

**Comment by fmy** [comment]
@esalipe Thanks! I'll close this PR.

**Comment by jrperritt** [comment]
closed by #196
