### ISSUE TITLE
flavorId should be string in trove api.

### ISSUE THREAD

**Issue by fmy** [gophercloud/gophercloud#160]
It's an issue corresponds to PR #158 .

> I'm inclined to think that it's the current design.
> Additionally, if a Trove Flavor ID is a reference to a Nova/Compute Flavor ID, it has to be a string.
> If this is incorrect, can you open an issue for further discussion?

Agree 😄 
Flavor ID should be string.
I will change `json.Number` to `string`. It's OK ?

**Comment by esalipe** [comment]
Created an alternative PR #197 to fix this. As described in the PR the types used for returning the flavor ID are different depending on whether the response is for `instances` or for `flavors`. Links to the trove source code are also provided in the PR.

**Comment by fmy** [comment]
Thanks.

**Comment by jrperritt** [comment]
closed by #197
