### ISSUE TITLE
FWaaS Rule - Allow Any Protocol

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#161]
@jrperritt quick side note: I just switched Terraform over to gophercloud/gophercloud. Thank you for your help over the past few months! I'm now going through the backlog of Terraform issues, some of which require upstream fixes.

FWaaS Rules should allow a protocol of "any", which is achieved by setting `protocol` to `null`.

Here's a list of acceptable protocols, the first being `None`: https://github.com/openstack/neutron-fwaas/blob/905c798db15e0a02bffe2014013be99f9943f56f/neutron_fwaas/extensions/firewall.py#L170-L172

Here's the output of the Neutron CLI client setting `--protocol any`:

``` json
{
    "firewall_rule": {
        "action": "allow",
        "destination_ip_address": "192.168.1.2",
        "enabled": "true",
        "ip_version": 4,
        "name": "foo",
        "protocol": null,
        "source_ip_address": "192.168.1.1"
    }
}
```

**Comment by jrperritt** [comment]
closed by #162
