### ISSUE TITLE
Blockstorage: Add support for setting image metadata for a volume in volumeactions

### ISSUE THREAD

**Issue by psinghal20** [gophercloud/gophercloud#1610]
Currently the `volumeactions` package doesn't support setting image metadata for a volume. The openstacks volume actions API mentions an endpoint for the same [here](https://developer.openstack.org/api-ref/block-storage/v3/index.html?expanded=set-image-metadata-for-a-volume-detail,upload-volume-to-image-detail#set-image-metadata-for-a-volume).

I would love to take it on if someone could give me some pointers for the start.

**Comment by jtopjian** [comment]
@psinghal20 Thanks for opening this.

We have a [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) which should get you started with the basics.

As for this specific API call, you should be able to add it to https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/volumeactions/requests.go with a name like `SetImageMetadata`.

Please let me know if you have any questions.

**Comment by psinghal20** [comment]
@jtopjian closing the issue. :slightly_smiling_face:
