### ISSUE TITLE
Octavia health monitor should not require URLPath to be set for HTTP/HTTPS monitors

### ISSUE THREAD

**Issue by dulek** [gophercloud/gophercloud#1639]
Currently gophercloud requires setting `URLPath` when creating an [Octavia health monitor with type HTTP or HTTPS](https://github.com/gophercloud/gophercloud/blob/master/openstack/loadbalancer/v2/monitors/requests.go#L148-L151). According to [Octavia API reference](https://developer.openstack.org/api-ref/load-balancer/v2/?expanded=create-health-monitor-detail#create-health-monitor) it should not be enforced as `url_path` defaults to "/" (and code confirms it for all Queens-Train Octavia releases).

This is really annoying because in Rocky's Octavia there's a bug preventing creation of HTTPS health monitors with url_path set. And when I try to not set it I get error from gopherclou.

**Comment by jtopjian** [comment]
@dulek Thank you for reporting this. This should be fixed once #1640 is merged.

It looks like the behavior you're seeing was only added to Octavia in June 2018 while the initial Gophercloud Octavia implementation most likely targeted toward a release/behavior before that. This might explain the results you're seeing currently.

**Comment by dulek** [comment]
@jtopjian: That was fast, thanks! Left a minor comment on the patch, but otherwise this would help us.

**Comment by jtopjian** [comment]
This has been merged. Please let me know if you're still seeing issues.
