### ISSUE TITLE
networking/v2/extensions/layer3/floatingips lack of `Time.time Created/Updated` fields

### ISSUE THREAD

**Issue by naumvd95** [gophercloud/gophercloud#1646]
Need to add `Time.time Created/Updated`  fields inside results.go,  mapped from `json:"updated_at"`/`json:"created_at"`

General API reference: https://developer.openstack.org/api-ref/network/v2/?expanded=list-floating-ips-detail,show-floating-ip-details-detail#show-floating-ip-details

that fields defined in standard_attr.py , that means that it should be applied to all neutron-resources though decorator:
https://github.com/openstack/neutron/blob/041203f1bb1a9cb814ab58c6088d0229cfe9d9bb/neutron/db/standard_attr.py#L181
https://github.com/openstack/neutron/blob/041203f1bb1a9cb814ab58c6088d0229cfe9d9bb/neutron/db/models/l3.py#L70-L71

**Comment by naumvd95** [comment]
I wanted to implement it by myself, don't know how to assign it properly

**Comment by jtopjian** [comment]
@naumvd95 I think adding a comment like you've done is the best way to go. 🙂

**Comment by naumvd95** [comment]
@jtopjian its ready for review , thanks in advance)

**Comment by jtopjian** [comment]
Implemented in #1647

**Comment by naumvd95** [comment]
@jtopjian thanks a lot ;)
