### ISSUE TITLE
`InterfaceType` enums are defined with wrong type

### ISSUE THREAD

**Issue by longkb** [gophercloud/gophercloud#1684]
Currently, `InterfaceType` enums (SATA, SCSI, SAS) are declared as `DiskType` [1] which incorrect. These enums should be declared as `InterfaceType` constants.

[1] https://github.com/gophercloud/gophercloud/blob/master/openstack/baremetal/v1/nodes/requests.go#L526

**Comment by jtopjian** [comment]
Fixed in #1683
