### ISSUE TITLE
openstack/compute/v2/servers/  lack of `OS-EXT-AZ:availability_zone` field

### ISSUE THREAD

**Issue by naumvd95** [gophercloud/gophercloud#1692]
Need to add `OS-EXT-AZ:availability_zone` field  inside results.go, mapped from json:"OS-EXT-AZ:availability_zone"

General API reference:https://docs.openstack.org/api-ref/compute/?expanded=list-all-metadata-detail,show-server-details-detail#show-server-details

that fields defined in:
https://github.com/openstack/nova/blob/38cd8d3cd712e205722bb77639a5a1b08d167e4a/api-ref/source/parameters.yaml#L5041

**Comment by naumvd95** [comment]
will do by myself

**Comment by ozerovandrei** [comment]
@naumvd95 hello.

Gophercloud has this feature in different package: https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/availabilityzones

**Comment by naumvd95** [comment]
@ozerovandrei yep, already diving into it, thanks for point, will close this issue)
