### ISSUE TITLE
Support for nova v2.1 API

### ISSUE THREAD

**Issue by thcdrt** [gophercloud/gophercloud#1697]
Hello,

First I would like to thank you for the great work you do around gophercloud, this is working like a charm.

Today I wanted to call the compute endpoint /v2.1/<project>/limits which add some information compared to /v2/<project>/limits.

Is it planned to support the v2.1 API ?
Am I the only one who need it ?

Thanks !
Thomas

**Comment by jtopjian** [comment]
@thcdrt Gophercloud can support the `/v2.1` endpoint. You either need to have your keystone catalog return that endpoint or configure Gophercloud to specifically hit it.

If the additions to `limits` require a microversion, you'll need to follow the guidelines in this doc (https://github.com/gophercloud/gophercloud/blob/master/docs/MICROVERSIONS.md). But if the changes are compatible with "base" 2.1, you should be able to just amend what's under https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/limits.

Please let me know if this helps or if you have any other questions.

**Comment by thcdrt** [comment]
Hello @jtopjian, thanks for your answer.

Indeed, this will work as it is, the missing information are on Cinder call /limits finally. 
Sorry for the miscomprehension.
