### ISSUE TITLE
Octavia: Support to query the API micro versions

### ISSUE THREAD

**Issue by lingxiankong** [gophercloud/gophercloud#1707]
Getting the API versions is useful to check if a feature is supported in a target OpenStack cloud.

**Comment by jtopjian** [comment]
@lingxiankong We already have this package: https://github.com/gophercloud/gophercloud/tree/master/openstack/loadbalancer/v2/apiversions

I can't remember why it was put in the v2 directory, but we can move it.

**Comment by lingxiankong** [comment]
> @lingxiankong We already have this package: https://github.com/gophercloud/gophercloud/tree/master/openstack/loadbalancer/v2/apiversions
> 
> I can't remember why it was put in the v2 directory, but we can move it.

Ah, nice, we could keep that for backward compatibility.
