### ISSUE TITLE
Octavia: Support listener allowed_cidrs

### ISSUE THREAD

**Issue by lingxiankong** [gophercloud/gophercloud#1709]
API: https://docs.openstack.org/api-ref/load-balancer/v2/index.html?expanded=create-listener-detail#id34

**Comment by jtopjian** [comment]
@lingxiankong After merging #1710, I think I see an issue:

With `UpdateOpts`, I don't think it's currently possible to remove all CIDRs from a listener. Empty slices with `omitempty` will cause the field to be omitted from the PUT request.

Therefore, I think `[]string` needs to be changed to `*[]string` so that `&allowedCIDRs` (which would be an empty string slice) can be passed.

Can you test this and confirm?

Or is removing all CIDRs not a valid use-case?

**Comment by lingxiankong** [comment]
@jtopjian yes, you are right, I didn't test this edge case, I will do a quick fix.

**Comment by lingxiankong** [comment]
@jtopjian after a second thought, I think it's OK in gophercloud to omit `allowed_cidrs` when updating a listener with `allowedCIDRs=[]string{}`. From a user's perspective, it doesn't make sense to pass an empty list to update a listener, which means the load balancer can't be accessed from anywhere.

It's like you can't create a listener with empty `allowed_cidrs` list, because the default behavior is to allow all, e.g.:
```
$ cat <<EOF | http post ${octavia_prefix}/lbaas/listeners X-Auth-Token:$token
> {
>     "listener": {
>         "loadbalancer_id": "b136383c-fab0-4816-9575-411015f2a9d6",
>         "protocol": "HTTP",
>         "protocol_port": "81",
>         "allowed_cidrs": []
>     }
> }
> EOF
HTTP/1.1 201 Created
Connection: close
Content-Length: 858
Content-Type: application/json
Date: Thu, 19 Sep 2019 03:37:36 GMT
Server: Apache/2.4.18 (Ubuntu)
x-openstack-request-id: req-995b97fc-8b53-417b-b4b9-3752ab6d5a60

{
    "listener": {
        "admin_state_up": true,
        "allowed_cidrs": null,
        "client_authentication": "NONE",
        "client_ca_tls_container_ref": null,
        "client_crl_container_ref": null,
        "connection_limit": -1,
        "created_at": "2019-09-19T03:37:36",
        "default_pool_id": null,
        "default_tls_container_ref": null,
        "description": "",
        "id": "fe076dca-dcf8-4df1-97a5-2de7d604413e",
        "insert_headers": {},
        "l7policies": [],
        "loadbalancers": [
            {
                "id": "b136383c-fab0-4816-9575-411015f2a9d6"
            }
        ],
        "name": "",
        "operating_status": "OFFLINE",
        "project_id": "db224b2f3e9a48108198821eb040e4fa",
        "protocol": "HTTP",
        "protocol_port": 81,
        "provisioning_status": "PENDING_CREATE",
        "sni_container_refs": [],
        "tags": [],
        "tenant_id": "db224b2f3e9a48108198821eb040e4fa",
        "timeout_client_data": 50000,
        "timeout_member_connect": 5000,
        "timeout_member_data": 50000,
        "timeout_tcp_inspect": 0,
        "updated_at": null
    }
}
```

Thoughts?

**Comment by jtopjian** [comment]
OK, so to confirm, having:

```
allowed_cidrs: null
```

Means that the Listener can be accessed by all, right?

The use-case I'm thinking of is how can a user change a Listener from only being accessible from a set of CIDRs to be accessible by all?

**Comment by lingxiankong** [comment]
> OK, so to confirm, having:
> 
> ```
> allowed_cidrs: null
> ```
> 
> Means that the Listener can be accessed by all, right?

Yes

> 
> The use-case I'm thinking of is how can a user change a Listener from only being accessible from a set of CIDRs to be accessible by all?

`allowedCIDRs=[]string{"0.0.0.0/0"}`

**Comment by jtopjian** [comment]
> allowedCIDRs=[]string{"0.0.0.0/0"}

OK, that works for me.

For other API calls, we have done:

```go
allowedCIDRs := []string{}
updateOpts.AllowedCIDRs = &allowedCIDRs
```

In order to have the JSON response go back to:

```
allowed_cidrs: null
```

But if this works differently and passing `0.0.0.0/0` is the way to go, I'm totally fine with that.

**Comment by lingxiankong** [comment]
I've tested again in my environment, in Octavia API response, `"allowed_cidrs": null,` leads to `listener.AllowedCIDRs == []` in Gophercloud. The corresponding source IP range in security group rule shows `0.0.0.0/0` which is what we expected. @jtopjian Please let me if you need more information.

**Comment by jtopjian** [comment]
> I've tested again in my environment, in Octavia API response, "allowed_cidrs": null, leads to listener.AllowedCIDRs == [] in Gophercloud.

Yes, this can also be seen by creating a listener without setting `AllowedCIDRs`, so we're all good here.

Can you confirm the following when `*[]string` is used in `UpdateOpts`?

```go
// Create the Listener
allowedCIDRs := []string{"192.168.255.0/24"}
createOpts.AllowedCIDRs = allowedCIDRs

listener, err := listeners.Create(client, ...)

// Update the name of the Listener only
newName := "new name"
updateOpts.Name = &newName

listener, err = listeners.Update(client, ...)

// Confirm AllowedCIDRs is unchanged

// Update the Listener
allowedCIDRs = []string{}
updateOpts.AllowedCIDRs = &allowedCIDRs

listener, err = listeners.Update(client, ...)

// Confirm AllowedCIDRs is now []/null
```

What I'm thinking is that using an empty slice when `UpdateOpts.AllowedCIDRs` is a `*[]string{}` and using `0.0.0.0/0` when `UpdateOpts.AllowedCIDRs` is `[]string{}` are the same thing.

If this is true, it's best to change to `*[]string{}` for consistency with other areas of Gophercloud. This allows common patterns to be used.

**Comment by lingxiankong** [comment]
@jtopjian Can I use this issue for a new commit to fix the allowedCIDRs when updating the listener?

**Comment by lingxiankong** [comment]
@jtopjian When using `*[]string{}`, after updating listener, `listener.AllowedCIDRs == []`

**Comment by jtopjian** [comment]
> Can I use this issue for a new commit to fix the allowedCIDRs when updating the listener?

Yes, that's totally fine :)

**Comment by jtopjian** [comment]
@lingxiankong thank you for your work on this!
