### ISSUE TITLE
Designate - Zone Read

### ISSUE THREAD

**Issue by grahamhayes** [gophercloud/gophercloud#172]
Add support for OpenStack DNS - Designate Zone Reads (List + Get)

**Comment by jtopjian** [comment]
@grahamhayes I wanted to touch base about the Designate work. If you're pressed for time, I would be happy to (attempt to) take over. This is something I'd really like to see in Gophercloud. :)

**Comment by jrperritt** [comment]
@jtopjian if you're still interested in implementing this, please go ahead

**Comment by jtopjian** [comment]
On it.

**Comment by jrperritt** [comment]
closed by #271
