### ISSUE TITLE
Lbaas: Listener's SniContainerRefs cannot be unset

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1722]
`UpdateOpts` struct for the listeners contains:

```
SniContainerRefs []string `json:"sni_container_refs,omitempty"`
```

Which means that `SniContainerRefs` cannot be set to an empty list.

I suggest to add the:

```
SniContainerRefs *[]string `json:"sni_container_refs,omitempty"`
```

UPD: the same has to be done for the `DefaultTlsContainerRef` and `AllowedCIDRs`.

UPD2: If the protocol is `TERMINATED_HTTPS`, then `DefaultTlsContainerRef` is required and cannot be unset.

**Comment by jtopjian** [comment]
@kayrus re `AllowedCIDRs`, please see the discussion at https://github.com/gophercloud/gophercloud/issues/1709. My understanding is that it's OK for it to not be `*[]string`.
