### ISSUE TITLE
Octavia LBaaSv2: creating a fully populated loadbalancer

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1740]
It is possible to create a loadbalancer with its elements in one call:
https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-a-load-balancer-detail#creating-a-fully-populated-load-balancer

The LB tree is already supported in a LB response struct: https://github.com/gophercloud/gophercloud/blob/9c34d1968ad7554db7fc49f1f43fe63633d3320f/openstack/loadbalancer/v2/loadbalancers/results.go#L16

**Comment by mandre** [comment]
Implemented via https://github.com/gophercloud/gophercloud/pull/2077
