### ISSUE TITLE
Openstack idempotency usage in gophercloud

### ISSUE THREAD

**Issue by guptavishal7982** [gophercloud/gophercloud#1741]
Hi,

I want to know how gophercloud library is making use of the OpenStack idempotency feature.

https://wiki.openstack.org/wiki/Support-retry-with-idempotency

Thanks!!

**Comment by jtopjian** [comment]
@guptavishal7982 The wiki page you linked to looks to define an old specification for the OpenStack Heat service as it communicates with other OpenStack components.

If you are asking about a similar implementation of this spec/policy within Gophercloud, then it would be out of scope of Gophercloud. It would be up to the application that consumes Gophercloud to implement this.

Gophercloud is only concerned with sending an API request and parsing the response. If you want your application to introduce some kind of idempotency similar to what's described in that wiki page, then your application will need to implement that logic.

For example:

> However, I think there are some circumstances/scenarios where API retry is appropriate. (i.e. 503 response or timeout due to server failover) 

In your application, you would use Gophercloud to issue an API request. If the response of that API request is a 503, the application would send another API request. This would be bundled into some kind of while/for loop until either a 503 is not returned or some kind of application retry or timeout threshold is reached.

Let me know if this helps.

**Comment by jtopjian** [comment]
@guptavishal7982 I'm going to close this issue but please let me know if you still have questions.
