### ISSUE TITLE
Core client: debug round-tripper as a part of gophercloud package

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1748]
@jtopjian currently debug logging is supported only in https://github.com/gophercloud/gophercloud/blob/6f9cb195db5276cf596293ac30b08c93acd12851/acceptance/clients/http.go package. OpenStack Terraform provider just copies this logic: https://github.com/terraform-providers/terraform-provider-openstack/blob/493f93252e8071f592f03ad2da3bdf4288dc365f/openstack/types.go#L26..L33

It would be nice to see the debug RoundTripper in gophercloud, therefore every app, which requires debug logging can reuse it. I'd like to create the "gophercloud/debug" package containing the LogRoundTripper struct with methods.

In addition it should support custom loggers, e.g. https://github.com/sirupsen/logrus or https://github.com/kubernetes/klog

**Comment by jtopjian** [comment]
We can look at adding this, but it would be better if it was added to https://github.com/gophercloud/utils/

**Comment by kayrus** [comment]
Can you move this issue into the https://github.com/gophercloud/utils/ project?
