### ISSUE TITLE
Introspection client incorrectly assumes URL structure

### ISSUE THREAD

**Issue by brokoli18** [gophercloud/gophercloud#1749]
When running introspection commands the client forms the URL with the following structure:

`http://introsepection-URL:5050/introspection`

From what I can see this is formed in the below snippets: 

* https://github.com/gophercloud/gophercloud/blob/6f9cb195db5276cf596293ac30b08c93acd12851/service_client.go#L46 
* https://github.com/gophercloud/gophercloud/blob/master/openstack/baremetalintrospection/v1/introspection/urls.go

This causes problems because this URL can vary from deployment to deployment and I can see no obvious way to provide a custom URL string (e.g. `http://introsepection-URL:5050/v1/introspection`

It would be useful to expose an option to the user to let them edit this URL. 

Its possible this affects other services although I have not investigated/confirmed this.

**Comment by jtopjian** [comment]
I'm not sure what the standard deployment configuration for Introspection is (whether the advertised endpoint should be "bare" or have `v1`). But you should be able to customize this by modifying the `ServiceClient`'s `ResourceBase` and/or `Endpoint`:

https://github.com/gophercloud/gophercloud/blob/master/openstack/client.go#L335

**Comment by brokoli18** [comment]
I did not realise those fields of the client were publicly exported, setting the URL via that method works. Thanks for your help @jtopjian, I will close this issue.
