### ISSUE TITLE
Go-yaml prior to v2.2.4 enabled ddos attack

### ISSUE THREAD

**Issue by petrkotas** [gophercloud/gophercloud#1750]
go-yaml prior to v2.2.4 enabled the [billion laughs bomb](https://en.wikipedia.org/wiki/Billion_laughs_attack), which makes the program unresponsive.

Upgrading to current version which is [v2.2.4](https://github.com/go-yaml/yaml/tree/v2.2.4) solves the issue.

**Comment by jtopjian** [comment]
Fixed in #1751
