### ISSUE TITLE
Support containerinfra node group API

### ISSUE THREAD

**Issue by tghartland** [gophercloud/gophercloud#1767]
* [x] Create #1800
* [x] Get / List #1774
* [x] Update #1800
* [x] Delete #1800

NodeGroup API representation:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L58-L127

Returned fields limited to these:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L147-L149

List method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L226-L262

Get method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L265-L280

Create method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L283-L323

Available fields when creating node group:
https://github.com/openstack/python-magnumclient/blob/c0d368360831cd29affa47e77eba4e81e4c6f0f8/magnumclient/v1/nodegroups.py#L21-L23

Update method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L326-L338

Delete method:
https://github.com/openstack/magnum/blob/9c7cf5d6eb050dbbcdcb036bd0af2b6586070c0c/magnum/api/controllers/v1/nodegroup.py#L341-L355

**Comment by tghartland** [comment]
@jtopjian I have the code for all API methods written now [1], but there is a Magnum fix waiting to be merged [2]. Is it fine to start reviewing / merging here?

[1] https://github.com/tghartland/gophercloud/tree/nodegroups-delete/openstack/containerinfra/v1/nodegroups and other branches
[2] https://review.opendev.org/#/c/694230/

**Comment by tghartland** [comment]
And I have a CRUD acceptance test that I'm using myself against a devstack instance, but since the gophercloud acceptance tests are not testing for the Train release it would not work. Can that be overlooked for now, or what's the best way to go about sorting this?

**Comment by jtopjian** [comment]
>  but since the gophercloud acceptance tests are not testing for the Train release it would not work

By default, the acceptance tests run on the master branches of OpenStack, so they should work. 

However, we have manual jobs that run for Stein, Rocky, down to Mitaka. So you'll need to add some code to skip those:

https://github.com/gophercloud/gophercloud/blob/5b7518307fb5b7148b632cdee6fd3fddacca78f8/acceptance/openstack/imageservice/v2/imageimport_test.go#L14-L18

Let me know if you have any questions or run into any problems.

**Comment by tghartland** [comment]
Ah, thanks for pointing that out to me.

I'll open the first PR for Get/List now and I can add the first part of the acceptance test tomorrow.

**Comment by jtopjian** [comment]
@tghartland You seem to have a good handle on all of this, so feel free to add additional features in a single PR (ie: POST, DELETE, etc). We should be able to fast-track merges that way.

**Comment by tghartland** [comment]
https://review.opendev.org/#/c/694230/ (list next URL fix) has now been merged.

As suggested I have created a single PR for the create / update / delete methods: #1800.

**Comment by jtopjian** [comment]
@tghartland Thank you!

Is this complete or do you still have additional actions/features you wanted to add?

**Comment by tghartland** [comment]
With Create/Update/Delete now merged this is complete. Thanks for your help and review!
