### ISSUE TITLE
Endpoint search: export GetEndpointType func helper

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1781]
It's worth to export the GetEndpointType func, which will get a string as an input and return a `gophercloud.Availability` value.

It can be moved from the terraform provider code: https://github.com/terraform-providers/terraform-provider-openstack/blob/c9123575b1ccc413498be8c24c74ba9aa1af7b64/openstack/config.go#L292..L302

**Comment by jtopjian** [comment]
@kayrus This is already available here: https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/utils.go#L167

**Comment by kayrus** [comment]
oh, my bad that I missed this.
