### ISSUE TITLE
Hypervisors Support

### ISSUE THREAD

**Issue by spjmurray** [gophercloud/gophercloud#179]
Gophercloud is missing the os-hypervisors API.  This would allow operators to collate global cluster statistics to monitor CPU and memory utilization (and over-commit) and also enable capacity planning based on trends.

**Comment by spjmurray** [comment]
Basic list functionality started in https://github.com/gophercloud/gophercloud/pull/178

**Comment by jtopjian** [comment]
Resolved by #178 and #344
