### ISSUE TITLE
Mistral api issue sort keys query param

### ISSUE THREAD

**Issue by snigle** [gophercloud/gophercloud#1808]
Sort keys doesn't work for cron trigger api call  : 
Bad request with: [GET https://workflow.*****.net/v2/cron_triggers?sort_key=project_id], error message: {\"debuginfo\": null, \"faultcode\": \"Client\", \"faultstring\": \"Unknown argument: \"sort_key\"\"}"

**Comment by jtopjian** [comment]
Fixed in #1809
