### ISSUE TITLE
blockstorage/extensions/schedulerstats/Capabilities: the field MaxOverSubscriptionRatio should be a number

### ISSUE THREAD

**Issue by dragon753** [gophercloud/gophercloud#1810]
gophercloud version: 0.7.0
openstack version: 3.8.1
cinder version: 1.11.0
The MaxOverSubscriptionRatio field of struct Capabilities should be number. The response that I got from the api is like this:
`{"pools":[{"capabilities":{"QoS_support":true,"allocated_capacity_gb":52647,"compression_support":true,"consistencygroup_support":true,"driver_version":"2.1.1","easytier_support":true,"free_capacity_gb":22083,"location_info":"some_location_info","max_over_subscription_ratio":20,"multiattach":true,"pool_name":"a_pool_name","provisioned_capacity_gb":69343,"reserved_percentage":0,"storage_protocol":"FC","thick_provisioning_support":false,"thin_provisioning_support":true,"timestamp":"2020-01-08T05:09:53.093905","total_capacity_gb":57344,"vendor_name":"18M","volume_backend_name":"svc_name"},"name":"node_name"}]}`

now the type is string, so there is a json decode error.

**Comment by jtopjian** [comment]
Fixed in #1817
