### ISSUE TITLE
Get token via password and scoped authentication method v3

### ISSUE THREAD

**Issue by erouvin** [gophercloud/gophercloud#1811]
Hi,

Is it possible to perform the following request with the current implementation ?

[Password authentication with scoped authorization - /v3/auth/tokens](https://docs.openstack.org/api-ref/identity/v3/?expanded=get-available-domain-scopes-detail,validate-and-show-information-for-token-detail,password-authentication-with-unscoped-authorization-detail,password-authentication-with-scoped-authorization-detail#password-authentication-with-scoped-authorization)

```
curl -k -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "name",
          "domain": { "id": "domain" },
          "password": "password"
        }
      }
    },
    "scope": {
      "domain": {
        "id": "default"
      }
    }
  }
}' \
  "https://localhost:5000/v3/auth/tokens" ; echo
```

Thank you.

**Comment by jtopjian** [comment]
I'm _pretty_ sure this is possible, but it might be easier to achieve using the `clientconfig` utility: https://github.com/gophercloud/utils/tree/master/openstack/clientconfig library

**Comment by erouvin** [comment]
Thanks a lot for your quick answer.

I gave it a shot but am new with this and am having the following issues :

```
panic: Get https://xx.xx.xx.xx:5000/: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs

goroutine 1 [running]:
main.main()
        /home/erouvin/devplay/go/trial.go:20 +0x1f3
```

This is most probably because I need to simulate the curl -k ( insecure ).
Also, it looks like a GET is sent but it should be a POST in this case.

Thank you for your guidance.

**Comment by jtopjian** [comment]
It sounds like you're trying to authenticate to a pretty customized environment. This should all be possible to do (for example, the ability to pass SSL information was coincidentally discussed here https://github.com/gophercloud/utils/issues/105), but unfortunately I don't have a straightforward answer. I recommend reviewing all of the links in https://github.com/gophercloud/utils/issues/105 and piecing together different areas of code.

**Comment by kayrus** [comment]
@erouvin not sure if this is your case, but I observed `cannot validate certificate` error, when I compiled an app using go 1.12. Switching to 1.13 solved an issue.

**Comment by erouvin** [comment]
Well, I ended up using the insecure setting for TLS http.Transport as follows : 

`	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}

	client := &http.Client{Transport: tr}`

Then went all the way, coding my own API subset that would fit my needs for an openstack client.

Thanks.

**Comment by jtopjian** [comment]
> Well, I ended up using the insecure setting for TLS http.Transport as follows

Yes, this is the correct way. I apologize - I must have originally interpreted your use-case for wanting to do SSL-based authentication and not just SSL support.

I'm going to close this issue, but let me know if you have any other questions.
