### ISSUE TITLE
Creating LoadBalancers pool members does to allow to inject custom options

### ISSUE THREAD

**Issue by databus23** [gophercloud/gophercloud#1821]
In the package `github.com/gophercloud/gophercloud/opestack/looadbalancer/pools`, the functions `CreateMember` requires a `CreateMemberOpts` struct instead of the already defined `CreateMemberOptsBuilder` interface: https://github.com/gophercloud/gophercloud/blob/79f393baede6563f25e28015afe80b4d31d9bbeb/openstack/loadbalancer/v2/pools/requests.go#L286
Therefore it is not possible to pass custom options to this api call.

**Comment by jtopjian** [comment]
Fixed in #1822
