### ISSUE TITLE
Options for creating load balancers members is missing fields

### ISSUE THREAD

**Issue by databus23** [gophercloud/gophercloud#1823]
The Octavia API added a few fields to load balancer pool member api.

The fields are already supported by gophercloud in the `Member` result: https://github.com/gophercloud/gophercloud/blob/79f393baede6563f25e28015afe80b4d31d9bbeb/openstack/loadbalancer/v2/pools/results.go#L223-L230

Currently these are not supported in the `CreateMemberOpts` struct.

The missing fields are:
`MonitorPort` 
`MonitorAddress`
`Backup`

https://docs.openstack.org/api-ref/load-balancer/v2/#create-member

**Comment by jtopjian** [comment]
Implemented in #1823
