### ISSUE TITLE
Implementation of `NUMA` structure  

### ISSUE THREAD

**Issue by sana-aawan** [gophercloud/gophercloud#1825]
Currently, gophercloud is introspecting the baremetal-nodes and storing the introspection data in the respective pre-defined structures. There is no structure defined for details like, `NUMA` topology that we receive from Ironic introspection. We recommend `NUMA` parameters need to be added in gophercloud structure which would be helpful for `HPC` workloads like use-cases. For better performance, the selection of CPUs based on the `NUMA` topology becomes necessary. In case of nodes with `DPDK` aware NICs, the CPUs for poll mode driver (PMD) need to be selected from the `NUMA` node associated with the `DPDK` NICs. If hyperthreading is enabled, then the selection of the logical cores requires the knowledge of the siblings.

**Comment by jtopjian** [comment]
@sana-aawan Please feel free to open a PR to have this added. We have a [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) which should help you get started.

**Comment by jtopjian** [comment]
Implemented in #1842
