### ISSUE TITLE
Octavia LBaaSv2: redundant trailing version number

### ISSUE THREAD

**Issue by kciredor** [gophercloud/gophercloud#1828]
gophercloud assumes it needs to add v2.0/ to the octavia lb endpoint returned by OpenStack, yet some OpenStack providers return an endpoint having v2.0/ already appended.

Resulting in kops, using gophercloud, will run into issues like this:

W0114 16:08:08.423462   24356 executor.go:130] error running task "LB/api.xxxxx.k8s.local" (9m19s remaining to succeed): Failed to retrieve loadbalancers for name api.xxxxx.k8s.local: Request forbidden: [GET https://os.xxxxx.nl:9876/v2.0/v2.0/lbaas/loadbalancers?name=api.xxxxx.k8s.local], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Policy does not allow this request to be performed."}

**Comment by kciredor** [comment]
PR: https://github.com/gophercloud/gophercloud/pull/1829

**Comment by jtopjian** [comment]
Fixed in #1829
