### ISSUE TITLE
[Discuss] should we remove ubuntu-trusty nodeset?

### ISSUE THREAD

**Issue by bzhaoopenstack** [gophercloud/gophercloud#1831]
Hi Team,

I'm a maintainer from openlab.  

ubuntu-trusty is too old, and the test node is for openstack mitaka which already 5 years. So I think it's better to raise the discusstion to make clear that whether we still need ubuntu-trusty test node.

Thanks

**Comment by jtopjian** [comment]
@bzhaoopenstack Yes, please go ahead and delete Trusty. Thank you for checking!

**Comment by bzhaoopenstack** [comment]
Thanks.

**Comment by jtopjian** [comment]
@bzhaoopenstack I created #1832, but I'm guessing that some code will need removed on OpenLab's side first?

**Comment by jtopjian** [comment]
Implemented in #1832
