### ISSUE TITLE
LoadBalancer V2: lack of InsertHeaders in Listener.UpdateOpts 

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1834]
Octavia V2 API supports the update of "insert_headers" value: https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=update-a-listener-detail#update-a-listener

Gophercloud only supports this option in the Create and Read methods.

For https://github.com/terraform-providers/terraform-provider-openstack/issues/954

**Comment by jtopjian** [comment]
@ozerovandrei If there are 2 headers currently set and someone wants to remove one, I'm assuming that they will set `UpdateOpts.InsertHeaders` to only have 1 entry.

But what if they want to remove all headers? Should it be `*map[string]string` instead?

**Comment by ozerovandrei** [comment]
@jtopjian yeah you're right.
