### ISSUE TITLE
Connection is not reused

### ISSUE THREAD

**Issue by jonas0616** [gophercloud/gophercloud#1838]
In `provider_client.go`, it sets http request **Close** option to true to close the connection after replying to the request.
```go
// Set connection parameter to close the connection immediately when we've got the response
req.Close = true
```

It makes the connection cannot be reused, and every request requires to establish a new TCP connection. Not only does the latency increase, but also increase the overhead of both gophercloud clients and openstack services.

Furthermore, there are several requests do not close the response body after sending the request. It also makes the connections cannot be reused even after the **Close** option is set to false.

**Comment by jtopjian** [comment]
@jonas0616 Thanks for opening this issue. If you have any suggestions or ideas on how to make connection management more flexible, please let me know or feel free to open a PR for review/discussion.

**Comment by jonas0616** [comment]
@jtopjian In most cases, it should not set `req.Close` to true. If anyone needs to disable the connection keepalive, the `request` could be modified by `Transport` in `http.Client`.

Secondly, make sure all response body is closed. Most of the `DELETE` and `HEAD` requests do not close the body. Such as `ServiceClient.Delete()`, it does not close the body when `opts.JSONResponse` is not set. However, many of callers do not set `opts.JSONResponse`. e.g., `containers.Delete()`, `objects.Delete()`, etc.

```go
func (client *ServiceClient) Delete(url string, opts *RequestOpts) (*http.Response, error) {
    if opts == nil {
        opts = new(RequestOpts)
    }
    client.initReqOpts(url, nil, nil, opts)
    return client.Request("DELETE", url, opts)
}
```

**Comment by kayrus** [comment]
@jonas0616 can you test the latest master branch and close an issue if it is solved?

**Comment by jonas0616** [comment]
@kayrus It could reuse TCP connections after upgrade to v0.11.0. Thanks for your contributing.
