### ISSUE TITLE
Malformed JSON Struct Tags

### ISSUE THREAD

**Issue by alrs** [gophercloud/gophercloud#1839]
The `Op` and `Path` fields of the `UpdateOperation` struct in `baremetal/v1/ports/requests` both have the JSON tag argument `required`, which [does not exist](https://github.com/golang/go/issues/16426) in the Go JSON library.

The `VirtualIP` member of an anonymous struct in `networking/v2/extensions/lbaas/vips` is tagged with the same JSON tag twice.

**Comment by jtopjian** [comment]
@alrs Thanks.

The `required` tag should actually be:

```
`required:"true"`
```

Instead of part of the `json` tag.

https://github.com/gophercloud/gophercloud/blob/master/params.go#L64

**Comment by jtopjian** [comment]
Fixed in #1840
