### ISSUE TITLE
Implem compute servers instance_actions sdk

### ISSUE THREAD

**Issue by snigle** [gophercloud/gophercloud#1845]
Hi, this call api is not in the SDK : 
https://docs.openstack.org/api-ref/compute/?expanded=list-actions-for-server-detail

**Comment by jtopjian** [comment]
@snigle You're right - thanks! 

This should go under "extensions": https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions

**Comment by reenjii** [comment]
Correct link to documentation: https://docs.openstack.org/api-ref/compute/?expanded=list-actions-for-server-detail#list-actions-for-server

**Comment by jtopjian** [comment]
Implemented in #1848
