### ISSUE TITLE
Microversions: Simplify Implementation of additional result fields

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1853]
As microversions become more widespread throughout Gophercloud, it appears that our initial guideline of providing a dedicated `Extract` function will soon become unmaintainable. I propose treating _result_ fields that have been added by a microversion the same way we treat _request_ fields.

**Comment by ozerovandrei** [comment]
I agree.

**Comment by jtopjian** [comment]
Implemented in #1854
