### ISSUE TITLE
Unbounded recursion in provider_client

### ISSUE THREAD

**Issue by bwarden** [gophercloud/gophercloud#187]
ProviderClient's Request() method calls itself recursively after attempting reauthorization:
https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L223

If, despite client.ReauthFunc() succeeding, the request still returns http.StatusUnauthorized (401), it will continue to recurse. In the case of incorrect credentials, the server could continuously return 401, causing this path to recurse indefinitely.

**Comment by jrperritt** [comment]
This is known and intentional. It is documented [here](https://github.com/gophercloud/gophercloud/blob/master/auth_options.go#L46).
