### ISSUE TITLE
openstack/compute/v2/servers/testing Dropped Error

### ISSUE THREAD

**Issue by alrs** [gophercloud/gophercloud#1887]
There is a dropped error in ` TestExtractPassword_no_pwd_data()` in `opentack/compute/v2/servers/testing`.

**Comment by jtopjian** [comment]
@alrs Thank you for your work with these fixes. If you have any more you'd like to work on, feel free to create a single generic issue like "Unit test fixes" and link all of the PRs to them. Should make things a little easier.

**Comment by mandre** [comment]
Fixed via https://github.com/gophercloud/gophercloud/pull/1888
