### ISSUE TITLE
look into handling deprecated services/packages

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#189]
There are several `gophercloud` packages that have been deprecated (for example, `blockstorage/v1` and several of the `compute/v2/extension` subpackages). We should consider moving deprecated packages out of `gophercloud/gophercloud` and into something like `gophercloud/deprecated`. That way users who don't want to upgrade their cloud can continue to use them (ideally) by just changing the import path. This needs more research.

**Comment by jtopjian** [comment]
Thank you for bringing this topic up. There's a lot in common here with the comment I made about API versions the other month.

> That way users who don't want to upgrade their cloud 

A lot of the time it's much more than not _wanting_ to upgrade. If it was possible, I'd have all the clouds I maintain run the latest commit of each OpenStack project, but that's not realistic. This might be nit-picking words, but I think it's important to be empathetic about devs/ops/users in situations where they can't use the latest version of something.

> can continue to use them (ideally) by just changing the import path. 

And this is a good example of being empathetic: this is a low-barrier way of providing access to older features. Sometimes finding information about old stuff is [hard to come by](http://lists.openstack.org/pipermail/openstack-operators/2016-November/011993.html). So I _really_ appreciate this being suggested out of the gate.

I'm not opposed to a `deprecated` repo, but I'm curious about the logistics of it being maintained. As well, having a separate repo makes the code feel second-class. Even though features and APIs are deprecated, they are still deployed for a very long time. 

The timeframe I take under consideration is a long-term supported release of something (Ubuntu LTS, RHEL, etc). For example, Canonical/Ubuntu is going to support Mitaka (and therefore nova-network, and therefore the corresponding API features, even if they are not widely used in Mitaka) until 2021. Will anyone actually be using nova-network in 2021? I hope not (I'm a die-hard fan of nova-network, but it's gotta go at some point), but it highlights that nova-network was not globally disabled the moment it was declared deprecated.

I wonder if just having the package documented as "DEPRECATED - WILL ACCEPT CONTRIBUTIONS BUT NON-DEPRECATED FEATURES TAKE PRIORITY" is suitable?

However, I totally understand the responsibility that entails. It means that all packages, even ones supporting deprecated features, must be just as well maintained as current. But by not maintaining them, it lends toward seeing `deprecated` as that dusty 'ol repo that no one cares about.

So I'm going in circles now. As you said, this needs some more research. The only strong opinion I have is making sure deprecated features are not immediately ignored... but determining how long they are kept in mind is a tough call.

**Comment by jrperritt** [comment]
@jtopjian Thank you for joining the discussion.

> A lot of the time it's much more than not wanting to upgrade.

True; it was just an example. "Unwilling or unable" would be more accurate.

> having a separate repo makes the code feel second-class.

It is, though. By definition, deprecated code has been replaced by something "better" (whatever that means) and, often, will no longer receive new features.

> The timeframe I take under consideration is a long-term supported release of something

I may have a different view on this. Canonical is a company that likely attracts many users to its products exactly _because_ of its commitment to long-term support. In contrast, `gophercloud` is an, open-source (permissively-licensed) Go package; anyone can fork, clone, copy, delete... whatever. The suggested way to use it is to vendor it, in large part because long-term support of any feature/service is not guaranteed.

> I wonder if just having the package documented as "DEPRECATED - WILL ACCEPT CONTRIBUTIONS BUT NON-DEPRECATED FEATURES TAKE PRIORITY" is suitable?

I'm not sure users would see that warning, but moreover it doesn't solve the problem I have in mind (that is, wasting time implementing/reviewing changes/additions to deprecated features/services).

> But by not maintaining them, it lends toward seeing deprecated as that dusty 'ol repo that no one cares about.

I could see that. I envisioned `deprecated` meaning services that have been deprecated from OpenStack (and not necessarily from `gophercloud`), but the name is admittedly ambiguous.

> The only strong opinion I have is making sure deprecated features are not immediately ignored

NOTE: Below are my opinions, and I'm speaking only for myself.

I understand where you're coming from. You and others are using this library (and you especially have contributed to it quite a bit), and y'all want support for all the features that y'all're interested in. What we're facing here is the reality of open-source software development: OSS projects exist because they provide utility to the creators (or owners), and if they provide utility to others as well, that's a bonus. It doesn't seem reasonable to expect an entity (individual or corporate) to invest time and money into OSS work that doesn't benefit that entity in some way. I suspect supporting (and certainly adding onto) deprecated features would be an example of something considered not to be worthwhile. I am interested, however, in implementing a reasonable compromise if one arises.

**Comment by jtopjian** [comment]
Thank you for the input.

Just to be clear: I fully understand the nature of open source. I don't want to descend into a discussion about responsibility and entitlement because I think that's garbage. 

My comments about LTS releases weren't so much about vendor commitment, but more about the longevity of a deployment. I think the link at the end of my comment is a better example of this. It's pretty crazy that the majority of deployed OpenStack environments are considered EOL.

I think a more refined opinion of mine is: it would be one thing if Gophercloud had 100% coverage of the deprecated APIs. Since it doesn't, and since there's such a large pool of possible environments that use them, I think there should be some ability to maintain them.  I think this could be fairly low-effort, too: it's totally reasonable to do things like have all maintenance and patches be from outside contributions or pointing people to other code for how to solve a bug. If someone wants a feature badly enough, they will put in the effort.

What I wouldn't want to see (and again, thank you for this not being the first suggestion) is if the deprecated packages were altogether removed.

**Comment by jrperritt** [comment]
> I fully understand the nature of open source

I know :) You are more involved in it than I am. But others will read this thread who may not understand the dilemma.

> it's totally reasonable to do things like have all maintenance and patches be from outside contributions

Couldn't this just as well happen in a `deprecated` (or better named) repo? If you'd like to volunteer, I _think_ we can set it up such that you're the (or a) maintainer of such a repo.

> is if the deprecated packages were altogether removed.

You mean deleted instead of moved? I don't think that'll happen. I certainly wouldn't want to through away people's hard work.

**Comment by jtopjian** [comment]
> Couldn't this just as well happen in a deprecated (or better named) repo?

Yes, absolutely. I'm sorry - I realized I didn't reinforce my support of a separate repository. As well, I'm glad you clarified the point about "deprecated API doesn't mean deprecated from Gophercloud".

**Comment by jtopjian** [comment]
I'm going to close this issue since I think we have a pretty good process of managing all sorts of API statuses.
