### ISSUE TITLE
Cinder V3: Support a backup record export and import

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1892]
Export a backup: https://docs.openstack.org/api-ref/block-storage/v3/?expanded=export-a-backup-detail#export-a-backup
https://github.com/openstack/cinder/blob/c29285e7dcda7f5300c5a3375294dfa4aeb56430/cinder/api/contrib/backups.py#L239..L253

Import a backup: https://docs.openstack.org/api-ref/block-storage/v3/?expanded=import-a-backup-detail#import-a-backup
https://github.com/openstack/cinder/blob/c29285e7dcda7f5300c5a3375294dfa4aeb56430/cinder/api/contrib/backups.py#L257..L280

**Comment by kayrus** [comment]
@jtopjian when you export a backup, the `backup_url` is a base64 encoded struct. In my case, if you decode it:

```json
{
  "status": "available",
  "temp_snapshot_id": null,
  "display_name": null,
  "availability_zone": "region1b",
  "deleted": false,
  "volume_id": "cf9bc6fa-c5bc-41f6-bc4e-6e76c0bea959",
  "restore_volume_id": null,
  "updated_at": "2020-03-11T19:29:08Z",
  "host": "cinder-backup-host1",
  "snapshot_id": null,
  "user_id": "93514e04-a026-4f60-8176-395c859501dd",
  "service_metadata": "volume_cf9bc6fa-c5bc-41f6-bc4e-6e76c0bea959/20200311192855/az_regionb_backup_b87bb1e5-0d4e-445e-a548-5ae742562bac",
  "id": "b87bb1e5-0d4e-445e-a548-5ae742562bac",
  "size": 1,
  "object_count": 2,
  "deleted_at": null,
  "container": "my-test-backup",
  "service": "cinder.backup.drivers.swift.SwiftBackupDriver",
  "driver_info": {},
  "created_at": "2020-03-11T19:25:24Z",
  "display_description": null,
  "data_timestamp": "2020-03-11T19:25:24Z",
  "temp_volume_id": null,
  "parent_id": null,
  "encryption_key_id": null,
  "num_dependent_backups": 0,
  "fail_reason": null,
  "project_id": "14f1c1f5d12b4755b94edef78ff8b325",
  "metadata": {}
}
```

it is the full backup description https://github.com/openstack/cinder/blob/c29285e7dcda7f5300c5a3375294dfa4aeb56430/cinder/objects/backup.py#L32..L84

Shall we transparently base64 encode/decode this struct in gophercloud? Or just leave it as is like you mentioned in https://github.com/gophercloud/gophercloud/pull/1881#issuecomment-594020382

**Comment by jtopjian** [comment]
@kayrus good catch. Please leave as encoded and have the app do the decoding.

**Comment by kayrus** [comment]
@jtopjian can I add a `BackupURL` struct for convenience?

**Comment by jtopjian** [comment]
As long as the fields are defined in Cinder, yes.
