### ISSUE TITLE
Missing list options to Compute API services list call

### ISSUE THREAD

**Issue by dkt26111** [gophercloud/gophercloud#1903]
The Compute API for listing services allows the specification of query parameters for binary or host name: https://docs.openstack.org/api-ref/compute/#list-compute-services

The current implementation of the List call does not allow for the specification of those parameters:
https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/services/requests.go#L9

I will put a PR to add options to the List API.

**Comment by jtopjian** [comment]
Implemented in #1904
