### ISSUE TITLE
ContainerInfra v1: Support health_status and health_status_reason for cluster

### ISSUE THREAD

**Issue by openstacker** [gophercloud/gophercloud#1909]
This will allow user can check the health status and the health status reason of the cluster.

* [health_status](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L142)
* [health_status_reason](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L145)

Reference: https://review.opendev.org/#/c/570818/

**Comment by jtopjian** [comment]
Implemented in #1910 and #1968
