### ISSUE TITLE
Keystone V3: tokens package cleanup

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1920]
@jtopjian due to historical reasons `subjectTokenHeaders` func in tokens package has a client pointer argument.

https://github.com/gophercloud/gophercloud/blob/e2dceb1b9e0b3d2ec714f59139bb7ce7de822bd7/openstack/identity/v3/tokens/requests.go#L100

I'd remove it, since it is not used.

**Comment by jtopjian** [comment]
Nice find. I'll try to get to this today or tomorrow, unless someone beats me to it.

**Comment by jtopjian** [comment]
Fixed in #1923
