### ISSUE TITLE
How to use existing OS-FEDERATED token by gophercloud?

### ISSUE THREAD

**Issue by TenSt** [gophercloud/gophercloud#1929]
We have next scenario:
OpenStack is integrated with KeyCloak via federation. As I understood, gophercloud does not support authentication via federation (please prove me wrong if I am), so I've written basic functions to get necessary token from OpenStack directly via API. Now I have token (unscoped and scoped) and want to pass it to gophercloud to utilize the sdk, but can't find a proper way of doing it. 
Here is the process how I get tokens:
1) Go to KeyCloak and receive OpenIDConnect access token
2) Go to OS-FEDERATED auth to get unscoped OS-FEDERATED token:
https://docs.openstack.org/api-ref/identity/v3-ext/?expanded=#request-an-unscoped-os-federation-token
3) Go to /v3/auth/tokens to get scoped OS-FEDERATED token:
https://docs.openstack.org/api-ref/identity/v3-ext/?expanded=request-a-scoped-os-federation-token-detail#request-a-scoped-os-federation-token

Here is the func to get all projects:
```
func getAllProjects(token string) []projects.Project {
	var openstackOpts = gophercloud.AuthOptions{
		IdentityEndpoint: "https://indentity/v3",
		TokenID:          token,
	}
	provider, err := openstack.AuthenticatedClient(openstackOpts)
	if err != nil {
		log.Fatalf("Error with authentication provider from gophercloud/openstack: %s\n", err)
	}
	epOpts := gophercloud.EndpointOpts{
		Region: "RegionOne",
	}

	clientProject, err := openstack.NewIdentityV3(provider, epOpts)
	if err != nil {
		log.Fatalf("Error with getting identity client: %s\n", err)
	}

	listOpts := projects.ListOpts{
		Enabled: gophercloud.Enabled,
	}

	allpj, err := projects.List(clientProject, listOpts).AllPages()
	if err != nil {
		panic(err)
	}

	allProjects, err := projects.ExtractProjects(allpj)
	if err != nil {
		panic(err)
	}
	return allProjects
}
```
When I run it passing valid token (tried both scoped and unscoped), I'm receiving next error:
```
Error with getting identity client: No suitable endpoint could be found in the service catalog.
```
It seems like I was able to authenticate (got provider), but can't get the Identity client to work with Keystone. So the question is how to use OS-FEDERATED tokens in gophercloud? Or how to pass federated auth process using gophercloud? Any assistance is much appreciated.

Worth to mention that when I use these tokens as 'X-Auth-Token' header in direct requests to API - all works as expected.

Note: I've found this python plugin which do the job, but I'd rather not switch to python from golang:
https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/contrib/auth/v3/oidc.py

**Comment by jtopjian** [comment]
> As I understood, gophercloud does not support authentication via federation (please prove me wrong if I am)

This is correct - it hasn't been implemented yet.

I'd recommend looking at the [`clientconfig`](https://github.com/gophercloud/utils/tree/master/openstack/clientconfig) package in `gophercloud/utils` for authentication. It should be a lot easier to work with than the more raw authentication in gophercloud "core".

Let me know if this helps. If not, we'll start troubleshooting the issues you're running into :slightly_smiling_face:

**Comment by kayrus** [comment]
@TenSt I see that you're using unscoped auth parameters:

```go
	var openstackOpts = gophercloud.AuthOptions{
		IdentityEndpoint: "https://indentity/v3",
		TokenID:          token,
	}
```

Therefore auth is fine, but it doesn't return a catalog, therefore `openstack.NewIdentityV3(provider, epOpts)` fails. Catalog is empty, see:

https://github.com/gophercloud/gophercloud/blob/41239d7cba900437ce094408df1f74e0a2074f70/openstack/client.go#L223

or

https://github.com/gophercloud/gophercloud/blob/41239d7cba900437ce094408df1f74e0a2074f70/openstack/client.go#L241

If you want to get a scoped token with a catalog, you need to define a scope for the auth, e.g.

```go
	var openstackOpts = gophercloud.AuthOptions{
		IdentityEndpoint: "https://indentity/v3",
		TokenID:          token,
                Scope: &gophercloud.AuthScope{
                       DomainID: "foo",
                       ProjectID: "bar",
                       # or
                       DomainName: "foo",
                       ProjectName: "bar",
                },
	}
```

**Comment by kayrus** [comment]
@TenSt to debug JSON requests and responses you can use a special debug client from [github.com/gophercloud/utils/client](https://github.com/gophercloud/utils/tree/master/client) package: https://godoc.org/github.com/gophercloud/utils/client

**Comment by TenSt** [comment]
@jtopjian @kayrus Thanks for the information, guys!
Using Scope in the AuthOptions resolved the issue. Even using unscoped OS-FEDERATED token is enough for gophercloud to get its own scoped token and proceed to next steps.
And thanks for mentioning clientconfig package - didn't tried it yet, but if you recommend - definitely will try using it instead of raw auth in gophercloud "core".
