### ISSUE TITLE
servers.CreateOpts  AdminPass  not use

### ISSUE THREAD

**Issue by randomHHH** [gophercloud/gophercloud#1940]
i`m set AdminPass when create server ,but use the password in ssh not use.
use default password has same issue

**Comment by jtopjian** [comment]
@randomHHH Are you sure the admin pass feature is enabled in your OpenStack cloud?

**Comment by randomHHH** [comment]
@jtopjian oh,may be is this problem. Em....how to check the feature is enabled?not default enabled in OpenStack cloud?

**Comment by jtopjian** [comment]
If you aren't the admin for the OpenStack cloud you're using, you'll have to contact them to see if it's an enabled feature.

**Comment by randomHHH** [comment]
@jtopjian thank u,i will see
