### ISSUE TITLE
Core: close response body, when body is not used

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1949]
While working on #1942 I noticed that in certain cases there can be a resource leak. E.g. in delete operations:

https://github.com/gophercloud/gophercloud/blob/b88f26317c347bc39d800e54663fd86c2a35d53e/openstack/networking/v2/ports/requests.go#L185

When `JSONResponse` parameter is nil, the response body is not closed, therefore the existing connection cannot be reused.

See https://golang.org/pkg/net/http/#Client.Do

> If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close. If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request.

@jtopjian is it something that should be considered or do I dramatize things?

Relates to #1015

**Comment by jtopjian** [comment]
> is it something that should be considered or do I dramatize things?

My understanding is that it's not very efficient to have these left open and we should investigate how to handle this properly. 

This is also mentioned here: https://github.com/gophercloud/gophercloud/issues/1838 which is Yet Another Issue on my TODO list 🙂 

Similar was https://github.com/gophercloud/gophercloud/issues/1856 and https://github.com/thanos-io/thanos/pull/1489.

**Comment by kayrus** [comment]
@jtopjian thanks for confirming my concerns. I suppose that removing `req.Close` from `provider_client.go` and adding a `resp.Body.Close()` into all `request.go`, where `&r.Body` is not used, would be fine. There may be exceptions like `oauth` package I currently work on, or:
https://github.com/gophercloud/gophercloud/blob/b88f26317c347bc39d800e54663fd86c2a35d53e/openstack/imageservice/v2/imagedata/requests.go#L34
https://github.com/gophercloud/gophercloud/blob/b88f26317c347bc39d800e54663fd86c2a35d53e/openstack/objectstorage/v1/objects/requests.go#L134

It should be quite easy to grep pieces of code, where the `resp.Body` requires a special attention. If you don't mind I can submit a PR.

**Comment by jtopjian** [comment]
I think it's worth a try. We'll see how OpenLab reacts. If things look good, we can merge and see if anyone reports issues.

**Comment by jtopjian** [comment]
Also: thank you for looking into this!
