### ISSUE TITLE
How to add a QoS policy to an existing floating ip?

### ISSUE THREAD

**Issue by randomHHH** [gophercloud/gophercloud#1950]
How to add a QoS policy to an existing floating ip?

**Comment by kayrus** [comment]
According to OpenStack API [reference](https://docs.openstack.org/api-ref/network/v2/?&expanded=create-qos-policy-detail#create-qos-policy) it is possible to assign a QoS policy only to a project.

**Comment by randomHHH** [comment]
for now. i create a qos with rule bind to port, then create server with the port. but i wonder to know, in this way ,the qos could able to limit the server egress and ingress?
