### ISSUE TITLE
How to add extra param in floatingips opts

### ISSUE THREAD

**Issue by randomHHH** [gophercloud/gophercloud#1955]
i wonder to add a extra param in update opts

**Comment by jtopjian** [comment]
Are you trying to add an officially supported field of the OpenStack API? If so, which field is missing?

Or are you adding a custom field that has been added by your OpenStack cloud maintainers? If so, then you need to add additional parameters to a request, you'll need to define your own options struct which extends the original `UpdateOpts` struct  and then you'll need to define a `ToFloatingIPUpdateMap` method on your new opts structure.

An example of this being done to a different type of resource can be seen here: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/fw_firewall_v1.go#L19-L29
