### ISSUE TITLE
Object Store v1 Container: Misleading requests opts ContentType and DetectContentType

### ISSUE THREAD

**Issue by pdesgarets** [gophercloud/gophercloud#1959]
`ContentType` and `DetectContentType` make no sense for Containers requests (see the [reference](https://docs.openstack.org/api-ref/object-store/index.html?expanded=create-or-replace-object-detail,create-container-detail,list-activated-capabilities-detail,show-account-details-and-list-containers-detail,create-update-or-delete-account-metadata-detail,show-account-metadata-detail,show-container-details-and-list-objects-detail,create-update-or-delete-container-metadata-detail,show-container-metadata-detail,delete-container-detail,get-object-content-and-metadata-detail,copy-object-detail,delete-object-detail,show-object-metadata-detail,create-or-update-object-metadata-detail,list-endpoints-detail), they are only used either in responses, or for Objects requests)

Maybe they should be deleted to avoid any confusion ?

**Comment by jtopjian** [comment]
I think these two are used with the Bulk Request Middleware: https://github.com/openstack/swift/blob/742835a6ec12944f606d6cd65ca7f18fdf78a09c/swift/common/middleware/bulk.py

The operations for this middleware are done on the container endpoint rather than the object endpoint.

If that's not the case, then there still might have been a valid reason for including these headers in the request - I recall looking into something similar a few years ago (https://github.com/gophercloud/gophercloud/issues/596).

**Comment by pdesgarets** [comment]
Well, BulkDelete is supported but uses a hard coded `"Content-Type": "text/plain",`; and BulkUpload seems not to be supported.

But I get your point that they could be useful for a future implementation of BulkUpload.

**Comment by jtopjian** [comment]
Check out the documentation beginning on Line 47: https://github.com/openstack/swift/blob/742835a6ec12944f606d6cd65ca7f18fdf78a09c/swift/common/middleware/bulk.py#L47

**Comment by pdesgarets** [comment]
I read that, but the "extract-archive call" can not currently be achieved because it would need a queryparam `?extract-archive`; in the same way there is a `bulkDeleteUrl` (https://github.com/gophercloud/gophercloud/blob/336458aa7f54a59c98a5c67743e5779c283a61e1/openstack/objectstorage/v1/containers/urls.go#L25), it would need a `bulkUploadUrl` setting this queryparam.

**Comment by jtopjian** [comment]
Ah, good point. So it looks like we've got something that may have been half-implemented or was implemented years ago but was somehow dropped.
