### ISSUE TITLE
Core: store token information inside the client struct

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1960]
In case when you need to know current user id / project id / domain id / whatever, you have to create a token request against keystone to get the result and extract the information. More convenient way would be to store this info inside the `ProviderClient` struct after an auth process and return it using a method. @jtopjian , what do you think?

**Comment by jtopjian** [comment]
Possibly. I can see pros and cons to this. 

Since the ProviderClient is performing authentication, that information is already available and requesting another token just to call the extract methods would be redundant.

I'm open to seeing a PR with this implemented.

**Comment by kayrus** [comment]
Hm. I missed the existence of the [GetAuthResult](https://pkg.go.dev/github.com/gophercloud/gophercloud?tab=doc#ProviderClient.GetAuthResult) method. However you need to assert its type to `tokens.CreateResult` or `tokens.GetResult` to get the struct. There is even a [nice doc](https://pkg.go.dev/github.com/gophercloud/gophercloud?tab=doc#AuthResult) :man_facepalming:
