### ISSUE TITLE
AvailabilityZone support for Cinder Volumes and RootVolume when Instance spawned on cinder

### ISSUE THREAD

**Issue by ITD27M01** [gophercloud/gophercloud#1965]
In the case of real clouds there are multiple availability zones for different services (Nova/Neutron/Cinder). For the consistency provided by cloud services in particular datacenter this services are marked by availabilty_zone attribute.

There is no support for availability zones of cinder volumes and as a result we cannot create instances on the cinder boot volume on specified availability zone.

https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/bootfromvolume/requests.go#L45

**Comment by kayrus** [comment]
@ITD27M01 there is no option to define availability zone for the boot_from_volume: https://github.com/openstack/nova/blob/ef3b5707328f460d0d03759061c01b1a20f28743/nova/api/openstack/compute/schemas/servers.py#L48..L88

Nova creates a volume in the region, where compute instance is created.

If you want to create a bootable volume in a specific availability zone, you can create a volume in advance using https://github.com/gophercloud/gophercloud/blob/822b5cd65fc83eaf2bf5ba859000069e2b838ccb/openstack/blockstorage/v3/volumes/requests.go#L21, and then reference it in a `boot_from_volume` struct: https://github.com/gophercloud/gophercloud/blob/822b5cd65fc83eaf2bf5ba859000069e2b838ccb/openstack/compute/v2/extensions/bootfromvolume/requests.go#L45

**Comment by ITD27M01** [comment]
Hi, thank you for your response.

We have never used such a workflow and have always created a volume and then a machine with the corresponding bdm. But I came across a restriction in the cluster-api and now I know where it came from:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/9e63a34907bca1829185fb5fca1f56deaba5ab4b/pkg/cloud/services/compute/instance.go#L252

So, as a workaround I can use AZ-aware volume types: https://docs.openstack.org/cinder/rocky/admin/blockstorage-availability-zone-type.html

**Comment by kayrus** [comment]
@ITD27M01 never heard about the https://github.com/kubernetes-sigs/cluster-api-provider-openstack project. Looks similar to Rancher or Gardener. As for the code: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/9e63a34907bca1829185fb5fca1f56deaba5ab4b/pkg/cloud/services/compute/instance.go#L252

it looks like it uses the existing volume: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/9e63a34907bca1829185fb5fca1f56deaba5ab4b/pkg/cloud/services/compute/instance.go#L255 and if it was created in a wrong AZ, then you'll get an error. I suppose you need to follow the https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/554 issue, it is not a gophercloud limitation.

**Comment by ITD27M01** [comment]
@kayrus Thank you!

**Comment by ITD27M01** [comment]
@kayrus One more caveat. The sourceUUID can be a Glance Image in this workflow:

`          rootVolume:
            deviceType: ""
            diskSize: 100
            sourceType: image
            sourceUUID: rhcos-4.4.3-x86_64-openstack
            volumeType: standard-infra`
