### ISSUE TITLE
Keystone v3 cannot use listOpts (type tenants.ListOpts) as type *tenants.ListOpts in argument to tenants.List

### ISSUE THREAD

**Issue by gmontalvoy** [gophercloud/gophercloud#1972]
Hey everyone,

Using the example I saw on godocs about listing identities I'm facing the following:
`
./main.go:31:31: cannot use listOpts (type tenants.ListOpts) as type *tenants.ListOpts in argument to tenants.List
`
I'm just trying to list tenants user can see using their authOpts

`
	authOpts, err := openstack.AuthOptionsFromEnv()
	if err != nil {
		log.Fatal(err)
	}

	provider, err := openstack.AuthenticatedClient(authOpts)

	opts := gophercloud.EndpointOpts{}
	identityClient, err := openstack.NewIdentityV3(provider, opts)

	identityOpts := tenants.ListOpts{}
	server := tenants.List(identityClient, identityOpts)

AFAIK tenants.listOpts is the required valid struct type to use as a tenant.List second argument. 
I'm assuming I'm doing something wrong as it is a very simple example, but I can't see it right now.

**Comment by jtopjian** [comment]
@gmontalvoy You need to use a pointer to the listops.

EIther:

```go
identityOpts := &tenants.ListOpts{}
v := tenants.List(identityClient, identityOpts)
```

or

```go
identityOpts := tenants.ListOpts{}
v := tenants.List(identityClient, &identityOpts)
```


I'll update the documentation - sorry about that.

**Comment by gmontalvoy** [comment]
Thank you so much @jtopjian 

Closed.
