### ISSUE TITLE
replace os-volumes_boot with servers in Bootfromvolume URL

### ISSUE THREAD

**Issue by jichenjc** [gophercloud/gophercloud#1974]
currently BFV is using

func createURL(c *gophercloud.ServiceClient) string {
       return c.ServiceURL("os-volumes_boot")
at  openstack/compute/v2/extensions/bootfromvolume/urls.go

according to
https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/routes.py#L726
os-volumes_boot is identical to servers routes and it will be deprecated later

https://docs.openstack.org/api-ref/compute/
os-volumes_boot is not listed at all

**Comment by kayrus** [comment]
@jichenjc this issue can be closed
