### ISSUE TITLE
Acc Tests: Fix any test failures for older releases

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#1976]
It's been a while since the acceptance tests have been run against various older versions of OpenStack. We should do this and fix any problems that arise.

**Comment by kayrus** [comment]
@jtopjian this issue can be closed

**Comment by jtopjian** [comment]
Not yet. Even though the suite of tests is now being successfully launched, there are individual tests that are failing that need to be investigated.

**Comment by jtopjian** [comment]
Fixed in #2001
