### ISSUE TITLE
DB Instances: IP parameter missing in result

### ISSUE THREAD

**Issue by esalipe** [gophercloud/gophercloud#198]
In case a Trove database instance has no hostname, gophercloud returns no information on how to connect to it.

In such a case Trove will return the IP address(es) of the database instance instead:
https://github.com/openstack/trove/blob/stable/newton/trove/instance/views.py#L46

This information could be parsed and returned to the user by gophercloud.

**Comment by jrperritt** [comment]
closed by #199
