### ISSUE TITLE
ContainerInfra v1: Support merge-labels when creating cluster

### ISSUE THREAD

**Issue by openstacker** [gophercloud/gophercloud#1984]
Now Magnum supports a new parameter named `marge-labels` when creating a new cluster. The default value is False, the labels passed in by the user will be automatically merged with the labels defined in the cluster template when it's set True. It's a quite useful feature that improves the UX a lot.

[1] https://review.opendev.org/#/c/720221/

**Comment by jtopjian** [comment]
Implemented in #1985
