### ISSUE TITLE
listeners lack support of TERMINATED_HTTPS protocol 

### ISSUE THREAD

**Issue by hamzazafar** [gophercloud/gophercloud#1991]
Octavia supports creating listeners of type TERMINATED_HTTPS.

Please see the *protocol* option in [requests section of creating listeners](https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail#id35)

TERMINATED_HTTPS protocol should be added to listeners in gophercloud!

**Comment by jtopjian** [comment]
Implemented in #1992
