### ISSUE TITLE
Example on using access key + secret Key (application credentials)

### ISSUE THREAD

**Issue by TomMann** [gophercloud/gophercloud#1996]
Afternoon GopherCloud,
I've gone through your documentation, but I can't find an example on how to get this to play nicely when my authentication method is using an access key.  Would be great to get this in the documentation or just an example in response is cool too :)
Thanks in advance
Tom.

**Comment by jtopjian** [comment]
@TomMann I believe you'll want to use the `ec2tokens` package: https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/extensions/ec2tokens/doc.go

**Comment by TomMann** [comment]
Thanks, looks to be what I needed 👍

**Comment by kayrus** [comment]
@TomMann accrding to the topic's `application credentials`, you may want to use [OpenStack Application Credentials](https://docs.openstack.org/keystone/latest/user/application_credentials.html). Endeed, I couldn't find an example for application credentials auth. Here is an example based on https://github.com/gophercloud/gophercloud/issues/1365#issuecomment-448294161:

1:

```go
authOptions := tokens.AuthOptions{
  IdentityEndpoint: "http://keystone/v3",
  Username: "username",
  DomainID: "domainID",
  ApplicationCredentialName: "name",
  ApplicationCredentialSecret: "secret",
}
token, err := tokens.Create(client, &authOptions).Extract()
```

1.1:

```go
authOptions := tokens.AuthOptions{
  IdentityEndpoint: "http://keystone/v3",
  Username: "username",
  DomainName: "domainName",
  ApplicationCredentialName: "name",
  ApplicationCredentialSecret: "secret",
}
token, err := tokens.Create(client, &authOptions).Extract()
```

2:

```go
authOptions := tokens.AuthOptions{
  IdentityEndpoint: "http://keystone/v3",
  ApplicationCredentialID: "id",
  ApplicationCredentialSecret: "secret",
}
token, err := tokens.Create(client, &authOptions).Extract()
```

3:

```go
authOptions := tokens.AuthOptions{
  IdentityEndpoint: "http://keystone/v3",
  UserID: "userID",
  ApplicationCredentialName: "name",
  ApplicationCredentialSecret: "secret",
}
token, err := tokens.Create(client, &authOptions).Extract()
```
