### ISSUE TITLE
[blockstorage]UnmarshalJSON error with RFC3339 timestamps in volumes.

### ISSUE THREAD

**Issue by zh-f** [gophercloud/gophercloud#1997]
When I tried to get volume details in our OpenStack environment, which version is queens 17.0.3,  using gophercloud blockstorage v3 like this :

```go
        volume, err := volumes.Get(client, "45fdb4fc-ad85-4512-85e6-980451edc57e").Extract()
        if err != nil {
                log.Errorf("err is %v", err)
        }
        log.Infof("Volume is %v", volume)
```
The volume detail is :
```
 cinder show el-volume
+------------------------------+-------------------------------------------------+
| Property                     | Value                                           |
+------------------------------+-------------------------------------------------+
| attached_servers             | []                                              |
| attachment_ids               | []                                              |
| availability_zone            | nova                                            |
| bootable                     | true                                            |
| consistencygroup_id          | None                                            |
| created_at                   | 2020-07-31T07:18:53Z                            |
| description                  | el-volume                                       |
| encrypted                    | False                                           |
| id                           | 45fdb4fc-ad85-4512-85e6-980451edc57e            |
| metadata                     |                                                 |
| multiattach                  | False                                           |
| name                         | el-volume                                       |
| os-vol-tenant-attr:tenant_id | bd6f9720483b4e259e840ead64a5b5d1                |
| replication_status           | None                                            |
| size                         | 20                                              |
| snapshot_id                  | None                                            |
| source_volid                 | None                                            |
| status                       | available                                       |
| updated_at                   | 2020-07-31T07:18:56Z                            |
| user_id                      | bfa8089a9eb542a7b43288979f697883                |
| volume_image_metadata        | checksum : 441af00e2dd98f1b2795b4b9a1ef84f0     |
|                              | container_format : bare                         |
|                              | ctcm_enabled : true                             |
|                              | disk_format : raw                               |
|                              | hw_qemu_guest_agent : yes                       |
|                              | hw_vif_multiqueue_enabled : true                |
|                              | image_id : f9de62d7-1896-4561-8571-b8e83b52696b |
|                              | image_name : newCentOS7.6                       |
|                              | image_version : v1.1                            |
|                              | min_disk : 0                                    |
|                              | min_ram : 0                                     |
|                              | os_distro : centos                              |
|                              | os_type : linux                                 |
|                              | os_version : 7.6                                |
|                              | size : 21474836480                              |
| volume_type                  | default_volume_type                             |
+------------------------------+-------------------------------------------------+
```

I got an error:

```
err is parsing time "2020-07-31T07:18:53Z": extra text: Z
```

The reason is that in [cinder/utils.py#L277](https://github.com/openstack/cinder/blob/2ecda828e9539a5c3fef554c357c18e27af951fa/cinder/utils.py#L277), we may get [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp like what I have `"2020-07-31T07:18:53Z"`，but current gophercloud dose not support unmarshal this format in volume, see [openstack/blockstorage/v3/volumes/results.go#L88-L105](https://github.com/gophercloud/gophercloud/blob/bd999d0da882fe8c5b0077b7af2dcc019c1ab458/openstack/blockstorage/v3/volumes/results.go#L88-L105). 

We have to double check to unmarshal error to support this format.

**Comment by jtopjian** [comment]
@zh-f Thanks for reporting this issue, but this might be an issue with the specific cloud you're interacting with.

In #2000, I have triggered our acceptance test suite to run on OpenStack Queens. You can see the logs here (https://logs.openlabtesting.org/logs/00/2000/daa4dfc1857bfda6039a27a82b78caa24a417e80/recheck-queens/gophercloud-acceptance-test-queens/531989e/job-output.txt.gz) 

Ignoring that the test suite, as a whole, failed, search for the string `=== RUN   TestVolumes`. You'll see the test results for the Block Storage v3 service. The timestamp format is `2020-08-03T20:53:01.000000`.

**Comment by zh-f** [comment]
@jtopjian Thanks for replying so quickly. As the code (https://github.com/openstack/cinder/blob/2ecda828e9539a5c3fef554c357c18e27af951fa/cinder/utils.py#L277-L290) shows if we have at.tzinfo, then the timestamp format is `2020-08-03T20:53:01.000000`, I've tried in our cloud:

```
>>> from oslo_utils import timeutils
>>> at = timeutils.utcnow()
>>> at.tzinfo
>>> at
datetime.datetime(2020, 8, 4, 6, 21, 18, 825985)
```
It seems that tzinfo here is none.  The timestamp formats in our env, from nova to neutron,  are all the same, with Z at the end of timestamp. 

In gophercloud, we can see network code supports two format here (https://github.com/gophercloud/gophercloud/blob/ffb0421108ba77e952c6af78f20748ca99c1186d/openstack/networking/v2/networks/results.go#L95-L131). When I get network details in our env, nothing bad happends.

Is there any chance gophercloud is compatible with this scenario?

**Comment by jtopjian** [comment]
@zh-f 

> In gophercloud, we can see network code supports two format here 

This is because it was confirmed that the Neutron project changed time formats between OpenStack releases. We were able to confirm this by pulling information from multiple environments as well as being able to reproduce the behaviour in Devstack.

The time format being used for Block Storage in Gophercloud has been used without problems for the past 5 years. Have you seen this issue in multiple OpenStack environments or just one?

Can you please deploy a Devstack environment, have it use `stable/queens`, and double-check the behaviour? The result should be what I showed previously: a format of `2020-08-03T20:53:01.000000`. 

If this problem only exists in one cloud (due to the API service code being customized), then Gophercloud won't support that kind of change. Gophercloud only supports vanilla/unmodified OpenStack. However, one possible solution is to create a local copy of the `volumes` Go package which extracts the timestamp differently.

**Comment by zh-f** [comment]
@jtopjian Thanks, I'll try to use a local copy 😄
