### ISSUE TITLE
add support for cells v1 DifferentCells filter

### ISSUE THREAD

**Issue by cardoe** [gophercloud/gophercloud#2011]
The filter was added in https://github.com/openstack/nova/commit/596ee8796a028596e5ea1ad0529aa3f14b6f5934 to the OpenStack codebase. gophercloud supports it's corresponding filter TargetCell but doesn't support DifferentCell. While it's a cells v1 feature it's useful to folks that still have cells v1 deployments.

**Comment by jtopjian** [comment]
Implemented in #2012
