### ISSUE TITLE
Neutron v2: Lists l3 agents hosting a specific router.

### ISSUE THREAD

**Issue by alexeymyltsev** [gophercloud/gophercloud#2022]
The L3 agent scheduler extension (l3_agent_scheduler) allows retrieve mappings between Neutron routers and L3 agents.

API doc:
https://docs.openstack.org/api-ref/network/v2/?expanded=list-l3-agents-hosting-a-router-detail#l3-agent-scheduler
Source code:
https://github.com/openstack/neutron/blob/fefd9a6bb1e5b685d56c75e7a538b0dfc0a959ec/neutron/db/l3_hascheduler_db.py#L44-L55

**Comment by jtopjian** [comment]
@alexeymyltsev Thanks for reporting this. If you would like, please feel free to submit a PR for this and/or let me know if you need any help.

**Comment by alexeymyltsev** [comment]
@jtopjian I have a question about structure for agents in response. It looks like same that already [exist](https://github.com/gophercloud/gophercloud/blob/b1ee3a6a3b9297e670c54cafbf247744b9b8026b/openstack/networking/v2/extensions/agents/results.go#L57-L102) but with extra two field:
`           "resource_versions": {},
            "ha_state": "standby"`
resource_versions everywhere in my tests is empty, but ha_state is exactly key field of this api endpoint.
Should I add `ha_state` to existing type or copy same type from agent extension to layer3 and adding additional field?

**Comment by jtopjian** [comment]
@alexeymyltsev You'll need to look at the Neutron API code directly to determine the how the JSON response is built. I would imagine that the general Neutron agent extension would handle responses for both DHCP agents and router agents. If that's true, then the fields you see were amended sometime after that code was submitted to Gophercloud. But who knows - maybe there are two distinct agent extensions. In which case you will need to copy the struct to a new package.

**Comment by jtopjian** [comment]
Implemented in #2025
