### ISSUE TITLE
Support Magnum cluster upgrade API

### ISSUE THREAD

**Issue by jkmw** [gophercloud/gophercloud#2031]
Currently there is no support for the cluster `upgrade`-action.

API doc:
- https://docs.openstack.org/api-ref/container-infrastructure-management/?expanded=upgrade-a-cluster-detail#upgrade-a-cluster

source from cluster-actions controller:
- https://github.com/openstack/magnum/blob/e8467e94d88b6feb67ff7c167f5e167cd452c772/magnum/api/controllers/v1/cluster_actions.py#L58
- https://github.com/openstack/magnum/blob/e8467e94d88b6feb67ff7c167f5e167cd452c772/magnum/api/controllers/v1/cluster_actions.py#L132

**Comment by jtopjian** [comment]
@jkmw Thank you for opening this. Please note that API documentation alone is not enough to support a feature being added. More information is [here](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-03-code-hunting.md) in our Contributor Tutorial. Let me know if you have any questions.

**Comment by jkmw** [comment]
@jtopjian well, I have linked the code location now, so that it's clear that my change is supported.

I hope this is enough?

**Comment by jtopjian** [comment]
Thanks. 

In your PR, you are defining a new struct with a set of fields. Do you know where these fields are defined? In other words, how do we know that `max_batch_size` is a valid field to be sent in a JSON request?

**Comment by jkmw** [comment]
I have now also linked the class, which contains all parameters that are used for the upgrade call. These are in the same file as the reference to calling the controller.

I assumed that the rest of the context is self-evident from the file :shrug:

**Comment by jtopjian** [comment]
Implemented in #2032
