### ISSUE TITLE
Add ip, ip6, user_id fields to servers.ListOpts

### ISSUE THREAD

**Issue by sfiera** [gophercloud/gophercloud#2035]
I’d like to submit a PR to add three fields to servers.ListOpts: `ip`, `ip6`, and `user_id`.

Documentation: https://docs.openstack.org/api-guide/compute/server_concepts.html#server-query
Source: https://github.com/openstack/nova/blob/a948a803b561606a892133940915caae610c080b/nova/api/openstack/compute/schemas/servers.py#L567

**Comment by jtopjian** [comment]
@sfiera Sure, sounds good to me.

**Comment by jtopjian** [comment]
Implemented in #2038
