### ISSUE TITLE
Status of RAX-KSKEY (APIKey removed?)

### ISSUE THREAD

**Issue by dave2** [gophercloud/gophercloud#204]
It appears in commit db0ae14 the option to provide Rackspace API keys (an extension to the keystone API) was removed. Packer currently provides an option for passing the API key.

I can't see any sign of the API keys for Rackspace being deprecated, so will RAX-KSKEY be added back into gophercloud? What is the status of support for Rackspace being driven by gophercloud?

Thanks!

**Comment by jrperritt** [comment]
> so will RAX-KSKEY be added back into gophercloud?

Rackspace-specific code won't be added to this repository.

> What is the status of support for Rackspace being driven by gophercloud?

Gophercloud has shifted focus to exclusively support OpenStack proper. You should be able to use it with Rackspace Private Cloud but probably not Rackspace Public Cloud. For Rackspace Public Cloud, you can continue to use the `rackspace/gophercloud` repo.
