### ISSUE TITLE
Job on Travis-CI failing 

### ISSUE THREAD

**Issue by kishorkunal-raj** [gophercloud/gophercloud#2042]
Hi All,
I am running jobs on travis-ci and found that jobs are failing for go1.11.X and 1.12.X. Below are the logs

$ git clone --depth=50 --branch=master https://github.com/kishorkunal-raj/gophercloud.git kishorkunal-raj/gophercloud
$ travis_export_go 1.14 github.com/kishorkunal-raj/gophercloud
0.01s
Setting environment variables from .travis.yml
$ export GO111MODULE=on
6.35s$ travis_setup_go
go version go1.14 linux/amd64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.14.linux.amd64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="on"
$ gimme version
v1.5.4
$ go version
go version go1.14 linux/amd64
go.env
$ go env
install.1
1.96s$ GO111MODULE=off go get golang.org/x/crypto/ssh
6.31s$ GO111MODULE=off go get -v -tags 'fixtures acceptance' ./...
github.com/gophercloud/gophercloud (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
openstack/identity/v3/groups/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/identity/v3/policies/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/identity/v3/projects/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/identity/v3/regions/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/identity/v3/roles/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/identity/v3/services/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/identity/v3/users/results.go:8:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/imageservice/v2/images/results.go:11:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
openstack/messaging/v2/queues/results.go:7:2: use of internal package github.com/gophercloud/gophercloud/internal not allowed
The command "GO111MODULE=off go get -v -tags 'fixtures acceptance' ./..." failed and exited with 1 during .

Your build has been stopped.

Please look into it

**Comment by jtopjian** [comment]
We're only supporting Go 1.13+. 

Is there a specific reason you need to test with 1.11 and 1.12? 

The "use of internal package" error you're seeing is, IMO, a false error. We named the package "internal" to mean "don't use this outside of Gophercloud". We could change the package name, but since that error is not happening on Go 1.13+, I'm not concerned about it.

**Comment by kishorkunal-raj** [comment]
> We're only supporting Go 1.13+.
> 
> Is there a specific reason you need to test with 1.11 and 1.12?
> 
> The "use of internal package" error you're seeing is, IMO, a false error. We named the package "internal" to mean "don't use this outside of Gophercloud". We could change the package name, but since that error is not happening on Go 1.13+, I'm not concerned about it.

Apologies , My mistake. I wrongly specified the versions as 1.1 and 1.12. Actually I am trying on Go 1.13, 1.14, 1.15 & tip and with all version of its failing

**Comment by jtopjian** [comment]
That's odd. As you can see from the current PRs, Travis is passing.

**Comment by jtopjian** [comment]
@kishorkunal-raj This error did end up happening a while back. As a fix, the `internal` package has been removed.
