### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by rendaw** [gophercloud/gophercloud#2046]
On OVH trying to create a load balancer with the API disabled returns the error "Resource not found".  Using the octavia python client the error is "public endpoint for load-balancer service in REGION region not found".  With the former I got confused and thought it was referring to a cloud resource not being found (either the subnet or the lb itself from an earlier api operation).

I'm not sure if this was a 404 exactly and I'm not sure if 404 always indicates an api is missing but I think based on python-octaviaclient's behavior it should be possible to provide additional clarification.

**Comment by kayrus** [comment]
@rendaw can you provide the full API debug log? You can use this approach: https://pkg.go.dev/github.com/gophercloud/utils/client (see `OS_DEBUG` examples).

**Comment by rendaw** [comment]
Ah sorry, it looks like the specific issue was that I was using the Network ServiceClient instead of the LoadBalancer one.  The returned payload was
```
{
"code": "404 Not Found",
"message": "The resource could not be found.\u003cbr /\u003e\u003cbr /\u003e\n\n\n",
"title": "Not Found",
}
```
Using the correct client I got the error "No suitable endpoint could be found in the service catalog"

Thanks for the help and sorry for the noise!

**Comment by rendaw** [comment]
I have the full log if it would be helpful for anything, I need to sanitize and check some stuff before I post though.

**Comment by kayrus** [comment]
@rendaw full log should include URLs as well

**Comment by rendaw** [comment]
Here's the full log of the request
```
2020/10/29 16:08:16 [DEBUG] OpenStack Request URL: GET https://network.compute.gra7.cloud.ovh.net/v2.0/lbaas/loadbalancers?name=xyz
2020/10/29 16:08:16 [DEBUG] OpenStack Request Headers:
Accept: application/json
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
2020/10/29 16:08:16 [DEBUG] OpenStack Response Code: 404
2020/10/29 16:08:16 [DEBUG] OpenStack Response Headers:
Content-Length: 112
Content-Type: application/json; charset=UTF-8
Date: Thu, 29 Oct 2020 07:08:16 GMT
Strict-Transport-Security: max-age=15768000
X-Iplb-Instance: 25121
X-Openstack-Request-Id: req-332b3a4a-d15c-466d-8c9d-5d5eb1fe14b7
2020/10/29 16:08:16 [DEBUG] OpenStack Response Body: {
  "code": "404 Not Found",
  "message": "The resource could not be found.\u003cbr /\u003e\u003cbr /\u003e\n\n\n",
  "title": "Not Found"
}
```
Just to reiterate though, I don't think there's any bug here.  I'll check on the catalog, there's no loadbalancer endpoints listed though in their dashboard.

**Comment by jtopjian** [comment]
Thanks, @kayrus!
