### ISSUE TITLE
how to use microversion in this api

### ISSUE THREAD

**Issue by bboyHan** [gophercloud/gophercloud#2054]
Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

**Comment by kayrus** [comment]
@bboyHan a doc is available via https://github.com/gophercloud/gophercloud/blob/master/docs/MICROVERSIONS.md

**Comment by bboyHan** [comment]
thanks~

**Comment by jtopjian** [comment]
@kayrus Thanks

@bboyHan I'm going to close this issue, but please let us know if you have any other questions.
