### ISSUE TITLE
Networking v2: Add detailed quota reporting

### ISSUE THREAD

**Issue by EmilienM** [gophercloud/gophercloud#2060]
Neutron supports the ability to get not just the current quota for a project, but also the current allocation against the quota [1] through a "details.json" endpoint. Please enable this collection.

[1] https://docs.openstack.org/api-ref/network/v2/index.html?expanded=show-quota-details-for-a-tenant-detail#quotas-extension-quotas

This action would look similar to the existing quota fetch action, with a more complex response set.

**Comment by jtopjian** [comment]
Implemented in #2061
