### ISSUE TITLE
Objectstorage v1: metadata cannot be removed from accounts and objects

### ISSUE THREAD

**Issue by reenjii** [gophercloud/gophercloud#2062]
Related to [#1511](https://github.com/gophercloud/gophercloud/issues/1511)

When updating an objectstorage account or object, it is not possible to remove a metadata. If you set a key to an empty string [the empty header is stripped from the request when the POST is made](https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L307).

> // MoreHeaders specifies additional HTTP headers to be provide on the request. If a header is
> // provided with a blank value (""), that header will be *omitted* instead: use this to suppress
> // the default Accept header or an inferred Content-Type, for example.
> MoreHeaders map[string]string

Both calls should have a `RemoveMetadata` slice to allow sending `X-Remove-xxx-Meta-xxx` headers.

**Comment by jtopjian** [comment]
Implemented in #2063
