### ISSUE TITLE
Support of update snapshot operation

### ISSUE THREAD

**Issue by TenSt** [gophercloud/gophercloud#2066]
Hi Gophercloud team.
I was going through crud operations of snapshots and I see that update is not there. There is update metadata, however no update for snapshot. There is an API call for this operation in OpenStack:
https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=#update-a-snapshot

I'm willing to work on contribution of it, but before starting wanted to know if there was some reason behind not covering it from the start? Is there some issue with it or it was just missed and I can work on contributing it?

Thanks,
Stepan

**Comment by jtopjian** [comment]
@TenSt Thanks for opening this issue. It looks like the update call was just overlooked and never added.

**Comment by TenSt** [comment]
@jtopjian thanks. Then I will start working on contributing it. It may take some time as it would be my first contribution to gophercloud and I will be configuring local environment for the first time.

**Comment by jtopjian** [comment]
@TenSt No problem. Let me know if you need any help or have any questions.

**Comment by TenSt** [comment]
@jtopjian 
Sorry for the delay, I was really pinned down at work. Here is the PR, I hope I've covered everything: #2081

**Comment by TenSt** [comment]
Closing, as the code was successfully merged and released in v0.15.0
