### ISSUE TITLE
PUT/DELETE for nova quota-sets

### ISSUE THREAD

**Issue by dbaumgarten** [gophercloud/gophercloud#207]
At the moment there is only a function for getting the current nova quotas for a tenant/project and no possibility to update (PUT) or reset (DELETE) them. 

I would be happy to contribute this functionality to gophercloud. ( In fact, as I needed this for work I have already written the needed code)

If you are ok with that, I would open a PR.

**Comment by jrperritt** [comment]
closed by #214
