### ISSUE TITLE
Add support for volume_type blockstorage quota

### ISSUE THREAD

**Issue by nikParasyr** [gophercloud/gophercloud#2072]
Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Block Storage api allows to set quota per volume type as shown [here](https://docs.openstack.org/api-ref/block-storage/v3/?expanded=update-quotas-for-a-project-detail#quota-sets-extension-os-quota-sets).

I'd like to work on this but i'm a bit unsure given the nature that the blockstorage api approaches this with `volumes_<volume_type>` etc and how to updateOpts are [set](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/quotasets/requests.go#L62). Any suggestions or direction would be welcome. :)

**Comment by jtopjian** [comment]
@nikParasyr I apologize for the late reply.

Yes, this looks like a tricky feature to implement. 

There are a few areas in Gophercloud where we use a utility function called [`RemainingKeys`](https://github.com/gophercloud/gophercloud/search?q=RemainingKeys). This function will bundle all JSON response fields that don't match the corresponding struct into a map. In the case of per-volume-type quotas, all returned fields such as `volumes_foo` could be bundled into a map. 

For `UpdateOpts`, we might have to add a field called `Extra` which will allow arbitrary fields to be added to the JSON body, similar to what's done [here](https://github.com/gophercloud/gophercloud/blob/f0b37a3eb4b4251a1041975345294c22fa083822/openstack/identity/v3/groups/requests.go#L147-L163).

I hope that helps. Please let me know if you have any questions.

**Comment by jtopjian** [comment]
Implemented in #2109
