### ISSUE TITLE
Backups list detail

### ISSUE THREAD

**Issue by rendaw** [gophercloud/gophercloud#2083]
`openstack volume backup list --volume X` uses `/v3/.../backups/detail?volume_id=...` whereas gophercloud uses `/v3/.../backups?volume_id=...`.  `detail` adds the backup status which can be useful for filtering out failed backups (significantly reduces number of requests if there are a lot).

I'd be glad to make a PR adding this if someone can give me an overview of the form it should take.  New `ListDetail` function and `listDetailUrl` which takes the same query struct?

**Comment by jtopjian** [comment]
@rendaw Thank you for opening this issue.

I think it's best to implement a whole new set of code, duplicating the existing [regular list call](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/backups/requests.go#L86-L146), but for `ListDetail`. 

Perhaps the detailed list call is backwards compatible with the regular list call, and perhaps could have superseded the regular list call, but it's probably better and more flexible to users to have both as separate calls.

Let me know if this makes sense or if you have any questions.

**Comment by rendaw** [comment]
Perfect, thanks!

**Comment by jtopjian** [comment]
Implemented in #2085
