### ISSUE TITLE
Clustering: Return ActionResult for node remove API

### ISSUE THREAD

**Issue by dkt26111** [gophercloud/gophercloud#2088]
The Node Remove API in Senlin Clustering returns a actionID same as Node Add API:

https://docs.openstack.org/api-ref/clustering/?expanded=remove-nodes-from-a-cluster-detail#remove-nodes-from-a-cluster

Therefore, the Node Remove API should return an ActionResult same as Node Add API.

**Comment by jtopjian** [comment]
Implemented in #2089
