### ISSUE TITLE
Apparently-completed connections to Keystone and Cinder fail with "i/o timeout"

### ISSUE THREAD

**Issue by jralbert** [gophercloud/gophercloud#2100]
Hello,
I'm using the Kubernetes Cinder CSI plugin (https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md) to allow a Kubernetes cluster running on my OpenStack cloud to provision Cinder volumes dynamically. The plugin uses gophercloud to connect to the OpenStack APIs.

Some of the time, requests to the OpenStack APIs are successful, and with plugin debug logging turned way up I can see that the plugin is sometimes able to connect to Keystone, get a token, and then connect to Cinder to list and create volumes. However, most of the time connections to either Keystone or Cinder will appear to retry several times at 10-second intervals, and eventually fail with a message like:

I0120 17:39:17.616376       1 openstack.go:581] OpenStack connection error, retries exhausted. Aborting
W0120 17:39:17.616511       1 main.go:108] Failed to GetOpenStackProvider: Post "https://<CLOUD_DOMAIN>:5000/v3/auth/tokens": OpenStack connection error, retries exhausted. Aborting. Last error was: dial tcp <CLOUD_IP>:5000: i/o timeout

This result occurs with both POSTs and GETs, and requests that often fail still do sometimes succeed.

Since I'm also in control of the OpenStack cloud infrastrucutre, I've been able to confirm in the API server logs that the requests which are being retried have in fact been received and responded to by the API servers, all with 2xx or 3xx response codes and in response times well under 10 seconds (most GETs are under 1 second), which leads me to think that there's not a genuine timeout condition here.

Basic connectivity testing with cURL inside the container where the plugin is running confirms that there's no difficulty or delay in querying the API server endpoints; tcpdump on the Kubernetes worker node hosting the container shows complete TCP conversations between the container and the API servers, with no indication of RSTs or broken connections.

Based on all that, I have to think there must be either a bug in the gophercloud client implementation, or some unexpected interaction between gophercloud and the HAproxy service I'm running in front of the of the API servers.

Is this something you've seen before? How should I move forward in troubleshooting this issue?

**Comment by jtopjian** [comment]
@jralbert I'm sorry you're running into this issue, but I'm not sure what the cause could be - I'm not familiar with how `cloud-provider-openstack` works.

How are you resolving this problem? Do connections begin working automatically after some time? 

When you say you have tested with curl, were you hitting the haproxy service or going directly to an API server? 

Are you able to have Kubernetes bypass HAProxy? This would be the best way to rule out HAProxy interfering.

If all else fails, have you opened an issue about this at https://github.com/kubernetes/cloud-provider-openstack? Ultimately that might be the better place to discuss to get more information. 

There are certainly ways of digging into this and debugging in more detail, but they would involve modifying Gophercloud with logging statements and then recompiling `cloud-provider-openstack`. I'm happy to help where I can, but my unfamiliarity with `cloud-provider-openstack` will probably be a hinderance here.

**Comment by jralbert** [comment]
@jtopjian I appreciate the response, I know this is a very poorly-defined issue report - as much as anything I was hoping that this would be a condition the gophercloud developer community would have seen before, as I've had no success finding related issues or documentation from either the `cloud-provider-openstack` community or the broader web.

As far as I can tell from the source, the cinder CSI plugin (which is functionally a stand-alone component of `cloud-provder-openstack` just wraps gophercloud to perform its interactions with OpenStack; most of its unique code is on the Kubernetes CSI side. The issues I'm encountering seem to have to do with "i/o timeout" being returned in response to gophercloud's HTTPClient.do call (eg https://github.com/gophercloud/gophercloud/blob/7d4ec67e8c6c0b4b608026d33a74a5433185e458/provider_client.go#L415) - and that's not a handled error type in gophercloud or in the go HTTP client library, as far as I can see. It looks like it's bubbling up from way down in the Go core networking code: https://github.com/golang/go/blob/master/src/net/net.go#L573

The comments there make it look like this is a deprecated condition really meant to highlight when a context deadline has been exceeded. Is the context deadline for gophercloud's HTTP requests tuneable? I'm quite suspicious that this is an actual timeout condition, given that it seems to be occurring much more quickly than e.g. a common TCP timeout window.

**Comment by jtopjian** [comment]
> Some of the time, requests to the OpenStack APIs are successful, and with plugin debug logging turned way up I can see that the plugin is sometimes able to connect to Keystone, get a token, and then connect to Cinder to list and create volumes. However, most of the time connections to either Keystone or Cinder will appear to retry several times at 10-second intervals, and eventually fail with a message like

Does this behaviour appear as soon as the plugin starts or does it take some time for it to begin? In other words, if you restart the plugin, are 100% of the connections successful up until a certain point in time? And if so, approximately how long does it take to exhibit this behviour?

The reason I ask is because if this CSI plugin in a long-running binary, then this could be an issue of stale clients and not refresh/recreating them.

If you're hitting HAProxy, is it possible that the failed requests are going to a specific node (or nodes) that are configured differently than the other nodes?

> Is the context deadline for gophercloud's HTTP requests tuneable?

Tunable in what way? It's possible to set a custom [`http.Client`](https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L69) and [`Context`](https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L84) in the Provider Client, though I'm not sure how `cloud-provider-openstack` interacts with those.

@kayrus I think you work with `cloud-provider-openstack` quite a bit - do you have any idea what might be causing this?

**Comment by kayrus** [comment]
@jralbert gophercloud allows to set the context, but cloud-provider openstack doesn't set it. Nevertheless the http client transport allows to set fine-grained timeouts, which are not set and cloud controller manager client uses the golang [defaults](https://golang.org/pkg/net/http/#RoundTripper):

```go
var DefaultTransport RoundTripper = &Transport{
    Proxy: ProxyFromEnvironment,
    DialContext: (&net.Dialer{
        Timeout:   30 * time.Second,
        KeepAlive: 30 * time.Second,
        DualStack: true,
    }).DialContext,
    ForceAttemptHTTP2:     true,
    MaxIdleConns:          100,
    IdleConnTimeout:       90 * time.Second,
    TLSHandshakeTimeout:   10 * time.Second,
    ExpectContinueTimeout: 1 * time.Second,
}
```

For sure you need to open an issue in https://github.com/kubernetes/cloud-provider-openstack repo, besides there is a related request to introduce a http connection tracing into the occm client: https://github.com/kubernetes/cloud-provider-openstack/issues/1207

**Comment by jralbert** [comment]
@kayrus Thanks very much for this information, that helps a bunch; thanks @jtopjian for getting the conversation going. It sounds to me, if I understand @kayrus correctly, like both the lack of information in the debug logs and the apparent issue with expiring contexts are a part of the CPO implementation of gophercloud, and not gophercloud itself. I will pursue this with a bug report in the CPO repo as you suggest; thanks again for your engagement on this!

**Comment by jtopjian** [comment]
@jralbert Sounds good. Please feel free to revisit this here if needed.

@kayrus Thank you!
