### ISSUE TITLE
Auth: add TrustID support to AuthOptions

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#2114]
Trust based auth is supported, but it is not handled automatically in AuthOptions or `gophercloud/utils` package.

**Comment by pgaxatte** [comment]
This is probably superseded by https://github.com/gophercloud/gophercloud/issues/3105 and https://github.com/gophercloud/gophercloud/pull/3106

**Comment by pierreprinetti** [comment]
Good catch @pgaxatte.
@kayrus what do you think? Can we close this issue?

**Comment by pierreprinetti** [comment]
tentatively closing @kayrus please reopen if necessary
