### ISSUE TITLE
Personality isn't working 

### ISSUE THREAD

**Issue by brucemartins** [gophercloud/gophercloud#212]
Data is not being sent properly, I already have a fix for this and have tested it with terraform and would like to make a PR with the fix

**Comment by jtopjian** [comment]
Some prior discussion about this can be found here: https://github.com/hashicorp/terraform/pull/10517

Some of the acceptance tests implement "personality", but there isn't verification done within the instance to confirm it was successful.

**Comment by jrperritt** [comment]
closed by #213
