### ISSUE TITLE
Baremetal: Add automated_clean field to Ironic node

### ISSUE THREAD

**Issue by fmuyassarov** [gophercloud/gophercloud#2121]
I would like to add Ironic `Node.automated_clean` field which is currently missing in https://github.com/gophercloud/gophercloud/tree/master/openstack/baremetal/v1/nodes

Reference to the field in Ironic: [automated_clean](https://github.com/openstack/ironic/blob/8604f84fd7bda4e30d3f07005c4901f3662303a7/ironic/objects/node.py#L145)

**Comment by fmuyassarov** [comment]
Seems the issue didn't get closed automatically. Shall we close it now @jtopjian ?

**Comment by jtopjian** [comment]
Implemented in #2122

**Comment by jtopjian** [comment]
@fmuyassarov Yes, thank you 🙂
