### ISSUE TITLE
Support include_names option in role_assignments endpoint

### ISSUE THREAD

**Issue by objque** [gophercloud/gophercloud#2124]
Hello, after solving issue https://github.com/gophercloud/gophercloud/issues/550, support for role-assignments was added. 
The Identity API v3.6 introduce ability to load names with query arguments `include_names=True`

It will be great if someone add support of it

doc https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=id627-detail#id627

**Comment by objque** [comment]
@jtopjian

**Comment by jtopjian** [comment]
I agree that it would be great if someone added support for this.

**Comment by objque** [comment]
Okay, I'll take it

**Comment by objque** [comment]
Hey! delayed a little due to tasks at work. I'm working on a patch right now.

**Comment by jtopjian** [comment]
Implemented in #2133
