### ISSUE TITLE
Baremetal: Add maintenance mode flag/reason to nodes.CreateOpts

### ISSUE THREAD

**Issue by hardys** [gophercloud/gophercloud#2127]
I would like to add the fields to set maintenance mode on node creation, which are currently missing in https://github.com/gophercloud/gophercloud/tree/master/openstack/baremetal/v1/nodes `CreateOpts` (they do already exist in the gophercloud [Node definition](https://github.com/gophercloud/gophercloud/blob/master/openstack/baremetal/v1/nodes/results.go#L83)

Ironic API docs: https://docs.openstack.org/api-ref/baremetal/?expanded=create-node-detail

Reference to the field in Ironic code: 
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L151
https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L2133

It's mentioned that `maintenance_reason` was added for v1.8:
https://github.com/openstack/ironic/blob/ebaa359937817319c15bd6acfb88d74f0d2d63bb/ironic/objects/node.py#L48

**Comment by hardys** [comment]
@dtantsur am I reading this correctly - Ironic actually only allows setting `maintenance` and not `maintenance_reason` on create https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L151

The API docs say both can be set, but looking at the code I'm not sure that's actually the case?

**Comment by dtantsur** [comment]
@hardys for the reasons I don't even clearly remember (and definitely not support), maintenance is set through separate API endpoints: https://docs.openstack.org/api-ref/baremetal/?expanded=set-maintenance-flag-detail#set-maintenance-flag and https://docs.openstack.org/api-ref/baremetal/?expanded=set-maintenance-flag-detail,clear-maintenance-flag-detail#clear-maintenance-flag.

**Comment by hardys** [comment]
Ok I did some  testing, and confirmed you can set `maintenance` via the POST v1/nodes, but the validation in Ironic prevents setting `maintenance_reason`

That must be because maintenance_reason is missing in the schema ref https://github.com/openstack/ironic/blob/master/ironic/api/controllers/v1/node.py#L151

**Comment by hardys** [comment]
I'll close this for now since it seems Ironic doesn't support both fields on create, instead we can make two API calls
