### ISSUE TITLE
Compute: Handle Hypervisor request parameters

### ISSUE THREAD

**Issue by ntk148v** [gophercloud/gophercloud#2132]
Start from API version 2.53, Nova returns a list of server objects.

https://docs.openstack.org/api-ref/compute/?expanded=list-hypervisors-details-detail#hypervisors-os-hypervisors

https://github.com/openstack/nova/blob/stable/victoria/nova/api/openstack/compute/hypervisors.py#L89

**Comment by jtopjian** [comment]
Implemented in #2187
