### ISSUE TITLE
Blockstorage: support listing availability zones

### ISSUE THREAD

**Issue by Fedosin** [gophercloud/gophercloud#2134]
Cinder API extension `AvailabilityZones` provides the ability show summary for all availability zones for volumes. We need to support it to gophercloud.

API doc:

https://docs.openstack.org/cinder/latest/contributor/api/cinder.api.contrib.availability_zones.html
https://docs.openstack.org/api-ref/block-storage/v3/?list-known-api-extensions-detail&expanded=list-known-api-extensions-detail#list-known-api-extensions

Source code:

https://github.com/openstack/cinder/blob/master/cinder/api/contrib/availability_zones.py

**Comment by jtopjian** [comment]
Implemented in #2135
