### ISSUE TITLE
Question about static typing certain string values

### ISSUE THREAD

**Issue by jh125486** [gophercloud/gophercloud#2147]
I was wondering if there would be any good reason not to static type known string values, specifically things like `Server.Status`?

I see that `glance` has types defined @ https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/types.go, but nothing for the other services.

**Comment by jtopjian** [comment]
Gophercloud does have static typing throughout the different services (for example: https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/security/rules/requests.go), but you're right in that there are areas where it's missing.

There's no reason other than a matter of preference when the code is submitted and not being modified later. Totally open to implementing this where possible.

**Comment by jh125486** [comment]
OK, I may pursue adding some of this in my spare time.   
I got bit by the `Status` in Glance being `active` while in Nova it's `ACTIVE`, which threw me for a loop during tests 😕
