### ISSUE TITLE
loadbalancer listeners lack support of SCTP protocol 

### ISSUE THREAD

**Issue by nikParasyr** [gophercloud/gophercloud#2148]
Based on octavia api docs listeners support SCTP protocol: https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-listener-detail#create-listener

This was added on 2.23 microversion https://github.com/openstack/octavia/blob/4e53676b2a4f8e97b8c2412436813d890b67672f/octavia/api/root_controller.py#L136

**Comment by jtopjian** [comment]
Implemented in #2149

**Comment by nikParasyr** [comment]
Closing
