### ISSUE TITLE
keystone issue: why http request will be translate to https through openstack.AuthenticatedClient method

### ISSUE THREAD

**Issue by roccia** [gophercloud/gophercloud#2152]
when I was trying to init a keystone client through ``` openstack.AuthenticatedClient ``` method, it will change my auth_url: http://xxx.xx.xxx.x to https://xxx.xx.xxx.x  then I got  
``` Post "https://xxx.xx.xxx.x:35357/v3/auth/tokens": http: server gave HTTP response to HTTPS client``` error, 

 the keystone server was deployed by nginx+gunicorn, and I did not setup any ssl for  keystone server(actually I dont know how to do that) , when enter http://xxx.xx.xxx.x:35357 in browser I got 
 `{"versions": {"values": [{"id": "v3.14", "status": "stable", "updated": "2020-04-07T00:00:00Z", "links": [{"rel": "self", "href": "https://xxx.xx.xxx.x:35357/v3/"}], "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}]}]}} `, but it works fine with my custom code(init a client, send request),such as retrive a token, create user etc..

my questions are:
1. ``` Post "https://xxx.xx.xxx.x:35357/v3/auth/tokens": http: server gave HTTP response to HTTPS client```  is the url in this error come from  ``` "links": [{"rel": "self", "href": "https://xxx.xx.xxx.x:35357/v3/"}] ```?
2. how can I fix it, do I need to turn off or turn on ssl in keystone?
Thanks

**Comment by jtopjian** [comment]
Is the Identity endpoint configured as https in your catalog?

**Comment by roccia** [comment]
> Is the Identity endpoint configured as https in your catalog?

I did not do anything in catalog, just set the auth url with http in bootstrap

**Comment by jtopjian** [comment]
>  is the url in this error come from "links": [{"rel": "self", "href": "https://xxx.xx.xxx.x:35357/v3/"}]

Yes, this is the cause of the issue.

The is confirming that your catalog is configured for https and not http. You will need to update the endpoint entry in your OpenStack Identity catalog to use http and not https.

> how can I fix it, do I need to turn off or turn on ssl in keystone?

It's always best to use SSL, but you should be able to use plain http just by updating the entry in your OpenStack Identity catalog.

**Comment by jtopjian** [comment]
Glad to hear you figured it out 🙂
