### ISSUE TITLE
Add support for `network_data` field in baremetal Node

### ISSUE THREAD

**Issue by zaneb** [gophercloud/gophercloud#2153]
[In the Victoria release](https://docs.openstack.org/releasenotes/ironic/victoria.html#relnotes-15-2-0-stable-victoria-new-features), Ironic added a new `network_data` field to the Node API. It can be set on [create](https://docs.openstack.org/api-ref/baremetal/?expanded=create-node-detail#create-node) and retrieved in [show node details](https://docs.openstack.org/api-ref/baremetal/?expanded=show-node-details-detail#show-node-details). The minimum microversion required is 1.66.

**Comment by jtopjian** [comment]
Implemented in #2154
