### ISSUE TITLE
Ironic acceptance test broken due to iSCSI removal

### ISSUE THREAD

**Issue by zaneb** [gophercloud/gophercloud#2155]
The `iscsi` deploy method was removed from ironic a couple of days ago: https://review.opendev.org/c/openstack/ironic/+/789382

In the acceptance tests, we somehow still have it configured as a deploy method:

```
May 07 16:02:51.116565 ubuntu ironic-conductor[29096]: DEBUG oslo_service.service [-] enabled_deploy_interfaces      = ['iscsi', 'direct'] {{(pid=29096) log_opt_values /usr/local/lib/python3.6/dist-packages/oslo_config/cfg.py:2603}}
```

Yet we are using the latest ironic with no endpoint defined for iscsi, and hence ironic-conductor crashes at startup with the error:

```
May 07 16:02:51.626961 ubuntu ironic-conductor[29096]: ERROR oslo_service.service [None req-e8571b51-b066-4e40-9269-b3da9465bda7 None None] Error starting thread.: ironic.common.exception.DriverNotFoundInEntrypoint: Could not find the following items in the 'ironic.hardware.interfaces.deploy' entrypoint: iscsi.
```

**Comment by jtopjian** [comment]
@zaneb Thanks for looking into this. I'm not familiar with Ironic, but let me know if I can help.

**Comment by zaneb** [comment]
The config is hard-coded in openlab-zuul-jobs (for some reason, even though it was the same as the old default), so we just have to get someone to review that PR.

**Comment by jtopjian** [comment]
Other PRs now look to be passing. I'm going to close this issue.

@zaneb Thank you for identifying and fixing this.
