### ISSUE TITLE
Octavia: pool is missing SCTP and PROXYV2 protocols

### ISSUE THREAD

**Issue by nikParasyr** [gophercloud/gophercloud#2157]
2 more protocols were added recently to octavia pool resource. Specifically:
`PROXYV2`: in [2.22](https://github.com/openstack/octavia/blob/16e83eef0154a30ef91fb09842bf009c540f1c66/octavia/api/root_controller.py#L133)
`SCTP`: in [2.23](https://github.com/openstack/octavia/blob/16e83eef0154a30ef91fb09842bf009c540f1c66/octavia/api/root_controller.py#L136)

The createOpts need to be updated to allow these protocols.

**Comment by jtopjian** [comment]
Implemented in #2158
