### ISSUE TITLE
Existing Ironic API bios_interface fields are missing

### ISSUE THREAD

**Issue by bfournie** [gophercloud/gophercloud#2163]
There are a few bios_interface fields that are implemented in the Ironic API but are missing from gophercloud implementation, most likely because they were missing from the Ironic api-ref documentation at one point. 

The missing fields are:
- bios_interface in /v1/nodes Create Node, see https://docs.openstack.org/api-ref/baremetal/?expanded=create-node-detail#node-bios-nodes
- bios_interface in /v1/nodes/detail, added to api-ref by https://review.opendev.org/c/openstack/ironic/+/791493/2/api-ref/source/baremetal-api-v1-nodes.inc
- bios in /v1/nodes/{node_ident}/validate, added to api-ref by https://review.opendev.org/c/openstack/ironic/+/792210/1/api-ref/source/baremetal-api-v1-node-management.inc

**Comment by jtopjian** [comment]
Implemented in #2163
