### ISSUE TITLE
Add support for Ironic bios API

### ISSUE THREAD

**Issue by bfournie** [gophercloud/gophercloud#2165]
The Ironic bios API - `/v1/nodes/{node_ident}/bios`, has been available since version 1.40 of the Ironic API, see
https://docs.openstack.org/api-ref/baremetal/?expanded=#node-bios-nodes.  It provides the ability to get all or individual BIOS settings on a node. 

Support should be added to Gophercloud for the bios API.

**Comment by mandre** [comment]
Implemented via https://github.com/gophercloud/gophercloud/pull/2171.
