### ISSUE TITLE
Add support for additional bios API fields from Redfish bios registry

### ISSUE THREAD

**Issue by bfournie** [gophercloud/gophercloud#2166]
As described in the Ironic spec - https://review.opendev.org/c/openstack/ironic-specs/+/774681, additional fields are being added to the Ironic bios API in to include fields retrieved from the Redfish BIOS registry. This is currently up for review in 
https://review.opendev.org/c/openstack/ironic/+/786707 using the proposed micro-version 1.74.

This is a follow-on to the bios API support https://github.com/gophercloud/gophercloud/issues/2165 that should be implemented once the Ironic patch above merges.

**Comment by jtopjian** [comment]
Implemented in #2174
