### ISSUE TITLE
Authenticating with env vars and still needing OS_PROJECT_ID

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#2175]
From before 2018 I've been doing this to authenticate (error handling stuff removed):

```
// gophercloud uses non-standard env var names, so convert if necessary
if os.Getenv("OS_DOMAIN_ID") == "" && os.Getenv("OS_PROJECT_DOMAIN_ID") != "" {
	err := os.Setenv("OS_DOMAIN_ID", os.Getenv("OS_PROJECT_DOMAIN_ID"))
}

if os.Getenv("OS_DOMAIN_ID") == "" && os.Getenv("OS_DOMAIN_NAME") == "" && os.Getenv("OS_USER_DOMAIN_NAME") != "" {
	err := os.Setenv("OS_DOMAIN_NAME", os.Getenv("OS_USER_DOMAIN_NAME"))
}

opts, err := openstack.AuthOptionsFromEnv()
opts.AllowReauth = true
provider, err := openstack.AuthenticatedClient(opts)
```

The above fails if you set OS_PROJECT_NAME and not OS_PROJECT_ID.
One of my users complained that they shouldn't have to set OS_PROJECT_ID, and should be able to switch projects by just exporting a different OS_PROJECT_NAME.

After skimming https://github.com/gophercloud/gophercloud/issues/252 and looking at the latest version of the gophercloud README, I can simplify to:

```
opts, err := clientconfig.AuthOptions(&clientconfig.ClientOpts{})
opts.AllowReauth = true
provider, err := openstack.AuthenticatedClient(*opts)
```

This works without OS_PROJECT_ID being set, just OS_PROJECT_NAME. And it correctly handles DOMAIN related things (I only have `export OS_USER_DOMAIN_NAME="Default"; export OS_PROJECT_DOMAIN_ID="default"`).

So that's a good improvement. 

However, amongst other things I later need to call:

```
q, err := quotasets.Get(p.computeClient, p.tenantID).Extract()
[...]
p.externalNetworkID, err = networksutil.IDFromName(p.networkClient, p.poolName)
[...]
fIP, err := floatingips.Create(p.computeClient, floatingips.CreateOpts{
    Pool: p.poolName,
}).Extract()
```

I currently get the tenant ID and pool name like this:

```
if opts.TenantID == "" {
	return fmt.Errorf("either OS_TENANT_ID or OS_PROJECT_ID must be set")
}
p.tenantID = opts.TenantID

// we use a non-standard env var to find the default network from which to
// get floating IPs from, which defaults depending on age of OpenStack
// installation
p.poolName = os.Getenv("OS_POOL_NAME")
if p.poolName == "" {
	if os.Getenv("OS_TENANT_ID") != "" {
		p.poolName = "nova"
	} else {
		p.poolName = "public"
	}
}
```

Which re-introduces the "unnecessary" requirement for OS_PROJECT_ID (or OS_TENANT_ID in older systems).

Is there a solution to this, so that a project ID environment variable (and my own OS_POOL_NAME) is no longer needed?

**Comment by jtopjian** [comment]
A Nova "pool" can be thought of as a Neutron public subnet. It should be possible to query/search for a subnet using the Neutron API without having to provide a project ID and pool name.

**Comment by sb10** [comment]
Thanks, I'll look in to that. What about `quotasets.Get()` needing a tenant ID? Is there a way to query the current tenant ID using gophercloud? Or some alternative way of getting to the same result?

**Comment by jtopjian** [comment]
I think the quotasets API is still requiring an ID. One option might be to create a new token or get the current token and then analyze the details about it. The results should include the Tenant/Project ID:

https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/tokens/results.go

**Comment by sb10** [comment]
I didn't figure out the pool name side of things yet, but getting the project ID via identify is good enough for now, thanks.
