### ISSUE TITLE
floating ip tags are not able to be added

### ISSUE THREAD

**Issue by tobiasgiese** [gophercloud/gophercloud#2184]
Currently there is no way to add floating ip tags, as the `CreateOpts` struct does not have the tags field implemented yet.
Further, `ListOpts` is already able to list the tags.

xref: https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/layer3/floatingips/requests.go#L69-L81

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by kayrus** [comment]
Tags are supported for FIPs via [attributestags](https://pkg.go.dev/github.com/gophercloud/gophercloud@v0.18.0/openstack/networking/v2/extensions/attributestags) package. See how it is done in Terraform Openstack Provider: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/c26a60ac723f0bf70c8b68ccafe06e85da4a4b96/openstack/resource_openstack_networking_floatingip_v2.go#L239

**Comment by tobiasgiese** [comment]
Thanks, I didn't know that 👍🏻
