### ISSUE TITLE
Implement FWaaS Router Insertion

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#219]
I recently came across the `fwaasrouterinsertion` FWaaS extension. On environments with this extension enabled, the firewall will remain `INACTIVE` until the firewall is associated with one or more routers:

https://github.com/openstack/neutron-fwaas/blob/d2938b247104ac6d7c945167b246cfcfed8393e8/neutron_fwaas/extensions/firewallrouterinsertion.py

**Comment by jrperritt** [comment]
closed by #220

**Comment by jtopjian** [comment]
Thanks!
