### ISSUE TITLE
sharedfilesystems: Share struct is missing CreateShareFromSnapshotSupport field

### ISSUE THREAD

**Issue by gman0** [gophercloud/gophercloud#2190]
[`shares.Share` struct](https://github.com/gophercloud/gophercloud/blob/932f0916e113975e4d34bcd1d2dce9c01aa96570/openstack/sharedfilesystems/v2/shares/results.go#L17-L76) is missing mapping to `create_share_from_snapshot_support` field. See [Share details]( https://docs.openstack.org/api-ref/shared-file-system/?expanded=show-share-details-detail#show-share-details) request and response for reference.

**Comment by jtopjian** [comment]
Implemented in #2191
