### ISSUE TITLE
[question] Is it possible to do a create call in gophercloud with more than one extension applied? 

### ISSUE THREAD

**Issue by jichenjc** [gophercloud/gophercloud#2195]
copied from 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/921#discussion_r670487063

in CAPI we use portsbinding extension when creating port and now we want to add one more for security group
is it allowed or some gap existing now? 

more detail can be found https://kubernetes.slack.com/archives/CFKJB65G9/p1626700059187400

**Comment by jtopjian** [comment]
Yes, it's possible. 

To use multiple extensions in a request (create, update, etc), you need to "wrap" the opt struct inside the extension, and then wrap the result in another extension, etc. Here is an example:

* First a basic `ports.CreateOpts` is created: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L297-L310
* It is then wrapped in `extradhcpopts.CreateOptsExt` for DHCP options: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L328-L339
* It is then wrapped again in `portsecurity.PortCreateOptsExt` for port security: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L341-L348
* And again in `portsbinding.CreateOptsExt` for port bindings: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L365-L370
* And again in `dns.PortCreateOptsExt` for DNS: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L375-L378
* And finally in `policies.PortCreateOptsExt` for policies: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L382-L385

When you submit the request, the resulting JSON body will contain an extended port object. You can make sure all relevant fields are unmarshalled by creating a custom struct that combines multiple result struct extensions: For resulting structs, you can create custom types that combine a resource with multiple extensions. Extensions are just ways of adding additional fields to a struct (which turns into a JSON request). An example of that can be seen here: 

* https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/a0c0d478f9a4d3961b607bb5feff6e3bda4cf037/openstack/networking_port_v2.go#L21-L28
* https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_port_v2.go#L390-L396

I hope that helps.

**Comment by jichenjc** [comment]
@jtopjian that's great, thanks for the detailed info

**Comment by iamemilio** [comment]
Thanks @jichenjc for opening an issue for this!
