### ISSUE TITLE
Add support to get provider info of network details

### ISSUE THREAD

**Issue by TonyZhang1989** [gophercloud/gophercloud#2196]
networking/v2  networks.Network struct doesn't has provider info,  i need it.

type Network struct {
	// UUID for the network
	ID string `json:"id"`

	// Human-readable name for the network. Might not be unique.
	Name string `json:"name"`

	// Description for the network
	Description string `json:"description"`

	// The administrative state of network. If false (down), the network does not
	// forward packets.
	AdminStateUp bool `json:"admin_state_up"`

	// Indicates whether network is currently operational. Possible values include
	// `ACTIVE', `DOWN', `BUILD', or `ERROR'. Plug-ins might define additional
	// values.
	Status string `json:"status"`

	// Subnets associated with this network.
	Subnets []string `json:"subnets"`

	// TenantID is the project owner of the network.
	TenantID string `json:"tenant_id"`

	// UpdatedAt and CreatedAt contain ISO-8601 timestamps of when the state of the
	// network last changed, and when it was created.
	UpdatedAt time.Time `json:"-"`
	CreatedAt time.Time `json:"-"`

	// ProjectID is the project owner of the network.
	ProjectID string `json:"project_id"`

	// Specifies whether the network resource can be accessed by any tenant.
	Shared bool `json:"shared"`

	// Availability zone hints groups network nodes that run services like DHCP, L3, FW, and others.
	// Used to make network resources highly available.
	AvailabilityZoneHints []string `json:"availability_zone_hints"`

	// Tags optionally set via extensions/attributestags
	Tags []string `json:"tags"`

}

**Comment by jtopjian** [comment]
Does the `provider` extension help?

https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/provider/doc.go

**Comment by TonyZhang1989** [comment]
> Does the `provider` extension help?
> 
> https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/provider/doc.go

**Comment by TonyZhang1989** [comment]
> Does the `provider` extension help?
> 
> https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/provider/doc.go

Right, i got it. Thanks
