### ISSUE TITLE
Unable to parse Block Storage v1 Volume.CreatedAt

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#22]
When trying to create a volume, the following error is returned:

```
parsing time "2016-07-26T01:21:26.911126" as "2006-01-02T15:04:05.999999Z": cannot parse "" as "Z"
```

It looks like the [CreatedAt](https://github.com/gophercloud/gophercloud/blob/9b7b9e6a417dcbe0495f02a1eb381f3bcd193230/openstack/blockstorage/v1/volumes/results.go#L21) type needs changed to `gophercloud.JSONRFC3339MilliNoZ`.

**Comment by jrperritt** [comment]
closed by #23
