### ISSUE TITLE
servers.Server field missing

### ISSUE THREAD

**Issue by waibizi** [gophercloud/gophercloud#2202]
Hello, the servers.Server seem missing some fields ,example OS-EXT-SRV-ATTR attribute corresponding field
https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/results.go#L147

If you need validation, you can use command : nova show [serverID]

**Comment by jtopjian** [comment]
Please see:

* https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/extendedserverattributes
* https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/extendedstatus

**Comment by waibizi** [comment]
Thank you very much for answering my question in time, but I would like to ask if I can directly get the "OS-ext-SRV-attr" attribute field when get the server list, because servers.List(computeClient, listOpts).AllPages() inside the underlying code I see that when I take the list data at this point I can get this extended information。

**Comment by waibizi** [comment]
Thank you very much for your answer. I found the attribute extension pattern I need in your unit test. Sorry, I didn't see the unit test before.

**Comment by jtopjian** [comment]
No problem at all. Please let me know if you have any questions or need any help.
