### ISSUE TITLE
How to use OS-ext-srV-attr :user_data to create a VM?

### ISSUE THREAD

**Issue by waibizi** [gophercloud/gophercloud#2204]
Hello, could you please tell me that I need to use script injection to Create the virtual machine, that is, the extended attribute "OS-ext-SRV-attr :user_data", I would like to ask how to achieve this requirement through the method of Servers.create

**Comment by waibizi** [comment]
@jtopjian

**Comment by kayrus** [comment]
@waibizi please refer to #2202 issue raising a similar question.

**Comment by waibizi** [comment]
Ok, thank you for your timely reply, which has solved my problem
