### ISSUE TITLE
Display detailed message for 404 not found error

### ISSUE THREAD

**Issue by schirevko** [gophercloud/gophercloud#2222]
Hello.
Similarly to https://github.com/gophercloud/gophercloud/issues/243, some APIs may return detailed error message for 404 Not Found errors. For example:
`{"itemNotFound": {"code": 404, "message": "Resource ... cannot be found."}}`
It could be useful if `ErrDefault404.Error()` would show this detailed message instead of `"Resource not found"`
(https://github.com/gophercloud/gophercloud/blob/master/errors.go#L182)

**Comment by mandre** [comment]
Fixed via https://github.com/gophercloud/gophercloud/pull/2223.
