### ISSUE TITLE
DB Instances: Fault information missing in result

### ISSUE THREAD

**Issue by esalipe** [gophercloud/gophercloud#224]
When a DB instance has errored, Trove provides fault information in instance detail responses:
https://github.com/openstack/trove/blob/stable/newton/trove/instance/models.py#L395

The fault information class is defined here:
https://github.com/openstack/trove/blob/stable/newton/trove/instance/models.py#L1479
Only part of the fault information is returned in the response:
https://github.com/openstack/trove/blob/stable/newton/trove/instance/views.py#L128

Support for parsing the fault information would be useful as the information makes understanding why a DB instance is in ERROR state much simpler.

**Comment by jtopjian** [comment]
@esalipe I've fixed up your original branch and merged it as #1014. Let me know if you have any questions. :)
