### ISSUE TITLE
Is there any inconsistency between the document and interface when creating a VM using a security group?

### ISSUE THREAD

**Issue by waibizi** [gophercloud/gophercloud#2249]
hello，I see here that the document uses sgid ：https://github.com/gophercloud/gophercloud/blob/ecbce8932548dd33e3fd6a63e9f1f6f224537868/openstack/compute/v2/extensions/secgroups/doc.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L80
But what I see in the interface is ：
https://github.com/gophercloud/gophercloud/blob/ecbce8932548dd33e3fd6a63e9f1f6f224537868/openstack/compute/v2/extensions/secgroups/requests.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L180
Is there a problem with my understanding or with the original interface? Look forward to being answered.

**Comment by jtopjian** [comment]
@waibizi I'm going to close this issue, but please let me know if you have any additional questions and I can re-open this.
