### ISSUE TITLE
Ports: Removing Security Groups and Allowed Address Pairs

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#226]
The Neutron command-line client provides port update options of `--no-security-groups` and `--no-allowed-address-pairs` which passes empty arrays to the API server:

```
DEBUG: keystoneauth.session REQ: curl -g -i 
-X PUT http://10.1.15.127:9696/v2.0/ports/c9f02a7a-4aac-44ed-a2bc-947db82621d2.json 
-H "User-Agent: python-neutronclient" 
-H "Content-Type: application/json" 
-H "Accept: application/json" 
-H "X-Auth-Token: {SHA1}861547906c8c47c61d33008eae9c7877b09a6a4b" 
-d '{"port": {"security_groups": []}}'

DEBUG: keystoneauth.session REQ: curl -g -i 
-X PUT http://10.1.15.127:9696/v2.0/ports/e937b274-e3f8-4b64-b056-0885875620b1.json 
-H "User-Agent: python-neutronclient" 
-H "Content-Type: application/json" 
-H "Accept: application/json" 
-H "X-Auth-Token: {SHA1}c2478d044e2294608a20ac440eed08f42bc1d500" 
-d '{"port": {"allowed_address_pairs": []}}'
```

In order to emulate this behavior, the `omitempty` tags for [these fields](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/ports/requests.go#L122-L123) needs to be removed.

As for the server-side, I'm pretty sure this is where the empty array is being validated:

* [port](https://github.com/openstack/neutron/blob/7b3d7ba98e04286b14950cc9ab5c699a418dbb45/neutron/db/securitygroups_db.py#L723)
* [allowed_address_pairs](https://github.com/openstack/neutron/blob/0b9935a1411e58005370c762b5a5895e385e45b2/neutron/db/allowedaddresspairs_db.py#L104)

**Comment by jrperritt** [comment]
closed by #236
