### ISSUE TITLE
Add new CI job to sync acceptance tests

### ISSUE THREAD

**Issue by EmilienM** [gophercloud/gophercloud#2263]
We currently have no mechanism to check that our functional CI jobs execute all available acceptance tests in Gophercloud.

We could do the following:

* Maintain a list of acceptance tests per CI job
* Have a CI job that will:
  * Merge all these files, and make it unique, so we have a list of all the acceptance tests run by our CI
  * List all acceptance tests available in the project
  * Make sure the two lists are equal

This would complete the coverage check that we have, but making sure that if we have new tests available, that they're well exercised somewhere.

**Comment by mandre** [comment]
This was fixed by moving to github action.
