### ISSUE TITLE
PR template mandates an issue number but won't close related issue on merge

### ISSUE THREAD

**Issue by mandre** [gophercloud/gophercloud#2269]
Github allows to close related issue when a PR merges by using a special keyword [1]. We should make use of it in the PR template.
    
[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by pierreprinetti** [comment]
I believe that the choice of a keyword that doesn't trigger automation was deliberate.

For example, the maintainers of this project have asked contributors to create one PR per HTTP method (see [this example](https://github.com/gophercloud/gophercloud/issues/526#issuecomment-331717450)). If the PR template had "Fixes #...", then the implementer would have to change it on each PR to follow the required flow.

**Comment by jtopjian** [comment]
> I believe that the choice of a keyword that doesn't trigger automation was deliberate.

This is correct, though there is (was?) nothing preventing this from being changed. I always used it as a form of manual review to double-check that the issue was resolved. Though honestly most of the time I ended up forgetting to close the issue for a week or three...
