### ISSUE TITLE
How to use GopherCloud to remove OpenStack MAC+IP verification

### ISSUE THREAD

**Issue by waibizi** [gophercloud/gophercloud#2285]
Hello, I would like to ask how I should use GopherCloud to achieve this common ` openstack port set --no-security-group --disable-port-security `

**Comment by jtopjian** [comment]
These examples should help:

* https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/networking/v2/networking.go#L49-L76
* https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/networking/v2/networking.go#L153-L192
* https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/networking/v2/ports_test.go#L285-L325

Let us know if you have any questions or need any additional help.

**Comment by waibizi** [comment]
Thank you very much for your timely reply, which is very helpful to me. Thank you

**Comment by jtopjian** [comment]
No problem at all. I'm going to close this issue but let us know if you have any other questions.
