### ISSUE TITLE
Add supprt for identity v3 registered limits

### ISSUE THREAD

**Issue by nikParasyr** [gophercloud/gophercloud#2290]
As part of the `unified limits` keystone has added a `registered_limits` api.
Add support for it.

[docs](https://docs.openstack.org/api-ref/identity/v3/?expanded=list-projects-detail#unified-limits)
[code](https://github.com/openstack/keystone/blob/34a37772e866074f0bc5413c18bb446ac8c1d17e/keystone/api/registered_limits.py)

**Comment by emilmaruszczak** [comment]
To someone implementing "create" operation, please consider fixing the test introduced as part of https://github.com/gophercloud/gophercloud/pull/2464. It requires a registered limit to be created for arbitrary service, before a limit can be created.
Thank you

**Comment by nikParasyr** [comment]
Fixed by: #2616
