### ISSUE TITLE
Investigate sensible defaults for common HTTP functionality (e.g. re-auth limit, logging)

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#230]
These have caused confusion for enough people to consider adding defaults. In the case of implementing a default re-auth limit, it would likely be a backwards-incompatible change (for anyone counting on infinitely trying to re-auth).

**Comment by kayrus** [comment]
Logging was added in https://github.com/gophercloud/utils/tree/master/client
@jtopjian I believe the issue can be closed.
