### ISSUE TITLE
Add support for volume types in DBaaS

### ISSUE THREAD

**Issue by aurynn** [gophercloud/gophercloud#2340]
The OpenStack [API](https://docs.openstack.org/api-ref/database/?expanded=create-database-instance-detail) has support for both a volume Size and volume Type parameter, when declaring a new database instance.

The [current provider](https://github.com/gophercloud/gophercloud/blob/a1ac165819cd057e431dd1d37f05534ca355fdbe/openstack/db/v1/instances/requests.go#L72) only uses Size as an integer, and does not allow a volume Type field to be provided.

**Comment by aurynn** [comment]
Having looked into this some more, while the API does take the volume type as a value, it doesn't return it as part of the API responses, so there's not really a way to test whether or not the request will have succeeded as expected.

**Comment by mandre** [comment]
Hi @aurynn, if the create database API call doesn't return the volume type in its response, we can probably consider a successful response is OK to assert success, right? Would you be interested in producing a patch?

**Comment by aurynn** [comment]
Hi @mandre, I think that'd be a reasonable assumption. Changing the volume type would require rebuilding the database anyway, so I'd consider it to be a safe assumption.

Unfortunately I'm not very good with golang, so I'd need a lot of handholding and help to produce a patch.
