### ISSUE TITLE
Utils Repo

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#237]
With regard to the comment [here](https://github.com/gophercloud/gophercloud/pull/214#discussion_r96776107), I agree with @jrperritt that this function is better placed somewhere else, especially with regard to quotas. Quota management is a regular topic for OpenStack operators and this function could be mistaken for something officially in OpenStack. But I do think the function is clever. 

There have been other mentions of convenience functions, so I wanted to bring up the idea idea of some kind of utility repo. The repo would be separate from `gophercloud/gophercloud`, but still in a central location that's easily discoverable. 

The benefit would be that functions located in the repo could save someone from rewriting their own.

But there are downsides. Most notably, the value/use of a convenience function is highly subjective to the person who wrote it. It could be difficult to determine what makes sense for one person versus what's useful to many. The repo could easily devolve into a lot of bike shedding.

The OsOps group went through [something similar](https://wiki.openstack.org/wiki/Osops) to this. While one option is to point people to those repositories for contributing helpful code, the way Go packages work would probably not mesh well with the existing repositories. A new repository would have to be created under the OpenStack tent proper, but that comes with its own responsibilities.

In any case, I thought it couldn't hurt to open the discussion, regardless of the decision.

**Comment by jrperritt** [comment]
I'm open to suggestions for what would go in such a repo, and, if a consensus is reached that seems reasonable, we could create a new repo under the `gophercloud` Github organization for it. I probably don't have much input on ideas since I don't professionally administrate an OpenStack cluster.

> A new repository would have to be created under the OpenStack tent proper, but that comes with its own responsibilities.

Ah yes, the OpenStack tent. It was proposed a while back by someone involved in the OpenStack project to move Gophercloud (then under the `rackspace` Github organization) under the OpenStack tent. Fortunately, that didn't happen.

**Comment by jtopjian** [comment]
That sounds good. As a next step, when I get some time, I'll create a draft repo that contains some collected functions that have been suggested in the past.

**Comment by jtopjian** [comment]
Here's a quick draft that I put together:

https://github.com/jtopjian/gophertools

Most of the examples were pulled directly from Terraform. This is because they were easiest for me to find and they have proven useful in the field.

There are just a few examples, but each highlight a certain benefit:

* [`common.go`](https://github.com/jtopjian/gophertools/blob/master/common.go) is basically a slimmed down version of Terraform's StateChange system. This is to provide an easy way to monitor resource changes while not duplicating code within Terraform. [`RefreshServerStatus`](https://github.com/jtopjian/gophertools/blob/master/openstack/compute/v2/tools/servers.go) is a quick example of this. I can import this package into Terraform, cast it to a `StateRefreshFunc` and everyone benefits.
* [`DeleteMember`](https://github.com/jtopjian/gophertools/blob/master/openstack/networking/v2/extensions/lbaas_v2/tools/members.go) is a better example. This function includes a lot of contributed knowledge about how to handle LB member deletion.
* Functions such as [this](https://github.com/jtopjian/gophertools/blob/master/openstack/networking/v2/extensions/security/tools/rules.go) are just helpful and save everyone time.
* Functions such as [this](https://github.com/jtopjian/gophertools/blob/master/openstack/compute/v2/tools/quotasets.go) are a bit esoteric but still worthwhile to collect.

So this is kind of what I had in mind for a repo like this. The structure, naming conventions, etc aren't important at the moment -- more the general idea.

**Comment by jrperritt** [comment]
rendered: https://github.com/gophercloud/utils
