### ISSUE TITLE
Add os-volume_upload_image action to volumeactions 

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#238]
The Block Storage API has an undocumented extension/action called `os-volume_upload_image`. The implementation can be found here:

https://github.com/openstack/cinder/blob/a15459a27777e98599d70392191b0a6f0288ff34/cinder/api/contrib/volume_actions.py#L200-L271

#68 implements this. It's missing a few parameters (`visibility` and `protected`), but they have default values and can be added later. #68 also requires a rebase with master (notably, the `volumeactions` package has been moved).

I have a version rebased off of #218 that I can confirm works. I can open a PR with the required fixes while still retaining @sample's authorship once #218 is merged.

**Comment by jrperritt** [comment]
closed by #240
