### ISSUE TITLE
Failed bootfromvolume.Create calls still result in wasted volume creation

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#242]
A command like:

            server, err = bootfromvolume.Create(p.computeClient, keypairs.CreateOptsExt{
			CreateOptsBuilder: bootfromvolume.CreateOptsExt{
				CreateOptsBuilder: createOpts,
				BlockDevice: []bootfromvolume.BlockDevice{
					{
						UUID:                imageID,
						SourceType:          bootfromvolume.SourceImage,
						DeleteOnTermination: true,
						DestinationType:     bootfromvolume.DestinationVolume,
						VolumeSize:          diskGB,
					},
				},
			},
			KeyName: keyName,
		}).Extract()

that fails with an error like:

> Expected HTTP response code [200 202] when accessing [POST http://[xxx]:8774/v2.1/5377aa07ba904065b10bfceeda021fdc/os-volumes_boot], but got 403 instead
{"forbidden": {"message": "Maximum number of ports exceeded", "code": 403}}

Still results in a volume being queued for creation (and then immediate deletion), which can be very wasteful.

Firstly, is this a fixable bug in the way gophercloud is interacting with openstack, and secondly, is there an appropriate way for me to recognise all errors belonging to the class "you're not going to be able to create a server anymore due to lack of some quota, so stop trying until you terminate a server"?

**Comment by jtopjian** [comment]
> Firstly, is this a fixable bug in the way gophercloud is interacting with openstack,

Just to clarify things, how would you like to see Gophercloud handle this?

> secondly, is there an appropriate way for me to recognise all errors belonging to the class "you're not going to be able to create a server anymore due to lack of some quota, so stop trying until you terminate a server"?

It's been my experience that even the standard OpenStack command-line tools don't handle proactive quota checking very well. Maybe this has changed in the past six months or so, though. Off the top of my head, when a user submits a request to the Compute/Nova service, a request is turned into a "reservation" and then checked for adequate resources. It's at this point that an error would be returned if the user's quota is not sufficient enough. Problems probably arise when "cross-service" requests are made, for example: an instance that is creating a Block Storage boot device and using a Neutron-based network. I haven't dug into the code far enough to see if this is the case -- it's just an assumption on my part.

If your other questions around quotas are to do this type of proactive checking, I think that's a great idea and makes for a better end-user experience in the app you're building. :)

**Comment by sb10** [comment]
> Just to clarify things, how would you like to see Gophercloud handle this?

I don't know how things actually work under the hood on the OpenStack side of things, but I'd have hoped it would be possible to not send the request for the volume if we're not even allowed to create the server.

> If your other questions around quotas are to do this type of proactive checking, I think that's a great idea and makes for a better end-user experience in the app you're building.

Yes, this is what I'm trying to do :)

**Comment by jrperritt** [comment]
> is this a fixable bug in the way gophercloud is interacting with openstack

This should be handled in your app code.

>  is there an appropriate way for me to recognise all errors belonging to the class "you're not going to be able to create a server anymore due to lack of some quota, so stop trying until you terminate a server"

This is a question for OpenStack since it sends the errors. Based on the response you got, you'll want to check the error for a 403 response code and handle it appropriately.

**Comment by jtopjian** [comment]
> This should be handled in your app code.

Agreed.

I've often wondered why OpenStack isn't more efficient at cross-service collaboration, like in this case. Turns out it's a known "issue", but no set solution. There was some discussion on the openstack-dev list the other week about a "porcelain" API which would provide a more friendly interface. A few example implementations were noted on github, so check the mailing list archives if you're interested in this. But be aware that the noted examples were not complete or usable. More just sketching ideas.

In this specific instance, if a hypothetical porcelain api existed, you'd just end up calling some "create instance" action with a parameter to boot from volume and not have to worry about wasted calls and such.
