### ISSUE TITLE
How can I set a global request ID for clients?

### ISSUE THREAD

**Issue by tung491** [gophercloud/gophercloud#2428]
Hi! How can I set a global request ID for clients such as cinder, nova to whole flow have same request id

**Comment by kayrus** [comment]
You cannot set requestID, openstack services generate these requestIDs dynamically.

**Comment by tung491** [comment]
> You cannot set requestID, openstack services generate these requestIDs dynamically.

I already use the Python Openstack clients. They allows we set a fixed request id for whole flow. Under the hood, we only need to set the request header `X-OpenStack-Request-ID` to do it. Reference: https://specs.openstack.org/openstack/oslo-specs/specs/pike/global-req-id.html.

But in gophercloud, I don't know any way to do it

**Comment by pierreprinetti** [comment]
@tung491 Apologies for the late response.

`gophercloud.ServiceClient` has a field `MoreHeaders` that can be used to inject arbitrary headers.

Here's an example how it could be used right now, without waiting for any change in Gophercloud.
Here I inline the creation of a disposable `serviceClient` clone, so that I don't inadvertently set the same tracing header on every subsequent call:

```Go
package main

import (
	"fmt"
	"os"

	"github.com/gophercloud/gophercloud"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
	"github.com/gophercloud/utils/openstack/clientconfig"
)

// withTrace returns a copy of the ServiceClient, with an additional tracing
// header "X-OpenStack-Request-ID" bearing the traceID value.
func withTrace(client *gophercloud.ServiceClient, traceID string) *gophercloud.ServiceClient {
	clientCopy := *client

	moreHeadersCopy := make(map[string]string)
	for k, v := range client.MoreHeaders {
		moreHeadersCopy[k] = v
	}
	moreHeadersCopy["X-OpenStack-Request-ID"] = traceID

	clientCopy.MoreHeaders = moreHeadersCopy

	return &clientCopy
}

func main() {
	opts := &clientconfig.ClientOpts{
		Cloud: os.Getenv("OS_CLOUD"),
	}
	computeClient, err := clientconfig.NewServiceClient("compute", opts)
	if err != nil {
		panic(err)
	}

	{
		allPages, err := servers.List(withTrace(computeClient, "d77079f3-94af-4921-b18b-518ca6429e40"), nil).AllPages()
		if err != nil {
			panic(err)
		}
		allServers, err := servers.ExtractServers(allPages)
		if err != nil {
			panic(err)
		}
		for _, server := range allServers {
			fmt.Println(server.Name)
		}
	}

	computeClient.Microversion = "2.37"
	{
		createOpts := servers.CreateOpts{
			Name:      "server_name",
			ImageRef:  "11949c13-dd6b-4b95-8365-72f2985fbbd6",
			FlavorRef: "e21b78ed-2380-4505-ac6f-e94e729ed0b3",
			Networks:  "none",
		}
		server, err := servers.Create(withTrace(computeClient, "51e89f3a-372f-4b7d-823a-20e8d298a3ed"), createOpts).Extract()
		if err != nil {
			panic(err)
		}

		fmt.Printf("Created server %s\n", server.ID)
	}
}
```

Would that work for you?

To be honest, the ability to inject a header looks scary. However, if it's part of the OpenStack API, I see no reason not to add it to Gophercloud. It could be part of a `XxxWithContext` feature which I am personally looking forward to.

**Comment by tung491** [comment]
I already tried your solution. However, it's not work :( Our Openstack does not receive any request id that I specify in the `withTrace` function

**Comment by tung491** [comment]
I already tried and it's work
Thank for helping

**Comment by pierreprinetti** [comment]
I am closing this issue as it looks resolved. Please reopen or ping us if something more must be done.
