### ISSUE TITLE
[question] Is server stop api synchronous?

### ISSUE THREAD

**Issue by parkjeongryul** [gophercloud/gophercloud#2443]
Is server stop api synchronous?
Is it always guaranteed that the server stopped if we received 200 returns of the function?

```golang
if err := startstop.Stop(c.clientSet.computeV2, nodeID).ExtractErr(); err != nil {
		return err
	}
	return nil
```

**Comment by nikParasyr** [comment]
@parkjeongryul based on [docs](https://docs.openstack.org/api-ref/compute/?expanded=stop-server-os-stop-action-detail#stop-server-os-stop-action) its asynchronous. Also `202` which is the return code is typically used for asynchronous AFAIK.

**Comment by pierreprinetti** [comment]
Thanks @nikParasyr , that looks correct to me as well.
@parkjeongryul please reopen if there's something left to ask/add!
