### ISSUE TITLE
Update InstanceiUUID to InstanceUUID

### ISSUE THREAD

**Issue by Blueyin** [gophercloud/gophercloud#2457]
Path: https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/v3/attachments/doc.go
Line: 32
Change: InstanceiUUID is InstanceUUID

**Comment by pierreprinetti** [comment]
Thanks for reporting. Looks like it's just the docs: [the code itself looks fine](https://github.com/gophercloud/gophercloud/blob/d39505c79b112681a67b6adb7a63f8ebebd906f7/openstack/blockstorage/v3/attachments/requests.go#L24).
