### ISSUE TITLE
Add support for identity v3 OS-FEDERATION mappings extension

### ISSUE THREAD

**Issue by emilmaruszczak** [gophercloud/gophercloud#2461]
As part of the `OS-FEDERATION` keystone extension has added a `mappings` api.
Add support for it.

[docs](https://docs.openstack.org/api-ref/identity/v3-ext/index.html#os-federation-api)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/os_federation.py#L248)

- [x] List mappings
- [x] Create mapping
- [x] Get mapping
- [x] Update mapping
- [x] Delete mapping

**Comment by emilmaruszczak** [comment]
Answering the question asked in the opened MR #2468 : yes I do have all the operations implemented, just decided to push them one by one so they are not dependent on each other and it's easier for the merger to handle ;).

I will add acceptance tests soon as I figure them out.

**Comment by shaardie** [comment]
We are also interested in this feature and thought about implementing it our-self and bringing it upstream. And were happy to see, that there was already work done for that.

What is the current status of this? I see the List Mappings is already present. What about the other calls?

@emilmaruszczak Is it still your plan to create PR for them?

**Comment by emilmaruszczak** [comment]
@shaardie The logic and unit tests are implemented, I will PR them in shortly, after adding the acceptance tests.

**Comment by shaardie** [comment]
> @shaardie The logic and unit tests are implemented, I will PR them in shortly, after adding the acceptance tests.

Thanks, we are looking forward to it :+1:

**Comment by mandre** [comment]
@emilmaruszczak looks like you've implemented it all. Is there anything left, or can we close this issue now?

**Comment by emilmaruszczak** [comment]
> @emilmaruszczak looks like you've implemented it all. Is there anything left, or can we close this issue now?

Yes, all is implemented now. Thank you for reviews and your work.
