### ISSUE TITLE
Support for NoZ timestamps from network port requests in 1.0

### ISSUE THREAD

**Issue by andrewbaxter** [gophercloud/gophercloud#2469]
We're dealing with a provider using an old neuron release, and unfortunately the upgrade to 1.0 broke for us due to `updated_at` etc timestamp parsing errors.  If it's not too difficult, could workaround for both time formats be supported in the ports structure as it is for other networking responses?

**Comment by mandre** [comment]
Hi @andrewbaxter,  I called out this time format change in [the PR that added the CreatedAt and UpdatedAt fields to the port response](https://github.com/gophercloud/gophercloud/pull/2445), however I didn't realized older versions of OpenStack were still in use today. I've just pushed a fix for this. But please keep in mind however that versions prior to Train will always be best effort and could break anytime as you've experienced yourself.

**Comment by andrewbaxter** [comment]
Awesome, thank you! :bow: 

Yeah... I was hoping this level of compatibility wouldn't be a maintenance obstacle since there's other similar fixes, but I'm just going to cross my fingers really hard that our provider updates before we run into future compatibility issues.
