### ISSUE TITLE
Error ignored if connection fails when generating a v3 token

### ISSUE THREAD

**Issue by carolynvs** [gophercloud/gophercloud#247]
I am attempting to connect to an OpenStack instance which it turns out has an untrusted SSL certificate. Instead of seeing the correct error `x509: certificate signed by unknown authority`, the error was being ignored, and gophercloud was attempting to parse the empty response, resulting in a JSON parse error `parsing time "" as "2006-01-02T15:04:05.999999Z": cannot parse "" as "2006"`.

PR incomming.

**Comment by carolynvs** [comment]
Just realize that this is fixed on master (9152721b033df1efec3bd89195dc8ebe22a03fa6). I'll submit a PR to get it applied to the `magnum` branch as well.

**Comment by carolynvs** [comment]
@jrperritt Would you prefer that I bring in just the fix needed (correctly bubbling up the error), or should I rebase the `magnum` branch on top of `master`?

**Comment by jrperritt** [comment]
Just the fix is fine

**Comment by jrperritt** [comment]
closed by #253
