### ISSUE TITLE
Add support for availability zone in DBaaS 

### ISSUE THREAD

**Issue by pawcykca** [gophercloud/gophercloud#2483]
The OpenStack [API](https://docs.openstack.org/api-ref/database/?expanded=create-database-instance-detail,show-database-instance-details-detail#create-database-instance) has support for availability zone parameter, when declaring a new database instance.

Currently we can't provide this field while creating database instance.

**Comment by zhekazuev** [comment]
@pawcykca Hi,

Maybe you forget to close that issue.

**Comment by pawcykca** [comment]
Fixed by #2871
