### ISSUE TITLE
openstack flavor show [flavorID] properties

### ISSUE THREAD

**Issue by CloudCourierStation** [gophercloud/gophercloud#2497]
Hello, I use the command `openstack flavor show [flavorID]` ，flavor detail has the properties field，but I'm not found in the https://github.com/gophercloud/gophercloud/blob/0226ea5963656bcd435ab17af475e2345e523fcb/openstack/compute/v2/flavors/results.go#L51

**Comment by pierreprinetti** [comment]
Indeed, an `extra_specs` field could be added to the struct `flavors.Flavor`, with the mention of the proper microversion since which the field is supported.

Until that is implemented, you can extract to your own custom struct:

```Go
package main

import (
	"fmt"
	"os"

	"github.com/gophercloud/gophercloud/openstack/compute/v2/flavors"
	"github.com/gophercloud/utils/openstack/clientconfig"
)

func main() {
	opts := &clientconfig.ClientOpts{
		Cloud: os.Getenv("OS_CLOUD"),
	}
	computeClient, err := clientconfig.NewServiceClient("compute", opts)
	if err != nil {
		panic(err)
	}

	computeClient.Microversion = "2.61"

	var f Flavor
	{
		result := flavors.Get(computeClient, os.Args[1])
		var s struct {
			Flavor Flavor `json:"flavor"`
		}
		err = result.ExtractInto(&s)
		if err != nil {
			panic(err)
		}
		f = s.Flavor
	}

	fmt.Printf("%+v", f)
}

// Flavor represent (virtual) hardware configurations for server resources
// in a region.
type Flavor struct {
	// ID is the flavor's unique ID.
	ID string `json:"id"`

	// Disk is the amount of root disk, measured in GB.
	Disk int `json:"disk"`

	// RAM is the amount of memory, measured in MB.
	RAM int `json:"ram"`

	// Name is the name of the flavor.
	Name string `json:"name"`

	// RxTxFactor describes bandwidth alterations of the flavor.
	RxTxFactor float64 `json:"rxtx_factor"`

	// Swap is the amount of swap space, measured in MB.
	Swap int `json:"-"`

	// VCPUs indicates how many (virtual) CPUs are available for this flavor.
	VCPUs int `json:"vcpus"`

	// IsPublic indicates whether the flavor is public.
	IsPublic bool `json:"os-flavor-access:is_public"`

	// Ephemeral is the amount of ephemeral disk space, measured in GB.
	Ephemeral int `json:"OS-FLV-EXT-DATA:ephemeral"`

	// Description is a free form description of the flavor. Limited to
	// 65535 characters in length. Only printable characters are allowed.
	// New in version 2.55
	Description string `json:"description"`

	// Properties contains the extra_specs of the flavor
	// New in version x.xx
	Properties map[string]string `json:"extra_specs"`
}
```

**Comment by gxxxh** [comment]
Hi, I want to fix this issue. I wonder if anyone is doing this, if not, can I try to add this?

**Comment by CloudCourierStation** [comment]
@gxxxh  As @pierreprinetti  said, we can add to the struct via extra_specs field, so what are you trying to achieve, and I feel that this extension is flexible enough to use?

**Comment by pierreprinetti** [comment]
@gxxxh 

> I wonder if anyone is doing this, if not, can I try to add this?

Absolutely, that would be a welcome contribution.

**Comment by pierreprinetti** [comment]
@CloudCourierStation 
> this extension is flexible enough to use

True, but if it’s in the Nova api, there is no reason not to include it. Unless I’m missing something?

**Comment by gxxxh** [comment]
Hi, @pierreprinetti , I have commited my code and started a pull request. It's my first time to start a pr. Some of those ci failed and   the error message is can't clone nova, I don't know how to handle this problem. And if convenient, I also want to know how to add a label to the pull request, thank you!

**Comment by mandre** [comment]
Alternatively, you can also get the extra spec for a given flavor using the [flavors.ListExtraSpecs() method](https://github.com/gophercloud/gophercloud/blob/d777a1c/openstack/compute/v2/flavors/doc.go#L117-L126).
