### ISSUE TITLE
struct serverDiagnosticsResult is not exported

### ISSUE THREAD

**Issue by gxxxh** [gophercloud/gophercloud#2498]
I found the result struct here is not exported. Is it possiable to change the struct definition to ServerDiagnosticsResult like other results.
`
type ServerDiagnosticsResult struct {
	gophercloud.Result
}
`
https://github.com/gophercloud/gophercloud/blob/0226ea5963656bcd435ab17af475e2345e523fcb/openstack/compute/v2/extensions/diagnostics/results.go#L7-L9

**Comment by gxxxh** [comment]
Hi, here is another result definition which is not exported.
[https://github.com/gophercloud/gophercloud/blob/0226ea5963656bcd435ab17af475e2345e523fcb/openstack/blockstorage/v3/qos/results.go#L97-L99](url)

**Comment by pierreprinetti** [comment]
Hi @gxxxh, thanks for reporting that. I understand that corresponding result structs from other packages of Gophercloud are exported. However I would like to first understand what is your need first. What would you make of the exported result?

**Comment by gxxxh** [comment]
hi,@pierreprinetti. it's nothing.  I am a learner of golang and openstack. I was just curious why those struct were not exported and I want to know if it's proper for me to change those code to make they share the same coding style

**Comment by pierreprinetti** [comment]
Coding style per se wouldn't be a reason to change imho. Exported structs automatically become part of our compatibility promise, which means that a simple change to one of them means a major version bump for the whole library.

Unless there is a need, or a good reason, I'd tend to keep the API footprint as small as possible.

**Comment by gxxxh** [comment]
@pierreprinetti , ok, I get it. Thank you for the answer.
