### ISSUE TITLE
add a CLI

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#250]
I have been working on this for a while now trying to find a good balance between complexity and user experience. I expect to have a PR up in the next 10 days.

**Comment by dangogh** [comment]
I've been thinking about this, too..   can I help?

**Comment by jrperritt** [comment]
At this point it'd probably work best to wait for the PR and then we can decide what we like and don't like about the design and user experience. Much of the work was already done, as it's based on a CLI I'd worked on for Rackspace, but hopefully with improvements from lessons learned on that one. I'll ping you on the PR.

**Comment by dangogh** [comment]
fair enough..    thanks..

**Comment by dangogh** [comment]
any update?

**Comment by objque** [comment]
ping, any news?

**Comment by dangogh** [comment]
I have some code that implements a read-only CLI.  It takes a subcommand, e.g. `regions`, `security groups`, `servers`, etc and prints JSON.   It spans regions within the project/tenant concurrently.  Don'r want to step on toes,  but want to see something available in this area.  Should I submit a PR?

**Comment by jrperritt** [comment]
@dangogh Sorry for losing track of this.

> Should I submit a PR?

I don't think so. I did prototype this last year, and from what I remember, the gains didn't seem worth it. If you have something that works for you, I think that's great. An OpenStack CLI based on Gophercloud could easily live outside this repo; in fact, I created `gophercloud/cli` a while back, but may never populate it; the maintenance costs [currently] don't seem worth it.

**Comment by kayrus** [comment]
@jrperritt could you please push the code you already have?

**Comment by jrperritt** [comment]
I no longer have any code for this.

**Comment by jtopjian** [comment]
> I no longer have any code for this.

No worries. I'm going to go ahead and close this issue.
