### ISSUE TITLE
Add inspector timestamps for Nodes

### ISSUE THREAD

**Issue by BirknerAlex** [gophercloud/gophercloud#2525]
Currently the Ironic API exposes `inspection_started_at` and `inspection_finished_at` on node details which I need for my application but these values are not included in the `Node` struct.

MR is prepared to support this, the mockups already included the json fields but were not used yet.

**Comment by mandre** [comment]
Closing as a duplicate of #2544 (sorry, I realize your issue and patch came first, and the other one is technically the duplicate).
