### ISSUE TITLE
I am trying to list loadbalancer details. However I got error message that "interface conversion: pagination.Page is nil, not loadbalancers.LoadBalancerPage". Does anyone know cause of this error

### ISSUE THREAD

**Issue by aeromani91** [gophercloud/gophercloud#2527]
Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

**Comment by antonengelhardt** [comment]
Can you maybe post how you tried to list the loadbalancers? Looks like you need to fetch the pages first and then extract the loadbalancers...

**Comment by aeromani91** [comment]
pages, err := loadbalancers.List(networkclient, nil).AllPages()
alllb, err := loadbalancers.ExtractLoadBalancers(pages)
for _, lb := range alllb {
		fmt.Println(lb.Name)
	}

**Comment by antonengelhardt** [comment]
@aeromani91 I think i found your issue.

When calling the List function you are passing the network client and nil. You need to pass ListOpts instead of nil as the second argument. The ListOpts act like a filter. If you create a ListOpts with nothing "in it" it will return all loadbalancers.

Example:
```

listOpts := loadbalancers.ListOpts{
	Provider: "haproxy",
}

allPages, err := loadbalancers.List(networkClient, listOpts).AllPages()
if err != nil {
	panic(err)
}

allLoadbalancers, err := loadbalancers.ExtractLoadBalancers(allPages)
if err != nil {
	panic(err)
}

for _, lb := range allLoadbalancers {
	fmt.Printf("%+v\n", lb)
}

```
Link: https://pkg.go.dev/github.com/gophercloud/gophercloud@v1.1.1/openstack/loadbalancer/v2/loadbalancers#ListOpts

**Comment by pierreprinetti** [comment]
@aeromani91 

Your called your client `networkclient`, which looks suspicious! Have you created it with the correct provider name?

This works for me:

```Go
package main

import (
	"fmt"
	"os"

	"github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers"
	"github.com/gophercloud/utils/openstack/clientconfig"
)

func main() {
	opts := &clientconfig.ClientOpts{
		Cloud: os.Getenv("OS_CLOUD"),
	}
	lbclient, err := clientconfig.NewServiceClient("load-balancer", opts)
	if err != nil {
		panic(err)
	}

	pages, err := loadbalancers.List(lbclient, nil).AllPages()
	if err != nil {
		panic(err)
	}

	alllb, err := loadbalancers.ExtractLoadBalancers(pages)
	if err != nil {
		panic(err)
	}

	for _, lb := range alllb {
		fmt.Println(lb.Name)
	}
}
```
