### ISSUE TITLE
Containerinfra v1 ClusterTemplate missing field: hidden

### ISSUE THREAD

**Issue by bartekle** [gophercloud/gophercloud#2541]
ClusterTemplate also have `hidden` field (which we happen to use), but it is missing.

API Code:
https://opendev.org/openstack/magnum/src/commit/cd113dfc0c026b2a94e3e347f2ed4c114e5478d1/magnum/api/controllers/v1/cluster_template.py#L156

ClusterTemplate attributes in python-magnumclient:
https://github.com/openstack/python-magnumclient/blob/master/magnumclient/osc/v1/cluster_templates.py#L55

Also API Documentation:
https://docs.openstack.org/api-ref/container-infrastructure-management/#id84

**Comment by mandre** [comment]
Fixed with https://github.com/gophercloud/gophercloud/pull/2542. Thanks for the patch.
