### ISSUE TITLE
Where is the function of start or stop a server?

### ISSUE THREAD

**Issue by gxxxh** [gophercloud/gophercloud#2556]
I didn't find a start or stop function in [compute/v2/servers](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go) 
and from openstack api, there is rest api for those two operations.
[start server](https://docs.openstack.org/api-ref/compute/?expanded=update-server-detail,resize-server-resize-action-detail,start-server-os-start-action-detail#start-server-os-start-action)

**Comment by kayrus** [comment]
see https://pkg.go.dev/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/startstop
