### ISSUE TITLE
Remove deprecated services and extensions

### ISSUE THREAD

**Issue by mandre** [gophercloud/gophercloud#2577]
In preparation for a new major release, we should list the deprecated services that are no longer available in the minimum supported openstack version. While Train is already EOL upstream, it still serves as the base release for some of the popular distros and as a result a reasonable footprint. This is currently the minimum supported openstack version for gophercloud.

In the next major release, we'd like to remove these services and extensions:
- [x] blockstorage v1, deprecated in juno (https://github.com/gophercloud/gophercloud/pull/3008)
- [ ] ~blockstorage v2, deprecated in ocata~
- [x] cdn, unmaintained (https://github.com/gophercloud/gophercloud/pull/2809 and https://github.com/gophercloud/gophercloud/pull/3007)
- [ ] compute extension defsecrules, deprecated in newton
- [ ] compute extension floatingips, deprecated in newton
- [ ] compute extension networks, deprecated in newton
- [ ] compute extension tenantnetworks, deprecated in newton
- [ ] compute extension images, deprecated in ocata
- [ ] ~identity v2, deprecated in queens~ (we're told some people [still use it](https://github.com/gophercloud/gophercloud/issues/2651))
- [x] neutron extension fwaas v1, deprecated in newton (https://github.com/gophercloud/gophercloud/pull/3002)
- [x] neutron extensions lbaas and lbaasv2, deprecated in queens (https://github.com/gophercloud/gophercloud/pull/3003 and https://github.com/gophercloud/gophercloud/pull/3004)

**Comment by mandre** [comment]
See also @jtopjian's [comment](https://github.com/gophercloud/gophercloud/pull/2297#issuecomment-994965229) regarding removal of deprecated openstack services, for another perspective. In this case, I don't think that really matters as the plan is to keep supporting a v1 that includes all of these services.

**Comment by stephenfin** [comment]
I don't know if we should be removing block storage v2 either. There's a few users that I'm aware of. For example, I'm pretty sure Open Telekom Cloud uses the v2 API (or at least something that looks like the v2 API)

**Comment by mandre** [comment]
For later reference, there is a discussion about the compute extensions in https://github.com/gophercloud/gophercloud/pull/2945.
