### ISSUE TITLE
Incorrect Documentation on Provider Network Create

### ISSUE THREAD

**Issue by Radishaa** [gophercloud/gophercloud#2586]
[pull requests link](https://github.com/gophercloud/gophercloud/pull/2587)

`Example` are currently missing [Equal sign](https://pkg.go.dev/github.com/gophercloud/gophercloud@v1.2.0/openstack/networking/v2/extensions/provider) in the CreateOpts. 
```
	createOpts : provider.CreateOptsExt{
		CreateOptsBuilder: networkCreateOpts,
		Segments:          segments,
	}
```
Thank you for your attention to this matter.

**Comment by pierreprinetti** [comment]
Thanks!
