### ISSUE TITLE
ImageService v2: Unable to Read Properties

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#260]
The current `Image` struct looks for a JSON [`properties`](https://github.com/gophercloud/gophercloud/blob/ff77917b4d967827a1a375c97214f06b030e519a/openstack/imageservice/v2/images/results.go#L66) object, but one isn't actually returned by the server. Instead, properties are mixed in with all of the other top-level key/values.

I haven't dug into the Glance API / code enough to see what the best way of dealing with this is yet. I see the `python-glanceclient` making requests for a schema, so it's possible a schema is used as the basis of what is considered a "base" property and what is considered extra. 

The easier solution might be to just compare what else has been sent down by the server and if it's not defined in the `Image` struct, add it to the `Properties` map.

**Comment by jrperritt** [comment]
There is a Go feature (issue #15314) planned to be added soon (Go1.9early) that I think would solve this for us (a `[]string` would be returned in the `Unmarshal` `error` that would contain any unused fields). Until then, I think we should your easier solution.

**Comment by jrperritt** [comment]
@jtopjian I think `RemainingKeys` could be used for this, no?

**Comment by jtopjian** [comment]
Yep :)

**Comment by jtopjian** [comment]
Fixed by #376
