### ISSUE TITLE
Failing re-authentication

### ISSUE THREAD

**Issue by pierreprinetti** [gophercloud/gophercloud#2611]
I am running something very similar to this:

```Go
package main

import (
	"bytes"
	"os"
	"strconv"

	"github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects"
	"github.com/gophercloud/utils/openstack/clientconfig"
)

func main() {
	objectStorageClient, err := clientconfig.NewServiceClient("object-store", &clientconfig.ClientOpts{
		Cloud: os.Getenv("OS_CLOUD"),
	})
	if err != nil {
		panic(err)
	}

	for i := range [500000]struct{}{} {
		if _, err := objects.Create(objectStorageClient, "container-name", "obj_"+strconv.Itoa(i), objects.CreateOpts{
			Content: bytes.NewBuffer([]byte("file content")),
		}).Extract(); err != nil {
			panic(err)
		}
	}
}
```

Essentially: a very simple Gophercloud call in a loop that runs for ages.

**After exactly one hour, this program panics because it hits a 401.**

One hour being duration of my Keystone token, I suspect that Gophercloud does not refresh its token correctly.

**Comment by EmilienM** [comment]
I think the Keystone token is part of `objectStorageClient` so the client expires after some time (defined in `keystone.conf`)? or did I miss something?

**Comment by pierreprinetti** [comment]
I expect Gophercloud to automatically request a new Keystone token when the one at hand expires.

**Comment by pierreprinetti** [comment]
@jtopjian Am I doing something wrong in my code snippet? Or is it expected that the user re-authenticates manually?

**Comment by mandre** [comment]
Do you set [`allow_reauth`](https://github.com/gophercloud/utils/blob/09da01a284e350f39663928fb847514e364a6b8a/openstack/clientconfig/results.go#L133-L138)?

**Comment by pierreprinetti** [comment]
> Do you set [`allow_reauth`](https://github.com/gophercloud/utils/blob/09da01a284e350f39663928fb847514e364a6b8a/openstack/clientconfig/results.go#L133-L138)?

oh, that's interesting. This is certainly the answer to my problem, and probably the start to a great adventure
