### ISSUE TITLE
running travisci coverage script conceals unit test failures

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#263]
There are a few broken unit tests that went unnoticed because the coverage script runs the unit tests. It should fail if any unit test fails.

**Comment by jrperritt** [comment]
Bisected to these commits:
https://github.com/gophercloud/gophercloud/commit/368deee20062b2c7a043f792d7d998abe621872e
https://github.com/gophercloud/gophercloud/commit/6d2ec964420acd609b7ddc0ac69174ceebf4fe58

They look minor; I'll fix them.

/cc @jtopjian

**Comment by jtopjian** [comment]
Did those commits break unit tests outside of the respective packages? If I check out each commit, all tests under `testing/*` for the `secgroups` and `ports` packages pass.

**Comment by jtopjian** [comment]
Ah, I see. I took a look at a recent travis run. I'm sorry about that. :/

**Comment by jrperritt** [comment]
I don't think so. I haven't dived into it deeply (nor do I plan to). Travis reports the tests started failing at those commits:

https://travis-ci.org/gophercloud/gophercloud/jobs/202696803#L482
https://travis-ci.org/gophercloud/gophercloud/jobs/191446848#L404

But that's not really your fault; the coverage script needs a `set -e` line to fail on error. I'm taking care of it.

**Comment by jrperritt** [comment]
closed by #265
