### ISSUE TITLE
Issue Parsing Time

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#269]
A Terraform user reported that they started to get errors about parsing time beginning with Terraform v0.8.5. I confirmed that #190 was merged into Terraform's vendoring in time for 0.8.5.

The twist is that I'm unable to reproduce the problem. The user mentioned "binarylane", which is most likely [this](https://www.binarylane.com.au/) provider, so that makes this a little more difficult to test.

The issue details can be found here: https://github.com/hashicorp/terraform/issues/12126

The error log can be found here: https://gist.github.com/tjend/4f52f829da65bb84d2e8acad0bac3610

@jrperritt any idea off the top of your head?

If it helps, [this](https://github.com/hashicorp/terraform/pull/12089) will be available upon the next Terraform release, so a full log of the requests and responses should be available.

**Comment by jrperritt** [comment]
> any idea off the top of your head?

Possibly; the response would help. I just changed one of the `servers` unit tests to return `null` for the `updated` field and commented out the `Updated` field in the expected `Server` object, and it passed fine.

Note the error:
`parsing time "null" as ""2006-01-02T15:04:05Z07:00"": cannot parse "null" as """`

The time is double quoted; I suspect that's the problem, but it may be specific to that user or cloud provider.

**Comment by jtopjian** [comment]
> The time is double quoted

Ah, good catch. 

I've passed the info on. If I get some time, I might also create an account with BinaryLane and see if I can reproduce the issue.

**Comment by jtopjian** [comment]
The user has reported that this issue went away.
