### ISSUE TITLE
Add V2 Networks `router:external` Field

### ISSUE THREAD

**Issue by spjmurray** [gophercloud/gophercloud#2690]
Before starting a PR, please read our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Just so we can tell whether an external network is for a floating IP pool or not.  Useful as Cluster-API's CAPO component requires a floating-ip-network in order to provision correctly.

**Comment by spjmurray** [comment]
Actually on reflection, there does appear to be an extension in there, let me grok how the hell I'm supposed to use it...

**Comment by pierreprinetti** [comment]
Hi @spjmurray! Whatever you find in the docs, it would be really helpful if you could open a PR or even an issue about them, so that the next person finds them more useful

**Comment by spjmurray** [comment]
Closing because there is an extension
