### ISSUE TITLE
networks.Up missing

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#27]
I'm using gophercloud for the first time and note the recent transition from the rackspace repository to this one. Firstly, am I supposed to be using this version of the API?

I'm going through the various docs at http://gophercloud.io/docs/networking/ and the create code references networks.UP, which for some reason is no longer defined in the gophercloud/gophercloud version of https://github.com/rackspace/gophercloud/blob/master/openstack/networking/v2/networks/requests.go
It got removed in e3cb7e4 on Mar 7 https://github.com/gophercloud/gophercloud/blob/e3cb7e45cd599c4a14838e81ffa5175f203c2340/openstack/networking/v2/networks/requests.go
Why is it missing, and surely this would break people's code?

**Comment by jrperritt** [comment]
> Firstly, am I supposed to be using this version of the API?
They aren't different versions; they're different libraries altogether.

> I'm going through the various docs at http://gophercloud.io/docs/networking/
That site documents `rackspace/gophercloud`, not `gophercloud/gophercloud`.

> and the create code references networks.UP, which for some reason is no longer defined
That's purposeful. Use [`gophercloud.Enabled`](http://godoc.org/github.com/gophercloud/gophercloud#EnabledState).

**Comment by sb10** [comment]
Thanks, though may I suggest a clearer statement of this library's state and relationship to the rackspace one is put somewhere? Because my reading of https://github.com/rackspace/gophercloud/issues/592 ("the library will be migrated", "... it should be considered deprecated") made be believe it this was just the preferred newer version of the library, not a "different" one.
