### ISSUE TITLE
RouterID for floatingips

### ISSUE THREAD

**Issue by dbaumgarten** [gophercloud/gophercloud#273]
Hi,

the field router_id is missing in the ListOpts and the FloatingIP structs.

The documentation states it should be there and my test indicate the same.

I have the required commit ready (~4 lines), but did not yet create a PR, because I can't pass the acceptance tests because of #272 .

**Comment by jtopjian** [comment]
Just to add some info to this, I think [this](https://github.com/openstack/neutron-lib/blob/master/neutron_lib/api/definitions/l3.py) is where the floating IP fields are specified. The fields match up with the [API docs](https://developer.openstack.org/api-ref/networking/v2/index.html?expanded=list-floating-ips-detail).

**Comment by jrperritt** [comment]
closed by #283
