### ISSUE TITLE
gophercloud. ProviderClient globally.

### ISSUE THREAD

**Issue by ChinaGISboyYang** [gophercloud/gophercloud#2747]
Hello, I would like to ask if it is possible to store and use gophercloud. ProviderClient globally. I am now integrating gophercloud into a web project, and every API request requires AuthenticatedClient first. This is too responsible, and I hope to receive your reply. Thank you

**Comment by ChinaGISboyYang** [comment]
sorry，i find it how to use

**Comment by pierreprinetti** [comment]
`gophercloud.ProviderClient` should be safe for concurrent use. You should be able to instantiate a ProviderClient once, and use it throughout your application.

If anything goes wrong, please report it as a bug.

Is there anything else you need?

**Comment by ChinaGISboyYang** [comment]
>ok,nothing. thank u

**Comment by pierreprinetti** [comment]
I am closing this issue because I get the impression that it's resolved.

@ChinaGISboyYang please reopen if you still need support
