### ISSUE TITLE
Add support for NetworkType and SegmentationID to a network

### ISSUE THREAD

**Issue by chuliang** [gophercloud/gophercloud#2752]
Neutron v2 API [GET /v2.0/networks](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=list-networks-detail,create-network-detail#list-networks) [POST /v2.0/networks](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=list-networks-detail,create-network-detail#create-network) support provider network type and provider segment id:

provider:network_type (Optional) | body | string | The type of physical network that this network should be mapped to. For example, flat, vlan, vxlan, or gre. Valid values depend on a networking back-end.
-- | -- | -- | --

provider:segmentation_id (Optional) | body | integer | The ID of the isolated segment on the physical network. The network_type attribute defines the segmentation model. For example, if the network_type value is vlan, this ID is a vlan identifier. If the network_type value is gre, this ID is a gre key.
-- | -- | -- | --

But currently gophercloud does not support these attributes.
I think these attributes could be useful.

I'm working on it.

**Comment by kayrus** [comment]
@chuliang for creation you can use https://github.com/gophercloud/gophercloud/blob/8a293acd31e7fe249c2e79356c9efabf1cf42024/openstack/networking/v2/extensions/provider/requests.go#L10

It doesn't matter for neutron where exactly are you setting the `segment_id`, under the segments or not. It will automatically digest them.

**Comment by chuliang** [comment]
Outch, I didn't see the extension.
Thank you @kayrus
