### ISSUE TITLE
Wait for server UserData script to complete?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#284]
I am doing something like:

    createOpts := servers.CreateOpts{
		Name:           uniqueResourceName(resources.ResourceName),
		FlavorRef:      flavorID,
		ImageRef:       imageID,
		SecurityGroups: []string{p.securityGroup},
		Networks:       []servers.Network{{UUID: p.networkUUID}},
                UserData: userBashScript,
    }

    server, err = servers.Create(p.computeClient, keypairs.CreateOptsExt{
			CreateOptsBuilder: createOpts,
			KeyName:           resources.ResourceName,
    }).Extract()

    // ...
    current, err := servers.Get(p.computeClient, server.ID).Extract()
    // wait for current.Status == "ACTIVE"

This works as expected if userBashScript takes ~trivial time to run, but if it takes a long time, then I end up with a server I can ssh to, but where the things I expected to be installed on it via userBashScript have not been installed, for example.

Is there any way to wait until after userBashScript completes? Note that userBashScript is user input in my app, so I don't know what its contents are.

**Comment by jtopjian** [comment]
The User Data script runs asynchronously and, AFAIK, there is not a Compute API notification for when it completes. This might be more specific to `cloud-init`.

**Comment by jrperritt** [comment]
> Is there any way to wait until after userBashScript completes?

I think not. In addition to what @jtopjian said, there is no guarantee the script will complete (e.g. it could have an infinite loop acting as a listener).

**Comment by sb10** [comment]
Ok, thanks. I have a work-around for my particular use-case.
