### ISSUE TITLE
Identity v3: Users CRUD

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#287]
* [x] list / get (#288)
* [x] create (#392)
* [x] delete (#393)
* [x] update (#394)

General API reference: https://developer.openstack.org/api-ref/identity/v3/index.html#users

API processing: 
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L193
* https://github.com/openstack/keystone/blob/master/keystone/identity/backends/sql.py

Schema:
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/schema.py#L65-L74
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/backends/sql_model.py#L28

Options:
* https://github.com/openstack/keystone/blob/master/keystone/identity/backends/resource_options.py
* https://github.com/openstack/keystone/blob/4c83fb0f13d0a09db7a4ca66c3b0dc2745c34c5f/releasenotes/notes/bp-per-user-auth-plugin-reqs-feb95fd907be4b40.yaml
* https://github.com/openstack/keystone/blob/1ec73f3b97337bc3d98f34734abded8639fcffc9/releasenotes/notes/bug-1659995-f3e716de743b7291.yaml

List:
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L227

Get:
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L242

Create:
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L214
* https://github.com/openstack/keystone/blob/master/keystone/identity/backends/sql.py#L127
* https://github.com/openstack/keystone/blob/master/keystone/identity/schema.py#L80

Delete:
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L275
https://github.com/openstack/keystone/blob/master/keystone/identity/backends/sql.py#L330

Update:
* https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L254
* https://github.com/openstack/keystone/blob/master/keystone/identity/backends/sql.py#L204
* https://github.com/openstack/keystone/blob/master/keystone/identity/schema.py#L90

**Comment by heartlock** [comment]
+1 for this issue

**Comment by jrperritt** [comment]
@jtopjian great job on this

**Comment by jtopjian** [comment]
Thanks! Thank you for your help throughout - extra fields and all.
