### ISSUE TITLE
Network v2: FWaaS v1 Router Updates

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#291]
As a continuation of #220, @fatmcgav is trying to add this support to Terraform and we noticed two missing features:

1. The POST and PUT can accept an empty array for `router_ids`. This is to explicitly tell Neutron to not put the firewall on any routers:

```
curl -g -i -X POST http://10.1.12.81:9696/v2.0/fw/firewalls.json 
  -H "User-Agent: python-neutronclient" 
  -H "Content-Type: application/json" 
  -H "Accept: application/json" 
  -H "X-Auth-Token: {SHA1}a37ac68381b796bb766449a57f06964e051fdbd8" 
  
  -d '{"firewall": {"router_ids": [], "admin_state_up": true, "firewall_policy_id": "ab1c75bb-5731-4683-94d7-b68ee031637e", "name": "foo"}}'
```

2. The GET results of a firewall (or firewalls) now contains a `router_ids` attribute: https://github.com/openstack/neutron-fwaas/blob/d2938b247104ac6d7c945167b246cfcfed8393e8/neutron_fwaas/extensions/firewallrouterinsertion.py#L28

**Comment by jrperritt** [comment]
closed by #292
