### ISSUE TITLE
Contribute minor code fixes

### ISSUE THREAD

**Issue by yj-yoo** [gophercloud/gophercloud#2920]
I'm studying to contribute to gophercloud, and I've found a few small and trivial issues. I'd like to contribute to fixing the code.

1. There are deprecated functions in the current golang version.
ex) rand.Read() function

2. Code that requires small and trivial code style and optimization
ex) if opts.Detailed == true {} -> if opts.Detailed {}

Can I give it a try?

**Comment by pierreprinetti** [comment]
I think you did :)

**Comment by yj-yoo** [comment]
@pierreprinetti 

Thanks :)
However, some small issues are still found. I want to continue contributing.

Are there any rules for keeping this project's code clean? I've read the style guide, but it doesn't provide enough information.
ex) When the return value is not specified in the function declaration, but 'return' is used within the function.

**Comment by pierreprinetti** [comment]
I think that readability takes precedence over strict linting, and strict linting sometimes hinders readability. If you believe that a given line would be more readable when written differently, feel free to open a PR and we can discuss it.
