### ISSUE TITLE
v2: Get by name or ID

### ISSUE THREAD

**Issue by vooon** [gophercloud/gophercloud#2959]
Pretty often i need similar to python library calls where you get resource by name or ID.
So i think it will be nice to upstream my utility helpers.

Unsure how good it fits gophercloud API though...

A code like that:
```
func (m *OpenstackManager) GetServer(ctx context.Context, nameOrID string) (*servers.Server, error) {
	ctx, span := tracer.Start(ctx, "ostack/GetServer", trace.WithSpanKind(trace.SpanKindClient))
	defer span.End()

	_, err := uuid.Parse(nameOrID)
	if err == nil {
		srv, err := servers.Get(ctx, m.computeCli, nameOrID).Extract()
		if err != nil {
			span.RecordError(err)
			return nil, err
		}
		return srv, nil
	}

	page, err := servers.List(m.computeCli, servers.ListOpts{Name: nameOrID}).AllPages(ctx)
	if err != nil {
		span.RecordError(err)
		return nil, err
	}

	srvs, err := servers.ExtractServers(page)
	if err != nil {
		span.RecordError(err)
		return nil, err
	}

	if len(srvs) == 0 {
		err = fmt.Errorf("No servers with name: %s", nameOrID)
		span.RecordError(err)
		return nil, err
	}

	return &srvs[0], nil
}
```

(well, i'm not proud of that UUID usage, but that good-enough ad-hoc solution...)

**Comment by pierreprinetti** [comment]
we have that sort of functionality in utils at the moment: https://github.com/gophercloud/utils/blob/master/openstack/compute/v2/servers/utils.go

I would not be opposed to having some clever generic replacement for that in the main library.

**Comment by pierreprinetti** [comment]
I would be opposed to adding to Gophercloud a function that accepts a string that can equally be uuid or name. I’d let that guesswork to the caller application

**Comment by vooon** [comment]
@pierreprinetti and that guesswork already handled by my apps. Unfortunately i cannot expose my proprietary common code, but that's a pain, when i work with a things i'm allowed to opensource...

**Comment by pierreprinetti** [comment]
On the other hand, goohercloud/utils was created specifically to host this kind of code 😁

**Comment by vooon** [comment]
Well, i actually tried to drop dependencies on utils... :)

But can you please suggest me a name for that kind of functions?
Behaves like `Get`, but it's more than that. `GetBy` looks too short and non intuitive, but `GetByNameOrID` feels to long and verbose.

**Comment by pierreprinetti** [comment]
I understand that accepting both name or ID comes handy in the CLI and I would consider adding features that facilitate that use-case, but adding this kind of ambivalent functions across all packages is a no-go to me, because strong typing is a selling point of Gophercloud (and Go code in general).

**Comment by pierreprinetti** [comment]
I am tentatively closing this issue, because I don't see a path forward to this proposal as-is. Please feel free to reopen this or another issue to propose another solution for this problem.
