### ISSUE TITLE
Provider methods return `context canceled` error when using `ProviderClient.Context`

### ISSUE THREAD

**Issue by MichaelEischer** [gophercloud/gophercloud#2969]
Gophercloud 1.10 introduced context aware functions.

For requests sent by `ProviderClient.doRequest` the `ProviderClient.Context` field and the passed in `ctx` are merged:

https://github.com/gophercloud/gophercloud/blob/5b44c45ec947301d531178302c4cecc0a923ad96/provider_client.go#L401-L405

However, that merged context is also canceled using defer. This prevents reading from the `Body` of the returned `http.Response`. Thus when using `ProviderClient.Context`, every method that needs the request result currently fails with a context canceled error.

**Comment by pierreprinetti** [comment]
Thank you, that looks pretty serious. I'm having a look right now.

**Comment by pierreprinetti** [comment]
For lack of a better solution, in the attached PR I propose removing Context from v1.

If anyone has a better idea, please come forward.

**Comment by pierreprinetti** [comment]
Note that v1.9 is also affected.

**Comment by pierreprinetti** [comment]
Fixed in https://github.com/gophercloud/gophercloud/pull/2971. Any feedback is very welcome.
