### ISSUE TITLE
OS_PROJECT_NAME and OS_PROJECT_ID environment variables are not taken into account

### ISSUE THREAD

**Issue by pospispa** [gophercloud/gophercloud#297]
OpenStack v3 authentication replaced `OS_TENANT_NAME` and `OS_TENANT_ID` environment variables with the `OS_PROJECT_NAME` and `OS_PROJECT_ID` environment variables.

However, `gophercloud` does not take into account the `OS_PROJECT_NAME` and `OS_PROJECT_ID` environment variables.

There is a [wiki page](https://wiki.openstack.org/wiki/OpenStackClient/Authentication) that mentions the change from `OS_TENANT_NAME` and `OS_TENANT_ID` to `OS_PROJECT_NAME` and `OS_PROJECT_ID`.

IMO, the `OS_PROJECT_NAME` and `OS_PROJECT_ID` environment variables should be taken into account.

**Comment by pospispa** [comment]
This is duplicate of https://github.com/gophercloud/gophercloud/issues/461

**Comment by jtopjian** [comment]
@pospispa oops - I didn't notice this one. I would have used it instead of #461
