### ISSUE TITLE
Netowrk v2: multiple provider extention

### ISSUE THREAD

**Issue by takaishi** [gophercloud/gophercloud#301]
We can't create multiple provider network now.
So, add attribute "segments" to bind multiple physical network for logical network.

### api docuemnt

"segments" is array of segment object, segment has provider:network_type and provider:physical_network, provider:segmentation_id.

- https://developer.openstack.org/api-ref/networking/v2/?expanded=create-network-detail,update-segment-detail#create-network

### neutron source code
- https://github.com/openstack/neutron/blob/stable/mitaka/neutron/extensions/multiprovidernet.py#L24
- https://github.com/openstack/neutron/blob/stable/mitaka/neutron/extensions/providernet.py#L22

**Comment by jtopjian** [comment]
Resolved by #302
