### ISSUE TITLE
Block Storage (Cinder) V3 API support

### ISSUE THREAD

**Issue by xsgordon** [gophercloud/gophercloud#305]
Gophercloud currently supports the Block Storage (Cinder) V1 and V2 APIs. Both are now deprecated [1] in favor of the V3 API. Theoretically the initial V3 API is the same as V2, with additions/changes built on top of it via microversions.

It would be ideal if support for at least the initial V3 API could be added to Gophercloud as this will future proof it for if (when) the V2 API is removed in future.

[1] https://developer.openstack.org/api-ref/block-storage/

**Comment by jrperritt** [comment]
PR welcome. Please read the [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md) first.

**Comment by pospispa** [comment]
Does the PR https://github.com/gophercloud/gophercloud/pull/415 resolve this issue?
I believe the issue https://github.com/gophercloud/gophercloud/issues/412 is at least related.

**Comment by jtopjian** [comment]
Yes, #415 will resolve both this issue and #412

**Comment by jtopjian** [comment]
Gophercloud now has Block Storage v3, so I think this issue is resolved. If there are questions or comments on the implementation, I'd be happy to discuss / reopen.
