### ISSUE TITLE
Filter servers by metadata

### ISSUE THREAD

**Issue by teemukataja** [gophercloud/gophercloud#3071]
Hi,

Consider adding support to filtering `servers` with metadata, similarly to how it is already done in `volumes`.

- Metadata field missing from [servers.ListOpts](https://github.com/gophercloud/gophercloud/blob/v1.11.0/openstack/compute/v2/servers/requests.go#L18-L89)
- [servers.MetadataOpts](https://github.com/gophercloud/gophercloud/blob/v1.12.0/openstack/compute/v2/servers/requests.go#L574-L575) exists, but it can't be used to query and filter servers
- Example in [volumes.ListOpts](https://github.com/gophercloud/gophercloud/blob/v1.11.0/openstack/blockstorage/v1/volumes/requests.go#L77-L78)

Example in OpenStack Compute API [GET /servers](https://docs.openstack.org/api-ref/compute/#list-servers)
| Name | In | Type | Description |
|---|---|---|---|
|key_name (Optional)|query|string|Filter the server list result by keypair name. This parameter is restricted to administrators until microversion 2.83. If non-admin users specify this parameter on a microversion less than 2.83, it will be ignored.|

**Comment by pierreprinetti** [comment]
Hi @teemukataja :wave: 
I don't see `metadata` documented as a field [in the List call](https://docs.openstack.org/api-ref/compute/#list-servers). Can you point me to code or documentation that indicates that Nova lets you filter servers by metadata?

**Comment by teemukataja** [comment]
Sorry, it appears I was confused at the time, and metadata filtering for instances indeed does not exist in the Compute API. I was hoping it would have been possible to do the same with instances as it is possible with volumes.
