### ISSUE TITLE
MIGRATING.md should mention removed functionality

### ISSUE THREAD

**Issue by pierreprinetti** [gophercloud/gophercloud#3083]
* Removed `openstack/compute/v2/extensions/tenantnetworks` without replacement
* Removed `openstack/blockstorage/v1/*` without replacement
* Removed `openstack/compute/v2/extensions/floatingips` with suggestion to use `openstack/networking/v2/extensions/layer3/floatingips`

**Comment by stephenfin** [comment]
The removal of Cinder v1 support is called out [here](https://github.com/gophercloud/gophercloud/blob/master/docs/MIGRATING.md#removed-services-and-extensions). The rest do need to be addressed though, yes.
