### ISSUE TITLE
ObjectStorage v1: accounts.GetResult should parse quota

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#312]
The `X-Account-Meta-Quota-Bytes` header is recognized [here](https://github.com/openstack/swift/blob/2aa5811c7fdf86df302f5ce8b0413bf51e86e7ab/swift/common/middleware/account_quotas.py#L84-L85) for PUT requests and then stored with a Swift account just like any `X-Account-Meta-` type header.

This issue is specifically about the GET request, where the header is returned and should be parsed in the same way that e.g. the [`X-Account-Bytes-Used` header is already handled](https://github.com/gophercloud/gophercloud/blob/9a5595b8ffe429439c63781cdc312c254e4ad990/openstack/objectstorage/v1/accounts/results.go#L79) by GetResult's UnmarshalJSON.

**Comment by jtopjian** [comment]
Implemented in #313 and #1031
