### ISSUE TITLE
Shared file systems: Share Actions

### ISSUE THREAD

**Issue by pospispa** [gophercloud/gophercloud#315]
This issue is raised to track the development of the [shares](http://developer.openstack.org/api-ref/shared-file-systems/?expanded=#shares) - actions in the shared file systems api v2

- [x] Grant access
- [x] Revoke acess
- [x] List access rules
- [ ] Reset share state
- [ ] Force-delete share
- [ ] Extend share
- [ ] Shrink share
- [ ] Unmanage share
- [ ] Revert share to snapshot

**Comment by kayrus** [comment]
Extend and Shrink were implemented in #1175
