### ISSUE TITLE
Add reservation in scheduler hints

### ISSUE THREAD

**Issue by msimonin** [gophercloud/gophercloud#317]
Some OpenStack installation[[1](https://www.chameleoncloud.org/)] use a lease system.  Leases are usually
provided by blazar[[2](https://wiki.openstack.org/wiki/Blazar)] and each lease is composed of a list of
reservations. When creating servers, one must pass a valid reservation
id in order to indicate to the system which reservation will be used by
the future resource.

From the user perspective options could look like the following :
```
createOpts = servers.CreateOpts{
// regular opts
}
schedulerHints := schedulerhints.SchedulerHints{
    Reservation: "18c864af-ce7a-414e-8168-b586f11decf0",
  }
createOpts = &schedulerhints.CreateOptsExt{
    CreateOptsBuilder: createOpts,
    SchedulerHints: schedulerHints,
  }

server, err := servers.Create(client, createOpts).Extract()
```

**Comment by jtopjian** [comment]
Fixed by #316
