### ISSUE TITLE
PR #236 has broken port update.

### ISSUE THREAD

**Issue by fatmcgav** [gophercloud/gophercloud#318]
PR #236 appears to have broken Port updates for me. 

I'm seeing requests failing with the following error:
>2017/04/11 10:49:08 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 10:49:08 [DEBUG] OpenStack Request Options: {
2017/04/11 10:49:08 [DEBUG] plugin: terraform:   "port": {
2017/04/11 10:49:08 [DEBUG] plugin: terraform:     "allowed_address_pairs": null,
2017/04/11 10:49:08 [DEBUG] plugin: terraform:     "security_groups": [
2017/04/11 10:49:08 [DEBUG] plugin: terraform:       "115ebfa2-d112-42b6-8880-b57fe22b09bc"
2017/04/11 10:49:08 [DEBUG] plugin: terraform:     ]
2017/04/11 10:49:08 [DEBUG] plugin: terraform:   }
2017/04/11 10:49:08 [DEBUG] plugin: terraform: }
2017/04/11 10:49:09 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 10:49:09 [DEBUG] OpenStack Response Body: {
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "ErrorCode": "500",
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "ErrorMessage": "An internal server error occurred at your requested service. You should try to send the request again.detail: An error of service. (REQ_006945487)",
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "MessageID": "E500",
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "ServerID": "uk-1a_197"
2017/04/11 10:49:09 [DEBUG] plugin: terraform: }

Patching Gophercloud to remove the `allowed_address_pairs: null` line enables the request to work. 

Specifically, the removal of `omitempty` here:
https://github.com/gophercloud/gophercloud/pull/236/files#diff-207a560786d6d77722bc0cdcb81469daL123

**Comment by fatmcgav** [comment]
@jtopjian One for you to take a look at?

**Comment by fatmcgav** [comment]
Related to #226

**Comment by fatmcgav** [comment]
Actually, I believe this is probably a TF issue, rather than a Gophercloud issue. 
Raised against TF in https://github.com/hashicorp/terraform/issues/13531

@jtopjian Do you concur?

**Comment by jtopjian** [comment]
@fatmcgav Correct. This is not a Gophercloud issue.

**Comment by fatmcgav** [comment]
Okay, closing in favour of fixing in TF.
