### ISSUE TITLE
Get/set instance ssh host key?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#319]
Now that golang.org/x/crypto/ssh.ClientConfig requires a HostKeyCallback, I realise I haven't been doing any host key checking when ssh'ing to the instances I create via Gophercloud. Is there any way I can find out what the public key of those instances are? Or generate host keys myself and inject them when I create the instances?

`nova console-log [instance name]` shows the host key since it gets printed to the console during boot up. Is that, or could that, be captured and provided by gophercloud?

https://www.ibm.com/developerworks/cloud/library/cl-openstack-pythonapis/ (search for "ssh host key") shows an example of parsing this output. Is there at least a gophercloud method of getting the raw console output?

**Comment by jtopjian** [comment]
The ability to show the console output has been merged in #329 and #1032. The ability to parse the SSH key is out of scope of Gophercloud. An example function to do this can be seen in #329, however it was removed in #1032.
