### ISSUE TITLE
listing region availability zones?

### ISSUE THREAD

**Issue by zetaab** [gophercloud/gophercloud#320]
Is there method for listing availability zones? https://developer.openstack.org/api-ref/compute/?expanded=get-availability-zone-information-detail#get-availability-zone-information

if no, could it be implemented?

**Comment by dixudx** [comment]
@zetaab It has already been implemented. Please refer to [availabilityzones/requests.go](https://github.com/gophercloud/gophercloud/blob/master/openstack/sharedfilesystems/v2/availabilityzones/requests.go#L9).

**Comment by dixudx** [comment]
It is missing in [gophercloud godoc](https://godoc.org/github.com/gophercloud/gophercloud). Will add it later.

**Comment by dixudx** [comment]
@zetaab  [availabilityzones/requests.go](https://github.com/gophercloud/gophercloud/blob/master/openstack/sharedfilesystems/v2/availabilityzones/requests.go#L9) is shared file system availabilityzones, not compute availabilityzones.

I'll submit a new PR on this new feature. Sorry for misleading you.

**Comment by yongfengdu** [comment]
Should this issue being closed since this is tracked in #327?

**Comment by jtopjian** [comment]
@yongfengdu No, this needs to stay open for two reasons:

1. All Gophercloud Pull Requests must have a corresponding issue.
2. #327 seems to have gone stale. Likely someone else could/should follow-up with a new PR.

**Comment by dstdfx** [comment]
@jtopjian I'd like to finish this

**Comment by jtopjian** [comment]
@dstdfx Sure, go for it :)

**Comment by jtopjian** [comment]
Implemented in #704 

@dstdfx Thank you again for your work on this.
