### ISSUE TITLE
[manila] add scheduler_hints field to manila shares

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#3204]
https://docs.openstack.org/api-ref/shared-file-system/#create-share

Scheduler hints allow to create shares with affinity and anti-affinity rules, e.g.:

```json
{
    "share": {
...
        "scheduler_hints": {
            "same_host": "d9c66489-cf02-4156-b0f2-527f3211b243,4ffee55f-ba98-42d2-a8ce-e7cecb169182",
            "different_host": "903685eb-f242-4105-903d-4bef2db94be4"
        }
    }
}
```

**Comment by kayrus** [comment]
@stephenfin I'm not sure whether changing the signature of the `Create` function to have additional scheduler hints as an argument was a good idea in #3022. Now if we want to add scheduler hints to the share creation, we need to change the `Create` func signature, which means that such changes can be shipped only within a major release.

cc @pierreprinetti @EmilienM @mandre

**Comment by stephenfin** [comment]
> @stephenfin I'm not sure whether changing the signature of the `Create` function to have additional scheduler hints as an argument was a good idea in #3022. Now if we want to add scheduler hints to the share creation, we need to change the `Create` func signature, which means that such changes can be shipped only within a major release.
> 
> cc @pierreprinetti @EmilienM @mandre

No, no need to do that here. Manila sensibly placed the `scheduler_hints` field inside the `share` envelope, so you it belongs in `CreateOpts` like everything else.

**Comment by kayrus** [comment]
@stephenfin I'm looking into the v3/volumes, and the scheduler hints are passed as a func argument: https://github.com/gophercloud/gophercloud/blob/b9ceec888b3340a666a0c05bb9fe6462178ffd84/openstack/blockstorage/v3/volumes/requests.go#L146

However the shares/volumes API are more or less the same.
