### ISSUE TITLE
Should clientconfig be used?

### ISSUE THREAD

**Issue by cacack** [gophercloud/gophercloud#3216]
The docs on pkg.go.dev reference the use of clientconfig as the preferred way to perform auth (https://pkg.go.dev/github.com/gophercloud/gophercloud/v2?utm_source=godoc#hdr-Authenticating_with_Providers):

> It is now recommended to use the `clientconfig` package found at https://github.com/gophercloud/utils/tree/master/openstack/clientconfig for all authentication purposes.
>
> The below documentation is still relevant. clientconfig simply implements the below and presents it in an easier and more flexible way.

But the README in the repo doesn't reference that.  Additionally, the repo provides a different pattern for auth compare the the "manual" way presented in pkg.go.dev.

Should clientconfig still be used?  What is the recommended auth way?

**Comment by pierreprinetti** [comment]
Thank you for pointing out the inconsistency; I am going to update [the docs](https://github.com/gophercloud/gophercloud/blob/master/doc.go) immediately.

The recommended way to set up Gophercloud is documented [in the README](https://github.com/gophercloud/gophercloud#gophercloud-authentication).
