### ISSUE TITLE
application credentials cannot create without any roles assigned

### ISSUE THREAD

**Issue by zhangmeng011** [gophercloud/gophercloud#3224]
```
curl -g -H "X-Auth-Token: $TOKEN" -H "Content-Type: application/json" -X POST "$OS_AUTH_URL/users/<userID>/application_credentials" -d '{"application_credential": {"name": "curl-test", "roles":[]}}'

$ openstack application credential show <app_cred ID>
+--------------+------------------------------------------------------------------+
| Field        | Value                                                            |
+--------------+------------------------------------------------------------------+
| description  | None                                                             |
| expires_at   | None                                                             |
| id           | xxxx                                 |
| name         | curl-test                                                        |
| project_id   | None                                                             |
| roles        |                                                                  |
| system       | None                                                             |
| unrestricted | None                                                             |
| user_id      | xxxx |
+--------------+------------------------------------------------------------------+
```

I call [Identity API v3](https://docs.openstack.org/api-ref/identity/v3) to create application credentials, if the request body parameters roles set empty array, the roles will be limit with no roles assign. But with code, it’s not as expected:

According to https://github.com/gophercloud/gophercloud :

https://github.com/gophercloud/gophercloud/blob/22fe3c16350594fc77515cf040aefe75f8295075/openstack/identity/v3/applicationcredentials/requests.go#L98

https://github.com/gophercloud/gophercloud/blob/22fe3c16350594fc77515cf040aefe75f8295075/openstack/identity/v3/applicationcredentials/requests.go#L82

https://github.com/gophercloud/gophercloud/blob/22fe3c16350594fc77515cf040aefe75f8295075/params.go#L123-L138

We can see if the request body parameters are empty array, it will not go into the loop to build the request body.

**Comment by kayrus** [comment]
@zhangmeng011 thanks for the issue.

According to the Keystone API ref, roles are:

> An optional list of role objects, identified by ID or name. The list may only contain roles that the user has assigned on the project. If not provided, the roles assigned to the application credential will be the same as the roles in the current token.

Creating an application credential without a role doesn't make any sense. Authenticating with such application credential won't give you any permissions, even though the auth process against keystone can be successful, the token won't be able to do anything, since it doesn't have any role. Rescope the token also not possible, since this procedure is restricted even for the unrestricted app cred.

To conclude, an app cred without any role is a bug in keystone, and such app cred cannot be used anywhere.

**Comment by zhangmeng011** [comment]
Ok. I got your point. 
I want to create an app cred for container registry. But the viewer_registry roles seems to be exceeded since we don't expect the app cred to pull image registry from all counts but only specific account. We expect to control the permission by account access policy.

Do you know which roles will be appropriate for such scenario while create an app cred.

**Comment by zhangmeng011** [comment]
> @zhangmeng011 thanks for the issue.
> 
> According to the Keystone API ref, roles are:
> 
> > An optional list of role objects, identified by ID or name. The list may only contain roles that the user has assigned on the project. If not provided, the roles assigned to the application credential will be the same as the roles in the current token.
> 
> Creating an application credential without a role doesn't make any sense. Authenticating with such application credential won't give you any permissions, even though the auth process against keystone can be successful, the token won't be able to do anything, since it doesn't have any role. Rescope the token also not possible, since this procedure is restricted even for the unrestricted app cred.
> 
> To conclude, an app cred without any role is a bug in keystone, and such app cred cannot be used anywhere.
Ok. I got your point.
I want to create an app cred for container registry. But the viewer_registry roles seems to be exceeded since we don't expect the app cred to pull image registry from all counts but only specific account. We expect to control the permission by account access policy.

Do you know which roles will be appropriate for such scenario while create an app cred.
