### ISSUE TITLE
availability zones url in shared file system has changed

### ISSUE THREAD

**Issue by dixudx** [gophercloud/gophercloud#325]
The url in [openstack/sharedfilesystems/v2/availabilityzones/urls.go](https://github.com/gophercloud/gophercloud/blob/master/openstack/sharedfilesystems/v2/availabilityzones/urls.go#L5-L7) was indeed renamed.

Detailed code implementation can be found [manila/api/v2/router.py#L71-L84](https://github.com/openstack/manila/blob/master/manila/api/v2/router.py#L71-L84)

Reference: [shared-file-systems list-availability-zones](https://developer.openstack.org/api-ref/shared-file-systems/index.html?expanded=list-security-services-detail,list-all-major-versions-detail,show-details-of-specific-api-version-detail#list-availability-zones)

**Comment by dixudx** [comment]
Already fixed in #324

**Comment by jtopjian** [comment]
Per discussion, the URL will stay the same until support for microversion discovery is added.
