### ISSUE TITLE
volumeactions.ConnectorOpts not defined

### ISSUE THREAD

**Issue by akailash** [gophercloud/gophercloud#326]
I am trying to use 
import "github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions"
instead of 
import "github.com/rackspace/gophercloud/openstack/blockstorage/v2/extensions/volumeactions" in an existing repository(cinder-docker-driver). Please correct me if I am using the wrong import or if there is some other substitute available in the gophercloud/gophercloud repo for the ConnectorOpts

**Comment by jtopjian** [comment]
Doing a cursory review, it looks like `ConnectorOpts` might have been renamed to [`InitializeConnectionOpts`](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/volumeactions/requests.go#L116).

**Comment by jtopjian** [comment]
@akailash I'm going to close this issue, but please let me know if `InitializeConnectionOpts` is not what you were looking for.

**Comment by akailash** [comment]
Thanks @jtopjian I think it will work... I am replacing it with `volumeactions.InitializeConnectionOpts` or `volumeactions.TerminateConnectionOpts` as suitable. 
For me still some concerns left with this package: 
1. `volumeactions.InitializeConnectionOpts.Multipath` is no longer a boolean but a pointer to a boolean... not sure that is by design...
2. `volumeactions.Detach` has an extra parameter `volumeactions.DetachOptsBuilder` which I am confused with

**Comment by jtopjian** [comment]
> volumeactions.InitializeConnectionOpts.Multipath is no longer a boolean but a pointer to a boolean... not sure that is by design...

It is, yes. Most fields/parameters that take a true/false value will now be `*bool` because `bool` implies a default value of `false`. Sometimes not specifying a value at all is, in itself, a valid option. So in order to support true/false/nil, we use `*bool`. 

> volumeactions.Detach has an extra parameter volumeactions.DetachOptsBuilder which I am confused with

You'll want to pass a [`DetachOpts`](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/volumeactions/requests.go#L68-L70) type to `volumeactions.Detach`

**Comment by akailash** [comment]
Hi @jtopjian, I am still battling with my volume driver to get it working with this package. My cinder volume is of type "Ceph". Does that mean I cannot get iscsi target for it? Because when I try to call `volumeactions.InitializeConnection` to get `Target Portal` and `Target IQN`, I dont get these parameters in the response. This is the response I do get:

> May 12 00:42:33 swarm1-0 cinder-docker-driver[18267]: time="2017-05-12T00:42:33Z" level=debug msg="Response from InitializeConnection: {commonResult:{Result:{Body:map[connection_info:map[driver_volume_type:rbd data:map[qos_specs:<nil> volume_id:3496d6c2-b074-435c-baac-89d0dccb39eb discard:true auth_username:cinder secret_type:ceph encrypted:false auth_enabled:true hosts:[192.168.102.51 192.168.102.52 192.168.102.53] access_mode:rw ports:[6789 6789 6789] name:openstack-volume/volume-3496d6c2-b074-435c-baac-89d0dccb39eb secret_uuid:f59d1fd6-7f50-4cf9-9ac5-91c007fd1daf]]] Header:map[] Err:<nil>}}}\n"
I would really appreciate any inputs regarding this...

**Comment by jtopjian** [comment]
> My cinder volume is of type "Ceph". Does that mean I cannot get iscsi target for it?

That's possible, but I can't say for sure. I don't have any experience with Ceph. My understanding is that all communication with Ceph volumes happen over rbd, but I could be very wrong about that. 

I can confidently say that the `InitializeConnection` and `DetachOpts` work with a volume backend that supports iSCSI as I've implemented it [here](https://www.terraform.io/docs/providers/openstack/r/blockstorage_volume_attach_v2.html).

**Comment by akailash** [comment]
I managed to get rexray up on my swarm with my cinder volume. They added support for cinder few days back. It does look like the problem was iscsi not being supported in my volume backend. Thanks for the support!
