### ISSUE TITLE
[ANN] New repo maintainer: Joe Topjian

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#328]
I'm pleased to announce @jtopjian as a new maintainer for this repository. I no longer have the time necessary to devote to maintaining the library, so he will be assuming my responsibilities including reviewing PRs, addressing issues, and future development. I will remain involved in the repo, but starting today Joe should be considered the primary maintainer. I will be tying up some loose ends in the next few weeks in regards to service extensions and some other unresolved design decisions. Please support Joe in his new role and be patient as we transition responsibilities.

**Comment by mvalkon** [comment]
@jrperritt thanks for your efforts :+1:

**Comment by jtopjian** [comment]
Although I enjoy seeing my name posted, I think all the relevant people have seen this announcement, so I'm going to close this one :)
