### ISSUE TITLE
Keystoneless Client

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#34]
If it's not already possible, what's the general outline for making a client that bypasses Keystone? In particular, this would be for Swift clients that authenticate directly with Swift. It would resemble this: 

https://github.com/ncw/swift/blob/master/auth.go#L85-L94

Is this something that would make sense to have in Gophercloud or is there a requirement to have all clients go through Keystone?

**Comment by jrperritt** [comment]
`gophercloud.ProviderClient`'s `Request` method in pretty generic. It'll make any request based on the URL and headers you give it. Would this be something that calls `ProviderClient.Request` with pre-populated fields?

Can you provide a code example (Go or pseudo) of what you have in mind and how you'd use it? (I looked at the link, but still don't know in what context it'd be used).

**Comment by jtopjian** [comment]
> Would this be something that calls ProviderClient.Request with pre-populated fields?

After writing the below out, I came to the realization of "yes" :smile: 

The specific goal that I'm trying to accomplish is using Gophercloud in Swift environments that use Swift's native (non-Keystone) authentication, which is done by passing the headers found in the `ncw/swift` link above.

I _think_ this is along the right lines(?):

```golang
providerClient, _ := openstack.NewClient("http://example.com:8080/v1")
swiftClient, _ := openstack.NewObjectStorageV1(providerClient, gophercloud.EndpointOpts{})
```

And at this point, I should have a basic `gophercloud.ServiceClient` that never hit Keystone... but I still need to add those headers, which I think I can do [here](https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L84), but I'm not sure how to do that. I think I'd have to write my own `openstack.NewClient` in order to create the `ProviderClient` the way I want. 

Or would I create a new type of ProviderClient that has its own [AuthenticatedHeaders](https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L76) function that sets the `ApiKey` and `UserName`?

**Comment by jtopjian** [comment]
Oh, also: so it looks like this can be done because how flexible you've implemented all of the pieces (along the lines of the Debug question I had the other week, which the link you gave me might also be the example implementation I'm looking for... will look into that now).

Let's say I roll this into something like `openstack.NewSwiftAuthClient()`, would that be something you'd be interested in merging or would that stay as an app-specific implementation?

**Comment by jrperritt** [comment]
Let me think about this a bit. While you could modify the `*http.Request` with a custom `RoundTripper`, you're not really supposed to. One option would be to provide a way for users to provide their own headers, though I'm not sure what that would look like; the `MoreHeaders` field was created to be used by the `gophercloud` packages.

If this is only for Swift, then because it already uses headers to pass user options, I think this could be accomplished with slightly modified `*OptsBuilder` methods:

```go
type CreateOptsExt struct {
    containers.CreateOptsBuilder
    UserName string
    AuthKey string
}

func (opts CreateOptsExt) ToContainerCreateMap() (map[string]string, error) {
    h, err := opts.CreateOptsBuilder.ToContainerCreateMap()
    if err != nil {
        return nil, err
    }
    h["X-Auth-Key"] = opts.authKey
    h["X-Auth-User"] = opts.userName
    return h, nil
}
```

> Let's say I roll this into something like openstack.NewSwiftAuthClient(), would that be something you'd be interested in merging or would that stay as an app-specific implementation?

Any idea how popular that auth method is? As evidenced by the way `gophercloud` is built, we had no idea authenticating was possible without going through Keystone.

**Comment by jrperritt** [comment]
> I think this could be accomplished with slightly modified *OptsBuilder methods

Of course, you'd still need a custom `*ServiceClient` as you originally mentioned.

> Any idea how popular that auth method is?

In addition, do you know of any documentation for this? For example, is it an extension to Swift?

**Comment by jtopjian** [comment]
> If this is only for Swift

Yes, at the moment, Swift is the only service I have in mind for this.

> I think this could be accomplished with slightly modified *OptsBuilder methods:

That looks simple enough and I can give that a shot in a test environment.

> Any idea how popular that auth method is?

I've never worked directly with this type of Swift environment, but I know deployments exist. I've heard about them being used in digital archival environments and such. 

https://github.com/hashicorp/terraform/pull/8016 has all the details about why I'm now investigating this.

> In addition, do you know of any documentation for this? For example, is it an extension to Swift?

I know of two ways to use Swift without Keystone:

* [TempAuth](http://docs.openstack.org/developer/swift/overview_auth.html) (and [here](https://github.com/openstack/swift/blob/f2e344a4d98606385f34d3633a90c24aa32fc43d/swift/common/middleware/tempauth.py))
* [Swauth](https://swauth.readthedocs.io/en/latest/) (and [here](https://github.com/openstack/swauth/blob/d4d52ad8fefbb9c9347c490e0662639a0baaa583/swauth/middleware.py))

The second links for each auth system have references to the `x-auth-key` header.

TempAuth is core to Swift. I believe Swauth is just an enhanced version of TempAuth.

**Comment by jrperritt** [comment]
One option would be to add a `MoreHeaders` field to [`ServiceClient`](https://github.com/gophercloud/gophercloud/blob/master/service_client.go#L11). Then add a `Request` method on `*ServiceClient` that adds the headers to `*RequestOpts`, then calls `*ProviderClient.Request` with the new `*RequestOpts`.

**Comment by jrperritt** [comment]
@jtopjian Can you create a branch that does that ^ and see if it satisfies this issue? It should only be a dozen or so lines of code.

**Comment by jtopjian** [comment]
Yup - making my way to it, probably sometime this weekend :)

**Comment by jrperritt** [comment]
No rush. After rereading my comment from 4 days ago, I don't think it reads as decisive, so just remedying that.

**Comment by jtopjian** [comment]
Wow. I got this to work.

Thanks for the clear direction on `MoreHeaders` - I was able to get that done in 10 minutes: https://github.com/jtopjian/gophercloud/commit/41c79109ed5b7795465b9596a8cd3c3dc439e728

But then I realized I was interpreting Swauth incorrectly: only an initial request is sent using the user/key. That initial request returns a token and then that token is used in the headers for subsequent requests - kind of like a very basic Keystone process.

I was able to sketch this out and it works: https://github.com/jtopjian/gophercloud/commit/cd23453be9984c10012f481a75aa401cc495b1b5

Example: https://gist.github.com/jtopjian/fe27fde637053344a06021b8eba59292

It definitely needs some cleanup - thoughts on how to proceed?

**Comment by jrperritt** [comment]
Can we set this up like the other `ServiceClient`s? For example, would something like this work (thereby not necessitating the creation of `ServiceClient.MoreHeaders`: 

```go
package swauth

func NewObjectStorageV1(pc *gophercloud.ProviderClient, opts AuthOpts) (*gophercloud.ServiceClient, error) {
  auth, err := Authenticate(pc, authOpts).Extract()
  if err != nil {
    return nil, err
  }

  swiftClient := &gophercloud.ServiceClient{
    ProviderClient: pc,
    Endpoint:       auth.StorageURL,
  }

 swiftClient.TokenID = auth.Token

return swiftClient, nil
}
```

**Comment by jtopjian** [comment]
Sounds like a great idea.

I'll start working on this. I'll also need to start pulling request and response bodies for the `swauth` package tests.

I'll make a PR specifically for the `MoreHeaders` functionality.

**Comment by jtopjian** [comment]
Oh, sorry - just realized this does _not_ need `MoreHeaders`.

**Comment by jtopjian** [comment]
With #65 merged and with Swauth / Tempauth being the only two alternative authentication methods in OpenStack that I'm aware of, I'm going to close this issue. Thank you!
