### ISSUE TITLE
Shared file systems: Get Microversion

### ISSUE THREAD

**Issue by pospispa** [gophercloud/gophercloud#340]
Shared file systems v2 API uses microversions. Some services like [share instance export locations](https://developer.openstack.org/api-ref/shared-file-systems/?expanded=id234-detail#share-instance-export-locations-since-api-v2-9) are supported from a specific microversion.

That's why getting the shared file systems API microversion is necessary.

Related issue: [fix microversion header](https://github.com/gophercloud/gophercloud/issues/53).

**Comment by jtopjian** [comment]
@pospispa @jrperritt Unless I am totally misunderstanding how this all works, isn't this an appropriate solution?

https://github.com/jtopjian/gophercloud/commit/5bf58ab1beb18b3220bd0b63f74104a56e1f273e
https://github.com/jtopjian/gophercloud/commit/7f48e23cca311be0fb1796e61bbded54cfefb7d6

Note that the above was done in a rush and might be sloppy, but if it looks like a good foundation, I can submit a proper PR.

One piece of missing functionality that I see in the above is for the user to be able to specify a microversion (or to opt out at all).

**Comment by pospispa** [comment]
@jtopjian your implementation is really a good foundation.
I've tried it out [here](https://github.com/pospispa/gophercloud/commit/73d2fbf333e31055439b18cacf4c5330af99a6e9) and I haven't found any problems in it.

I will add a few comments directly to your code.

**Comment by pospispa** [comment]
This issue is fixed by https://github.com/gophercloud/gophercloud/pull/409
