### ISSUE TITLE
Keystone v3 is deprecating region in favor or region_id

### ISSUE THREAD

**Issue by arnaudmorin** [gophercloud/gophercloud#343]
Since keystone 3.2, as seen in keystone documentation (look for requests/response example):
https://developer.openstack.org/api-ref/identity/v3/

the field region is deprecated in favor of region_id.
Gophercloud is still using region.

Some Public Cloud keystone deployment (OVH) already dropped this parameter and only give region_id, and as a result is gophercloud keystonev3 is broken.

We should at least patch this file: 
https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/tokens/results.go#L15
and replace region by region_id.

Best is to handle both cases.

What cores dev think about that?

**Comment by dims** [comment]
Hey @lbragstad, what do you think of this?

**Comment by lbragstad** [comment]
The version should be discoverable using `GET /v3` [0]. That should help determine which representation of region to use. Are you seeing specific issues or confusing using ``region`` or ``region_id`` with the endpoints resource?

[0] https://github.com/openstack/keystone/blob/017b3477fdc3922f7a0ea0db420f3ed1df55b386/keystone/version/controllers.py#L144

**Comment by jrperritt** [comment]
closed by #783
