### ISSUE TITLE
SharedFilesystems v2: Change Specs to ExtraSpecs

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#345]
@ehdou I just came across this while doing a review of the last sfs PR:

https://github.com/gophercloud/gophercloud/blob/master/openstack/sharedfilesystems/v2/sharetypes/requests.go#L116

I think `Specs` should be changed to `ExtraSpecs` here for consistency. Let me know if you'd like to clean that up or I can do it. :)

**Comment by ehdou** [comment]
Hmm, that makes sense.
I have changed company some time ago and I don't really have a devstack setup anymore so it would be easier for me if you would take care of it :)
Let me know if I can assist you somehow.

**Comment by jtopjian** [comment]
@bugosiphionah How about this one? It should be an easy one to get started with.

**Comment by bugosiphionah** [comment]
@jtopjian  Sounds good. Working on this. I will set up and share a PR .

**Comment by jtopjian** [comment]
Fixed by #517
