### ISSUE TITLE
Block Storage (Cinder) Snapshot Support

### ISSUE THREAD

**Issue by rootfs** [gophercloud/gophercloud#349]
There is no Cinder Snapshot API support yet. Snapshot API will be needed in Kubernetes volume snapshot feature.

@jrperritt

**Comment by j-griffith** [comment]
I'll have a look at V3 shortly, no changes required for the Snapshot (V3.0 is actually V2), but it would be nice to get support for the new Attachment API sooner rather than later I think.

**Comment by jtopjian** [comment]
Implemented by #354
