### ISSUE TITLE
Incorrect Attachment Attributes in Block Storage V2 Volumes

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#35]
The [attachment struct](https://github.com/gophercloud/gophercloud/blob/c8834c1c34519f58fbb80453cb3c33c31956bbed/openstack/blockstorage/v2/volumes/results.go) for v2 volumes is incorrect. I think they were based off of the definition [here](https://github.com/openstack/cinder/blob/504b466295f3d97307216095f450ff8421796319/cinder/objects/volume_attachment.py) when they should have been based off of [here](https://github.com/openstack/cinder/blob/ed7a35de8299c9b948d25195764423f11f5cf00e/cinder/api/v2/views/volumes.py) (which I've confirmed is correct with `cinder --debug show <uuid>`).

Side note, perhaps for posterity, the [API sample](https://github.com/openstack/cinder/blob/1de24a08fddcae717d2152a17690523a7e14e7f4/api-ref/v2/source/samples/volumes-list-detailed-response.json) is incomplete as it's missing the `attached_at` attribute.

**Comment by jrperritt** [comment]
Great, thanks for reporting it. I think that's my fault.

**Comment by jrperritt** [comment]
closed by #36

**Comment by jtopjian** [comment]
Thank you!
