### ISSUE TITLE
Identity v3: Add Extract{User,Role,Project} to token

### ISSUE THREAD

**Issue by kwapik** [gophercloud/gophercloud#360]
There should be a way to extract following attributes from token:
- Roles - https://github.com/openstack/keystone/blob/32577e08b61b31cda045513f06535b474a54d2a2/keystone/models/token_model.py#L242
- Project - https://github.com/openstack/keystone/blob/32577e08b61b31cda045513f06535b474a54d2a2/keystone/models/token_model.py#L140
- User - https://github.com/openstack/keystone/blob/32577e08b61b31cda045513f06535b474a54d2a2/keystone/models/token_model.py#L89

**Comment by jrperritt** [comment]
closed by #361
