### ISSUE TITLE
BootFromVolume extension should support `disk_bus` and `device_type` fields

### ISSUE THREAD

**Issue by fatmcgav** [gophercloud/gophercloud#378]
As per the Openstack docs for [block_device_mapping](https://docs.openstack.org/developer/nova/block_device_mapping.html), it's possible to specify a `disk_bus` and `device_type` fields.

> disk_bus and device_type - low level details that some hypervisors (currently only libvirt) may support. Some example disk_bus values can be: _ide_, _usb_, _virtio_, _scsi_, while device_type may be _disk_, _cdrom_, _floppy_, _lun_. This is not an exhaustive list as it depends on the virtualization driver, and may change as more support is added. Leaving these empty is the most common thing to do.

Required for https://github.com/terraform-providers/terraform-provider-openstack/issues/18

**Comment by jtopjian** [comment]
Additional work required: Locate where `disk_bus` and `device_type` are defined in `block_device_mapping` v2.

Bonus: add these attributes to an existing (or new) [acceptance test](https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/compute/v2/bootfromvolume_test.go) and verify it works.

**Comment by yongfengdu** [comment]
I'll look into this issue

**Comment by yongfengdu** [comment]
@jtopjian , my-HenryS and I are in one team, and I asked my-HenryS to provide this patch.
Thanks for your review.

**Comment by jtopjian** [comment]
@yongfengdu That's perfect - thanks :smile:

**Comment by jtopjian** [comment]
Implemented in #1129
