### ISSUE TITLE
Identity v3: List user's groups

### ISSUE THREAD

**Issue by kars7e** [gophercloud/gophercloud#382]
It would be great to have support for retrieving groups a user belongs to. I could provide a PR for that, I'm just wondering whether it would be better to add this as a part of "users" package (something like users.ListGroups(userId) ), or better create new package "groups", that could deal with managing groups in general, and have a method like groups.ListByUser(userId).

**Comment by jtopjian** [comment]
I think the best way to determine would be to look at the URL used when making that API call. Is it hitting `/users` or `/groups`?

I did a quick look at the Keystone controller code, and confusingly [`list_groups_for_user`](https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L335) is defined in the Group controller and [`list_users_in_group`](https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/controllers.py#L236) is under the User controller. I would have imagined that being reversed.

**Comment by jrperritt** [comment]
For this issue, `users.ListGroups`.

`groups.ListUsers` would be the complementary function.

**Comment by jtopjian** [comment]
Sounds right:

https://github.com/openstack/keystone/blob/a3aee6ccb52d85eac1deedec31724a955d47fa96/keystone/identity/routers.py#L77-L84

**Comment by mfranc213** [comment]
I've written groups.ListUsers.  Will try to create a PR for this soon.

**Comment by kars7e** [comment]
I've added users.ListGroups in #386, please take a look. Thanks!

**Comment by jrperritt** [comment]
closed by #386
