### ISSUE TITLE
Identity v3: List the users in a group

### ISSUE THREAD

**Issue by mfranc213** [gophercloud/gophercloud#385]
This feature would list the users in a group.  I will try to push a PR for this soon.  

This functionality will complement the "list the groups for a user" functionality described in https://github.com/gophercloud/gophercloud/issues/382

**Comment by jtopjian** [comment]
@mfranc213 Are you still interested in implementing this? No problem at all if you don't have the time.

**Comment by dklyle** [comment]
I'm working on this, and I should have a pull request up in the next day or two.

**Comment by dklyle** [comment]
@jtopjian I believe this can be closed.

**Comment by jtopjian** [comment]
Yep, it sure can. Thanks, @dklyle.
