### ISSUE TITLE
investigate refactor of apiversions API

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#387]

**Comment by jtopjian** [comment]
At first glance, I thought a `common/apiversions` package could be made to parse _all_ OpenStack services' versions. Then I ran into one inconsistency and thought "well, maybe we can work around that". But then another, and another. So each service is going to need their own `apiversions` package, each slightly different than the other.

**Comment by jrperritt** [comment]
OK, thanks for looking into it; it was a good thought. It sounds like we can close this.
