### ISSUE TITLE
Bug: token validate does not work with AllowReauth = true

### ISSUE THREAD

**Issue by asmund-hvalman** [gophercloud/gophercloud#388]
I see problems with this line of code
https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/tokens/requests.go#L185

HTTP 401 is included in "ok codes". That means, that Request method would never enter this branch https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L188 and would never trigger reauth https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L211

**Comment by jtopjian** [comment]
Considering `401` is "Unauthorized" and especially given the context of a Token, I'm inclined to say you're correct here.

**Comment by jrperritt** [comment]
@asmund-hvalman thanks for catching this.

closed by #389
