### ISSUE TITLE
Identity v2: Enhance tenants

### ISSUE THREAD

**Issue by mozhuli** [gophercloud/gophercloud#395]
The tenants of identity v2 only has the List method, it is necessary to support Create, Update, Delete, Get methods for some users want to do use identity v2. I will try to push a PR for this soon.

**Comment by jtopjian** [comment]
@mozhuli First, thank you for submitting this. 

Please check out the [STYLEGUIDE](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md) on how to submit changes like this. In particular, there needs to be one PR per "route". So you'll need to break #396 up into separate PRs: one for Create, one for Update, etc.

You'll also want to collect links from the actual Keystone code that validate correct fields.

Check out https://github.com/gophercloud/gophercloud/issues/287 as a template/example and let me know if you have any questions. :)
