### ISSUE TITLE
How do you use keypairs?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#41]
I can create and get a keypair using github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs create() and get(), but how do I associate that keypair with a server? As far as I can see, github.com/gophercloud/gophercloud/openstack/compute/v2/servers CreateOpts does not have any keypair-related field.

**Comment by jtopjian** [comment]
There's a simple example of creating a server with a keypair in the acceptance tests:

https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/compute/v2/compute.go#L339-L354

Hope that helps!
