### ISSUE TITLE
No support for new V3.27 Cinder Attachment API

### ISSUE THREAD

**Issue by j-griffith** [gophercloud/gophercloud#414]
With V3.27 Cinder introduced a standalone Attachment API, this API allows attachments to be created/updated/deleted etc in lieu of Nova and are now treated as independent resources in Cinder.  

We should add V3 support and implement micro versions for Cinder (Issue #413) then add the attachment API impl.

**Comment by j-griffith** [comment]
I've started work on this but not sure how to assign myself here.

**Comment by jtopjian** [comment]
There you go :)

**Comment by kayrus** [comment]
https://docs.openstack.org/api-ref/block-storage/v3/index.html#attachments

[Router definition](https://github.com/openstack/cinder/blob/eb915e2dbbaf0a6382b6936b7e8c2f65b12753df/cinder/api/v3/router.py#L180..L184)

* [Create](https://github.com/openstack/cinder/blob/eb915e2dbbaf0a6382b6936b7e8c2f65b12753df/cinder/api/v3/attachments.py#L105)
* [List](https://github.com/openstack/cinder/blob/eb915e2dbbaf0a6382b6936b7e8c2f65b12753df/cinder/api/v3/attachments.py#L76)
* [Update](https://github.com/openstack/cinder/blob/eb915e2dbbaf0a6382b6936b7e8c2f65b12753df/cinder/api/v3/attachments.py#L203)
* [Delete](https://github.com/openstack/cinder/blob/eb915e2dbbaf0a6382b6936b7e8c2f65b12753df/cinder/api/v3/attachments.py#L259)
* [Complete](https://github.com/openstack/cinder/blob/eb915e2dbbaf0a6382b6936b7e8c2f65b12753df/cinder/api/v3/attachments.py#L276)
