### ISSUE TITLE
Compute v2: Make Rescue an Extension

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#425]
rescue is currently defined under the [`servers`](https://github.com/gophercloud/gophercloud/blob/177ebbf9d6d507338a9e9d7edeabd0cd26b9f9a9/openstack/compute/v2/servers/requests.go#L515-L546) package, but this should be moved to a dedicated extension since the `rescue` action is an extension:

https://github.com/openstack/nova/blob/stable/ocata/nova/api/openstack/compute/rescue.py

**Comment by jtopjian** [comment]
I just noticed that Nova is in the process of removing the concept of "extensions". You can see the difference between the original link I gave vs what is in the master branch:

https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/rescue.py

The file layout looks to be the same, though. `rescue.py` is not being merged into `servers.py`.

I think it still makes sense to break rescue out of the `servers` package. If all possible actions to a server were housed under the `servers` package, it would become quite unwieldy. 

I propose moving all packages currently under `extensions` to the `compute/v2` directory. I thought about suggesting the creation of an `actions` or `serveractions` directory, but given some packages  in `extensions` are not actions (ex: keypairs, servergroups, etc), it would make organizing various compute features difficult and bike-sheddy.

@jrperritt thoughts?

**Comment by jrperritt** [comment]
> thoughts?

I'd like to hear more about it. Can you elaborate on the desire to refactor this? Is it just to stay in sync with the OpenStack repo's structure? Are there any other services (or, in general, code) in Gophercloud that require a change like this? The reason I ask is because we'll have to weigh the benefit of that against the weight of this change breaking all the code using any of those extensions (if those users update their Gophercloud code to a commit with this change, of course).

**Comment by jtopjian** [comment]
The Gerrit topic for this change is here: https://review.openstack.org/#/c/453571/

It looks like the move is 90% complete. I did a search through Nova and found a few extensions that haven't been changed yet ([ex](https://github.com/openstack/nova/blob/5a39fe58ffbd3dab78543052c972989cc645262b/nova/api/openstack/compute/flavor_rxtx.py).

> Is it just to stay in sync with the OpenStack repo's structure?

It's mostly that. 

I also believe the results of the extensions API will be modified, too, though I'm not sure in what capacity. On a recent devstack build, `nova list-extensions` is still printing all of the current extensions. And even if the list of extensions retrieved from the extensions API is modified, that will not functionally change the placement of those packages in Gophercloud.

> Are there any other services (or, in general, code) in Gophercloud that require a change like this?

I think that's very dependent on the service. I haven't heard of another service doing this, though I only do a daily scan of the -dev list and might have missed something.

I don't believe this is an urgent move at all, possibly not required at all. None of the current Gophercloud compute extensions will be affected by these service-level changes -- the routes, request bodies, etc have not been changed.

Additionally, housing things as `extensions` could simply be the way these non "core" actions/features remain structured in Gophercloud. Networking does something similar - there's no `lbaas` or `lbaas_v2` extension defined in Neutron, but it's how it's organized in Gophercloud.

Perhaps the best action is to wait until the dust settles and see if there's an API-level change that prompts a reorganization?

**Comment by ozerovandrei** [comment]
Logic for the Compute Rescue was moved to the separate `rescueunrescue` package in #1168
