### ISSUE TITLE
Can't Get correct port by ip for server

### ISSUE THREAD

**Issue by FengyunPan** [gophercloud/gophercloud#431]
Currently there are same ips in different network, so user could get incorrect port by ip.
The openstack cloud provider of kubernetes have this issue:
https://github.com/kubernetes/kubernetes/issues/43909

The code comes from getPortByIP()
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L101

Actraully we can use 'nova interface-list' to get port for instance. 
So it is necessary to support list interface for a server.
through a GET on: /v2.1/{tenant_id}/servers/{server_id}/os-interface

The nova code as following:
https://github.com/openstack/python-novaclient/blob/master/novaclient/v2/servers.py#L1851

**Comment by jtopjian** [comment]
@FengyunPan Thanks for opening this.

The link you gave is to the nova client. We need the server implementation. This is so we can verify that the structs and API calls you are submitting in #430 are correct.

See these issues for examples:

* https://github.com/gophercloud/gophercloud/issues/281
* https://github.com/gophercloud/gophercloud/issues/287

Please let me know if you have any questions.

**Comment by FengyunPan** [comment]
All right, I find it:
The value of interfaceAttachments:
https://github.com/openstack/nova/blob/4f91ed3a547965ed96a22520edcfb783e7936e95/nova/api/openstack/compute/attach_interfaces.py#L36

It is hard to find the value of fixed_ips:
subnet_id:
https://github.com/openstack/nova/blob/4f91ed3a547965ed96a22520edcfb783e7936e95/nova/network/neutronv2/api.py#L1358
ip_address:
https://github.com/openstack/nova/blob/4f91ed3a547965ed96a22520edcfb783e7936e95/nova/api/openstack/compute/schemas/attach_interfaces.py#L35

Thank you.

**Comment by FengyunPan** [comment]
@jtopjian Is it ok? Need anything else? 
Thank you.

**Comment by jtopjian** [comment]
@FengyunPan I did a quick look and this does indeed to be closer to what we need - thank you! I hope to have some time this week to look at this in more detail.

**Comment by FengyunPan** [comment]
@jtopjian OK, thank you very much.

**Comment by jtopjian** [comment]
Implemented by #430
