### ISSUE TITLE
Issue with Unmarshalling endpoints from Openstack JSON response

### ISSUE THREAD

**Issue by skywalk7** [gophercloud/gophercloud#434]
OpenStack Swift response for Auth v2.0:
`2017/07/24 20:36:21 [DEBUG] OpenStack Response Body: {
  "access": {
    "serviceCatalog": [
      {
        "endpoints": [
          {
            "publicURL": "https://swift.company.com/v1/AUTH_plateng",
            "region": "default",
            "tenantId": "AUTH_plateng",
            "versionId": 1
          },
         ...
`
Error:
`json: cannot unmarshal number into Go struct field Endpoint.versionId of type
 string`

Looks like versionId is defined as string in gophercloud/openstack/identity/v2/tokens/results.go:
`VersionID   string `json:"versionId"``

**Comment by jtopjian** [comment]
@skywalk7 Thanks for reporting this.

Can you give any details about the OpenStack environment you're seeing this error on? I'm unable to find where an endpoint version is being used in either Mitaka or Ocata. Doing some quick google searching are turning some very old references.

**Comment by skywalk7** [comment]
@jtopjian Sorry for late reply. We resolved the issue by updating our SwiftStack Openstack Swift instance to latest version. Sorry for bugging.

**Comment by jtopjian** [comment]
@skywalk7 No problem at all - glad you got it resolved :)
