### ISSUE TITLE
Provide Better GoDoc Documentation

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#446]
This is a shell issue to house various PRs that will update the godoc documentation throughout Gophercloud.

**Comment by jtopjian** [comment]
@jrperritt Would you mind if I merged the PRs that only contain doc changes or do you prefer to do a review of them? There's going to be a good number of these over the next week.

**Comment by jrperritt** [comment]
> Would you mind

No, in fact I was going to suggest just that.

**Comment by jtopjian** [comment]
Alright. That'll do for now. I'll circle back to BlockStorage once the v3 stuff has been sorted out.

**Comment by jrperritt** [comment]
@jtopjian With #471 merging, it looks like all the referenced issues have merged. I think we can close this, but feel free to re-open if there's more to do. Thank you for all these docs
