### ISSUE TITLE
Missing Microversion Guards in Grant Access and Export Locations

### ISSUE THREAD

**Issue by pospispa** [gophercloud/gophercloud#447]
Shared Filesystems [Grant Access](https://developer.openstack.org/api-ref/shared-file-systems/?expanded=grant-access-detail) and [List Export Locations](https://developer.openstack.org/api-ref/shared-file-systems/?expanded=list-export-locations-detail) are available from microversion `2.7` or `2.9` respectively.

However, the implementation of Grant Access (https://github.com/gophercloud/gophercloud/pull/346) and List Export Locations (https://github.com/gophercloud/gophercloud/pull/381) is not guarded for specific microversion range. In case of Grant Access for `2.7+` and for List Export Locations for `2.14+` (sic).

The guarding shall be added after microversion design discussed in https://github.com/gophercloud/gophercloud/issues/441 is finished.

**Comment by jtopjian** [comment]
I'm going to close this issue since we now have standard patterns/processes in place for handling microversions.
