### ISSUE TITLE
BlockStorage v2: Fix small issues found in volumeactions

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#451]
While reviewing the `volumeactions` package, I came across two issues:

1. `ExtendSize` is throwing an `EOF` error due to an empty body trying to be set in the response.

2. `InitializeConnection` is using `commonResult` which isn't very common. This caused confusion during the Volume Image PR a few weeks ago.

**Comment by jrperritt** [comment]
closed by #452
