### ISSUE TITLE
Add support for OS_PROJECT_* variables

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#461]
`openstack.AuthOptionsFromEnv` doesn't support the `OS_PROJECT_ID` and `OS_PROJECT_NAME` environment variables. A standard `openrc` file that a user downloads from Horizon (when using Keystone v3) will have `PROJECT` set instead of `TENANT`.

Adding support for `PROJECT` will make it possible for users to not have to modify their `openrc` file when using `openstack.AuthOptionsFromEnv`.

**Comment by bugosiphionah** [comment]
I am applying for outreachy round 15 and starting to work on this issue as advised by Davanum Srinivas the mentor. I hope no one is working on it for now.

**Comment by jtopjian** [comment]
@bugosiphionah Thank you for your interest in this! However, there is a PR already in place: #462 (referenced above).

**Comment by bugosiphionah** [comment]
@jtopjian Thanks for the feedback I will let him know its been worked on so he can advise on another. If you have ideas for any first time bugs I can work on. You can also advise. Thanks

**Comment by jtopjian** [comment]
@bugosiphionah Sure, I can try to find something. What's your current skill level with each:

* OpenStack APIs
* Go

brand new, some experience, familiar, very familiar?

**Comment by bugosiphionah** [comment]
@jtopjian I am familiar with Go but brand new to OpenStack APIs but am flexible and willing to learn.

**Comment by jrperritt** [comment]
closed by #462
