### ISSUE TITLE
ListAddressesByNetwork().AllPages() panic

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#47]
I have a code path that checks to see if a server exists by its Name. If it doesn't, it creates it. Then I see what ip addresses the server has, to figure out if it has a floating ip:

    pager = servers.List(client, servers.ListOpts{Name: resourceName, Status: "ACTIVE"})
	var server *servers.Server
	err = pager.EachPage(func(page pagination.Page) (bool, error) {
		serverList, err := servers.ExtractServers(page)
		if err != nil {
			return false, err
		}
		server = &serverList[0]
		fmt.Printf("got pre-existing server %+v\n", server)
		return true, nil
	})
	if err != nil {
		panic(err)
	}
	if server == nil {
		server, err := servers.Create(client, keypairs.CreateOptsExt{
			servers.CreateOpts{
				Name:           resourceName,
				FlavorRef:      flavorId,
				ImageRef:       imageId,
				SecurityGroups: []string{resourceName},
				Networks:       []servers.Network{servers.Network{UUID: networkID}},
				// UserData []byte (will be base64-encoded for me)
				// Metadata map[string]string
			},
			resourceName, // keypair name
		}).Extract()
		if err != nil {
			panic(err)
		}

		fmt.Printf("created server %+v\n", server)

		// wait for it to come up
		err = servers.WaitForStatus(client, server.ID, "ACTIVE", 60) //*** not sure this timeout really works...
		if err != nil {
			panic(err)
		}

		fmt.Println("server now ACTIVE")
	}
	// check if the server has a floating ip; if not, get one and associate with
	// server
	allNetworkAddressPages, err := servers.ListAddressesByNetwork(client, server.ID, resourceName).AllPages() // panics here (no error returned) without a router
	if err != nil {
		fmt.Printf("ListAddressesByNetwork error: %s\n", err)
		os.Exit(1)
	}
	allNetworkAddresses, err := servers.ExtractNetworkAddresses(allNetworkAddressPages)
	if err != nil {
		panic(err)
	}
	var floatingIP string
	for _, address := range allNetworkAddresses {
		if address.Version == 4 && !strings.HasPrefix(address.Address, "192.168") {
			floatingIP = address.Address
			fmt.Printf("server already has floating ip %s\n", floatingIP)
			break
		}
	}
	if floatingIP == "" {
		fmt.Println("server has no floating ip")
		// [...]
	}

The first time I run my code, I create the server and get this from my debugging:

> created server &{ID:97586552-1c7c-47ab-8816-cd3816e99d7a TenantID: UserID: Name: Updated: Created: HostID: Status: Progress:0 AccessIPv4: AccessIPv6: Image:map[] Flavor:map[] Addresses:map[] Metadata:map[] Links:[map[href:http://172.31.0.18:8774/v2/ad5e4867d0174c8b8850e426ef5b215d/servers/97586552-1c7c-47ab-8816-cd3816e99d7a rel:self] map[href:http://172.31.0.18:8774/ad5e4867d0174c8b8850e426ef5b215d/servers/97586552-1c7c-47ab-8816-cd3816e99d7a rel:bookmark]] KeyName: AdminPass:AJvxG7v8BxDd SecurityGroups:[map[name:vrpipe-deployment]]}
server now ACTIVE
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x403c81]

The stack trace points to the line that I call ListAddressesByNetwork().AllPages() (and not the err check).

If I run my code again, changing nothing (except that now the server is already running), I get:

> got pre-existing server &{ID:97586552-1c7c-47ab-8816-cd3816e99d7a TenantID:ad5e4867d0174c8b8850e426ef5b215d UserID:0bdadd0bb3da45509d56c40dc98d73a5 Name:vrpipe-deployment Updated:2016-08-12T14:55:15Z Created:2016-08-12T14:54:57Z HostID:1d35adc28d9b40f4fb5e3cd869cfab8a3c119ecd051b0bd847429c72 Status:ACTIVE Progress:0 AccessIPv4: AccessIPv6: Image:map[id:002ca5be-3934-43d3-9d2c-eda816b57019 links:[map[href:http://172.31.0.18:8774/ad5e4867d0174c8b8850e426ef5b215d/images/002ca5be-3934-43d3-9d2c-eda816b57019 rel:bookmark]]] Flavor:map[id:2 links:[map[href:http://172.31.0.18:8774/ad5e4867d0174c8b8850e426ef5b215d/flavors/2 rel:bookmark]]] Addresses:map[vrpipe-deployment:[map[OS-EXT-IPS-MAC:mac_addr:fa:16:3e:84:30:2c OS-EXT-IPS:type:fixed addr:192.168.0.6 version:4]]] Metadata:map[] Links:[map[rel:self href:http://172.31.0.18:8774/v2/ad5e4867d0174c8b8850e426ef5b215d/servers/97586552-1c7c-47ab-8816-cd3816e99d7a] map[href:http://172.31.0.18:8774/ad5e4867d0174c8b8850e426ef5b215d/servers/97586552-1c7c-47ab-8816-cd3816e99d7a rel:bookmark]] KeyName:vrpipe-deployment AdminPass: SecurityGroups:[map[name:vrpipe-deployment]]}
server has no floating ip

ie. it works perfectly. Am I doing something wrong? I just want to find out if my server has a floating ip associated with it. What's the best way to do that?

**Comment by jtopjian** [comment]
After you create the server, try doing something like:

```go
newServer, err := servers.Get(client, server.ID).Extract()
```

The initially created server only has a minimal amount of information at the time of creation (in the background, the server launches, gets network info, etc). So after the server is active, performing a Get will return a "refreshed" server.

**Comment by sb10** [comment]
I tried that and it didn't help; note that ListAddressesByNetwork takes the server ID, not the server variable itself, so your Get trick wouldn't work here (though may be helpful in other situations!).

**Comment by jtopjian** [comment]
Ah, good point.

Have you ruled out a timing issue altogether? Can you try sleeping for 30 seconds before `ListAddressesByNetwork` just to see if it helps?

**Comment by jrperritt** [comment]
@sb10 Stack trace?

**Comment by sb10** [comment]
Gah, sorry for wasting everyone's time. The panic is caused by sending an empty string as the server ID. Note the := on my servers.Create line. It should be =.

**Comment by jrperritt** [comment]
> Gah, sorry for wasting everyone's time

No worries. Could have easily been `AllPages`.
