### ISSUE TITLE
Discussion: Improvements/Fixes to Grant Access and Share Export Locations Requests

### ISSUE THREAD

**Issue by pospispa** [gophercloud/gophercloud#488]
Grant Access and Share Export Locations requests were added in the below PRs:
- Grant Access: https://github.com/gophercloud/gophercloud/pull/346
- Share Export Locations: https://github.com/gophercloud/gophercloud/pull/381

I don't want to clutter discussions in https://github.com/gophercloud/gophercloud/issues/441 with detailed discussions whether the above PRs should be improved/fixed.

***

**Topic:** Newly added fields into results.

According to [List export locations documentation](https://developer.openstack.org/api-ref/shared-file-systems/?expanded=id236-detail) the field `preferred` was added in microversion "2.14" while other fields exist since microversion "2.9". I haven't found any change in [the Manila source code](https://github.com/openstack/manila/blob/stable/newton/manila/api/v2/share_instance_export_locations.py#L41-L50) because of this change except [this one](https://github.com/openstack/manila/blob/stable/newton/manila/api/views/export_locations.py#L79-L83).

Similarly, according to [Grant Access documentation](https://developer.openstack.org/api-ref/shared-file-systems/?expanded=grant-access-detail) the field `access_key` was added in microversion "2.21" while other fields exist since microversion "2.0". I haven't found any change in [the Manila source code](https://github.com/openstack/manila/blob/stable/newton/manila/api/v2/shares.py#L229-L236) because of this change except [this one](https://github.com/openstack/manila/blob/stable/newton/manila/api/views/share_accesses.py#L59-L61) and [this one](https://github.com/openstack/manila/blob/stable/newton/api-ref/source/parameters.yaml#L376-L382).

Even though a field was added in microversion "2.14", respectively in "2.21" the result data structures contain all fields for any microversion as seen [here](https://github.com/gophercloud/gophercloud/blob/master/openstack/sharedfilesystems/v2/shares/results.go#L121-L137) in the `ExportLocation` and [here](https://github.com/gophercloud/gophercloud/blob/master/openstack/sharedfilesystems/v2/shares/results.go#L150-L165) in `AccessRight` respectively.

However, @jtopjian proposed in https://github.com/gophercloud/gophercloud/issues/441#issuecomment-322087992 a different way how to handle extensions to results.

Should current implementation of parsing results of Grant Access and Export Locations requests be reworked?

***

**Topic:** Grant Access top element was renamed.

The Grant Access top element `os-allow_access` was renamed in microversion "2.7" to `allow_access` as described in [the documentation](https://developer.openstack.org/api-ref/shared-file-systems/?expanded=grant-access-detail).

However, the Grant Access request always uses `allow_access` top element for any microversion `>="2.0"`. This is incorrect.

I plan to create a PR for this problem.

**Comment by jtopjian** [comment]
__Topic__: Newly added fields into results.

> Should current implementation of parsing results of Grant Access and Export Locations requests be reworked?

I would say yes. But remember that things could still change. I wanted to merge the PRs you had because the fields were valid as of the current state of Manila (meaning: current api version) and we hadn't (and still haven't) made firm decisions about microversions yet. Just a heads up that any other PRs might take longer to merge as we don't want to keep making constant changes.

- - - 

__Topic__: Grant Access top element was renamed.

The same applies. This is a different type of change than the result field change. This is changing the key of the request body, right? I don't think we specifically discussed this kind of microversion change, but I'm definitely open to seeing how you want to implement it.

**Comment by pospispa** [comment]
**Topic:** Newly added fields into results.

> Should current implementation of parsing results of Grant Access and Export Locations requests be reworked?

@jtopjian I explained [in this comment](https://github.com/gophercloud/gophercloud/issues/441#issuecomment-323337653) that I prefer to keep the implementation as it is.

> I wanted to merge the PRs you had because the fields were valid as of the current state of Manila (meaning: current api version) and we hadn't (and still haven't) made firm decisions about microversions yet.

@jtopjian I'm gratefull for that.

***

**Topic:** Grant Access top element was renamed.

> This is a different type of change than the result field change.

Yes, it's a different type of change and I think it requires a completely different approach than the result field change because in case the key of the request body doesn't have correct value the request is rejected by the server.

> ... I'm definitely open to seeing how you want to implement it.

Well, I was too optimistic about creating a PR.

Firstly, I'd like to discuss how to approch this problem.

A solution seems pretty easy at first sight:
```
func (opts GrantAccessOpts) ToGrantAccessMap(microversion string) (map[string]interface{}, error) {
  if utils.LowerThan(microversion, "2.7") {
	  return gophercloud.BuildRequestBody(opts, "os-allow_access")
  }
  return gophercloud.BuildRequestBody(opts, "allow_access")
}
```
and adding the `client.Microversion` as a parameter in:
```
func GrantAccess(client *gophercloud.ServiceClient, id string, opts GrantAccessOptsBuilder) (r GrantAccessResult) {
	b, err := opts.ToGrantAccessMap(client.Microversion)
```

However, it's easy only if `client.Microversion` contains a particular microversion value, e.g. "2.5".

But there're two special cases:
- `client.Microversion == ""`
- `client.Microversion == "latest"`

I assume that `gophercloud` must support these two special cases.

How the two special cases should be interpreted? When should the `os-allow_access` be used and when `allow_access` should be used?

I interpret `client.Microversion == ""` as the server's minimum microversion. So in case server's minimum microversion is `<"2.7"` the `os-allow_access` must be used. Otherwise, the `allow_access` must be used.

Similarly, I interpret `client.Microversion == "latest"` as the server's maximum microversion. So in case server's maximum microversion is `<"2.7"` the `os-allow_access` must be used. Otherwise, the `allow_access` must be used.

Thus, for deciding which Grant Access top element must be used we need to know server's minimum and maximum microversion.

Therefore, at the time `gophercloud` ManilaV2 client is created we need to query the endpoint for server's minimum and maximum microversion in order to have these values in case they are needed in the `func (opts GrantAccessOpts) ToGrantAccessMap`.

So in case the request for server's minimum and maximum microversion fails we will fail the ManilaV2 client creation.

**Comment by pospispa** [comment]
@jtopjian as I was thinking about this issue, I came to conclusion that it make sense to introduce [`discover_versions`](https://github.com/openstack/keystoneauth/blob/master/doc/source/using-sessions.rst) option into endpoint options and use is it in similar way as in [keystoneauth](https://github.com/openstack/keystoneauth/blob/master/doc/source/using-sessions.rst)

I plan to set the `discover_versions` default value to `false` as this is the current gophercloud behavior.
The request for min/max server versions will be sent by gophercloud only in case `discover_versions` is set to `true` at the time of client creation.
Setting the `discover_versions` option to `true` at the time of client creation will be the only way how to get server's min/max versions.

So the part in `func GrantAccess` will look like:
```
func (opts GrantAccessOpts) ToGrantAccessMap(serverMin, serverMax, microversion string) (map[string]interface{}, error) {
  if microversion == "" && utils.LowerThan(serverMin, "2.7") {
    return gophercloud.BuildRequestBody(opts, "os-allow_access")
  }
  if microversion == "latest" && utils.LowerThan(serverMax, "2.7") {
    return gophercloud.BuildRequestBody(opts, "os-allow_access")
  }
  if utils.LowerThan(microversion, "2.7") {
	  return gophercloud.BuildRequestBody(opts, "os-allow_access")
  }
  return gophercloud.BuildRequestBody(opts, "allow_access")
}

func GrantAccess(client *gophercloud.ServiceClient, id string, opts GrantAccessOptsBuilder) (r GrantAccessResult) {
  var min, max string
  // in case the server min/max version was not requested (discover_versions was not set to true at the time of client creation) an error is reported
  if client.Microversion == "" || client.Microversion == "latest" {
    var err error
    min, max, err = GetServerMinMax(client)
    if err != nil {
      r.Err = err
      return
    }
  }
	b, err := opts.ToGrantAccessMap(min, max, client.Microversion)
	if err != nil {
		r.Err = err
		return
	}
	_, r.Err = client.Post(grantAccessURL(client, id), b, &r.Body, &gophercloud.RequestOpts{
		OkCodes: []int{200},
	})
	return
}
```

I plan to prepare a PR along the lines of the above design.

**Comment by chestack** [comment]
@pospispa , It's really helpful if GetServerMinMax(client) could get min/max microversions dynamically.

But until then Is it better to add microversion to the functions?(PR #585 ). It took me time to find out that I need set microversion to use GetExportLocations() and GrantAccess().

**Comment by pospispa** [comment]
> It took me time to find out that I need set microversion to use GetExportLocations() and GrantAccess().

I'm sorry for that. The error message one gets while trying to use `GetExportLocations()` or `GrantAccess()`  is not very useful.

This issue is waiting for results from https://github.com/gophercloud/gophercloud/issues/441 design discussion.

**Comment by jtopjian** [comment]
I'm going to close this issue since we now have some standard patterns and processes in place to handle microversions.
