### ISSUE TITLE
ToFlavorCreateMap takes a pointer receiver

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#498]
The [`ToFlavorCreateMap`](https://github.com/gophercloud/gophercloud/blob/22159404c80aa135fe54f2fc9903803fbf0b118f/openstack/compute/v2/flavors/requests.go#L126-L129) method takes a pointer receiver which is different than all of the other `ToXCreateMap` functions.

@jrperritt do you know if there's a reason for this?

**Comment by jrperritt** [comment]
> do you know if there's a reason for this?

I don't think it was intentional

**Comment by jtopjian** [comment]
I figured it was something like that. Was curious if there was some history or if it was purely accidental.

**Comment by jrperritt** [comment]
closed by #499
