### ISSUE TITLE
NewIdentityAdminV2 function missing in the client authentication

### ISSUE THREAD

**Issue by kgrvamsi** [gophercloud/gophercloud#5]
@smashwilson  @jrperritt  @jamiehannaford  Why is this function not available in this repo  which is available in the rackspace/gophercloud code base.

**Comment by jrperritt** [comment]
That function existed in the old repo there was no way to provide an `EndpointOpts` when creating an Identity client. Now there is, but it's not finished yet. I'll try to fix it this week.

**Comment by kgrvamsi** [comment]
Thanks @jrperritt

**Comment by jrperritt** [comment]
Working on this now.

**Comment by jrperritt** [comment]
closed by #17
