### ISSUE TITLE
Compute v2: Add Lock/Unlock Action

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#518]
Nova supports the ability to lock and unlock an instance:

* https://developer.openstack.org/api-ref/compute/#lock-server-lock-action
* https://developer.openstack.org/api-ref/compute/#unlock-server-unlock-action

This action would look very similar to the [pause/unpause](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/pauseunpause) action.

Additional work required: Locate the Nova API Server code that implements lock/unlock.

Bonus: Implement a lock/unlock [acceptance test](https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/compute/v2/servers_test.go#L447-L481) and verify it works.

**Comment by bugosiphionah** [comment]
@jtopjian I Would love to work on this over the weekend. We can discuss my solution on IRC on Monday.

**Comment by jtopjian** [comment]
Sure, go for it. :)

Github is the best way to discuss Gophercloud. I'm not normally on IRC.

**Comment by jtopjian** [comment]
Implemented in #522 

@bugosiphionah Nice work on this!
