### ISSUE TITLE
Compute v2: Add Evacuate Action

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#519]
Nova supports the ability to evacuate a compute node:

* https://developer.openstack.org/api-ref/compute/#evacuate-server-evacuate-action

This action would look similar to the [migrate](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/migrate) action.

Additional work required: Locate where evacuate is implemented in the Nova API service.

Bonus: Implement an evacuate [acceptance test](https://github.com/gophercloud/gophercloud/tree/master/acceptance/openstack/compute/v2). However, this might be difficult since it might require a multi-node OpenStack testing environment.

**Comment by bugosiphionah** [comment]
@jtopjian Working on this.

**Comment by jtopjian** [comment]
Implemented by #532
