### ISSUE TITLE
Designate Support

### ISSUE THREAD

**Issue by grahamhayes** [gophercloud/gophercloud#52]
Add support for OpenStack DNS - Designate

**Comment by jrperritt** [comment]
Can you break this into multiple issues so that we can have multiple PRs?
You can read about some of the procedural approaches this library is trying to move toward here: https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md

**Comment by grahamhayes** [comment]
OK, so adding one for zones, one for recordsets ? or one for creating zones, one for updating zone, one for reading zones, one for creating recordsets, etc ?

**Comment by jrperritt** [comment]
One of the banes of the old repo was PRs that were thousands of lines that no one wanted to review. The latter of your options would be preferable.

**Comment by grahamhayes** [comment]
OK. does github support the gerrit style dependency chain of commits? otherwise this could be painful to try and layer into multiple PRs

**Comment by jrperritt** [comment]
does github support the gerrit style dependency chain of commits?

Not really.

Options:
1. Submit stand-alone PRs and, after they're merged, base new PRs off of upstream `master`.
2. Still submit one PR at a time, but base each subsequent PR off the one before it. If the PRs are reviewed in order, the overlapping bits should be rendered obsolete with each dependent PR that gets merged. Note that this option _could_ be more work for you if, after review, there need to be changes to early PRs that necessitate rebasing all later (dependent) PRs.

**Comment by grahamhayes** [comment]
OK, cool.

I am used to rebase hell from OpenStack :) 

Have you seen http://gerrithub.io/ ? It might help with this style of approach

**Comment by jrperritt** [comment]
> Have you seen http://gerrithub.io/ ? 

No, I hadn't. Looks interesting.

> It might help with this style of approach 

Agreed. I think it'd be interesting to test, but at the same time I think we're going to stick with just Github for the foreseeable future.

**Comment by jrperritt** [comment]
Closing in favor of more targeted issues (i.e. #54, #56, #57)
