### ISSUE TITLE
Compute v2: Add Live Migration Action

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#520]
Nova supports the ability to live migrate instances between compute nodes:

* https://developer.openstack.org/api-ref/compute/#live-migrate-server-os-migratelive-action

This action should amend the current [migrate](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/migrate) action with a new request.

Additional work required: Locate where live migration is implemented in the Nova API service.

Bonus: Implement a live migration [acceptance test](https://github.com/gophercloud/gophercloud/tree/master/acceptance/openstack/compute/v2), however, this might be difficult since it would require a multi-node OpenStack test environment with shared storage. If an acceptance test is implemented, provide a way to enable or disable this test - possibly by an environment variable.

**Comment by ss22ever** [comment]
@jtopjian I would like to take this

**Comment by jrperritt** [comment]
@ss22ever Great, it's yours

**Comment by dstdfx** [comment]
@ss22ever Is there something you're still working on? 
@jtopjian I'd like to complete it

**Comment by jtopjian** [comment]
@dstdfx Let's give @ss22ever another day to give us an update. If we don't hear back, then I would say it's safe to proceed.

**Comment by jtopjian** [comment]
Implemented in #728
