### ISSUE TITLE
Compute v2: Add Reset State Action

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#521]
Nova supports the ability to reset an instance's state to either `active` or `error`:

* https://developer.openstack.org/api-ref/compute/#reset-server-state-os-resetstate-action

This action should look similar to the [migrate](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/migrate) action (but I might be wrong).

Additional work required: Locate where the reset state action is implemented in the Nova API service.

Bonus: Implement a reset state [acceptance test](https://github.com/gophercloud/gophercloud/tree/master/acceptance/openstack/compute/v2) and verify it works.

**Comment by ss22ever** [comment]
@jtopjian I would like to work on this

**Comment by jrperritt** [comment]
@ss22ever Great, it's yours

**Comment by ss22ever** [comment]
@jtopjian @jrperritt I tried creating the reset state action and when I test it shows me 
`go test .
--- FAIL: TestResetState (0.01s)
        convenience.go:300: Expected JSON:
                {
                  "os-resetState": null
                }
        convenience.go:308: Actual JSON:
                {
                  "os-resetState": {
                    "state": "active"
                  }
                }
        convenience.go:39: Failure in http_responses.go, line 90: The generated JSON structure differed.
FAIL
FAIL    github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/resetstate/testing   0.191s
`
Even when it follows the example Reset Server State (os-resetState Action)
`{
    "os-resetState": {
        "state": "active"
    }
}`

**Comment by jtopjian** [comment]
Implemented by #545
