### ISSUE TITLE
Compute v2: Small Extension Fixes

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#524]
Packages under `compute/v2/extensions` require some small fixes:

* lock/unlock doc fix
* Change `ErrResult` in suspend/resume
* migrate doc fix
* Change `ErrResult` in defsecrules
* Change `ErrResult` in pause/unpause
* Change `ErrResult` in start/stop
* Change `ErrResult` in secgroups

These are all small, minor changes, so I'm going to submit a PR with the collection.

**Comment by jrperritt** [comment]
closed by #525
