### ISSUE TITLE
Attach/detach configuration groups

### ISSUE THREAD

**Issue by eugenetaranov** [gophercloud/gophercloud#544]
Currently db/v1/configurations is missing functions that would attach or detach configuration group to/from the instance. Is there something I am missing? Otherwise I would be happy to submit pull request.

**Comment by jtopjian** [comment]
> Is there something I am missing

I don't think so. If it looks like it's missing, it's most likely missing 😄 

The most confident way to determine this is to see if any of the `urls.go` files contain the URL of this API.

You are most welcomed to submit a PR for this!

**Comment by eugenetaranov** [comment]
Thanks @jtopjian, submitted pr https://github.com/gophercloud/gophercloud/pull/547

**Comment by jtopjian** [comment]
Implemented in #547
