### ISSUE TITLE
Compute v2: Add detailed quota reporting

### ISSUE THREAD

**Issue by nate-johnston** [gophercloud/gophercloud#549]
Nova supports the ability to get not just the current quota for a tenant, but also the current allocation against the quota [1] through a "detail" endpoint.  Please enable this collection.

[1] https://developer.openstack.org/api-ref/compute/#show-the-detail-of-quota

This action would look similar to the existing quota fetch action, with a more complex response set.

**Comment by nate-johnston** [comment]
I am waiting for approval from a core contributor before creating a PR.

**Comment by jtopjian** [comment]
@nate-johnston You're more than welcome to open a PR for this.

**Comment by jtopjian** [comment]
Implemented in #564
