### ISSUE TITLE
Compute v2: Add Simple Tenant Usage extension

### ISSUE THREAD

**Issue by nate-johnston** [gophercloud/gophercloud#551]
Nova's os-simple-tenant-usage extension [1] provides the ability to show metered usage data for OpenStack clouds.  This is very useful information to create a billing model around OpenStack clouds.  This would be a new Compute v2 extension.

[1] https://developer.openstack.org/api-ref/compute/#usage-reports-os-simple-tenant-usage

**Comment by nate-johnston** [comment]
I am waiting for approval from a core contributor before creating a PR.

**Comment by jtopjian** [comment]
@nate-johnston Apologies - you're more than welcome to open a PR for this.

**Comment by jtopjian** [comment]
Implemented in #565 and #1125
