### ISSUE TITLE
Identity v3: Add assigning role to user on project

### ISSUE THREAD

**Issue by dongwoo1005** [gophercloud/gophercloud#566]
I need a support for assigning role to user on project: https://developer.openstack.org/api-ref/identity/v3/#assign-role-to-user-on-project
If nobody is working on it at the moment, I will make a PR for this.

I can start working on this first. Then I might as well add 
- assign/unassign role to group on domain
- assign/unassign role to user on domain
- assign/unassign role to group on project
- assign/unassign role to user on project

May I start working on this PR?

**Comment by dongwoo1005** [comment]
I can start with this first. Then I might as well add 
- assign/unassign role to group on domain
- assign/unassign role to user on domain
- assign/unassign role to group on project
- assign/unassign role to user on project
May I start working on this PR?

**Comment by jtopjian** [comment]
@dongwoo1005 Thanks for offering. You're more than welcome to work on these items. Please make sure to open a separate PR for each one, though.

I'd also wait until #561 is merged before opening any PRs since you'll most likely need to rebase based on those changes.

**Comment by dongwoo1005** [comment]
Yep. I forked from dklyle:role-list and my implementation is complete. 
As you said though, I need to wait for #561 to be merged for my acceptance test.
I'll make a PR once #561 is checked in.

**Comment by jtopjian** [comment]
@dongwoo1005 You are clear to go.

Please use some of the other Role Issues/PRs as templates for including all of the required information.

**Comment by jtopjian** [comment]
Implemented in #570
