### ISSUE TITLE
Identity v3 role C_UD

### ISSUE THREAD

**Issue by dklyle** [gophercloud/gophercloud#571]
- [x] Create (#572)
- [x] Delete (#577)
- [x] Update (#578)

Read was already covered by #550 

API Docs:
https://developer.openstack.org/api-ref/identity/v3/#roles

Schema:
https://github.com/openstack/keystone/blob/stable/pike/keystone/assignment/role_backends/sql.py#L196
https://github.com/openstack/keystone/blob/stable/pike/keystone/assignment/role_backends/sql.py#L201

Create:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L319

Delete:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L383

Update:
https://github.com/openstack/keystone/blob/83bd595b22944d38eff1cdef77b4c07a75af0fdc/keystone/assignment/controllers.py#L367

**Comment by jtopjian** [comment]
:tada: 

@dklyle Thank you very much for the work you've been doing.
