### ISSUE TITLE
Neutron Router: Enable/Disable SNAT

### ISSUE THREAD

**Issue by Crapworks** [gophercloud/gophercloud#573]
Hi there,

I learned today that some OpenStack providers have SNAT disabled by default. Of course, I'd like to enable it, so I can actually access the internet from instances without attached floating IPs...

Gophercloud doesn't support this at the moment, because there is no `enable_snat` parameter for the `external_gateway_info` in the router resource. I am not very experienced with GO but as far as I can see this should be a simple fix so I will create a PR for this.

Cheers,
Christian

**Comment by jtopjian** [comment]
Implemented in #574
