### ISSUE TITLE
add support for sort image new syntax

### ISSUE THREAD

**Issue by iaroslavscript** [gophercloud/gophercloud#579]
Hi,
there is a new syntax for sorting images.
It makes it easier to sort by multiple keys.
https://specs.openstack.org/openstack/glance-specs/specs/api/v2/lists-image-api-v2.html
https://github.com/openstack/glance/blob/stable/pike/glance/api/v2/images.py#L683

**Comment by jtopjian** [comment]
Implemented in #580
