### ISSUE TITLE
Identity V3: Region CRUD

### ISSUE THREAD

**Issue by dklyle** [gophercloud/gophercloud#583]
- [x] List / Get (#584)
- [x] Create (#586)
- [x] Delete (#587)
- [x] Update (#594)

API:
https://developer.openstack.org/api-ref/identity/v3/#regions

Schema:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/backends/sql.py#L34
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/schema.py#L22

List:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L70

Get:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L78

Create:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L54

Update:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L83

Delete:
https://github.com/openstack/keystone/blob/2764b49bc209245276da31693ef31f1525cf17d8/keystone/catalog/controllers.py#L92

**Comment by jtopjian** [comment]
:tada: 

Another resource added. Thank you, @dklyle!
