### ISSUE TITLE
Objects v1: endless loop when perform objects.List on directory with subdirectories

### ISSUE THREAD

**Issue by awskii** [gophercloud/gophercloud#588]
Hi.

When you have non empty directory with subdirectories, and specify Delimiter in options, you will have an endless loop because of endless asking server with `&marker=`.  Also we have empty names instead of `$(dirname)/`, e.g.: we have one directory in container on swift server and asking listing of directory and got next:
```
test
test/
```
which reduces by Gophercloud to that:
```
test
''
```

last parameter returned as marker so we have what we have.

I think, problem may be much more deeper than that, but i update tests  and you can see by yourselves. Don't forget to set test timeout.

Also, i provide an easy solution in PR.

**Comment by jtopjian** [comment]
@awskii I've pinpointed the problem and have a working solution here:

https://github.com/jtopjian/gophercloud/commits/objectsv1-subdir

Would you be able to test this and let me know if it works for you?

The above might not be a final version -- I think there's room for some improvement in my implementation, but it _should_ fix the problem.

Details of the problem: Gophercloud is not detecting the existence of a `subdir` entry. When a `subdir` entry exists, it should be used as the paging marker. This is done [here](https://github.com/openstack/python-swiftclient/blob/c50823ebf1fc3d691e1589321fb03a6464604530/swiftclient/client.py#L910-L913) in the Python `swiftclient` package.

**Comment by awskii** [comment]
Ok, i will test it.

**Comment by awskii** [comment]
All my integration tests has passed.

**Comment by jtopjian** [comment]
@awskii That's great news. I updated my branch with a cleaner function to check for the marker. When you have time, can you test once more? If it works, I will open a PR for review.

**Comment by awskii** [comment]
@jtopjian Seems like works fine, nothing has been broken.

**Comment by jtopjian** [comment]
Perfect. Thank you so much for testing.

**Comment by jrperritt** [comment]
closed  by #606
