### ISSUE TITLE
New CI system integration request

### ISSUE THREAD

**Issue by liu-sheng** [gophercloud/gophercloud#592]
I'd like to introduce a CI system which is built based zuul[1] and nodepool[2] tools, it is for running Gophercloud tests(both unit tests and acceptance tests) based on a devstack[3] environment. For now, my colleague and I have basicially finish the CI system building, and have tested with Gophercloud, it can work OK, please see[4]. We will long-term maintain the CI system and would like to propose to intergrate with Gophercloud official repo(also, we will try with Terraform project).

FYI, the zuul jobs definition can be found in[5], the zuul jobs status web page is[6], the test jobs log server is[7] and there is a job log example[8], tests result can be found in the "job-output.txt.gz" file of the log page.

If it is possible to integrate the CI system with Gophercloud official repo, there are two things need to to with Gophercloud repo to integrate with this CI system:
a). Need to add a webhook to trigger the CI system running testing jobs when new pull request comming
b). Need to add a ".zuul.yaml" file as a CI jobs entrypoint into the gophercloud repo.

Thanks.

[1] https://docs.openstack.org/infra/zuul/
[2] https://docs.openstack.org/infra/nodepool/
[3] https://docs.openstack.org/devstack/latest/
[4] https://github.com/theopenlab/gophercloud/pull/5
[5] https://github.com/theopenlab/openlab-zuul-jobs
[6] http://80.158.20.68/
[7] http://80.158.20.68/logs/
[8] http://80.158.20.68/logs/5/5/3a173240e5d1ca246990330d1176361fc8161a6b/check/gophercloud-unittest/96d4f26/

**Comment by jtopjian** [comment]
@jrperritt This is the CI testing I mentioned to you about a few weeks ago.

I've been fielding some questions from this team and they're making great progress.

**Comment by jrperritt** [comment]
Brilliant. This is very welcome. Feel free to submit a PR to add the .zuul.yaml file, and if you provide me (or @jtopjian ) with the pertinent webhook information, we'll get it added to the repo.

**Comment by liu-sheng** [comment]
@jtopjian @jrperritt Thanks for all your support! will submit a PR to add the .zuul.yaml file and will send the webhook infomation :)

**Comment by animationzl** [comment]
@jtopjian @jrperritt I have sent an email about the webhook information to you, please let me know if you have the webhook added and we will double check then. Thanks for your support :)

**Comment by jtopjian** [comment]
@jrperritt It doesn't look like I have the right level of privileges in the Gophercloud repo to do this. Did you receive the info via email? If not, I can forward to you.

**Comment by jrperritt** [comment]
Oh, OK. I did get the email and just added the webhook

**Comment by animationzl** [comment]
Thanks Jon, Joe

The webhook works properly, so do our ci system, which couldn't succeed without your help.

But there is another issue may need your help, since we need to report the check job status for each PR via a specific account, could you help add the account 'theopenlab-ci' as a collaborator to this project for access rights?

**Comment by jrperritt** [comment]
Yes, I've just added that user as a collaborator with Read permissions.

**Comment by jrperritt** [comment]
I think we can close this since the CI system appears to be working. Feel free to comment here if this should be reopened.
