### ISSUE TITLE
Objects v1: API calls seem mixed up

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#596]
@jrperritt I'm digging into #588 and noticed that some of the object storage API calls seem mixed up.

The [API Reference](https://developer.openstack.org/api-ref/object-store/) shows that the "accounts" group of actions performs a List on containers, but in Gophercloud this functionality is in the `containers` package.

Similar, the "containers" group in the API reference has a List action which is implemented in the `objects` package in Gophercloud.

I can see both the API reference and Gophercloud being valid:

* From the API reference view, calls are grouped by endpoint URL
* From Gophercloud's view, calls are grouped by which resource is being acted upon.

I don't think there's a need to reorganize Gophercloud. I might update the godoc to make note of this, though.

The reason I'm posting this is to see if you know of a reason why this was done as well as to have a historical documented issue for others who might come across this.

**Comment by jrperritt** [comment]
> From Gophercloud's view, calls are grouped by which resource is being acted upon.

Exactly that. We're trying to go for readability: we decided it'd be weird if `containers.List` returned a list of objects. I think we may have discussed `containers.ListObjects` at the time, but maybe all the other list operations were just `List`, so consistency won out.

**Comment by jtopjian** [comment]
Makes sense to me. I'll leave this issue open until I add a note to the docs.

**Comment by jtopjian** [comment]
Closed by #962
