### ISSUE TITLE
Compute Acceptance Test Issues

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#6]
I tried running the `TestListFlavor` acceptance test and had to fix a lot of errors in the `acceptance/openstack/compute/v2` directory to just get the test to run. The test passed, but incorrectly -- no flavors were printed.

Here's the diff of what needed to be changed just to get the test to run:

https://github.com/jtopjian/gophercloud/commit/74cd982df7d38472c66955b8061165763e332c34

It looks like there have been a good amount of changes that have happened to the code base - are these the types of things that should be documented in the MIGRATING doc?

I'd be happy to submit PRs to fix the tests, but having no flavors printed is throwing me off. It looks like there might be some auth issues and I have no doubt that someone else can figure that one out quicker than me.

Nice work on this new repo, by the way!

**Comment by jrperritt** [comment]
>> I tried running the TestListFlavor acceptance test and had to fix a lot of errors

You're right; the acceptance tests haven't been touched in a while. See my comment [here](https://github.com/rackspace/gophercloud/issues/592#issuecomment-231936468).

>> It looks like there have been a good amount of changes that have happened to the code base - are these the types of things that should be documented in the MIGRATING doc?

Yes

>> I'd be happy to submit PRs to fix the tests

Great. Please read the [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md) (which I'm continuing to add to) first.

**Comment by jtopjian** [comment]
Sounds good.

If it helps, I have [this stuff](https://github.com/jtopjian/terraform-devstack) which I have been using to run the Terraform acceptance tests. I'm hoping to keep the number of configurations down to two:

* standard: current api versions (currently sorting out issues with lbaas v2 and keystone v3)
* legacy: lbaas v1 and keystone v2

It doesn't look like there is an official way of restarting devstack-based services any more, which means it's not possible to snapshot these configurations into an image and launch on-demand... I usually build them once every week or two and manually fire off the Terraform acceptances whenever I review a PR.

**Comment by jrperritt** [comment]
closed by #8
