### ISSUE TITLE
objectstorage/v1/objects etag auto computed value

### ISSUE THREAD

**Issue by yanndegat** [gophercloud/gophercloud#600]
@jtopjian : The autocomputed etag value should be optionnally set by the end user, not the lib.
The computed value based on the content of the body is wrong in some usecases

cf : https://docs.openstack.org/swift/latest/api/large_objects.html

"etag (optional). If provided, this value must match the ETag of the segment object. This was included in the response headers when the segment was created. Generally, this will be the MD5 sum of the segment."
(and so, it can't be the md5sum of the json manifest payload)

**Comment by yanndegat** [comment]
@jtopjian

**Comment by jtopjian** [comment]
Fixed in #957
