### ISSUE TITLE
How to get the reason for a failed servers.Create?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#601]
I currently do something like:

    server, err := servers.Create(p.computeClient, keypairs.CreateOptsExt{
        CreateOptsBuilder: createOpts,
        KeyName:           resources.ResourceName,
    }).Extract()
    if err != nil {
        return
    }
    
    // in a go routine (code simplified)
    for {
        select {
        case <-ticker.C:
            current, err := servers.Get(p.computeClient, server.ID).Extract()
            if err != nil {
                return
            }
            if current.Status == "ACTIVE" {
                // report success
                return
            }
            if current.Status == "ERROR" {
                // report failure
                return
            }
        }
    }

Periodically checking the server Status is what your servers.WaitForStatus() method does. But if the status is ERROR, how do you get the reason for the error?

For example, it may have gone in to error state because "No valid host was found. There are not enough hosts available." (code 500). But how do I get gophercloud to tell me this?

**Comment by jtopjian** [comment]
@sb10 Sorry for the late reply, I somehow missed this one.

I believe this issue is the same (or similar) to https://github.com/gophercloud/gophercloud/issues/243. This is probably the last area of Gophercloud I haven't familiarized myself with, so I can't say for certain if there's a workaround or how to best fix this.

I'm going to close this one in favor of #243, but opening this has renewed my interest, so I'll try to make some time to look into it.

If what you're reporting is altogether different than #243, do let me know and I'll re-open this.

**Comment by sb10** [comment]
No, I think #243 would be an error returned by the api, eg. in my above code it I would capture that error on line 6.

I'm talking about a _successful_ `servers.Get(`) call that that has .Status == "ERROR", but no explanation of the error.

At the bottom of https://developer.openstack.org/api-guide/compute/faults.html you can see an example "faults" section that has the information I'd like to see, though I've no idea how to get the OpenStack API to actually furnish you with a faults section.

**Comment by jtopjian** [comment]
Ah, I see.

When you do `nova --debug show <uuid>`, what's the field that contains the details of the error?

**Comment by sb10** [comment]
The field is called 'fault', here's an example:

> | fault                                | {"message": "Conflict updating instance c2ce4dea-b73f-4d01-8633-2c6032869281. Expected: {'task_state': [u'spawning']}. Actual: {'task_state': None}", "code": 500, "created": "2017-11-11T07:58:39Z"} |

**Comment by jtopjian** [comment]
Can you confirm the field is called `fault` in the JSON output? Are you able to paste the full response body?

**Comment by sb10** [comment]
> DEBUG (connectionpool:396) http://172.27.66.32:8774 "GET /v2.1/297dfc60ad694802aa9f9019362b5888/servers/c2ce4dea-b73f-4d01-8633-2c6032869281 HTTP/1.1" 200 1590
DEBUG (session:419) RESP: [200] Content-Type: application/json Content-Length: 1590 X-Openstack-Nova-Api-Version: 2.12 Vary: X-OpenStack-Nova-API-Version X-Compute-Request-Id: req-5725183b-7b6a-4526-ad95-13fe494841e9 Date: Sat, 11 Nov 2017 07:59:05 GMT
RESP BODY: {"server": {"status": "ERROR", "updated": "2017-11-11T07:58:39Z", "hostId": "", "addresses": {}, "links": [{"href": "http://172.27.66.32:8774/v2.1/297dfc60ad694802aa9f9019362b5888/servers/c2ce4dea-b73f-4d01-8633-2c6032869281", "rel": "self"}, {"href": "http://172.27.66.32:8774/297dfc60ad694802aa9f9019362b5888/servers/c2ce4dea-b73f-4d01-8633-2c6032869281", "rel": "bookmark"}], "key_name": "wr-development-sb10", "image": {"id": "0fea53f3-a79f-459f-9c52-9ed49d537170", "links": [{"href": "http://172.27.66.32:8774/297dfc60ad694802aa9f9019362b5888/images/0fea53f3-a79f-459f-9c52-9ed49d537170", "rel": "bookmark"}]}, "OS-EXT-STS:task_state": null, "OS-EXT-STS:vm_state": "error", "OS-SRV-USG:launched_at": "2017-11-11T07:58:39.000000", "locked": false, "flavor": {"id": "2001", "links": [{"href": "http://172.27.66.32:8774/297dfc60ad694802aa9f9019362b5888/flavors/2001", "rel": "bookmark"}]}, "id": "c2ce4dea-b73f-4d01-8633-2c6032869281", "OS-SRV-USG:terminated_at": null, "OS-EXT-AZ:availability_zone": "", "user_id": "2ded1096516d46d88495b32cb7b7e4f5", "name": "wr-development-sb10-4579cc84-19dc-41bb-ab2a-ca1d7f26148f", "created": "2017-11-11T07:58:35Z", "tenant_id": "297dfc60ad694802aa9f9019362b5888", "OS-DCF:diskConfig": "MANUAL", "os-extended-volumes:volumes_attached": [], "accessIPv4": "", "accessIPv6": "", "fault": {"message": "Conflict updating instance c2ce4dea-b73f-4d01-8633-2c6032869281. Expected: {'task_state': [u'spawning']}. Actual: {'task_state': None}", "code": 500, "created": "2017-11-11T07:58:39Z"}, "OS-EXT-STS:power_state": 1, "config_drive": "", "metadata": {}}}

**Comment by jtopjian** [comment]
Perfect - thanks :)

There indeed looks to be a field called `fault`. I'll do some digging and see if I can find more about this.

**Comment by sb10** [comment]
@jtopjian For some reason I can't comment on the #607, but it works great, thank you.

**Comment by jtopjian** [comment]
Nice. Thank you for testing.
