### ISSUE TITLE
Does gophercloud support additional headers?

### ISSUE THREAD

**Issue by awskii** [gophercloud/gophercloud#602]
In my case i should pass to server X-Forwarded-For header with different ip (not gophercloud node). Is there proper way to do it?

**Comment by jtopjian** [comment]
There's probably a few ways to do this. I should mention that I might be wrong and if I am maybe @jrperritt can correct me.

The FAQ has an entry about how to [implement logging and re-auth](https://github.com/gophercloud/gophercloud/blob/master/FAQ.md#implementing-default-logging-and-re-authentication-attempts). This should also work for adding a custom header. Searching for documentation about `RoundTripper` shows it can be used for adding auth headers, so I don't see why `X-Forwarded-For` can't also be added.

If you wanted to see a complete example of how to do this:

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L71-L126
* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/types.go#L28-L154

Most of it will not be applicable if you simply want to add an extra header, but it's a full example that is compatible with Gophercloud.

Another option is to create a custom HTTP request and using the `MoreHeaders` field. Search the gophercloud code for `MoreHeaders` and you'll see a few examples of how this is done. The FAQ entry about creating [custom objects](https://github.com/gophercloud/gophercloud/blob/master/FAQ.md#implementing-custom-objects) might be applicable here.

The [`swauth`](https://github.com/gophercloud/gophercloud/blob/master/openstack/objectstorage/v1/swauth) package might also be a good reference for how to create a simple Object Storage request with custom headers.

Out of all of the above, I think `RoundTripper` would be the best way to go.
