### ISSUE TITLE
Incomplete Identity v3 services API support

### ISSUE THREAD

**Issue by dklyle** [gophercloud/gophercloud#605]
- [x] Create (#610)
- [x] Update (#611)
- [x] List (#612)

Looking at https://developer.openstack.org/api-ref/identity/v3/#service-catalog-and-endpoints

The implementation for `Create` and `Update` services are incomplete in the options that are provided. 
The schema https://github.com/openstack/keystone/blob/master/keystone/catalog/backends/sql.py#L53
supports `id`, `type`, `enabled`, and `extra`. At a minimum, being able to set and update `enabled` is important. The API docs explicitly call out `description` and `name` as well.

Create currently supports setting `type` only
Update currently supports update `type` only.

I'm posting this to ask for suggestions on how to flesh out the rest. The methods `Create` and `Update` already exist and in order to keep backward compatibility we can't just change the method definition. 

Is the answer something as simple creating new methods with similar names?

This is common for a few APIs that have an older implementation. So just looking for a strategy to tackle them.

**Comment by jtopjian** [comment]
Thank you for pointing this out.

Regardless of the reason this happened (simple oversight, `type` being the only settable attribute at the time, etc), IMO, the best solution is to rewrite the function to use the standard `CreateOpts` and `UpdateOpts` pattern. This is a breaking change, but I think it's acceptable here. It should be a one-time thing and doing this will ensure future attributes can be supported without further breakage.

Gophercloud makes no guarantees about breaking changes. An example of a recently merged breaking change is https://github.com/gophercloud/gophercloud/pull/445. 

Of course, it's always best to avoid breaking changes, but it the best long-term solution involves breaking, so be it. The README warns about this and to make sure Gophercloud is vendored. Vendoring is a way to ensure the application can opt-in to this change when it's ready.

> The API docs explicitly call out description and name as well.

From looking a the schema, it seems these fields might be implicitly part of `Extra`?

**Comment by dklyle** [comment]
That's how I interpret it. Once I code it up, I will know for sure. But the python kwargs look like the mechanism `description` and `name` are passed through. Seems strange for keystone to call out optional `extra` fields specifically in the API docs, but that seems like what they've done.

**Comment by dklyle** [comment]
After testing and working on this, `description` and `name` are indeed stored in `extra`. Even more fun is that `name` is a supported filter which I tested and it works.

**Comment by jtopjian** [comment]
@dklyle Thank you for fixing this up :)
