### ISSUE TITLE
Fix openstack NewClient to not remove relative paths from IdentityBase

### ISSUE THREAD

**Issue by dlipovetsky** [gophercloud/gophercloud#609]
A [PR with the fix](https://github.com/rackspace/gophercloud/pull/582) for this was merged to rackspace's gophercloud fork in 06/2016, but the commit was not merged to this fork.

I use the Kubernetes OpenStack cloud provider, which uses this fork, and as a result I can't deploy Keystone at a relative URL.

I'd love to get some feedback on this. Thanks!

**Comment by jtopjian** [comment]
@dlipovetsky I believe #508 should have fixed this. Can you confirm if it's still not working? If it's not, can you provide the URL that is failing?

**Comment by dlipovetsky** [comment]
@jtopjian You are right. I cannot reproduce the issue with the changes in #508, but I can reproduce it at 2804b72,  the parent of the changes in #508. Thanks for pointing out the PR!

For others' reference, this issue is fixed in the Kubernetes OpenStack cloud provider in 1.9:
[Kubernetes 1.8 uses](https://github.com/kubernetes/kubernetes/blob/release-1.8/Godeps/Godeps.json#L1625) 2bf16b9, which does not have the changes from #508, but [1.9 uses](https://github.com/kubernetes/kubernetes/blob/release-1.9/Godeps/Godeps.json#L1560) 0b6b13c, which does.
