### ISSUE TITLE
network deletion fails with NetworkInUse, if it was recently used

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#61]
I set up networking for server, launch the server, kill the server after 10 seconds (this is for a test), and want to immediately delete the networking things as well, but it fails unless I sleep for another 10 seconds after deleting my server. How can I avoid this?

In outline (error checking removed), I create like this:

    externalNetworkId, err := networks.IDFromName(networkClient, poolName)
    //...
    network, err := networks.Create(networkClient, networks.CreateOpts{Name: resourceName, AdminStateUp: gophercloud.Enabled}).Extract()
    networkID = network.ID
    var gip = new(string)
    *gip = "192.168.0.1"
    subnet, err := subnets.Create(networkClient, subnets.CreateOpts{
        NetworkID: networkID,
        CIDR:      "192.168.0.0/16",
        GatewayIP: gip,
        IPVersion: 4,
        Name: subnetName,
    }).Extract()
    //...
    router, err := routers.Create(networkClient, routers.CreateOpts{
        Name:         resourceName,
        GatewayInfo:  &routers.GatewayInfo{NetworkID: externalNetworkId},
        AdminStateUp: gophercloud.Enabled,
    }).Extract()
    _, err = routers.AddInterface(networkClient, router.ID, routers.AddInterfaceOpts{SubnetID: subnet.ID}).Extract()
    //...
    server, err := servers.Create(client, keypairs.CreateOptsExt{
        servers.CreateOpts{
            Name:           resourceName,
            FlavorRef:      flavorId,
            ImageRef:       imageId,
            SecurityGroups: []string{resourceName},
            Networks:       []servers.Network{servers.Network{UUID: networkID}},
        },
        resourceName, // keypair name
    }).Extract()
    err = servers.WaitForStatus(client, server.ID, "ACTIVE", 60)
    //...
    allFloatingIPPages, err := floatingips.List(client).AllPages()
    allFloatingIPs, err := floatingips.ExtractFloatingIPs(allFloatingIPPages)
    var floatingIP string
	for _, fIP := range allFloatingIPs {
		if fIP.InstanceID == "" {
			floatingIP = fIP.IP
			break
		}
	}
	if floatingIP == "" {
		// create a new one
		fIP, err := floatingips.Create(client, floatingips.CreateOpts{
			Pool: poolName,
		}).Extract()
		floatingIP = fIP.IP
	}
    err = floatingips.AssociateInstance(client, server.ID, floatingips.AssociateOpts{
        FloatingIP: floatingIP,
    }).ExtractErr()

And I try to delete like this:

    <-time.After(10 * time.Second)
    err = floatingips.DisassociateInstance(client, server.ID, floatingips.DisassociateOpts{FloatingIP: floatingIP}).ExtractErr() // must explicitly do this first, or can't delete router
    err = servers.Delete(client, server.ID).ExtractErr()
    //...
    _, err = routers.RemoveInterface(networkClient, router.ID, routers.RemoveInterfaceOpts{SubnetID: subnet.ID}).Extract() // must do this or can't delete router
    err = routers.Delete(networkClient, router.ID).ExtractErr()
    // <-time.After(10 * time.Second) // this is required to make the following line work
    err = networks.Delete(networkClient, networkID).ExtractErr()

Without waiting a few seconds before trying to delete my network, I get:

> Expected HTTP response code [202 204] when accessing [DELETE http://172.31.0.18:9696/v2.0/networks/a2c5835d-f1e7-4def-9abe-d7e996caf24d], but got 409 instead
{"NeutronError": {"message": "Unable to complete operation on network a2c5835d-f1e7-4def-9abe-d7e996caf24d. There are one or more ports still in use on the network.", "type": "NetworkInUse", "detail": ""}}

If I try to explicitly delete my subnet first with:

    err = subnets.Delete(networkClient, subnet.ID).ExtractErr()

I instead get:

> Expected HTTP response code [202 204] when accessing [DELETE http://172.31.0.18:9696/v2.0/subnets/8ab18cac-add7-4328-9f29-0771111a6378], but got 409 instead
{"NeutronError": {"message": "Unable to complete operation on subnet 8ab18cac-add7-4328-9f29-0771111a6378. One or more ports have an IP allocation from this subnet.", "type": "SubnetInUse", "detail": ""}}

Firstly, is this the right approach to setting up to launch a server so you can ssh to it, and is the right way to tear everything down afterwards?

What do I need to delete or alter to let me cleanly delete my network without waiting for some arbitrary and unknown time?

**Comment by jrperritt** [comment]
It sounds like you're wanting to wait for certain events to happen before performing others; [this](https://github.com/gophercloud/gophercloud/blob/master/util.go#L15) can help with that. Something like the following pseudocode:

```
create server
wait for server status = "ACTIVE"
// defer will run the function before returning from current function
// defers are run in last in, first out order and syncronously (iirc)
defer func(){ delete server }()

create network
wait for network to be up
defer func(){ delete network }()

create subnet
wait for subnet to be up
defer func(){ delete subnet }()

...
```

**Comment by jtopjian** [comment]
> defers are run in last in, first out order and syncronously

Yes, so the order of the pseudocode would be:

```
create network
wait for status active
defer func(){ 
  delete network 
  wait for 404 / confirmation it's deleted
}

create subnet
wait for status active
defer func(){ delete subnet; wait for delete }

create server
wait for status active
defer func(){ delete server; wait for delete }

allocate fip
defer func(){ deallocate fip }
associate fip
defer func(){ disassociate fip }
```

A note about floating IPs specifically: I've found that when using the compute API to handle floating IPs, the create, delete, associate, and disassociate calls will be returned when the job is done - no need to wait for a certain status for some reason. This is not true if you use the Network API - you must check the state.

> It sounds like you're wanting to wait for certain events to happen before performing others; this can help with that.

+1

There's some example implementations of `WaitFor` [here](https://github.com/gophercloud/gophercloud/blob/master/acceptance/openstack/compute/v2/compute.go)

The API docs can be hit or miss with documenting the status/states of the different components. The various people who have worked on [Terraform](https://github.com/hashicorp/terraform/tree/master/builtin/providers/openstack) have done a great job aggregating and documenting them. For example, [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_networking_network_v2.go#L140-L147) and [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_networking_network_v2.go#L261-L292).

@jrperritt would more specific `WaitFor` helper functions be useful additions to the main code?

**Comment by sb10** [comment]
Can you give a specific example for my case? What exactly am I supposed to wait for before I can delete a network? If I must wait for the server to be deleted first, can I use servers.WaitForStatus(client, server.ID, "???", 60)? If so, what status string means "actually deleted"?

**Comment by jrperritt** [comment]
(@jtopjian )
> would more specific WaitFor helper functions be useful additions to the main code? 

I don't think so. It's easy enough to write a `WaitFor` closure.

(@sb10)
> If I must wait for the server to be deleted first, can I use servers.WaitForStatus(client, server.ID, "???", 60)? 

Yes

> Can you give a specific example for my case?

jtopjian gave you the exact logic to implement in his comment above.

> What exactly am I supposed to wait for before I can delete a network?
> If so, what status string means "actually deleted"?

You're no longer asking Gophercloud questions, but instead OpenStack questions. In addition to documentation and source code, there are OpenStack communication channels for questions like that (mailing lists/IRC/slack).

This issue was created in response to a delete operation failing, but, as far as I can tell, the cause of it failing is not a bug in this library.

**Comment by sb10** [comment]
In the end, it was indeed as simple as:

    err = servers.WaitForStatus(client, server.ID, "xxxx", 60)
    if err != nil && err == "Resource not found" { ... }

The key is to realise that, given a nonsense status, WaitForStatus() won't hit the timeout, but will return the "Resource not found" error as soon as the server has actually been deleted.

I'm not sure this behaviour is obvious from the documentation.
