### ISSUE TITLE
BuildQueryString does not build map type data structure

### ISSUE THREAD

**Issue by zengchen1024** [gophercloud/gophercloud#613]
For the codes at https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v2/volumes/requests.go#L85-L100. The value of 'r' in the following codes will be wrong.
opt := ListOpts{
    Metadata: map[string]string{"a":"b", }
    Name: "test"
}
r, _ := opt.ToVolumeListQuery()
r is "?name=test" , but the expect value is "?metadata=%7B%27a%27%3A%27b%27%7D&name=test". The reason is BuildQueryString does not build map type data like ListOpts.Metadata.

**Comment by TommyLike** [comment]
This looks like a valid issue. Does it exist in other commands? Cinder have other APIs that support key&value filters.

**Comment by jtopjian** [comment]
I apologize for the late reply. I looked into this the other night but forgot to follow up.

The fact that `BuildQueryString` does not support maps is indeed a valid problem. I'm not sure when I will have time to look into this, but if someone wanted to work on it, I would be happy to review.

It's also probably best to point out where in the Cinder API maps/hashes are supported for list operations and to show a few real URLs as examples.

**Comment by jtopjian** [comment]
Implemented in #619
