### ISSUE TITLE
Adding support for ipv6_address_mode and ipv6_ra_mode for a subnet

### ISSUE THREAD

**Issue by stone** [gophercloud/gophercloud#620]
I intend to make a PR with adds support for IPv6 Stateless Address Autoconfiguration (SLAAC), Stateful DHCPv6, and Stateless DHCPv6 for a subnet.  By adding the following fields (with links to openstack/neutron code)

-  [ipv6_ra_mode](https://github.com/openstack/neutron/blob/8e9959725eda4063a318b4ba6af1e3494cad9e35/neutron/objects/subnet.py#L190)
- [ipv6_address_mode](https://github.com/openstack/neutron/blob/8e9959725eda4063a318b4ba6af1e3494cad9e35/neutron/objects/subnet.py#L191)

Reference: terraform-providers/terraform-provider-openstack#160

**Comment by jtopjian** [comment]
Implemented in #660
