### ISSUE TITLE
Add support for availability_zone_hints to a network

### ISSUE THREAD

**Issue by stone** [gophercloud/gophercloud#621]
This will allow users to associate an availability zone with their resources so that the resources get high availability. Which is missing.

I intend to make a PR with adds support for setting availability_zone_hints to a network.
By adding the following fields (with links to openstack/neutron code)

- [availability_zone_hints](https://github.com/openstack/neutron/blob/8e9959725eda4063a318b4ba6af1e3494cad9e35/neutron/objects/network.py#L191)

Reference: terraform-providers/terraform-provider-openstack#160

**Comment by jtopjian** [comment]
Implemented in #662
