### ISSUE TITLE
Q. Releases, roadmap and documentation fo supported features and limitation

### ISSUE THREAD

**Issue by swapnilgm** [gophercloud/gophercloud#623]
Hi, 
I came to this branch from [rackspace/gophercloud](https://github.com/rackspace/gophercloud). There we already have a release. Do you have any plan and roadmap that when are you going to release this? What is current status of project using this as client library in production environment?

Since gophercloud sounds to more recommended go client for OpenStack, are there any plans to take this project as the official go-lang SDK for OpenStack?

Is there any documentation available about currently supported/stabilised features and limitations?

**Comment by jtopjian** [comment]
@swapnilgm I very much apologize for the late reply about this. One reason for the delay is that there are some current internal discussions about releases, but nothing has been finalized yet. 

In the meantime, you can use Gophercloud in combination with a Go vendor tool (such as the official `dep` or something like `govendor`) to pin your application to a specific commit.

> What is current status of project using this as client library in production environment?

It's very stable to use. Gophercloud is being used in applications like Kubernetes and Terraform to provide OpenStack support. 

> Since gophercloud sounds to more recommended go client for OpenStack, are there any plans to take this project as the official go-lang SDK for OpenStack?

I'm comfortable saying Gophercloud is the de-facto Go library for OpenStack. It has been recognized in different OpenStack developer conversations as the best choice. If your concern is longevity of the project and if there will be another library which will supersede Gophercloud, you're safe choosing Gophercloud.

> Is there any documentation available about currently supported/stabilised features and limitations?

We do not have a check-list or chart which shows features. The best place to see what is supported is in the [godoc](https://godoc.org/github.com/gophercloud/gophercloud) documentation.

Additionally, the list of [Terraform resources](https://www.terraform.io/docs/providers/openstack/index.html) available is also a good way to see what's currently possible (though there are a few other features in Gophercloud not listed there).

Again, I apologize for the late reply. Please let me know if you have any other questions.

**Comment by swapnilgm** [comment]
@jtopjian Thank you for the details.

Still, it would be really nice to see in future, the documented hints of roadmap and feature list, may be in the form of regularly updated change-log.
