### ISSUE TITLE
Compute v2: Flavor Result `is_public` is incorrect

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#625]
The current `flavors.Flavor` result has the [`IsPublic`](https://github.com/gophercloud/gophercloud/blob/89881f8ce3ec9fe2aa2a846716dd2315aba0ffb3/openstack/compute/v2/flavors/results.go#L68) field looking for the JSON field `is_public` when it should be `os-flavor-access:is_public`:

https://github.com/openstack/nova/blob/1878039f8fcf757651c7923910a253f187891576/nova/api/openstack/compute/views/flavors.py#L48-L89

**Comment by jrperritt** [comment]
closed by #626
