### ISSUE TITLE
Wrong status result in Resize function comment

### ISSUE THREAD

**Issue by obedmr** [gophercloud/gophercloud#629]
According to https://developer.openstack.org/api-guide/compute/server_concepts.html
Once resize is finished the status of an instance should be on ``VERIFY_RESIZE `` instead of ``RESIZE_VERIFY ``:
https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L518

**Comment by jrperritt** [comment]
closed by #630
