### ISSUE TITLE
Extend volume is unavailable

### ISSUE THREAD

**Issue by TommyLike** [gophercloud/gophercloud#632]
Extend volume action is missing both in blockstorage's V2&V3 APIs.

**Comment by j-griffith** [comment]
Thanks @TommyLike to be clear I don't think gophercloud should try and implement every Cinder feature.  Also, we should avoid anything that isn't clearly supported by all backend devices in my opinion.

Extend makes sense to add, but I also think it's important that we select things wisely and avoid having a ton of micro-versions to maintain and deal with here.

**Comment by jtopjian** [comment]
> Also, we should avoid anything that isn't clearly supported by all backend devices in my opinion.

This is a good point. While I don't want to make a firm decision here, I'm inclined to agree with this solely on the basis that we couldn't confidently test the implementation. It should be easy enough for a vendor to create a Gophercloud-compatible package that implements the third-party driver. 

> Extend makes sense to add, but I also think it's important that we select things wisely and avoid having a ton of micro-versions to maintain and deal with here.

Another good point. I haven't looked into these PRs in detail yet, but my (perhaps too lazy?) strategy was going to be: if it's available in v2, then it's also available in base v3 and shouldn't be an issue with microversions.

**Comment by jtopjian** [comment]
As mentioned in #633, this is already implemented:

https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/extensions/volumeactions/requests.go#L192-L223

And again, I apologize for not catching this sooner.
