### ISSUE TITLE
Compute v2: Add ability to attach, detach and show a port for the given server

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#641]
Nova's os-interface extension provides the ability to manage server's interfaces.
Currently the gophercloud can only be used for list server interfaces action via the **compute/v2/extensions/attachinterfaces** extension.

I intend to make several PRs that add support for the attach, detach and show actions for the os-interface.

Doc-reference: https://developer.openstack.org/api-ref/compute/#port-interfaces-servers-os-interface

Show code-reference:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/attach_interfaces.py#L75

Attach code-reference: https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/attach_interfaces.py#L104

Detach code-reference:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/attach_interfaces.py#L161

**Comment by jtopjian** [comment]
@ozerovandrei Thank you for submitting this work. I've left review comments on all three.

Overall, this is _really_ good work and is really appreciated - thank you very much :)

**Comment by jtopjian** [comment]
Thank you for adding support for this :)
