### ISSUE TITLE
Deadlock on reauth

### ISSUE THREAD

**Issue by mlowery** [gophercloud/gophercloud#645]
Perhaps introduced in #636, I think I'm seeing a deadlock. See [unit test](https://gist.github.com/mlowery/b44c5757485bcecffb9493804d3584e2) that demonstrates the issue (it never returns).

I think it's because during reauth, we're holding the [writer lock](https://github.com/gophercloud/gophercloud/blob/36c5f2c8d78de24fc1325f4b2044b46d4763cb42/provider_client.go#L242) but in `Request`, we ask for [`AuthenticatedHeaders()`](https://github.com/gophercloud/gophercloud/blob/36c5f2c8d78de24fc1325f4b2044b46d4763cb42/provider_client.go#L192) which attempts an `RLock`. This `RLock` during reauth is where it never returns for me.

As far as solutions, what is the reason to hold the write lock during reauth (instead of letting reauth func control it)? Is it because legacy reauth funcs don't know about the lock and you'd like to keep it that way?

During a reauth, why do we need authenticated headers anyway? Again, I assume this is because both reauth and every other request goes through common code.

During a write locked reauth, there is no need for a reader lock, but the code that performs the reauth is the generic `Request` and so cannot assume this right?

**Comment by jrperritt** [comment]
> I think I'm seeing a deadlock ... I think it's because during reauth, we're holding the writer lock but in Request, we ask for AuthenticatedHeaders() which attempts an RLock. This RLock during reauth is where it never returns for me.

Yep, that's exactly what it is.

> what is the reason to hold the write lock during reauth

This is all discussed in #636 . But yes, we don't want to expose the lock right now.

Thank you for reporting this. I've created a PR (#646) to address this.

**Comment by mlowery** [comment]
@jrperritt: In this [file](https://gist.github.com/mlowery/4d84dc0140c346c855ddc79be0e05cab), there are two tests. The first test shows a deadlock on a recursive reauth (by triggering the 401 to start a reauth then returning 401 from that reauth) with just `AllowReauths=true`. (In other words, the lock is already held in response to first 401 and another lock is attempted in response to the second 401 and there is no recursive/reentrant feature to the lock.) Now you can argue that it's my fault for not stopping the recursion. But I don't understand why the out-of-the-box reauth should itself allow a reauth in the first place.

The second test shows the same 401 setup but instead of setting `AllowReauths=true`, I set a `ReauthFunc`. This reauth func will never recurse. Why is this or something similar not the out-of-the-box reauth func? Another benefit is that the reauth func uses none of the mutexes in the "real" client. I think this could eliminate the need for the `reauthmut`. It also is a version-agnostic reauth func.

Perhaps the write lock/unlock responsibility can be given to `ReauthFunc`. If that would break existing users, then perhaps the entire thread-safety feature should be an explicit opt-in and that might free you to create a mechanism that doesn't conflict with historical behavior.

Thoughts?

**Comment by jrperritt** [comment]
I see. Trying to shim in concurrency in a backward-compatible hasn't gone well for me.

> Why is this or something similar not the out-of-the-box reauth func?

Because we actually _do_ intend to repeatedly retry the request by default. This behavior can (and is intended to) be modified by setting a custom `HTTPClient` in the `ProviderClient`. It's also in the [FAQ](https://github.com/gophercloud/gophercloud/blob/master/FAQ.md#implementing-default-logging-and-re-authentication-attempts).

> Perhaps the write lock/unlock responsibility can be given to ReauthFunc

Currently we can't get the functionality that's there now in a backward-compatible way (namely, only 1 goroutine reauthing when any number of goroutines need to reauth). But I do agree that ideally the [reauth] locking would happen in `ReauthFunc`, so this may be warranted. To accomplish that, we can change the type of `ReauthFunc` to be `func(*http.Request) error` and give it the unauthorized request.
To allow users to do their own locking, we could add a `UseTokenLockWith(*sync.RWMutex)` method to `ProviderClient` and set the `ProviderClient`'s mutex with the user-provided one. 

Does that sound reasonable (or even satisfactory)? If so, and you'd like to submit a PR for it, I'd be happy to review it. Otherwise I may be able to get to it this weekend.

**Comment by jrperritt** [comment]
> Why is this or something similar not the out-of-the-box reauth func?

Thinking about this some more, I think I misunderstood what you meant. Looking at your test more closely, I think using the throwaway client does seem more reasonable. If you'd like to send a change for implementing that, please go ahead.

**Comment by mlowery** [comment]
@jrperritt: First of all, thanks for this discussion and this library.

> repeatedly retry the request by default

For me, the recursion itself (or rather the possibility of infinite recursion) is the surprising part. In my usage of this library, I have a work queue with backoffs such that if the client returns any error at all, it will be put back into the queue with a backoff and retried at some point in the future. I think this is a choice between internal library retries vs. deferring to the user. I would have expected the following for a single client call: attempt1 (results in 401) -> reauth (let's assume 2xx) -> attempt2 (we stop here regardless of what happens).

> It's also in the FAQ.

I have referred to that FAQ many times to write my own `http.RoundTripper` and, while I appreciate all that this library does, that method of control has proven, for me at least, very crude (hard to get right). Among the problems I've personally had are:

* it is indiscriminate (401s from either the service or keystone will cause the counter to increase)
* it can't recover once exceeded max
* example itself isn't thread-safe
* depending on how it's implemented, you can either get `ErrUnableToReauthenticate` or `ErrErrorAfterReauthentication` and that inconsistency was unfortunate

But I think it all comes back to the recursion--the `http.RoundTripper` wouldn't be necessary if the recursion simply didn't happen.

> I think using the throwaway client does seem more reasonable

If I can confirm, you're saying that the throwaway client approach (which implements a reauth without the chance of recursion) can become the out-of-the-box, default `ReauthFunc` that you get just by setting `AllowReauths=true`? This would prevent the double-lock and also, it seems, an entire class of recursion problems.

It seems `Request` can recurse in either of two ways:

1. Calling `ReauthFunc` (which uses `Request` indirectly).
2. Calling `Request` after a reauth.

It seems that 1 above would be eliminated with a throwaway client (but wouldn't stop users' custom `ReauthFunc`s from doing the wrong thing).

Number 2 is what I was referring to above. Why can't the `Request` after reauth prevent both a subsequent `ReauthFunc` and `Request`? If you want to preserve your "repeatedly retry" behavior, what about just `reauth=false` and `recurse=false` flags?

But I also have to ask, when does retrying more than once yield a desirable result? In my experience, I only want to reauth on an expired token and everything else is some problem that requires a human (e.g. misconfiguration, expired password, etc). In other words, trying again will not yield success and just creates traffic for keystone.

Thoughts?

**Comment by jrperritt** [comment]
> If I can confirm, you're saying that the throwaway client approach (which implements a reauth without the chance of recursion) can become the out-of-the-box, default ReauthFunc that you get just by setting AllowReauths=true?

Yes, that's right. To be clear, I'm OK with removing any recursive HTTP calls where possible.

> when does retrying more than once yield a desirable result?

That's a fair point; I can imagine cases where it _could_ be desired (maybe waiting for an OpenStack environment to be properly setup), but I agree with you: for reauth, it's probably rarely what we want. Even in that contrived case, all that logic could be handled in application code.

**Comment by jrperritt** [comment]
@mlowery thank you for your help with this. Please let me know if you experience another re-authentication issue.

**Comment by mlowery** [comment]
@jrperritt: Thanks for the fixes! Coincidentally, I just got around to picking up the latest changes a few days ago. So reauth no longer recurses. Perfect.

However, we are using gophercloud as the client for a custom service that authenticates via keystone. Due to the misuse of the 401 code by this custom service (it's misusing it to mean forbidden instead of the correct 403 code), we can have the following loop occur:

service:401 -> keystone:200 -> service:401 -> repeat...

Ideally, gophercloud's design would never recurse--either on reauth or on the attempt-after-reauth. In other words, if reauth fails, it should return (as it does now). If the attempt-after-reauth fails, it should return (it recurses today).

To address this admittedly uncommon scenario, I have a custom ReauthFunc which returns an error if two consecutive reauths happen too close together.

Any thoughts on eliminating recursion completely?

**Comment by jrperritt** [comment]
That's probably something you'll have to handle in your app with a custom `http.Client` since the cause is app-specific. One option may be, within the custom `http.Client`, checking the request path and response code and then correcting the response code before sending the response back to Gophercloud.
