### ISSUE TITLE
Compute v2: Support OS-EXT-STS attributes

### ISSUE THREAD

**Issue by shiftky** [gophercloud/gophercloud#658]
Compute v2 API [/servers/detail](https://developer.openstack.org/api-ref/compute/#list-servers-detailed) supports the extended status information:

```
The extended status information appears in the OS-EXT-STS:vm_state,
OS-EXT-STS:power_state, and OS-EXT-STS:task_state attributes.
```

But currently gophercloud does not support these attributes.
I think these attributes could be useful.

**Comment by jtopjian** [comment]
Implemented in #659
