### ISSUE TITLE
TestNetworksProviderCRUD run failed

### ISSUE THREAD

**Issue by liu-sheng** [gophercloud/gophercloud#663]
When try to run the Acceptance tests of networking v2 extensions API, it raised an error, seems because the *provider.ExtractGet* function is undefined.

related logs:

$ go test -v -tags "fixtures acceptance" github.com/gophercloud/gophercloud/acceptance/openstack/networking/v2/extensions -list "Test"                         
acceptance/openstack/networking/v2/extensions/provider_test.go:29:21: undefined: provider.ExtractGet

**Comment by jtopjian** [comment]
Thank you for catching these. The network and port resources had some extension work done to them a while back and the acceptance tests were never modified to account for it.

**Comment by jrperritt** [comment]
@jtopjian Isn't the TOL testing intended to catch things like this?

**Comment by jtopjian** [comment]
Yes, but I believe only a selective set of tests are being run. The TOL team is probably looking at expanding the set and are catching issues like this.

**Comment by jrperritt** [comment]
> Yes, but I believe only a selective set of tests are being run

Ah, gotcha. Additionally, they may only be running the tests that have changed (or, better, the tests that use a package that's changed), which would be reasonable
