### ISSUE TITLE
build failed of TestShareTypeExtraSpecs test of shared file system v2 API

### ISSUE THREAD

**Issue by liu-sheng** [gophercloud/gophercloud#670]
A syntax error occurred when listing the tests of shared file system v2 API. see:

go test -v -tags "fixtures acceptance" ./acceptance/openstack/sharedfilesystems/v2  -list "Test"

acceptance/openstack/sharedfilesystems/v2/sharetypes_test.go:73:8: unknown field 'Specs' in struct literal of type sharetypes.SetExtraSpecsOpts

**Comment by jtopjian** [comment]
Fixed in #671
