### ISSUE TITLE
[Enhancement] Add support for subnet pools on OpenStack

### ISSUE THREAD

**Issue by louis-gounot** [gophercloud/gophercloud#672]
Hello,

Would it be posible to add subnet pools support for OpenStack networking.

Documentation is available here : 
- https://docs.openstack.org/neutron/pike/admin/config-subnet-pools.html (general presentation)
- https://developer.openstack.org/api-ref/network/v2/index.html#subnet-pools-extension-subnetpools (API spec)

It will also impact subnet management as subnet pool extension allows to create a subnet without providing a CIDR (we only provide a CIDR length or use the default length configured on subnet pool). So CIDR attribute from subnet will move from mandatory to exclusively mandatory with subnet-pool-id/prefixlength.

Regards,

Louis

**Comment by louis-gounot** [comment]
Main use case is for private clouds (on premise cloud) where addressing plan consistency is quite usefull.

Secondary use case is the use of "address scope" extension which allows direct connectivity between tenants without SNAT/FIP NAT when tenants are in the same address scope (a bit like VPC peering on AWS).

**Comment by jtopjian** [comment]
> Would it be posible to add subnet pools support for OpenStack networking.

This is certainly an applicable feature to add. If you would be interested in adding this, take a look at our [contributing guide](https://github.com/gophercloud/gophercloud/blob/master/.github/CONTRIBUTING.md). But if you aren't interested (which is fine), I'll leave this issue opened until the feature is added.

**Comment by ozerovandrei** [comment]
Hi.
I would like to take this issue.

Code references:
https://github.com/openstack/neutron/blob/stable/pike/neutron/db/db_base_plugin_v2.py#L707
https://github.com/openstack/neutron/blob/stable/pike/neutron/api/v2/attributes.py#L214
https://github.com/openstack/neutron/blob/stable/pike/neutron/ipam/subnet_alloc.py#L244

**Comment by jtopjian** [comment]
List has been implemented in #694. I will leave this issue open as a point of reference if someone wants to add Create, Update, and Delete.

**Comment by ozerovandrei** [comment]
@louis-gounot all API requests were implemented.

**Comment by jtopjian** [comment]
:tada: 

@ozerovandrei Thank you for your work on this :smile:
