### ISSUE TITLE
openstack/orchestration/v1/stacks unit tests are broken

### ISSUE THREAD

**Issue by nim-nim** [gophercloud/gophercloud#707]
+ echo 'Testing openstack/orchestration/v1/stacks…'
+ pushd /builddir/build/BUILD/gophercloud-fe4853e064e386919340e25c447d0fed6cd8c6ea/_build/src/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks
+ go test -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
--- FAIL: TestGetRRFileContents (0.00s)
	convenience.go:236: Failure in environment_test.go, line 184:at [resource_registry] expected "2015-04-30", but got map[string]interface {}{"My::WP::Server":"my_env.yaml", "resources":map[string]interface {}{"my_db_server":map[string]interface {}{"OS::DBInstance":"my_db.yaml"}}}
	convenience.go:236: Failure in environment_test.go, line 184:at  expected map[string]interface {}{"resource_registry":"2015-04-30", "My::WP::Server":"file:///builddir/build/BUILD/gophercloud-fe4853e064e386919340e25c447d0fed6cd8c6ea/_build/src/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/my_env.yaml", "resources":map[string]interface {}{"my_db_server":map[string]interface {}{"OS::DBInstance":"file:///builddir/build/BUILD/gophercloud-fe4853e064e386919340e25c447d0fed6cd8c6ea/_build/src/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/my_db.yaml"}}}, but got <nil>
	convenience.go:35: Failure in environment_test.go, line 184: The structures were different.
--- FAIL: TestTemplateParsing (0.00s)
	convenience.go:236: Failure in template_test.go, line 36:at [parameters][flavor][default] expected 4353, but got 4353
	convenience.go:35: Failure in template_test.go, line 36: The structures were different.
FAIL

**Comment by jtopjian** [comment]
Looks like `stacks` is now passing. Thank you @nim-nim and @ozerovandrei for reporting and fixing.

**Comment by nim-nim** [comment]
Works for me, thanks a lot!
