### ISSUE TITLE
IDFromName functions cause unnecessary traffic

### ISSUE THREAD

**Issue by boyvinall** [gophercloud/gophercloud#711]
Looks like all the `IDFromName()` functions are not using that name in the list request.  This means you can end up pulling down way more pages of results than you actually need. 

In all cases, the fix is just changing this:

	pages, err := List(client, nil).AllPages()
	if err != nil {
		return "", err
	}

to this:

	pages, err := List(client, ListOpts{Name: name}).AllPages()
	if err != nil {
		return "", err
	}

For one example, see the [servers](https://github.com/gophercloud/gophercloud/blob/b2bf8a613b41baa2a8b56a6a8483321a84520dfa/openstack/compute/v2/servers/requests.go#L759) source.

The one example where this doesn't seem to work is the flavors API, which seemingly [doesn't support](https://developer.openstack.org/api-ref/compute/#list-flavors) filtering by name.

**Comment by boyvinall** [comment]
As per the [styleguide](../blob/master/STYLEGUIDE.md), I'll submit a PR once there's a comment here.  😄

**Comment by jtopjian** [comment]
@boyvinall Thanks for looking into this.

It might be worthwhile to purge these functions from this repo and move them to the https://github.com/gophercloud/utils repo. If you'd like to re-implement them over there, we can remove them from this repo once that's done.

The directory structure should match this repo (at least to start), for example `openstack/compute/v2/servers/requests.go`.

Let me know if you have any questions.

**Comment by boyvinall** [comment]
@jtopjian Happy to do that if that's the general consensus, but I'm not sure I see the need to move them into that repo, and it will cause breaking change for (I'm guessing) quite a few people. 

After a night's sleep, is it still your suggestion to move these functions out?

**Comment by jtopjian** [comment]
Yes, I still believe we should move these functions out of this repo. These functions are purely convenience/utility functions and have no part in the core functionality of Gophercloud.

Gophercloud makes no guarantees about backwards compatibility. If users are correctly vendoring their dependencies, then moving these functions won't have a dangerous impact on compatibility.

**Comment by jtopjian** [comment]
@boyvinall I've gone ahead and made the changes to the functions in this repository. However, at some point, these functions will be removed from this repository.

**Comment by boyvinall** [comment]
@jtopjian thanks, sorry for dragging my feet so long on this. I had meant to get back to it but somehow not quite found the time yet.  Not forgotten, maybe someday soon you might get the PR you actually wanted. 🙂
