### ISSUE TITLE
Compute v2: Show Hypervisor Statistics

### ISSUE THREAD

**Issue by dstdfx** [gophercloud/gophercloud#719]
Compute v2 Nova's os-hypervisors extension provides the ability show summary statistics for all enabled hypervisors over all compute nodes. 

API doc:
- [https://developer.openstack.org/api-ref/compute/#show-hypervisor-statistics](https://developer.openstack.org/api-ref/compute/#show-hypervisor-statistics)

Source code:

- [https://github.com/openstack/nova/blob/e66fc365c84497a19bab4a3bc06ac02e1461f9d7/nova/api/openstack/compute/hypervisors.py#L404](https://github.com/openstack/nova/blob/e66fc365c84497a19bab4a3bc06ac02e1461f9d7/nova/api/openstack/compute/hypervisors.py#L404)

I'm ready to sent a PR.

**Comment by jtopjian** [comment]
Implemented in #720
