### ISSUE TITLE
Compute v2: Hypervisors API

### ISSUE THREAD

**Issue by dstdfx** [gophercloud/gophercloud#721]
I haven't found the following parts of Hypervisors API at Gophercloud: 

- https://developer.openstack.org/api-ref/compute/#show-hypervisor-details 
- https://developer.openstack.org/api-ref/compute/#show-hypervisor-uptime

I'm ready to send few PRs.

**Comment by jtopjian** [comment]
:tada: 

Thank you for your work on this :)
