### ISSUE TITLE
Compute v2: Host aggregates API 

### ISSUE THREAD

**Issue by dstdfx** [gophercloud/gophercloud#738]
I haven't found the following parts of Host aggregates API at Gophercloud:

- [x] [Create Aggregate ](https://developer.openstack.org/api-ref/compute/#create-aggregate)
- [x] [Delete Aggregate](https://developer.openstack.org/api-ref/compute/#delete-aggregate)
- [x] [Show Aggregate Details](https://developer.openstack.org/api-ref/compute/#show-aggregate-details)
- [x] [Update Aggregate](https://developer.openstack.org/api-ref/compute/#update-aggregate)
- [x] [Add Host](https://developer.openstack.org/api-ref/compute/#add-host)
- [x] [Remove Host](https://developer.openstack.org/api-ref/compute/#remove-host)
- [x] [Create Or Update Aggregate Metadata](https://developer.openstack.org/api-ref/compute/#create-or-update-aggregate-metadata)

I'm gonna work on it

**Comment by jtopjian** [comment]
🎉 

@dstdfx Thank you for working on this :)
