### ISSUE TITLE
token renewal should be thread-safe by default

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#741]
#636 added API for enabling thread-safe token renewals, but since it's not on by default, nobody is going to use it. There is a tiny added cost to always guarding all token accesses with mutexes, but I think it's worth the cost of avoiding duplicate token renewals.

**Comment by jrperritt** [comment]
> nobody is going to use it.

It's used by default if `gophercloud.NewClient` is called, which is called from any library function that creates a provider client. In fact, I think the only way to _not_ use it by default is by creating a provider client via 
```go 
var pc gophercloud.ProviderClient
```
which almost no one does. Maybe I'm missing something?

**Comment by majewsky** [comment]
Ah sorry, since `UseTokenLock` is public, I assumed that it was meant to be used by the library user, but afaics it's only public to cross package boundaries inside Gophercloud. In light of that, I withdraw my criticism.
