### ISSUE TITLE
use interfaces for errors

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/gophercloud#76]
Instead of exporting custom error types, I think it'd be better to not export them, and instead have them implement an interface (e.g. `InvalidInput`, `MissingInput`).

Needs more thought.

**Comment by chaosaffe** [comment]
Interfaces are used to ensure common functionality. Unless you intend to implement specific functionality on `InvalidInput` and `MissingInput` then they would match the `error` interface as well as any other interface that has the same functionality. There is no way to declare that a struct belongs to a specific interface, you can only implement the functionality required by the interface. So your options are to add frivolous functionality to match the interface, or use the `error` interface and have it match `error`, `InvalidInput` and `MissingInput` interfaces, negating the idea of separating them. 

In golang the common practice (see the core and `x` packages for reference) to export custom error types to allow users to do appropriate error checking and handling.

**Comment by pierreprinetti** [comment]
Error handling has slightly improved in v2. I don't think we're there yet though, and I would invite you to formulate a use-case you'd want Gophercloud to handle more ergonomically. I'll go ahead and close this, please open a new issue with a case if you are still interested.
