### ISSUE TITLE
UseTokenLock is not thread-safe

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#778]
Title says it all. When a ProviderClient or ServiceClient is passed into a library or other piece of code that requires thread-safe token renewal, that code cannot speculatively call `UseTokenLock` because of the missing threadsafeness.

Possible solutions:

- Make it thread-safe.
- Make it idempotent (which makes it thread-safe for the purpose of the usecase discussed above.)
- Just get rid of it; it has no reason at all to exist. In concurrent usecases, you absolutely need it. In single-threaded usecases, the overhead of locking a mutex that only one goroutine uses is absolutely negligible.

**Comment by jtopjian** [comment]
@majewsky The recent changes to reauth locking have indeed raised some questions. Unfortunately they're out of my comfort area to try to fix.

I believe @jrperritt has been busy away from Gophercloud, but we'll get this addressed as soon as possible.

I realize this update isn't very helpful but I wanted to at least let you know it's not being silently ignored.

**Comment by majewsky** [comment]
Thanks, that's much appreciated.

**Comment by jrperritt** [comment]
I agree that we should get rid of it. 

@majewsky I'd also like to understand your issue better. Do you have a repro that causes the race?

**Comment by majewsky** [comment]
Ah sorry, since `UseTokenLock` is public, I assumed that it was meant to be used by the library user, but afaics it's only public to cross package boundaries inside Gophercloud. In light of that, I withdraw my criticism.
