### ISSUE TITLE
Image Service v2: Add Missing Fields to ListOpts

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#779]
Following-up on an old Terraform feature request, there are a few fields missing from ListOpts:

1. It's possible to list by `container_format` and `disk_format`:

https://github.com/openstack/glance/blob/05e9bdb656d9c120ed3cd6ffc8ae7dbf5614b5e4/glance/db/simple/api.py#L324-L325

2. `Tag` should actually be `Tags` as multiple tags are allowed:

https://github.com/openstack/glance/blob/05e9bdb656d9c120ed3cd6ffc8ae7dbf5614b5e4/glance/db/simple/api.py#L340

https://developer.openstack.org/api-ref/image/v2/index.html#images

> To filter using image tags, use the filter tag (note the singular). To filter on multiple tags, include each tag separately in the query. For example, to find images with the tag ready, include tag=ready in your query string. To find images tagged with ready and approved, include tag=ready&tag=approved in your query string. (Note that only images containing both tags will be included in the response.)

3. It's possible to search by `created_at` and `updated_at`, but they can also have filter operations applied to them:

See "Time Comparison Filters" here: https://developer.openstack.org/api-ref/image/v2/index.html#images

https://github.com/openstack/glance/blob/9eddf85d8ab457d2eabb21597bd3e5b8d33f0086/glance/common/utils.py#L696-L723

https://github.com/openstack/glance/blob/05e9bdb656d9c120ed3cd6ffc8ae7dbf5614b5e4/glance/db/simple/api.py#L317-L323

**Comment by jrperritt** [comment]
closed by #780
