### ISSUE TITLE
Networking v2: Fix up subnetpools

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#788]
During implementation of https://github.com/terraform-providers/terraform-provider-openstack/pull/243, we discovered that it is not possible to query by Prefixes.

The fields which Neutron allows for listing is dynamic, based on the fields of the resource itself. I guess a limitation of this is fields which are arrays.

Doing further testing, I found that it is also not possible to list by `created_at` or `updated_at`.

And in reviewing the code, I found a few other areas I missed during the original code review:

* The `bool` fields in `ListOpts` need to be `*bool` to allow values of `false` to be sent.
* The result struct's `CreatedAt` and `UpdatedAt` need converted to `time.Time`. This is probably the first occurrence I've seen where the timestamp doesn't need a special conversion.

**Comment by jrperritt** [comment]
closed by #789
