### ISSUE TITLE
Network v2: ProjectID/TenantID Support

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#790]
In the past few PRs, I began questioning the use of TenantID when both TenantID and ProjectID were bundled, favoring ProjectID. However, that's not entirely correct.

We ran into an issue today at `$work` with the Python SDK where we were unable to create a network on behalf of another tenant/project. The cause is a bug in the Python SDK which incorrectly strips `tenant_id` from the network request body. We're running Mitaka which doesn't support `project_id`. The Python SDK will only accept `project_id` for the network resource but supports `tenant_id` for everything else (subnet, port, etc). Manually patching the SDK fixed this problem.

According to the API docs (https://developer.openstack.org/api-ref/network/v2/#tenant-and-project-attributes-in-requests), `project_id` was introduced in Newton and `tenant_id` is supported for backwards compatibility. So this means that, within the Neutron v2 API, the dev _must_ use `TenantID` on anything earlier than Newton and can _optionally_ use `ProjectID` on anything later. Hopefully `TenantID` sticks around for the entirety of the Neutron v2 API lifecycle.

The docs say that `project_id` is enabled by way of an extension.

Upon review of the Gophercloud networking packages, I found that all of them support `TenantID`. The only package that doesn't is `ListOpts` for `rbacpolicies` which is because I requested it to be removed. There's a good amount of irony in that recent decision and running into the above-mentioned bug at `$work`.

There are a handful of packages which already support both Project and Tenant in their Results.

There are a few ways of going about this:

1. Re-add `TenantID` to `rbacpolicies`'s `ListOpts` and do nothing else. This is the easy way to go, but creates inconsistency within Gophercloud for prior work (for the handful of packages which have both in their results).
2. Do 1 and also remove `ProjectID` where it's defined. This has merit because it creates a standard, but may not be future-proof and we'll have to make sure ProjectID is not included in future PRs.
3. Support both `TenantID` and `ProjectID` for the networking resources' List, Create, and Results. Oddly enough, LBaaSv2 does _not_ send `project_id` in its results. It's the only service within gophercloud which doesn't. I have a patch which does for all existing networking packages and has been tested (which is how I discovered the LBaaSv2 behavior).
4. Create extensions for all resources to support `ProjectID` in their list, create, and results. I'm _very_ loathe to do this.

Going forward, we'll need to verify if either one of ProjectID, TenantID, or both are supported for List, Create, and Results. This would be quite tedious to do for acceptance tests (you would have to run the test as admin, create a dummy project, create resources under that project, list them, and verify they were created as the user). It's possible to create such a test, but I would totally understand if someone didn't want to submit it in their PR. Therefore, ensuring the PR contains real test fixtures (and not API references) is probably the most practical way to go.

Thoughts?

_edit_: clarified use of "network resource" and "networking resources"

**Comment by dklyle** [comment]
I'd be very hesitant to remove project_id where supported. That is the preferred terminology and neutron took the effort to support the transition from tenant_id to project_id https://specs.openstack.org/openstack/neutron-specs/specs/newton/moving-to-keystone-v3.html  Unfortunately, LBaaSv2 is not part of neutron proper and thus has not followed the same conventions. I would prefer option 3. And leave LBaaSv2 as an odd duck.

**Comment by jtopjian** [comment]
@dklyle Thanks for that link - it's very helpful! From reading the technical implementation, `project_id` is a synonym/alias for `tenant_id`. While an extension would work, `project_id` is more of a first-class attribute within Neutron and so it should be alongside the resources.

It sounds like Option 3 is definitely the right way to go.

**Comment by jrperritt** [comment]
closed by #801
