### ISSUE TITLE
Fields removed from Service struct

### ISSUE THREAD

**Issue by gimmeshelter** [gophercloud/gophercloud#795]
In commit b47265a60452b8c6b31422c18482bcddc9ffc89e by @dklyle, the `Name` and `Description` fields were removed from the `Service` struct.  Reviewing the documentation for the [Identity V3 API](https://developer.openstack.org/api-ref/identity/v3/index.html#service-catalog-and-endpoints), these fields are still present in the response from the API.  Is there an explanation for why they were dropped?

**Comment by dklyle** [comment]
They were not dropped. I changed the way they were supported to more accurately match the API. While those fields are named in the API docs, they are not specifically stored in the backing for `Service`. For more details around the motivation for these changes see https://github.com/gophercloud/gophercloud/pull/610

The change also allows for more consistency between GET and POST operations.

The way to specify `Name` and `Description` is as follows. https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/services/doc.go#L29
The result of a get or list will also have the `description` and `name` in the extras map.

While I find it extremely odd that the API doc specifies fields not specifically stored in the backing, I thought the consistency was more valuable.

**Comment by gimmeshelter** [comment]
Thank you for that info, David (@dklyle).
