### ISSUE TITLE
sequence of port create calls with 10 sec delay in between failing with "connection reset by peer"

### ISSUE THREAD

**Issue by koteswar16** [gophercloud/gophercloud#814]
I am calling portsbinding.Create(client, portBindingOptions).Extract() sequentially from k8s pod to openstack neutron running remotely. If the delay between 2 calls is 60sec they all ports are getting created but if i reduce to 20 sec, few ports are NOT getting created with the following error "ERROR: Post https://xyz/neutron/v2.0/ports: read tcp 10.0.3.181:43380->10.201.109.131:3128: read: connection reset by peer"

Is there any scale limitation for gophercloud? how to solve this scale issue?
-Koteswar

**Comment by jrperritt** [comment]
I agree with @jtopjian ; this seems like a problem elsewhere. Feel free to comment if you think otherwise and can provide more information (or a repro).
