### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by stgleb** [gophercloud/gophercloud#82]
Is there currently ability to migrate server using gophercloud?

**Comment by jrperritt** [comment]
Not that I know of

**Comment by jtopjian** [comment]
@stgleb Sorry for the delay with this.

It looks like this can be implemented just like how [`ForceDelete`](https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L283) is implemented. The way both are implemented in the API server is functionally the same, too:

* https://github.com/openstack/nova/blob/77b11a9e31e265c338857326418bfe8cd135c1f8/nova/api/openstack/compute/migrate_server.py
* https://github.com/openstack/nova/blob/77b11a9e31e265c338857326418bfe8cd135c1f8/nova/api/openstack/compute/deferred_delete.py

Unless you know of a reason why the options should be extended? Do you know of a deployed OpenStack that has extended the migrate action?

Let me know if you'd like to continue working on this one. If not, I'm happy to take it over.

**Comment by jrperritt** [comment]
closed by #444
