### ISSUE TITLE
Docs: Contributor Tutorial

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#837]
While we have our CONTRIBUTING and STYLE guides, I wanted to try a different approach to documenting the contribution process.

I've written up a detailed contributor's tutorial here:

https://github.com/jtopjian/gophercloud/tree/docs-tutorial/docs/contributor-tutorial

If this looks like it's useful, I'll submit a PR.

note: the first few commits of that branch are re-arranging some of the docs into a `docs` directory to avoid doc sprawl.

**Comment by lingxiankong** [comment]
hi, @jtopjian thanks for writing the so amazing doc, it's helpful for me.

BTW, how does gophercloud team communicate with each other besides the github, do you use slack or irc to online chatting?

**Comment by jtopjian** [comment]
Awesome - I'm glad it was helpful :)

> BTW, how does gophercloud team communicate with each other besides the github, do you use slack or irc to online chatting?

Communication is all done through Github. We all work on Gophercloud in our spare time so a real-time tool like IRC or Slack wouldn't work very well. This is the main reason we have a defined process in place for contributing code - it helps make it easier for us to review and merge items quickly.

**Comment by lingxiankong** [comment]
Fair enough, thanks for your time for review :-)

**Comment by jrperritt** [comment]
closed by #845
