### ISSUE TITLE
Identity V3: add user to group

### ISSUE THREAD

**Issue by zhangzujian** [gophercloud/gophercloud#866]
API reference:
[Identity API v3 - Add user to group](https://developer.openstack.org/api-ref/identity/v3/#add-user-to-group)

Python source code:
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/routers.py#L49
https://github.com/openstack/keystone/blob/a6adc72e3e7ff4ff0bff0702e69ebd8f697d6261/keystone/identity/core.py#L1248
https://github.com/openstack/python-keystoneclient/blob/40642d597deecce4dd81428449353bbd0c2ad5be/keystoneclient/v3/users.py#L228

**Comment by jtopjian** [comment]
Implemented in #867
