### ISSUE TITLE
LBaaS doesn't return vip_port_id

### ISSUE THREAD

**Issue by vmtyler** [gophercloud/gophercloud#9]
The LBaaSv2 code returns all the loadbalancer details, including vip_subnet_id and vip_address, but doesn't return vip_port_id.  When creating a loadbalancer, neutron only applies the default security group. If you wish to expose a loadbalancer externally through a floating ip, you'll want to attach another security group which is applied to the vip_port. As of right now, the workaround is the port is named ```loadbalancer-<loadbalancer_id>``` so you can get the id and then work the port that way, but it would be much cleaner to return the vip_port_id when querying a loadbalancer.

**Comment by dagnello** [comment]
hello @vmtyler,

I have submitted a PR for this issue last week:
https://github.com/rackspace/gophercloud/pull/606

This change will have to be pulled into this repo once it is ready.

**Comment by vmtyler** [comment]
Awesome. Did you see my comment on the Kubernetes driver? 
upon creation of the LB, I'd like it to take this vip_port_id and apply a security group to it (supplied by the config file). The proper behavior of LBaaS should allow you to supply a sec group upon creation, but currently it just applies the default sec group to the port only  (https://bugs.launchpad.net/neutron/+bug/1295424).

**Comment by dagnello** [comment]
I haven't seen your comment, I raised the following issue in Kubernetes wrt missing the port id:  https://github.com/kubernetes/kubernetes/issues/28790
can you send me a link to the security group feature?

**Comment by vmtyler** [comment]
I had noted here https://github.com/kubernetes/kubernetes/pull/25987 - I'll add more detail there.

**Comment by jrperritt** [comment]
closed by #20
