### ISSUE TITLE
Cinder Backup

### ISSUE THREAD

**Issue by egrh3** [gophercloud/gophercloud#903]
It looks like `gophercloud` doesn't support `cinder-backup`? Is it on your roadmap?

**Comment by jtopjian** [comment]
@egrh3 Do you mean the backup API actions?

https://developer.openstack.org/api-ref/block-storage/v3/index.html#backups-backups

I don't think anyone is actively working on it at the moment. You're more than welcome to work on it if you'd like. Or else I can mark this issue as "Help Wanted" for anyone else to.

**Comment by egrh3** [comment]
Yes. Sorry, I could have made my initial question more explicit by referencing what I was asking for.

I may not have the time available to assist with this. I don't in the short-term ( next couple of weeks ). If you can tag this is "help wanted", that'd be great. I'll know more when I'm done with my current list of work / tasks.

**Comment by jtopjian** [comment]
Sure, sounds good. There's no obligation at all.

**Comment by jtopjian** [comment]
Implemented in #960 and #1552
