### ISSUE TITLE
Invalid required tags

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#910]
While poking around test coverage, I spotted two places where the "required" tag is used incorrectly. Both occurrences are with header opts. No query opts are being used incorrectly (or at all, for that matter).

**Comment by jrperritt** [comment]
Reposting from the PR to here (which is probably the more correct place for discussion):

I'm fine with either being the format. The `tag,required` is more in agreement with the `json` package (and probably looks better), but then either the `required` label is position-dependent or you iterate over the comma-split slice looking for "required".

**Comment by jtopjian** [comment]
IMO, I'm leaning on the non-comma required field for two reasons:

1. It's more commonly used right now so it'll be a larger change than the opposite.
2. It's more apparent that it's a tag specific go Gophercloud.

**Comment by jrperritt** [comment]
Sounds good

**Comment by jrperritt** [comment]
closed by #913
