### ISSUE TITLE
Networking v2: Subnet CIDR is not a required field

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#931]
As reported in https://github.com/terraform-providers/terraform-provider-openstack/issues/282, specifying a CIDR is optional when using subnet pools:

https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/subnets/requests.go#L83

**Comment by jrperritt** [comment]
closed by #940

**Comment by jrperritt** [comment]
really closed by #943
