### ISSUE TITLE
Sometimes No ImageRef is OK

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#94]
Currently, server creation will [fail](https://github.com/gophercloud/gophercloud/blob/37b56e8781b116e76a7818251674c63a30d5dd63/openstack/compute/v2/servers/requests.go#L222) if neither `ImageRef` and `ImageName` are provided, but sometimes it's OK for the `ImageRef` to be empty. Notably when [booting from a volume](https://github.com/openstack/nova/blob/9d9212c2a696950045301328a58e06d029926c3b/nova/api/openstack/compute/servers.py#L936).

What's the best way to modify the `ToServerCreateMap` to account for this? Does `opts` have access to `BlockDevice` (or `block_device_mapping`) inside `servers.ToServerCreateMap`?

If it doesn't, is the next option to modify the check for `ImageRef` and `ImageName` to not fail when neither are provided?

**Comment by jrperritt** [comment]
This is a good example of why errors should be exported but internal-only.

> Does opts have access to BlockDevice (or block_device_mapping) inside servers.ToServerCreateMap?

No, but it's in `bfv.ToServerCreateMap` where this should be handled. It would entail type-asserting a non-nil error returned from `servers.ToServerCreateMap` to see if it was the "NoImageNameOrID" error and, if so, ignoring it.

**Comment by jtopjian** [comment]
> No, but it's in bfv.ToServerCreateMap where this should be handled. It would entail type-asserting a non-nil error returned from servers.ToServerCreateMap to see if it was the "NoImageNameOrID" error and, if so, ignoring it.

Ahh - I see. Clever.  I'll see if I can get this in place and submit a PR.

Thanks!

**Comment by jrperritt** [comment]
closed by #97
