### ISSUE TITLE
Orchestration docs

### ISSUE THREAD

**Issue by etegan** [gophercloud/gophercloud#949]
I'm having a really hard time finding any documentation on the orchestration/v1 packages at [godoc](https://godoc.org/github.com/gophercloud/gophercloud). Am I missing something trivial? Thanks for a great product!

**Comment by jtopjian** [comment]
Nope, you're not missing anything. Unfortunately the orchestration packages get the least amount of attention. It's nothing against Heat/Orchestration, which is a great service, it's more that they aren't regularly used by frequent Gophercloud contributors.

I'll mark this as "Help Wanted" to flag that we'd like to see this improved.

**Comment by ricolin** [comment]
I will help to on this ASAP

**Comment by jtopjian** [comment]
Fixed in #1221

**Comment by jtopjian** [comment]
@hellt Sometimes you need to directly visit a package on godoc.org before it appears in the main index page.

For example, orchestration was not listed on the index page (https://godoc.org/github.com/gophercloud/gophercloud) a few minutes ago, but I directly went to https://godoc.org/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks (by building the URL myself) and now it appears on the index page.

**Comment by hellt** [comment]
thanks @jtopjian !
