### ISSUE TITLE
Is there a way to debug by printing all api calls?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#95]
I'm having a problem where if I create a network and a server on that network, I can't ssh to the server for over 5 (sometimes 30) minutes. If the network has been up for long enough, ssh'ing to new servers works in < 1 minute as expected.

If I create the network with seemingly the same settings using the python 'openstack' command line tool, however, I have no problems with new networks.

So I'm trying to debug if this is a gophercloud-specific issue.

Is there a way to print out all the api calls that gophercloud makes (like a debug switch I can turn on somewhere), and if not, which places in which files can I temporarily hack to ensure I capture all outgoing api requests?

**Comment by jtopjian** [comment]
Hi there,

There isn't a built-in way, but it's possible to make some changes to the `http.Client`. Take a look here for more information:

https://github.com/rackspace/gophercloud/pull/601
