### ISSUE TITLE
SecGroupRule.PortRangeMin/Max unmarshaling error when server provides string value

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#958]
I have code like this:

```go
import "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups"

result, err := groups.Create(c, groups.CreateOpts{
	Name:        "foo",
	Description: "bar",
}).Extract()
```

This emits a `POST $neutron_endpoint/v2.0/security-groups` with request body

```js
{ "security_group": { "name": "foo", "description": "bar" } }
```

and my Neutron (Mitaka) answers with 201 and the following response body:

```js
{
    "security_group": {
        "description": "bar",
        "id": "16a92d14-2cc6-40e2-8db3-ff2ffec2e1dd",
        "name": "foo",
        "security_group_rules": [
            {
                "description": "",
                "direction": "egress",
                "ethertype": "IPv4",
                "id": "3224102d-3a07-41c3-a1af-a5383cc158ca",
                "port_range_max": null,
                "port_range_min": null,
                "protocol": null,
                "remote_group_id": null,
                "remote_ip_prefix": null,
                "security_group_id": "16a92d14-2cc6-40e2-8db3-ff2ffec2e1dd",
                "tenant_id": "e9141fb24eee4b3e9f25ae69cda31132"
            },
            {
                "description": "",
                "direction": "egress",
                "ethertype": "IPv6",
                "id": "35668718-6915-4403-8969-1fc93997127b",
                "port_range_max": null,
                "port_range_min": null,
                "protocol": null,
                "remote_group_id": null,
                "remote_ip_prefix": null,
                "security_group_id": "16a92d14-2cc6-40e2-8db3-ff2ffec2e1dd",
                "tenant_id": "e9141fb24eee4b3e9f25ae69cda31132"
            },
            {
                "direction": "both",
                "port_range_max": "bootpc",
                "port_range_min": "bootps",
                "protocol": "dhcp",
                "remote_group_id": null,
                "remote_ip_prefix": null
            }
        ],
        "tenant_id": "e9141fb24eee4b3e9f25ae69cda31132"
    }
}
```

This causes an error because Gophercloud expects the "port_range_min/max" attributes to always be integers, not strings:

```go
err.Error() == "json: cannot unmarshal string into Go struct field SecGroupRule.port_range_max of type int"
```

**Comment by jtopjian** [comment]
@majewsky Do you know what security group driver the cloud is using? I'm unable to find the word `bootps` in https://github.com/openstack/neutron or https://github.com/openstack/neutron-lib. As well, I checked a Mitaka cloud that I have access to and still no results for `bootps` nor am I seeing the same behavior.

Maybe it's custom middleware for security group creation or a third-party security group driver?

**Comment by majewsky** [comment]
> Do you know what security group driver the cloud is using?

@abattye Can you answer that for Converged Cloud?

**Comment by majewsky** [comment]
The culprit is our Arista driver: https://github.com/sapcc/networking-arista/blame/9221b2635f87ca45dae3610c4f5ccfa7c5fe95dd/networking_arista/ml2/arista_sec_gp.py#L515 - It's breaking the API contract and thus breaking a lot of other clients, too, so we'll develop a fix on our side. Sorry for the noise.

**Comment by jtopjian** [comment]
No problem at all! This is a common occurrence with Terraform. I'll add Arista to my list of known vendors that do weird things 😄 

Thanks for following-up.
