### ISSUE TITLE
Support for Keystone Federation

### ISSUE THREAD

**Issue by dims** [gophercloud/gophercloud#966]
Ran into this at https://massopen.cloud/ They have setup Keystone federation with Github and other providers 

- https://kaizen.massopen.cloud/dashboard/auth/login/?next=/dashboard/
- https://osticket.massopen.cloud/kb/faq.php?id=16
- https://docs.openstack.org/keystoneauth/latest/plugin-options.html#v3oidcpassword

Looks like all the magic is done in the python client side. So we will have to emulate what's being done there:
http://git.openstack.org/cgit/openstack/keystoneauth/tree/keystoneauth1/identity/v3/oidc.py

**Comment by dims** [comment]
cc @fedosin @flaper87

**Comment by kayrus** [comment]
@dims could you please clarify why this feature request was closed? Is it implemented somewhere?

**Comment by dims** [comment]
@kayrus i opened this request a while ago. I no longer plan to chase this :)
