### ISSUE TITLE
Identity V3: Incorrect Fields of Struct endpoints.ListOpts

### ISSUE THREAD

**Issue by zhangzujian** [gophercloud/gophercloud#975]
According to the Python source code of Keystone, the filter *page* and *per_page* are no longer supported while a new one(*region_id*) is added.

https://github.com/openstack/keystone/blob/master/keystone/catalog/controllers.py#L200
https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/v3/endpoints.py#L97

**Comment by jtopjian** [comment]
Fixed in #977
