### ISSUE TITLE
Error 400 while disassociating floating IP

### ISSUE THREAD

**Issue by jccomputing** [gophercloud/gophercloud#99]
When disassociating a floating IP from a Neutron port, I receive a 400 error: "Invalid request due to incorrect syntax or missing required parameters."

``` go
import "github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips"
floatingips.Update(client, floatingIP.ID, floatingips.UpdateOpts{})
```

I dumped the request and I saw that the `PortID` attribute of `UpdateOpts` is serialized as an empty string. The Neutron API reference states that it should be a null value.

I'm not sure what could be a proper fix for this, but when I convert `PortID` to a pointer, it works fine:

``` go
type UpdateOpts struct {
     PortID *string `json:"port_id"`
}
```

**Comment by jrperritt** [comment]
closed by #103
