### ISSUE TITLE
openlab CI job config cleanup

### ISSUE THREAD

**Issue by yongfengdu** [gophercloud/gophercloud#994]
For historical reasons, the acceptance job only covers partial of the acceptance test
Now the job is moved to gophercloud repo,
.zuul/playbooks/gophercloud-acceptance-test/run.yaml
so we can do some cleanup and enable more acceptance tests as needed.

Currently enabled tests:
              # Only enable these successful test cases
              go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v3/
              go test -v -tags "fixtures acceptance" ./acceptance/openstack/networking/v2/
              go test -v -tags "fixtures acceptance" ./acceptance/openstack/blockstorage/v2/
              go test -v -tags "fixtures acceptance" -run "SecGroup|Flavor" ./acceptance/openstack/compute/v2/
              # To enable more after the fix of https://github.com/gophercloud/gophercloud/issues/608
              # go test -v -tags "fixtures acceptance" ./acceptance/openstack/imageservice/v2/
              # go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v2/
              # go test -v -tags "fixtures acceptance" ./acceptance/openstack/compute/v2/
              } 2>&1 | tee $TEST_RESULTS_TXT

**Comment by yongfengdu** [comment]
The acceptance test needs more work. Ideally, we can just call
./script/acceptancetest -v 2>&1 |tee $TEST_RESULTS_TXT
And gophercloud project should define what tests need to be run in the above acceptancetest script.

TO DISCUSS:
Since we support multiple versions of OpenStack, it is reasonable to provide version specific scripts to enable different accept tests, like acceptance-mitaka and acceptance-queens, to make sure the tests run being compatible with OpenStack API Versions(devstack).

**Comment by jtopjian** [comment]
> The acceptance test needs more work.

Yep, this is something I've been slowly working on: https://github.com/gophercloud/gophercloud/issues/818

This issue can probably be closed in favor of #818 since it has links to several PRs related to this.

> Since we support multiple versions of OpenStack, it is reasonable to provide version specific scripts to enable different accept tests, like acceptance-mitaka and acceptance-queens, to make sure the tests run being compatible with OpenStack API Versions(devstack).

Yes, I would like this to be possible. :)

**Comment by yongfengdu** [comment]
Took a look at #818, those are most update for test cases themselves.
I'd like to keep this issue open for these changes bind to job config itself:
1. Move the above pasted embedded run.yml scripts to script/acceptancetest
2. Cleanup the obsolete code for testing theopenlab/gophercloud

After that, all changes to enable/disable different test sets can be done in script/acceptencetest, not touch the job definition.

**Comment by jtopjian** [comment]
Sounds good :)
